#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const executionRoot=path.resolve(here,'..');
const sourcePackageRoot=path.basename(path.dirname(executionRoot))==='.aledevos'?null:path.resolve(executionRoot,'..');
const workerManager=path.join(executionRoot,'workers','worker-manager.mjs');
const workerRuntime=path.join(executionRoot,'workers','worker-runtime.mjs');
const policyPath=path.join(executionRoot,'policies','concurrency-policy.json');
const p2PolicyPath=path.join(executionRoot,'policies','worker-policy.json');
const args=process.argv.slice(2),[group,cmd]=args;
const take=(flag,def=null)=>{const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:def};
const takes=flag=>{const a=[];for(let i=0;i<args.length;i++)if(args[i]===flag&&i+1<args.length)a.push(args[i+1]);return a};
const out=v=>process.stdout.write(JSON.stringify(v,null,2)+'\n');
const die=(status,code=2,extra={})=>{out({status,...extra});process.exit(code)};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const atomicWrite=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.${process.pid}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,p)};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const hashFile=p=>sha(fs.readFileSync(p));
const stable=(v,omit)=>Array.isArray(v)?v.map(x=>stable(x,omit)):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!omit.has(k)).sort().map(k=>[k,stable(v[k],omit)])):v;
const hashObj=(v,...omit)=>sha(Buffer.from(JSON.stringify(stable(v,new Set(omit)))));
const now=()=>new Date().toISOString();
const sleep=ms=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);
const norm=s=>String(s??'').replaceAll('\\','/').replace(/^\.\//,'').replace(/\/+$/,'');
const policy=()=>read(policyPath);
const p2Policy=()=>read(p2PolicyPath);
function runJson(script,argv,cwd){const r=spawnSync(process.execPath,[script,...argv],{cwd,encoding:'utf8',windowsHide:true});let data={};try{data=JSON.parse(r.stdout||'{}')}catch{}return{ok:r.status===0,status:r.status,data,stdout:r.stdout||'',stderr:r.stderr||''}}
function pathEq(a,b){const A=path.resolve(a).replace(/[\\/]+$/,''),B=path.resolve(b).replace(/[\\/]+$/,'');return process.platform==='win32'?A.toLowerCase()===B.toLowerCase():A===B}
function globToRx(g){g=norm(g);let r='^';for(let i=0;i<g.length;i++){const c=g[i];if(c==='*'&&g[i+1]==='*'){r+='.*';i++}else if(c==='*')r+='[^/]*';else if(c==='?')r+='[^/]';else r+=c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}return new RegExp(r+'$',process.platform==='win32'?'i':'')}
function rootPrefix(g){const n=norm(g),parts=n.split('/');const out=[];for(const x of parts){if(/[?*]/.test(x))break;out.push(x)}return out.join('/')}
function scopesOverlap(a,b){a=norm(a);b=norm(b);if(!a||!b)return true;if(a==='**'||b==='**'||a==='*'||b==='*')return true;const ar=rootPrefix(a),br=rootPrefix(b);if(!ar||!br)return true;if(ar===br||ar.startsWith(br+'/')||br.startsWith(ar+'/'))return true;const samples=[ar,br,ar+'/x',br+'/x'];const ax=globToRx(a),bx=globToRx(b);return samples.some(s=>ax.test(s)&&bx.test(s))}
function stateRoot(repo){return path.join(repo,'.aledevos','state','execution','phase3')}
function groupsDir(repo){return path.join(stateRoot(repo),'groups')}
function groupFile(repo,id){return path.join(groupsDir(repo),id,'group.json')}
function groupLock(repo,id){return path.join(groupsDir(repo),id,'control.lock')}
function globalLock(repo){return path.join(stateRoot(repo),'control.lock')}
function leaseRegistryPath(repo){return path.join(stateRoot(repo),'leases.json')}
function runtimeDir(repo,id,workerId){return path.join(groupsDir(repo),id,'runtime',workerId)}
function withLock(repo,id,fn){const l=id==='__GLOBAL__'?globalLock(repo):groupLock(repo,id);fs.mkdirSync(path.dirname(l),{recursive:true});let fd;for(let attempt=0;attempt<2;attempt++){try{fd=fs.openSync(l,'wx');break}catch(e){if(e?.code!=='EEXIST')throw e;let stale=false;try{const x=read(l);stale=!pidAlive(Number(x.pid))}catch{stale=true}if(stale){try{fs.rmSync(l,{force:true})}catch{};continue}die('CONCURRENCY_GROUP_BUSY',7,{group_id:id})}}if(fd==null)die('CONCURRENCY_GROUP_BUSY',7,{group_id:id});try{fs.writeFileSync(fd,JSON.stringify({pid:process.pid,created_at:now()})+'\n');return fn()}finally{try{fs.closeSync(fd)}catch{};try{fs.rmSync(l,{force:true})}catch{}}}

function emptyLeases(repo){return{schema_version:'1.0',phase:'ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY',repository_root:path.resolve(repo),active_groups:{},lease_sha256:''}}
function sealLeases(r){r.lease_sha256=hashObj(r,'lease_sha256');return r}
function loadLeases(repo){const f=leaseRegistryPath(repo);if(!fs.existsSync(f)){const r=sealLeases(emptyLeases(repo));atomicWrite(f,r);return r}const r=read(f);if(r.phase!=='ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY'||!pathEq(r.repository_root,repo)||r.lease_sha256!==hashObj(r,'lease_sha256'))die('CONCURRENCY_LEASE_REGISTRY_INVALID',7,{errors:['LEASE_REGISTRY_INTEGRITY_INVALID']});return r}
function saveLeases(repo,r){sealLeases(r);atomicWrite(leaseRegistryPath(repo),r)}
function activeAssignments(repo,leases){const out=[];for(const [gid,e] of Object.entries(leases.active_groups||{})){if(!e.group_file||!fs.existsSync(e.group_file)){delete leases.active_groups[gid];continue}let g;try{g=read(e.group_file)}catch{delete leases.active_groups[gid];continue}if(!['RUNNING','DEGRADED','STARTING'].includes(g.state)){delete leases.active_groups[gid];continue}for(const x of Object.values(g.workers||{})){if(x.assignment_path&&fs.existsSync(x.assignment_path))out.push({group_id:gid,worker_id:x.worker_id||null,assignment:read(x.assignment_path),assignment_path:x.assignment_path})}}return out}
function crossGroupConflicts(repo,q,leases){const active=activeAssignments(repo,leases),conflicts=[];for(const nw of q.workers){const na=read(nw.assignment_path);for(const aw of active){const c=conflict(na,aw.assignment);if(c)conflicts.push({new_worker:nw.worker_id,active_group:aw.group_id,active_worker:aw.assignment.worker_id,...c})}}return{active,conflicts}}

function pidAlive(pid){if(!Number.isInteger(pid)||pid<=0)return false;try{process.kill(pid,0)}catch{return false}if(process.platform==='linux'){try{const s=fs.readFileSync(`/proc/${pid}/stat`,'utf8').trim().split(' ')[2];if(s==='Z'||s==='X')return false}catch{}}return true}
function readHeartbeat(p){try{return read(p)}catch{return null}}
function assignmentVerify(repo,file){const r=runJson(workerManager,['assignment','verify','--repo',repo,'--assignment',file],repo);return r.ok?{valid:true,assignment:r.data.assignment}:{valid:false,errors:r.data.errors||['P2_ASSIGNMENT_INVALID']}}
function loadAssignment(repo,file){const v=assignmentVerify(repo,file);if(!v.valid)return v;const a=v.assignment;return{valid:true,assignment:a,path:path.resolve(file),sha256:hashFile(file)}}
function conflict(a,b){const aw=a.permissions?.write_scope||[],ar=a.permissions?.read_scope||[],bw=b.permissions?.write_scope||[],br=b.permissions?.read_scope||[];for(const x of aw)for(const y of bw)if(scopesOverlap(x,y))return{type:'WRITE_WRITE',a:x,b:y};for(const x of aw)for(const y of br)if(scopesOverlap(x,y))return{type:'WRITE_READ',a:x,b:y};for(const x of bw)for(const y of ar)if(scopesOverlap(x,y))return{type:'WRITE_READ',a:y,b:x};return null}
function plan(repo,files){const p=policy(),errors=[];if(!repo||!fs.existsSync(repo))errors.push('REPOSITORY_MISSING');if(files.length<1)errors.push('NO_WORKERS_REQUESTED');if(files.length>p.max_group_workers)errors.push('GROUP_SIZE_LIMIT_EXCEEDED');const workers=[];for(const f of files){const x=loadAssignment(repo,path.resolve(f));if(!x.valid){errors.push(...x.errors.map(e=>`ASSIGNMENT_INVALID:${path.basename(f)}:${e}`));continue}const a=x.assignment;if((a.permissions?.write_scope||[]).some(s=>norm(s)==='*'||norm(s)==='**'))errors.push(`GLOBAL_WRITE_SCOPE_BLOCKED:${a.worker_id}`);workers.push({worker_id:a.worker_id,task_id:a.task_id,role:a.worker_role,assignment_path:x.path,assignment_sha256:a.assignment_sha256,assignment_file_sha256:x.sha256,worktree_path:a.worktree.path,worktree_receipt_sha256:a.worktree.receipt_sha256,read_scope:a.permissions.read_scope||[],write_scope:a.permissions.write_scope||[]})}
 const ids=new Set(),wts=new Set();for(const w of workers){if(ids.has(w.worker_id))errors.push(`DUPLICATE_WORKER_ID:${w.worker_id}`);ids.add(w.worker_id);const k=process.platform==='win32'?path.resolve(w.worktree_path).toLowerCase():path.resolve(w.worktree_path);if(wts.has(k))errors.push(`DUPLICATE_WORKTREE:${w.worker_id}`);wts.add(k)}
 const conflicts=[];for(let i=0;i<workers.length;i++)for(let j=i+1;j<workers.length;j++){const av=read(workers[i].assignment_path),bv=read(workers[j].assignment_path),c=conflict(av,bv);if(c)conflicts.push({worker_a:workers[i].worker_id,worker_b:workers[j].worker_id,...c})}if(conflicts.length)errors.push('SCOPE_CONFLICTS_PRESENT');
 const groupId='group-'+sha(Buffer.from(JSON.stringify(workers.map(w=>[w.worker_id,w.assignment_sha256])))).slice(0,24);const obj={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY',status:errors.length?'CONCURRENCY_PLAN_BLOCKED':'CONCURRENCY_PLAN_READY',group_id:groupId,repository_root:path.resolve(repo),workers,conflicts,limits:{max_parallel_workers:p.max_parallel_workers,max_group_workers:p.max_group_workers},boundaries:{dispatcher_used:false,queue_used:false,multi_machine_used:false,network_used:false,target_agent_runtime_binding:p.boundaries.target_agent_runtime_binding},prepared_at:now(),plan_sha256:''};obj.plan_sha256=hashObj(obj,'plan_sha256');return{valid:!errors.length,errors,plan:obj}}
function planVerify(repo,file){if(!fs.existsSync(file))return{valid:false,errors:['PLAN_MISSING']};let q;try{q=read(file)}catch{return{valid:false,errors:['PLAN_UNREADABLE']}};const errors=[];if(q.phase!=='ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY'||q.schema_version!=='1.0')errors.push('PLAN_PHASE_INVALID');if(q.plan_sha256!==hashObj(q,'plan_sha256'))errors.push('PLAN_INTEGRITY_MISMATCH');if(!pathEq(q.repository_root,repo))errors.push('PLAN_REPOSITORY_DRIFT');const rerun=plan(repo,(q.workers||[]).map(w=>w.assignment_path));if(rerun.plan.group_id!==q.group_id||rerun.plan.status!==q.status||JSON.stringify(rerun.plan.conflicts)!==JSON.stringify(q.conflicts))errors.push('PLAN_RECOMPUTE_DRIFT');for(const w of q.workers||[]){if(!fs.existsSync(w.assignment_path)||hashFile(w.assignment_path)!==w.assignment_file_sha256)errors.push(`ASSIGNMENT_FILE_DRIFT:${w.worker_id}`)}return{valid:!errors.length,errors,plan:q}}
function safeEnv(w){const allow=p2Policy().environment_allowlist||[],e={};for(const k of allow)if(process.env[k]!=null)e[k]=process.env[k];e.ALEDEVOS_WORKER_ID=w.worker_id;e.ALEDEVOS_TASK_ID=w.task_id;e.ALEDEVOS_WORKER_ROLE=w.role;e.ALEDEVOS_WORKTREE_ROOT=w.worktree_path;e.ALEDEVOS_EXECUTION_PHASE='P3_SAFE_CONCURRENCY';return e}
function runtimeConfig(repo,gid,w){const d=runtimeDir(repo,gid,w.worker_id),c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P2_ISOLATED_WORKERS',worker_id:w.worker_id,task_id:w.task_id,worker_role:w.role,worktree_root:w.worktree_path,state_dir:d,heartbeat_interval_ms:p2Policy().heartbeat_interval_ms,config_sha256:''};c.config_sha256=hashObj(c,'config_sha256');return c}
function groupStart(repo,planFile){const pv=planVerify(repo,planFile);if(!pv.valid)die('CONCURRENCY_START_BLOCKED',5,{errors:pv.errors});const q=pv.plan,p=policy();if(q.status!=='CONCURRENCY_PLAN_READY')die('CONCURRENCY_START_BLOCKED',5,{errors:['PLAN_NOT_READY']});if(q.workers.length>p.max_parallel_workers)die('CONCURRENCY_START_BLOCKED',5,{errors:['MAX_PARALLEL_WORKERS_EXCEEDED']});return withLock(repo,'__GLOBAL__',()=>{const gf=groupFile(repo,q.group_id);if(fs.existsSync(gf)){const old=read(gf);if(['RUNNING','STARTING'].includes(old.state))die('CONCURRENCY_GROUP_ALREADY_ACTIVE',6,{group_id:q.group_id})}const leases=loadLeases(repo),cross=crossGroupConflicts(repo,q,leases),activeCount=cross.active.length;if(activeCount+q.workers.length>p.max_parallel_workers)die('CONCURRENCY_START_BLOCKED',7,{errors:['GLOBAL_MAX_PARALLEL_WORKERS_EXCEEDED'],active_workers:activeCount,requested_workers:q.workers.length});if(cross.conflicts.length)die('CONCURRENCY_START_BLOCKED',7,{errors:['ACTIVE_SCOPE_CONFLICTS_PRESENT'],conflicts:cross.conflicts});
 const g={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY',group_id:q.group_id,state:'STARTING',plan_sha256:q.plan_sha256,repository_root:q.repository_root,workers:{},started_at:null,stopped_at:null,boundaries:{concurrency_used:true,dispatcher_used:false,queue_used:false,multi_machine_used:false,network_used:false},group_sha256:''};
 for(const w of q.workers){const d=runtimeDir(repo,q.group_id,w.worker_id);fs.mkdirSync(d,{recursive:true});const c=runtimeConfig(repo,q.group_id,w),cf=path.join(d,'runtime-config.json');atomicWrite(cf,c);for(const n of ['heartbeat.json','control.json'])try{fs.rmSync(path.join(d,n),{force:true})}catch{};let child;try{child=spawn(process.execPath,[workerRuntime,'--config',cf],{cwd:w.worktree_path,env:safeEnv(w),detached:true,stdio:'ignore',windowsHide:true})}catch(e){die('CONCURRENCY_START_FAILED',8,{errors:[`SPAWN_FAILED:${w.worker_id}`],message:String(e.message||e)})}child.unref();g.workers[w.worker_id]={task_id:w.task_id,role:w.role,assignment_path:w.assignment_path,assignment_sha256:w.assignment_sha256,worktree_path:w.worktree_path,pid:child.pid,runtime_config_sha256:c.config_sha256,heartbeat_path:path.join(d,'heartbeat.json'),control_path:path.join(d,'control.json'),state:'STARTING',recovery_count:0,start_count:1,last_error:null}}
 const deadline=Date.now()+p.start_timeout_ms;let all=false;while(Date.now()<deadline){all=true;for(const x of Object.values(g.workers)){const h=readHeartbeat(x.heartbeat_path);if(!h||h.status!=='RUNNING'||h.pid!==x.pid||h.runtime_config_sha256!==x.runtime_config_sha256){all=false;break}}if(all)break;sleep(50)}if(!all){for(const x of Object.values(g.workers))try{process.kill(x.pid,'SIGTERM')}catch{};die('CONCURRENCY_START_FAILED',8,{errors:['GROUP_HEARTBEAT_NOT_ESTABLISHED']})}for(const x of Object.values(g.workers))x.state='RUNNING';g.state='RUNNING';g.started_at=now();g.group_sha256=hashObj(g,'group_sha256');atomicWrite(gf,g);leases.active_groups[q.group_id]={group_file:gf,worker_count:q.workers.length,started_at:g.started_at};saveLeases(repo,leases);return{status:'CONCURRENCY_GROUP_STARTED',group_file:gf,group:g}})}
function groupVerify(repo,file){if(!fs.existsSync(file))return{valid:false,errors:['GROUP_MISSING']};let g;try{g=read(file)}catch{return{valid:false,errors:['GROUP_UNREADABLE']}};const errors=[];if(g.phase!=='ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY'||g.group_sha256!==hashObj(g,'group_sha256'))errors.push('GROUP_INTEGRITY_INVALID');if(!pathEq(g.repository_root,repo))errors.push('GROUP_REPOSITORY_DRIFT');for(const [id,x] of Object.entries(g.workers||{})){if(!fs.existsSync(x.assignment_path))errors.push(`ASSIGNMENT_MISSING:${id}`);else{const a=read(x.assignment_path);if(a.assignment_sha256!==x.assignment_sha256)errors.push(`ASSIGNMENT_DRIFT:${id}`)}if(x.state==='RUNNING'){const h=readHeartbeat(x.heartbeat_path);if(!pidAlive(x.pid))errors.push(`PROCESS_LOST:${id}`);else if(!h||h.worker_id!==id||h.pid!==x.pid||h.runtime_config_sha256!==x.runtime_config_sha256)errors.push(`HEARTBEAT_INVALID:${id}`);else if(Date.now()-Date.parse(h.last_heartbeat_at)>policy().heartbeat_timeout_ms)errors.push(`HEARTBEAT_STALE:${id}`)}}return{valid:!errors.length,errors,group:g}}
function stopOne(x,reason){atomicWrite(x.control_path,{schema_version:'1.0',phase:'ADVANCED_EXECUTION_P2_ISOLATED_WORKERS',worker_id:path.basename(path.dirname(x.control_path)),action:'STOP',reason,requested_at:now()});const dl=Date.now()+policy().stop_timeout_ms;while(Date.now()<dl){if(!pidAlive(x.pid))return true;sleep(50)}return !pidAlive(x.pid)}
function groupStop(repo,file){const gv=groupVerify(repo,file);if(!gv.group)die('CONCURRENCY_STOP_BLOCKED',5,{errors:gv.errors});const g=gv.group;return withLock(repo,'__GLOBAL__',()=>{const leases=loadLeases(repo),failures=[];for(const [id,x] of Object.entries(g.workers)){if(x.state==='RUNNING'&&pidAlive(x.pid)){if(!stopOne(x,'P3_GROUP_STOP'))failures.push(id)}x.state='STOPPED'}g.state=failures.length?'DEGRADED':'STOPPED';g.stopped_at=now();g.group_sha256=hashObj(g,'group_sha256');atomicWrite(file,g);delete leases.active_groups[g.group_id];saveLeases(repo,leases);if(failures.length)die('CONCURRENCY_STOP_PARTIAL',8,{failures,group:g});return{status:'CONCURRENCY_GROUP_STOPPED',group:g}})}
function recoverOne(repo,file,workerId){const gv=groupVerify(repo,file),g=gv.group;if(!g)die('CONCURRENCY_RECOVERY_BLOCKED',5,{errors:gv.errors});const x=g.workers?.[workerId];if(!x)die('CONCURRENCY_RECOVERY_BLOCKED',5,{errors:['WORKER_NOT_IN_GROUP']});return withLock(repo,g.group_id,()=>{if(pidAlive(x.pid))die('CONCURRENCY_RECOVERY_NOT_REQUIRED',4,{worker_id:workerId});if((x.recovery_count||0)>=policy().max_recovery_count_per_worker){x.state='FAILED';x.last_error='RECOVERY_EXHAUSTED';g.state=Object.values(g.workers).some(w=>w.state==='RUNNING')?'DEGRADED':'FAILED';g.group_sha256=hashObj(g,'group_sha256');atomicWrite(file,g);die('CONCURRENCY_RECOVERY_EXHAUSTED',7,{worker_id:workerId,group:g})}const w=read(x.assignment_path),lite={worker_id:w.worker_id,task_id:w.task_id,role:w.worker_role,worktree_path:w.worktree.path},d=runtimeDir(repo,g.group_id,workerId),c=runtimeConfig(repo,g.group_id,lite),cf=path.join(d,'runtime-config.json');atomicWrite(cf,c);for(const n of ['heartbeat.json','control.json'])try{fs.rmSync(path.join(d,n),{force:true})}catch{};const child=spawn(process.execPath,[workerRuntime,'--config',cf],{cwd:lite.worktree_path,env:safeEnv(lite),detached:true,stdio:'ignore',windowsHide:true});child.unref();const dl=Date.now()+policy().start_timeout_ms;let h;while(Date.now()<dl){h=readHeartbeat(path.join(d,'heartbeat.json'));if(h?.status==='RUNNING'&&h.pid===child.pid)break;sleep(50)}if(!h||h.pid!==child.pid)die('CONCURRENCY_RECOVERY_FAILED',8,{worker_id:workerId});x.pid=child.pid;x.runtime_config_sha256=c.config_sha256;x.heartbeat_path=path.join(d,'heartbeat.json');x.control_path=path.join(d,'control.json');x.state='RUNNING';x.recovery_count=(x.recovery_count||0)+1;x.start_count=(x.start_count||0)+1;x.last_error=null;g.state='RUNNING';g.group_sha256=hashObj(g,'group_sha256');atomicWrite(file,g);return{status:'CONCURRENCY_WORKER_RECOVERED',worker_id:workerId,group:g}})}
function policyVerify(){const p=policy(),errors=[];if(p.schema_version!=='1.0'||p.phase!=='ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY')errors.push('PHASE_INVALID');for(const k of ['max_parallel_workers','max_group_workers','heartbeat_timeout_ms','start_timeout_ms','stop_timeout_ms','max_recovery_count_per_worker'])if(!Number.isInteger(p[k])||p[k]<1)errors.push(`NUMERIC_INVALID:${k}`);if(p.max_parallel_workers>p.max_group_workers)errors.push('PARALLEL_LIMIT_EXCEEDS_GROUP_LIMIT');for(const k of ['write_write_overlap','write_read_overlap','unknown_scope','global_write_scope'])if(p.admission?.[k]!=='BLOCK')errors.push(`ADMISSION_RULE_INVALID:${k}`);if(p.admission?.read_read_overlap!=='ALLOW')errors.push('READ_READ_MUST_ALLOW');for(const k of ['require_distinct_worktrees','require_distinct_worker_ids','require_p2_assignment_valid','require_live_p1_worktree'])if(p.admission?.[k]!==true)errors.push(`ADMISSION_REQUIREMENT_MISSING:${k}`);if(p.fairness?.policy!=='FIFO_STABLE')errors.push('FAIRNESS_POLICY_INVALID');for(const k of ['dispatcher_used','queue_used','multi_machine_used','network_used'])if(p.boundaries?.[k]!==false)errors.push(`BOUNDARY_INVALID:${k}`);if(p.boundaries?.target_agent_runtime_binding!=='DEFERRED_MASTER_VALIDATION')errors.push('TARGET_RUNTIME_BOUNDARY_INVALID');return{status:errors.length?'CONCURRENCY_POLICY_INVALID':'CONCURRENCY_POLICY_VALID',valid:!errors.length,errors,policy:p}}
function certificatePaths(){return['advanced-execution/concurrency/concurrency-manager.mjs','advanced-execution/policies/concurrency-policy.json','advanced-execution/contracts/SAFE_CONCURRENCY.md','advanced-execution/schemas/concurrency-plan.schema.json','advanced-execution/schemas/concurrency-group.schema.json','advanced-execution/schemas/concurrency-lease-registry.schema.json','advanced-execution/templates/concurrency-request.example.json','advanced-execution/workers/worker-runtime.mjs','advanced-execution/workers/worker-manager.mjs','release/certifications/advanced-execution-p1.json','release/certifications/advanced-execution-p2.json','scripts/05-install-into-project.ps1']}
function certifyRun(outFile){if(!sourcePackageRoot)die('ADVANCED_EXECUTION_P3_CERTIFICATION_SOURCE_LAYOUT_REQUIRED',4);const pv=policyVerify(),p1=runJson(path.join(executionRoot,'worktrees','worktree-manager.mjs'),['certify','verify','--certificate',path.join(sourcePackageRoot,'release/certifications/advanced-execution-p1.json')],sourcePackageRoot),p2=runJson(workerManager,['certify','verify','--certificate',path.join(sourcePackageRoot,'release/certifications/advanced-execution-p2.json')],sourcePackageRoot),inputs=certificatePaths().map(rel=>({path:rel,sha256:hashFile(path.join(sourcePackageRoot,rel))}));const ok=pv.valid&&p1.ok&&p2.ok;const c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY',status:ok?'ADVANCED_EXECUTION_P3_PACKAGE_CERTIFIED':'ADVANCED_EXECUTION_P3_PACKAGE_CERTIFICATION_FAILED',package_only:true,target_runtime_validation:'DEFERRED',claims:{multi_worker_local_concurrency:true,scope_conflict_admission:true,stable_fifo_admission:true,max_parallelism_enforced:true,independent_worker_recovery:true,p1_p2_frozen_dependencies:true,dispatcher_disabled:true,queue_disabled:true,multi_machine_disabled:true,network_disabled:true,target_agent_runtime_binding:false},dependencies:{p1_certificate_valid:p1.ok,p2_certificate_valid:p2.ok},inputs,created_at:now(),evidence_sha256:''};c.evidence_sha256=hashObj(c,'evidence_sha256');if(outFile)atomicWrite(path.resolve(outFile),c);return c}
function certifyVerify(file){if(!sourcePackageRoot)return{status:'ADVANCED_EXECUTION_P3_CERTIFICATE_INVALID',valid:false,errors:['SOURCE_LAYOUT_REQUIRED']};if(!file||!fs.existsSync(file))return{status:'ADVANCED_EXECUTION_P3_CERTIFICATE_INVALID',valid:false,errors:['CERTIFICATE_MISSING']};const c=read(file),errors=[];if(c.phase!=='ADVANCED_EXECUTION_P3_SAFE_CONCURRENCY')errors.push('PHASE_INVALID');if(c.evidence_sha256!==hashObj(c,'evidence_sha256'))errors.push('CERTIFICATE_INTEGRITY_MISMATCH');const expected=certificatePaths();if((c.inputs||[]).length!==expected.length)errors.push('INPUT_SET_DRIFT');for(const rel of expected){const x=(c.inputs||[]).find(i=>i.path===rel);if(!x||x.sha256!==hashFile(path.join(sourcePackageRoot,rel)))errors.push(`INPUT_DRIFT:${rel}`)}return{status:errors.length?'ADVANCED_EXECUTION_P3_CERTIFICATE_STALE_OR_TAMPERED':'ADVANCED_EXECUTION_P3_CERTIFICATE_VALID',valid:!errors.length,errors,certificate:c}}

if(group==='policy'&&cmd==='verify'){const r=policyVerify();out(r);process.exit(r.valid?0:3)}
if(group==='plan'&&cmd==='prepare'){const repo=path.resolve(take('--repo','')),r=plan(repo,takes('--assignment')),dest=take('--out');if(dest)atomicWrite(path.resolve(dest),r.plan);out({status:r.valid?'CONCURRENCY_PLAN_READY':'CONCURRENCY_PLAN_BLOCKED',...r,plan_path:dest?path.resolve(dest):null});process.exit(r.valid?0:5)}
if(group==='plan'&&cmd==='verify'){const r=planVerify(path.resolve(take('--repo','')),path.resolve(take('--plan','')));out({status:r.valid?'CONCURRENCY_PLAN_VALID':'CONCURRENCY_PLAN_INVALID',...r});process.exit(r.valid?0:5)}
if(group==='group'&&cmd==='start'){const r=groupStart(path.resolve(take('--repo','')),path.resolve(take('--plan','')));out(r);process.exit(0)}
if(group==='group'&&cmd==='status'){const r=groupVerify(path.resolve(take('--repo','')),path.resolve(take('--group','')));out({status:r.valid?'CONCURRENCY_GROUP_HEALTHY':'CONCURRENCY_GROUP_DEGRADED',...r});process.exit(r.valid?0:6)}
if(group==='group'&&cmd==='stop'){const r=groupStop(path.resolve(take('--repo','')),path.resolve(take('--group','')));out(r);process.exit(0)}
if(group==='worker'&&cmd==='recover'){const r=recoverOne(path.resolve(take('--repo','')),path.resolve(take('--group','')),take('--worker-id',''));out(r);process.exit(0)}
if(group==='certify'&&cmd==='run'){const c=certifyRun(take('--out'));out(c);process.exit(c.status.endsWith('CERTIFIED')?0:4)}
if(group==='certify'&&cmd==='verify'){const r=certifyVerify(path.resolve(take('--certificate','')));out(r);process.exit(r.valid?0:4)}
die('CONCURRENCY_COMMAND_UNKNOWN',2,{usage:['policy verify','plan prepare --repo <repo> --assignment <p2.json>... --out <plan.json>','plan verify --repo <repo> --plan <plan.json>','group start --repo <repo> --plan <plan.json>','group status|stop --repo <repo> --group <group.json>','worker recover --repo <repo> --group <group.json> --worker-id <id>','certify run|verify']});
