#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const distRoot=path.resolve(here,'..');
const args=process.argv.slice(2);const [group,cmd]=args;
const take=(f,d=null)=>{const i=args.indexOf(f);return i>=0&&i+1<args.length?args[i+1]:d};
const has=f=>args.includes(f);
function fail(status,code=1,extra={}){process.stdout.write(JSON.stringify({status,...extra},null,2)+'\n');process.exit(code)}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n','utf8')}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())if(!['integrity_sha256','plan_sha256','contract_sha256','report_sha256'].includes(k))o[k]=stable(v[k]);return o}return v}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(stable(v))).digest('hex')}
function fileSha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function seal(o,key='integrity_sha256'){o[key]='';o[key]=sha(o);return o}
function validSeal(o,key='integrity_sha256'){return typeof o?.[key]==='string'&&o[key]===sha(o)}
function rootOf(p){const r=path.resolve(p||process.cwd());if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())fail('PROJECT_ROOT_INVALID',80);return r}
function inside(root,p){const rr=path.resolve(root),pp=path.resolve(p);return pp===rr||pp.startsWith(rr+path.sep)}
function rel(root,p){return path.relative(root,p).split(path.sep).join('/')}
function policy(){return readJson(path.join(distRoot,'policies','uxui-policy.json'))}
function designRoot(root){return path.join(root,'.aledevos','design')}
function stateRoot(root){return path.join(root,'.aledevos','state','uxui','phase5')}
function manifestPath(root){return path.join(designRoot(root),'design-context.json')}
function languagePath(root){return path.join(root,policy().phase5.motion_language.machine_path)}
function languageMdPath(root){return path.join(root,policy().phase5.motion_language.human_path)}
function requireManifest(root){const f=manifestPath(root);if(!fs.existsSync(f))fail('DESIGN_CONTEXT_MISSING',81);const m=readJson(f);if(!validSeal(m))fail('DESIGN_CONTEXT_INVALID',82);return m}
function initLanguage(root){requireManifest(root);const f=languagePath(root);if(fs.existsSync(f)){const o=readJson(f);if(!validSeal(o))fail('MOTION_LANGUAGE_INTEGRITY_MISMATCH',83);return o}const o=seal({schema_version:'1.0',language_version:1,status:'UNSET',source_kind:null,source_ref:null,durations:{},easings:{},semantic_roles:{},reduced_motion:{required:true,default_behavior:null},rules:{decorative_infinite_motion:'DENY',raw_motion_literals:'DENY_UNLESS_APPROVED_EXCEPTION'},platform_overrides:{},integrity_sha256:''});writeJson(f,o);return o}
function validateProposal(q){const p=policy().phase5.motion_language,e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!['human_approved_design_context','existing_canonical_design_system','verified_runtime_discovery','verified_skill_output'].includes(q?.source_kind))e.push('source_kind');if(!q?.source_ref)e.push('source_ref');for(const k of p.required_duration_tokens){const d=q?.durations?.[k];if(!d)e.push(`duration_missing:${k}`);else{if(!Number.isFinite(d.min_ms)||!Number.isFinite(d.max_ms))e.push(`duration_not_numeric:${k}`);else{if(d.min_ms<p.duration_ms_min||d.max_ms>p.duration_ms_max||d.min_ms>d.max_ms)e.push(`duration_range_invalid:${k}`)}}}for(const k of p.required_easing_tokens)if(typeof q?.easings?.[k]!=='string'||!q.easings[k].trim())e.push(`easing_missing:${k}`);const ds=q?.durations||{};if(ds.micro&&ds.standard&&ds.large&&!(ds.micro.max_ms<=ds.standard.max_ms&&ds.standard.max_ms<=ds.large.max_ms))e.push('duration_scale_not_monotonic');if(q?.reduced_motion?.required!==true)e.push('reduced_motion_must_be_required');if(!p.allowed_reduced_motion_behaviors.includes(q?.reduced_motion?.default_behavior))e.push('reduced_motion_default_invalid');for(const [id,r] of Object.entries(q?.semantic_roles||{})){if(!ds[r.duration_token])e.push(`semantic_role_duration_invalid:${id}`);if(!q?.easings?.[r.easing_token])e.push(`semantic_role_easing_invalid:${id}`)}return [...new Set(e)]}
function renderLanguageMd(o){const rows=['# Motion Language','','Status: ACTIVE','','Canonical semantic motion tokens for this project.','','## Durations'];for(const [k,v] of Object.entries(o.durations))rows.push(`- ${k}: ${v.min_ms}–${v.max_ms}ms`);rows.push('','## Easings');for(const [k,v] of Object.entries(o.easings))rows.push(`- ${k}: ${v}`);rows.push('','## Reduced motion',`- Required: ${o.reduced_motion.required?'yes':'no'}`,`- Default behavior: ${o.reduced_motion.default_behavior}`,'','## Rules',`- Decorative infinite motion: ${o.rules.decorative_infinite_motion}`,`- Raw motion literals: ${o.rules.raw_motion_literals}`,'');return rows.join('\n')}
function applyLanguage(root,q,approved){const e=validateProposal(q);if(!approved)e.push('explicit_approval_required');if(e.length)fail('MOTION_LANGUAGE_APPLY_BLOCKED',84,{errors:e});const m=requireManifest(root),f=languagePath(root),old=fs.existsSync(f)?readJson(f):null;const o=seal({schema_version:'1.0',language_version:Math.max(1,Number(old?.language_version||0)+1),status:'ACTIVE',source_kind:q.source_kind,source_ref:q.source_ref,durations:q.durations,easings:q.easings,semantic_roles:q.semantic_roles||{},reduced_motion:q.reduced_motion,rules:{decorative_infinite_motion:'DENY',raw_motion_literals:'DENY_UNLESS_APPROVED_EXCEPTION',...(q.rules||{})},platform_overrides:q.platform_overrides||{},integrity_sha256:''});writeJson(f,o);const md=languageMdPath(root);fs.mkdirSync(path.dirname(md),{recursive:true});fs.writeFileSync(md,renderLanguageMd(o),'utf8');const sec=m.sections?.motion_language;if(!sec)fail('MOTION_LANGUAGE_SECTION_MISSING',85);sec.status='PRESENT';sec.source=q.source_kind;sec.source_sha256=o.integrity_sha256;sec.artifact_sha256=fileSha(md);sec.notes=`Canonical Motion Language managed by UX/UI Phase 5 from ${q.source_ref}.`;m.context_version=Math.max(5,Number(m.context_version||1)+1);m.integrity_sha256='';m.integrity_sha256=sha(m);writeJson(manifestPath(root),m);return {status:'MOTION_LANGUAGE_ACTIVE',language_version:o.language_version,language_integrity:o.integrity_sha256,design_context_integrity:m.integrity_sha256}}
function verifyLanguage(root){const e=[];let o=null,m=null;const f=languagePath(root);if(!fs.existsSync(f))e.push('motion_language_missing');else{try{o=readJson(f);if(!validSeal(o))e.push('motion_language_integrity_mismatch')}catch{e.push('motion_language_unreadable')}}try{m=requireManifest(root)}catch{e.push('design_context_invalid')}if(o?.status==='ACTIVE'&&m){const sec=m.sections?.motion_language,md=languageMdPath(root);if(!sec||sec.status!=='PRESENT')e.push('design_context_motion_language_not_present');if(!fs.existsSync(md))e.push('motion_language_human_artifact_missing');else if(sec?.artifact_sha256!==fileSha(md))e.push('motion_language_human_artifact_drift');if(sec?.source_sha256!==o.integrity_sha256)e.push('motion_language_source_hash_mismatch')}return {valid:e.length===0,errors:e,status:o?.status||'MISSING',language_version:o?.language_version||null,language_integrity:o?.integrity_sha256||null,design_context_integrity:m?.integrity_sha256||null}}
function makePlan(root,taskId,platform='generic'){const p=policy().phase5.motion_director,plat=String(platform||'generic').toLowerCase();if(!p.preferred_skills[plat])fail('MOTION_PLATFORM_UNSUPPORTED',86,{platform:plat});const m=requireManifest(root),lv=verifyLanguage(root);const out=seal({schema_version:'1.0',task_id:taskId,platform:plat,status:'MOTION_PLAN_READY',design_context_integrity:m.integrity_sha256,motion_language_status:lv.status,motion_language_integrity:lv.language_integrity,skill_route_request:{schema_version:'1.0',task_id:`${taskId}.motion`,intent:'specialist-task',required_capabilities:[p.skill_capability],preferred_skills:p.preferred_skills[plat],max_skills:p.max_skills_per_stage,missing_skill_policy:p.missing_skill_policy},stages:['MOTION_OPPORTUNITY_SCAN','MOTION_VOCABULARY','MOTION_CONTRACT','IMPLEMENTATION_GUIDANCE','MOTION_REVIEW'],invariants:['SKILLS_ON_DEMAND','SKILL_OUTPUT_IS_EVIDENCE_ONLY','MISSING_SKILLS_USE_SAFE_ACQUISITION','NO_RAW_MOTION_LITERALS_WITHOUT_EXCEPTION','REDUCED_MOTION_REQUIRED','NO_AUTO_CANONICALIZATION'],integrity_sha256:''});const d=path.join(stateRoot(root),'plans');fs.mkdirSync(d,{recursive:true});writeJson(path.join(d,`${taskId}.json`),out);return out}
function verifyPlan(root,o){const e=[];if(!validSeal(o))e.push('motion_plan_integrity_mismatch');const m=requireManifest(root);if(o.design_context_integrity!==m.integrity_sha256)e.push('design_context_drift_since_motion_plan');const lv=verifyLanguage(root);if(o.motion_language_integrity&&o.motion_language_integrity!==lv.language_integrity)e.push('motion_language_drift_since_motion_plan');return {valid:e.length===0,errors:e,task_id:o.task_id,platform:o.platform}}
function validException(x,rule){return x&&x.rule_id===rule&&String(x.reason||'').trim().length>=8&&String(x.approval_ref||'').trim().length>=2}
function validateContractInput(root,q){const p=policy().phase5.contract,mp=policy().phase5.motion_language,e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');if(typeof q?.motion_required!=='boolean')e.push('motion_required');if(!String(q?.rationale||'').trim())e.push('rationale');if(!Array.isArray(q?.changed_files))e.push('changed_files');for(const rp of q?.changed_files||[]){const abs=path.resolve(root,rp);if(p.changed_files_must_be_inside_project&&!inside(root,abs))e.push(`changed_file_external:${rp}`);else if(p.changed_files_must_exist&&!fs.existsSync(abs))e.push(`changed_file_missing:${rp}`)}if(!q?.motion_required){if((q?.interactions||[]).length)e.push('interactions_present_when_motion_not_required');return [...new Set(e)]}const lv=verifyLanguage(root);if(!lv.valid||lv.status!=='ACTIVE')e.push('motion_language_not_active');const lang=lv.status==='ACTIVE'?readJson(languagePath(root)):null;const ints=q?.interactions;if(!Array.isArray(ints)||!ints.length)e.push('interactions_required');if((ints||[]).length>p.max_interactions)e.push('too_many_interactions');const ids=new Set();for(const x of ints||[]){if(!x?.id||ids.has(x.id))e.push(`interaction_id_invalid:${x?.id||'missing'}`);ids.add(x?.id);if(!p.allowed_intents.includes(x?.intent))e.push(`intent_invalid:${x?.id}`);if(!lang?.durations?.[x?.duration_token])e.push(`duration_token_invalid:${x?.id}`);if(!lang?.easings?.[x?.easing_token])e.push(`easing_token_invalid:${x?.id}`);if(mp.reduced_motion_required&&!mp.allowed_reduced_motion_behaviors.includes(x?.reduced_motion_behavior))e.push(`reduced_motion_missing:${x?.id}`);if(('duration_ms' in (x||{}))&&!((q.exceptions||[]).some(z=>validException(z,'RAW_MOTION_LITERAL'))))e.push(`raw_duration_literal:${x?.id}`);if(('easing' in (x||{}))&&!((q.exceptions||[]).some(z=>validException(z,'RAW_MOTION_LITERAL'))))e.push(`raw_easing_literal:${x?.id}`);if(x?.loop===true&&x?.essential!==true&&!((q.exceptions||[]).some(z=>validException(z,'DECORATIVE_INFINITE_MOTION'))))e.push(`decorative_infinite_loop:${x?.id}`)}for(const s of q?.skill_evidence||[]){if(!s?.skill_id||!s?.receipt_ref)e.push('skill_evidence_reference_invalid');for(const k of ['prompt','completion','body','instructions','transcript'])if(k in (s||{}))e.push(`skill_evidence_inline_forbidden:${k}`)}return [...new Set(e)]}
function sealContract(root,q){const e=validateContractInput(root,q);if(e.length)fail('MOTION_CONTRACT_BLOCKED',87,{errors:e});const m=requireManifest(root),lv=verifyLanguage(root);const out=seal({schema_version:'1.0',task_id:q.task_id,motion_required:q.motion_required,rationale:q.rationale,changed_files:q.changed_files||[],interactions:q.interactions||[],skill_evidence:q.skill_evidence||[],exceptions:q.exceptions||[],design_context_integrity:m.integrity_sha256,motion_language_integrity:q.motion_required?lv.language_integrity:null,status:q.motion_required?'MOTION_CONTRACT_READY':'NO_MOTION_REQUIRED',integrity_sha256:''},'contract_sha256');const d=path.join(stateRoot(root),'contracts');fs.mkdirSync(d,{recursive:true});writeJson(path.join(d,`${q.task_id}.json`),out);return out}
function verifyContract(root,o){const e=[];if(!validSeal(o,'contract_sha256'))e.push('motion_contract_integrity_mismatch');const m=requireManifest(root);if(o.design_context_integrity!==m.integrity_sha256)e.push('design_context_drift_since_motion_contract');if(o.motion_required){const lv=verifyLanguage(root);if(!lv.valid||lv.status!=='ACTIVE')e.push('motion_language_not_active');else if(o.motion_language_integrity!==lv.language_integrity)e.push('motion_language_drift_since_motion_contract')}const raw={schema_version:'1.0',task_id:o.task_id,motion_required:o.motion_required,rationale:o.rationale,changed_files:o.changed_files,interactions:o.interactions,skill_evidence:o.skill_evidence,exceptions:o.exceptions};e.push(...validateContractInput(root,raw));return {valid:[...new Set(e)].length===0,errors:[...new Set(e)],task_id:o.task_id,status:o.status}}
function review(root,contract){const c=verifyContract(root,contract),m=requireManifest(root),lv=verifyLanguage(root),blockers=c.errors.map(message=>({rule_id:'MOTION_CONTRACT',severity:'BLOCKER',message}));const report=seal({schema_version:'1.0',task_id:contract.task_id,status:blockers.length?'MOTION_BLOCKED':'MOTION_PASS',blockers,warnings:[],motion_required:contract.motion_required,interaction_count:(contract.interactions||[]).length,reduced_motion_covered:!contract.motion_required||(contract.interactions||[]).every(x=>!!x.reduced_motion_behavior),design_context_integrity:m.integrity_sha256,motion_language_integrity:contract.motion_required?lv.language_integrity:null,contract_sha256:contract.contract_sha256,report_sha256:''},'report_sha256');const d=path.join(stateRoot(root),'reviews');fs.mkdirSync(d,{recursive:true});writeJson(path.join(d,`${contract.task_id}.json`),report);return report}
function verifyReview(root,r,contract){const e=[];if(!validSeal(r,'report_sha256'))e.push('motion_review_integrity_mismatch');if(r.contract_sha256!==contract.contract_sha256)e.push('motion_review_contract_mismatch');const c=verifyContract(root,contract);if(!c.valid)e.push(...c.errors);const m=requireManifest(root);if(r.design_context_integrity!==m.integrity_sha256)e.push('design_context_drift_since_motion_review');if(r.motion_required){const lv=verifyLanguage(root);if(r.motion_language_integrity!==lv.language_integrity)e.push('motion_language_drift_since_motion_review')}return {valid:[...new Set(e)].length===0,errors:[...new Set(e)],status:r.status,task_id:r.task_id}}
function detect(root,files){const patterns=[/\banimation(?:-|\s*:|\s*=)/i,/\btransition(?:-|\s*:|\s*=)/i,/\bframer-motion\b/i,/\bmotion\./i,/\bAnimated\b/,/\bwithTiming\b/,/\bwithSpring\b/,/\bkeyframes\b/i,/\banimate\s*\(/i];const rows=[];for(const rp of files){const abs=path.resolve(root,rp);if(!inside(root,abs)||!fs.existsSync(abs)||!fs.statSync(abs).isFile())continue;const text=fs.readFileSync(abs,'utf8').slice(0,262144);const matches=patterns.filter(re=>re.test(text)).map(re=>re.source);if(matches.length)rows.push({path:rel(root,abs),sha256:fileSha(abs),signals:matches})}return seal({schema_version:'1.0',motion_detected:rows.length>0,files:rows,integrity_sha256:''})}
function usage(){console.error('motion.mjs language init|apply|verify | plan create|verify | contract seal|verify | review create|verify | detect scan')}
const root=rootOf(take('--project-root'));
if(group==='language'&&cmd==='init'){const o=initLanguage(root);process.stdout.write(JSON.stringify(o,null,2)+'\n')}
else if(group==='language'&&cmd==='apply'){const f=take('--input');if(!f||!fs.existsSync(f))fail('MOTION_LANGUAGE_INPUT_REQUIRED',88);const o=applyLanguage(root,readJson(path.resolve(f)),has('--approve'));process.stdout.write(JSON.stringify(o,null,2)+'\n')}
else if(group==='language'&&cmd==='verify'){const o=verifyLanguage(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(89)}
else if(group==='plan'&&cmd==='create'){const id=take('--task-id');if(!id)fail('TASK_ID_REQUIRED',90);const o=makePlan(root,id,take('--platform','generic')),out=take('--out');if(out)writeJson(path.resolve(out),o);process.stdout.write(JSON.stringify(o,null,2)+'\n')}
else if(group==='plan'&&cmd==='verify'){const f=take('--plan');if(!f||!fs.existsSync(f))fail('MOTION_PLAN_REQUIRED',91);const o=verifyPlan(root,readJson(path.resolve(f)));process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(92)}
else if(group==='contract'&&cmd==='seal'){const f=take('--input');if(!f||!fs.existsSync(f))fail('MOTION_CONTRACT_INPUT_REQUIRED',93);const o=sealContract(root,readJson(path.resolve(f))),out=take('--out');if(out)writeJson(path.resolve(out),o);process.stdout.write(JSON.stringify(o,null,2)+'\n')}
else if(group==='contract'&&cmd==='verify'){const f=take('--contract');if(!f||!fs.existsSync(f))fail('MOTION_CONTRACT_REQUIRED',94);const o=verifyContract(root,readJson(path.resolve(f)));process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(95)}
else if(group==='review'&&cmd==='create'){const f=take('--contract');if(!f||!fs.existsSync(f))fail('MOTION_CONTRACT_REQUIRED',94);const c=readJson(path.resolve(f)),o=review(root,c),out=take('--out');if(out)writeJson(path.resolve(out),o);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(o.status!=='MOTION_PASS')process.exit(96)}
else if(group==='review'&&cmd==='verify'){const rf=take('--report'),cf=take('--contract');if(!rf||!cf||!fs.existsSync(rf)||!fs.existsSync(cf))fail('MOTION_REVIEW_INPUT_REQUIRED',97);const o=verifyReview(root,readJson(path.resolve(rf)),readJson(path.resolve(cf)));process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(98)}
else if(group==='detect'&&cmd==='scan'){const fsArg=String(take('--files','')).split(',').map(x=>x.trim()).filter(Boolean);const o=detect(root,fsArg);process.stdout.write(JSON.stringify(o,null,2)+'\n')}
else{usage();process.exit(2)}
