#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const distRoot=path.resolve(here,'..');
const args=process.argv.slice(2);const [group,cmd]=args;
const HASH=/^[a-f0-9]{64}$/;

function take(flag,fallback=null){const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:fallback}
function has(flag){return args.includes(flag)}
function fail(status,code=1,obj=null){process.stdout.write(JSON.stringify(obj||{status},null,2)+'\n');process.exit(code)}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n','utf8')}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())if(!['integrity_sha256','record_sha256','index_sha256','contract_sha256','review_sha256'].includes(k))o[k]=stable(v[k]);return o}return v}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(stable(v))).digest('hex')}
function fileSha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function policy(){return readJson(path.join(distRoot,'policies','uxui-policy.json')).phase6}
function rootOf(p){const r=path.resolve(p||process.cwd());if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())fail('PROJECT_ROOT_INVALID',90);return r}
function norm(p){return String(p||'').replaceAll('\\','/').replace(/^\.\//,'')}
function inside(root,p){const rr=path.resolve(root)+path.sep,aa=path.resolve(p);return aa===path.resolve(root)||aa.startsWith(rr)}
function validHash(o,field){return typeof o?.[field]==='string'&&HASH.test(o[field])&&o[field]===sha(o)}
function writeText(p,t){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,t,'utf8')}
function refsOnly(obj,prefix=''){const bad=[];const forbidden=new Set(['prompt','completion','transcript','body','content','raw','skill_body','instructions','secret','token','api_key','password']);function rec(v,k=''){if(Array.isArray(v)){v.forEach((x,i)=>rec(x,`${k}[${i}]`));return}if(v&&typeof v==='object'){for(const [a,b] of Object.entries(v)){const key=String(a).toLowerCase();if(forbidden.has(key)&&b!==null&&b!==''&&(!(Array.isArray(b))||b.length))bad.push(`${prefix}${k?`${k}.`:''}${a}`);rec(b,`${k?`${k}.`:''}${a}`)}}}rec(obj);return bad}
function designManifest(root){const p=path.join(root,'.aledevos','design','design-context.json');if(!fs.existsSync(p))fail('DESIGN_CONTEXT_MISSING',91);const m=readJson(p);if(!validHash(m,'integrity_sha256'))fail('DESIGN_CONTEXT_INVALID',92,{status:'DESIGN_CONTEXT_INVALID',errors:['design_context_integrity_mismatch']});return {path:p,obj:m,sha:fileSha(p)}}
function syncDesignContextArtifacts(root,ids){
  const dm=designManifest(root),m=dm.obj,designRoot=path.join(root,'.aledevos','design');
  for(const id of ids){
    const sec=m.sections?.[id];if(!sec)continue;
    const abs=path.join(designRoot,sec.path);
    if(fs.existsSync(abs)&&fs.statSync(abs).isFile())sec.artifact_sha256=fileSha(abs);
  }
  m.context_version=Math.max(6,Number(m.context_version||1));
  m.integrity_sha256='';m.integrity_sha256=sha(m);writeJson(dm.path,m);return m;
}

function paths(root){const p=policy();return {
  a11y:path.join(root,p.accessibility.machine_path),a11yHuman:path.join(root,p.accessibility.human_path),
  responsive:path.join(root,p.responsive.machine_path),responsiveHuman:path.join(root,p.responsive.human_path),
  states:path.join(root,p.states.catalog_path),adrRoot:path.join(root,p.ui_decisions.root),adrIndex:path.join(root,p.ui_decisions.index_path)
}}
function unsetA11y(){return {schema_version:'1.0',status:'UNSET',standard:null,requirements:{semantics:null,keyboard:null,focus:null,labels:null,contrast:null,reduced_motion:null},source_ref:null,approval_ref:null,human_artifact_sha256:null,integrity_sha256:''}}
function unsetResponsive(){return {schema_version:'1.0',status:'UNSET',strategy:null,viewports:[],container_policy:null,overflow_policy:null,source_ref:null,approval_ref:null,human_artifact_sha256:null,integrity_sha256:''}}
function unsetStates(){return {schema_version:'1.0',status:'UNSET',conventions:{},source_ref:null,approval_ref:null,integrity_sha256:''}}
function emptyAdrIndex(){return {schema_version:'1.0',version:1,records:[],index_sha256:''}}
function humanA11y(o){const req=Object.entries(o.requirements||{}).map(([k,v])=>`- ${k}: ${v??'UNSET'}`).join('\n');return `# Accessibility Policy\n\nStatus: ${o.status}\nStandard: ${o.standard??'UNSET'}\nApproval: ${o.approval_ref??'UNSET'}\n\n## Requirements\n${req}\n`}
function humanResponsive(o){const rows=(o.viewports||[]).map(v=>`- ${v.id}: ${v.width}px${v.height?` × ${v.height}px`:''} — ${v.expectation}`).join('\n')||'- UNSET';return `# Responsive Policy\n\nStatus: ${o.status}\nStrategy: ${o.strategy??'UNSET'}\nApproval: ${o.approval_ref??'UNSET'}\n\n## Viewports\n${rows}\n\nContainer policy: ${o.container_policy??'UNSET'}\nOverflow policy: ${o.overflow_policy??'UNSET'}\n`}
function sealWithHuman(machine,humanPath,humanText){writeText(humanPath,humanText);machine.human_artifact_sha256=fileSha(humanPath);machine.integrity_sha256=sha(machine);return machine}
function ensureAdrRoot(ps){
  const legacyPlaceholder='# UI Decision Records\n\nNo decisions recorded yet.\n';
  if(fs.existsSync(ps.adrRoot)){
    const st=fs.statSync(ps.adrRoot);
    if(st.isDirectory())return;
    if(st.isFile()){
      const raw=fs.readFileSync(ps.adrRoot,'utf8');
      if(raw===legacyPlaceholder)fs.unlinkSync(ps.adrRoot);
      else fail('UI_DECISIONS_PATH_COLLISION',126,{status:'UI_DECISIONS_PATH_COLLISION',path:norm(ps.adrRoot),reason:'existing_file_is_not_safe_legacy_placeholder'});
    }else fail('UI_DECISIONS_PATH_COLLISION',126,{status:'UI_DECISIONS_PATH_COLLISION',path:norm(ps.adrRoot),reason:'existing_path_is_not_directory'});
  }
  fs.mkdirSync(ps.adrRoot,{recursive:true});
}
function initStandards(root){designManifest(root);const ps=paths(root);fs.mkdirSync(path.dirname(ps.a11y),{recursive:true});ensureAdrRoot(ps);
  if(!fs.existsSync(ps.a11y)){const o=unsetA11y();sealWithHuman(o,ps.a11yHuman,humanA11y(o));writeJson(ps.a11y,o)}
  if(!fs.existsSync(ps.responsive)){const o=unsetResponsive();sealWithHuman(o,ps.responsiveHuman,humanResponsive(o));writeJson(ps.responsive,o)}
  if(!fs.existsSync(ps.states)){const o=unsetStates();o.integrity_sha256=sha(o);writeJson(ps.states,o)}
  if(!fs.existsSync(ps.adrIndex)){const o=emptyAdrIndex();o.index_sha256=sha(o);writeJson(ps.adrIndex,o)}
  const verified=verifyStandards(root);
  if(verified.valid)syncDesignContextArtifacts(root,['accessibility','responsive']);
  return verified
}
function verifyMachineHuman(machinePath,humanPath,hashField='integrity_sha256'){const errors=[];if(!fs.existsSync(machinePath))return ['missing:'+norm(machinePath)];let o;try{o=readJson(machinePath)}catch{return ['unreadable:'+norm(machinePath)]};if(!validHash(o,hashField))errors.push('integrity_mismatch:'+path.basename(machinePath));if(o.human_artifact_sha256!==undefined&&o.human_artifact_sha256!==null){if(!fs.existsSync(humanPath))errors.push('human_missing:'+path.basename(humanPath));else if(o.human_artifact_sha256!==fileSha(humanPath))errors.push('human_drift:'+path.basename(humanPath))}return errors}
function verifyAdrIndex(root){const ps=paths(root),errors=[];if(!fs.existsSync(ps.adrIndex))return ['adr_index_missing'];let idx;try{idx=readJson(ps.adrIndex)}catch{return ['adr_index_unreadable']};if(!validHash(idx,'index_sha256'))errors.push('adr_index_integrity_mismatch');const ids=new Set();for(const e of idx.records||[]){if(ids.has(e.id))errors.push(`adr_duplicate_id:${e.id}`);ids.add(e.id);const rp=path.join(root,e.path);if(!inside(root,rp)||!fs.existsSync(rp)){errors.push(`adr_record_missing:${e.id}`);continue}const rec=readJson(rp);if(!validHash(rec,'record_sha256'))errors.push(`adr_record_integrity_mismatch:${e.id}`);if(e.record_sha256!==rec.record_sha256)errors.push(`adr_index_record_drift:${e.id}`);if(e.active&&e.superseded_by)errors.push(`adr_active_and_superseded:${e.id}`)}return errors}
function verifyStandards(root){designManifest(root);const ps=paths(root),errors=[];errors.push(...verifyMachineHuman(ps.a11y,ps.a11yHuman));errors.push(...verifyMachineHuman(ps.responsive,ps.responsiveHuman));if(!fs.existsSync(ps.states))errors.push('states_catalog_missing');else{try{const s=readJson(ps.states);if(!validHash(s,'integrity_sha256'))errors.push('states_catalog_integrity_mismatch')}catch{errors.push('states_catalog_unreadable')}}errors.push(...verifyAdrIndex(root));return {status:errors.length?'UI_STANDARDS_INVALID':'UI_STANDARDS_VALID',valid:errors.length===0,errors}}
function approveA11y(root,input,approvalRef){const p=policy(),ps=paths(root);initStandards(root);if(!approvalRef||String(approvalRef).trim().length<3)fail('APPROVAL_REQUIRED',93);const q=readJson(input),errors=[];if(!String(q.standard||'').trim())errors.push('standard_required');for(const k of p.accessibility.required_requirement_keys)if(!String(q.requirements?.[k]||'').trim())errors.push(`requirement_missing:${k}`);if(refsOnly(q,'input:').length)errors.push('inline_sensitive_content_forbidden');if(errors.length)fail('ACCESSIBILITY_PROPOSAL_INVALID',94,{status:'ACCESSIBILITY_PROPOSAL_INVALID',errors});const o={schema_version:'1.0',status:'ACTIVE',standard:String(q.standard),requirements:Object.fromEntries(p.accessibility.required_requirement_keys.map(k=>[k,String(q.requirements[k])])),source_ref:String(q.source_ref||'human-approved'),approval_ref:String(approvalRef),human_artifact_sha256:null,integrity_sha256:''};sealWithHuman(o,ps.a11yHuman,humanA11y(o));writeJson(ps.a11y,o);return o}
function verifyA11y(root){const ps=paths(root);const e=verifyMachineHuman(ps.a11y,ps.a11yHuman);let o=null;if(fs.existsSync(ps.a11y))o=readJson(ps.a11y);return {valid:e.length===0,errors:e,status:o?.status||'MISSING',standard:o?.standard||null}}
function approveResponsive(root,input,approvalRef){const p=policy(),ps=paths(root);initStandards(root);if(!approvalRef||String(approvalRef).trim().length<3)fail('APPROVAL_REQUIRED',95);const q=readJson(input),errors=[];if(!p.responsive.allowed_strategies.includes(q.strategy))errors.push('strategy_invalid');const v=Array.isArray(q.viewports)?q.viewports:[];if(v.length<p.responsive.min_viewports||v.length>p.responsive.max_viewports)errors.push('viewport_count_invalid');const ids=new Set(),widths=new Set();for(const x of v){if(!String(x.id||'').trim())errors.push('viewport_id_required');if(ids.has(x.id))errors.push(`duplicate_viewport_id:${x.id}`);ids.add(x.id);if(!Number.isInteger(x.width)||x.width<p.responsive.width_min||x.width>p.responsive.width_max)errors.push(`viewport_width_invalid:${x.id}`);if(widths.has(x.width))errors.push(`duplicate_viewport_width:${x.width}`);widths.add(x.width);if(!String(x.expectation||'').trim())errors.push(`viewport_expectation_required:${x.id}`)}if(!String(q.container_policy||'').trim())errors.push('container_policy_required');if(!String(q.overflow_policy||'').trim())errors.push('overflow_policy_required');if(refsOnly(q,'input:').length)errors.push('inline_sensitive_content_forbidden');if(errors.length)fail('RESPONSIVE_PROPOSAL_INVALID',96,{status:'RESPONSIVE_PROPOSAL_INVALID',errors});const o={schema_version:'1.0',status:'ACTIVE',strategy:q.strategy,viewports:v.map(x=>({id:String(x.id),width:x.width,...(x.height?{height:x.height}:{}),expectation:String(x.expectation)})).sort((a,b)=>a.width-b.width),container_policy:String(q.container_policy),overflow_policy:String(q.overflow_policy),source_ref:String(q.source_ref||'human-approved'),approval_ref:String(approvalRef),human_artifact_sha256:null,integrity_sha256:''};sealWithHuman(o,ps.responsiveHuman,humanResponsive(o));writeJson(ps.responsive,o);return o}
function verifyResponsive(root){const ps=paths(root);const e=verifyMachineHuman(ps.responsive,ps.responsiveHuman);let o=null;if(fs.existsSync(ps.responsive))o=readJson(ps.responsive);return {valid:e.length===0,errors:e,status:o?.status||'MISSING',strategy:o?.strategy||null,viewports:o?.viewports||[]}}
function approveStates(root,input,approvalRef){const p=policy(),ps=paths(root);initStandards(root);if(!approvalRef||String(approvalRef).trim().length<3)fail('APPROVAL_REQUIRED',97);const q=readJson(input),errors=[];const conv=q.conventions||{};for(const [k,v] of Object.entries(conv)){if(!p.states.allowed_state_types.includes(k))errors.push(`state_type_invalid:${k}`);if(!String(v||'').trim())errors.push(`state_convention_empty:${k}`)}if(!Object.keys(conv).length)errors.push('state_conventions_required');if(refsOnly(q,'input:').length)errors.push('inline_sensitive_content_forbidden');if(errors.length)fail('STATE_CATALOG_INVALID',98,{status:'STATE_CATALOG_INVALID',errors});const o={schema_version:'1.0',status:'ACTIVE',conventions:Object.fromEntries(Object.entries(conv).sort(([a],[b])=>a.localeCompare(b))),source_ref:String(q.source_ref||'human-approved'),approval_ref:String(approvalRef),integrity_sha256:''};o.integrity_sha256=sha(o);writeJson(ps.states,o);return o}
function verifyStates(root){const ps=paths(root),errors=[];if(!fs.existsSync(ps.states))errors.push('states_catalog_missing');let o=null;if(!errors.length){o=readJson(ps.states);if(!validHash(o,'integrity_sha256'))errors.push('states_catalog_integrity_mismatch')}return {valid:errors.length===0,errors,status:o?.status||'MISSING'}}
function baselineStates(kind,p){return p.states.baselines[kind]||[]}
function sealStateContract(root,input,out){const p=policy(),q=readJson(input),errors=[];const surfaces=Array.isArray(q.surfaces)?q.surfaces:[];if(!String(q.task_id||'').trim())errors.push('task_id_required');if(!surfaces.length)errors.push('surfaces_required');if(surfaces.length>p.states.max_surfaces)errors.push('surface_limit_exceeded');for(const s of surfaces){if(!String(s.id||'').trim())errors.push('surface_id_required');if(!p.states.surface_kinds.includes(s.kind))errors.push(`surface_kind_invalid:${s.id}`);const req=new Set([...(baselineStates(s.kind,p)),...((s.required_states||[]).map(String))]);for(const st of req)if(!p.states.allowed_state_types.includes(st))errors.push(`state_type_invalid:${s.id}:${st}`);for(const ev of s.evidence||[]){if(!req.has(ev.state))errors.push(`unexpected_state_evidence:${s.id}:${ev.state}`);if(!String(ev.evidence_ref||'').trim())errors.push(`state_evidence_ref_required:${s.id}:${ev.state}`);const bad=refsOnly(ev,`surface:${s.id}:`);if(bad.length)errors.push(`state_evidence_inline_forbidden:${s.id}:${ev.state}`)}s._required=[...req].sort()}
  if(refsOnly(q,'contract:').length)errors.push('inline_sensitive_content_forbidden');if(errors.length)fail('UI_STATE_CONTRACT_INVALID',99,{status:'UI_STATE_CONTRACT_INVALID',errors});const dm=designManifest(root);const o={schema_version:'1.0',task_id:String(q.task_id),surfaces:surfaces.map(s=>({id:String(s.id),kind:s.kind,required_states:s._required,evidence:(s.evidence||[]).map(e=>({state:String(e.state),evidence_ref:String(e.evidence_ref)})).sort((a,b)=>a.state.localeCompare(b.state))})),design_context_sha256:dm.sha,contract_sha256:''};o.contract_sha256=sha(o);writeJson(out,o);return o}
function verifyStateContract(root,pth){const errors=[];if(!pth||!fs.existsSync(pth))return {valid:false,errors:['state_contract_missing']};const o=readJson(pth);if(!validHash(o,'contract_sha256'))errors.push('state_contract_integrity_mismatch');const dm=designManifest(root);if(o.design_context_sha256!==dm.sha)errors.push('design_context_drift_since_state_contract');for(const s of o.surfaces||[]){const got=new Set((s.evidence||[]).map(e=>e.state));for(const r of s.required_states||[])if(!got.has(r))errors.push(`state_evidence_missing:${s.id}:${r}`)}return {valid:errors.length===0,errors,task_id:o.task_id,status:errors.length?'UI_STATES_BLOCKED':'UI_STATES_PASS',contract_sha256:o.contract_sha256}}
function adrRecordPath(root,id){return path.join(paths(root).adrRoot,`${id}.json`)}
function activeEntry(idx,id){return (idx.records||[]).find(x=>x.id===id&&x.active)||null}
function createAdr(root,input){const p=policy(),ps=paths(root);initStandards(root);const q=readJson(input),errors=[];if(!new RegExp(p.ui_decisions.id_pattern).test(String(q.id||'')))errors.push('adr_id_invalid');for(const k of ['title','context','decision','consequences'])if(String(q[k]||'').trim().length<p.ui_decisions.min_text_chars)errors.push(`adr_${k}_too_short`);if(refsOnly(q,'adr:').length)errors.push('inline_sensitive_content_forbidden');if(errors.length)fail('UI_ADR_INVALID',100,{status:'UI_ADR_INVALID',errors});const rp=adrRecordPath(root,q.id);if(fs.existsSync(rp))fail('UI_ADR_ALREADY_EXISTS',101);const idx=readJson(ps.adrIndex);if(!validHash(idx,'index_sha256'))fail('UI_ADR_INDEX_INVALID',102);let supersedes=null;if(q.supersedes){const e=activeEntry(idx,String(q.supersedes));if(!e)fail('UI_ADR_SUPERSEDES_NOT_ACTIVE',103);supersedes=String(q.supersedes)}const rec={schema_version:'1.0',id:String(q.id),title:String(q.title),context:String(q.context),decision:String(q.decision),consequences:String(q.consequences),scope:(q.scope||[]).map(norm).sort(),source_refs:(q.source_refs||[]).map(String).sort(),approval_ref:String(q.approval_ref||'').trim(),supersedes,record_sha256:''};if(rec.approval_ref.length<3)fail('UI_ADR_APPROVAL_REQUIRED',104);rec.record_sha256=sha(rec);writeJson(rp,rec);if(supersedes){const old=idx.records.find(x=>x.id===supersedes);old.active=false;old.superseded_by=rec.id}idx.records.push({id:rec.id,path:norm(path.relative(root,rp)),record_sha256:rec.record_sha256,active:true,superseded_by:null});idx.records.sort((a,b)=>a.id.localeCompare(b.id));idx.version=(idx.version||0)+1;idx.index_sha256=sha(idx);writeJson(ps.adrIndex,idx);return rec}
function verifyAdr(root,id){const ps=paths(root),errors=verifyAdrIndex(root),idx=fs.existsSync(ps.adrIndex)?readJson(ps.adrIndex):null,e=idx?.records?.find(x=>x.id===id);if(!e)errors.push('adr_not_indexed');return {valid:errors.length===0,errors,id,active:!!e?.active,superseded_by:e?.superseded_by||null,record_sha256:e?.record_sha256||null}}
function scanSource(root,files,responsive){const p=policy(),blockers=[],warnings=[],hashes=[];const minWidth=responsive?.status==='ACTIVE'&&responsive.viewports?.length?Math.min(...responsive.viewports.map(v=>v.width)):null;for(const rp0 of files){const rp=norm(rp0),abs=path.join(root,rp);if(!inside(root,abs)||!fs.existsSync(abs)){blockers.push({rule_id:'SOURCE_EVIDENCE',message:'changed_file_missing_or_external',file:rp});continue}const st=fs.statSync(abs);if(!st.isFile()){continue}hashes.push({path:rp,sha256:fileSha(abs)});if(st.size>p.review.max_scan_bytes){warnings.push({rule_id:'SOURCE_SCAN_LIMIT',message:'source_too_large_for_static_scan',file:rp});continue}const text=fs.readFileSync(abs,'utf8');if(/<img\b(?![^>]*\balt\s*=)[^>]*>/i.test(text))blockers.push({rule_id:'A11Y_IMG_ALT',message:'image_without_alt_detected',file:rp});if(/<(div|span)\b[^>]*\bonClick\s*=/.test(text)&&!/(role\s*=|tabIndex\s*=|onKeyDown\s*=|onKeyUp\s*=)/.test(text))blockers.push({rule_id:'A11Y_INTERACTIVE_SEMANTICS',message:'nonsemantic_click_target_without_keyboard_affordance',file:rp});if(/outline\s*:\s*(none|0)\b/i.test(text)&&!/(focus-visible|:focus\b)/i.test(text))blockers.push({rule_id:'A11Y_FOCUS_VISIBLE',message:'focus_outline_removed_without_visible_replacement',file:rp});if(minWidth!==null){const re=/min-width\s*:\s*(\d+)px/gi;let m;while((m=re.exec(text))){const v=Number(m[1]);if(v>minWidth)blockers.push({rule_id:'RESPONSIVE_MIN_WIDTH',message:`min_width_${v}px_exceeds_narrowest_${minWidth}px`,file:rp})}}if(/overflow-x\s*:\s*hidden/i.test(text))warnings.push({rule_id:'RESPONSIVE_OVERFLOW_MASK',message:'overflow-x hidden may mask layout defects',file:rp})}return {blockers,warnings,hashes}}
function validateEvidenceRefs(list,errors,prefix){const arr=Array.isArray(list)?list:[];for(const e of arr){if(!String(e.evidence_ref||'').trim())errors.push(`${prefix}_evidence_ref_required:${e.criterion||e.viewport_id||'unknown'}`);if(refsOnly(e,`${prefix}:`).length)errors.push(`${prefix}_evidence_inline_forbidden:${e.criterion||e.viewport_id||'unknown'}`)}return arr}
function validAdrRefs(root,ids){const bad=[];for(const id of ids||[]){const v=verifyAdr(root,String(id));if(!v.valid||!v.active)bad.push(String(id))}return bad}
function createReview(root,input,out){const p=policy(),q=readJson(input),errors=[],blockers=[],warnings=[];const std=verifyStandards(root);if(!std.valid)errors.push(...std.errors);const ps=paths(root),a11y=fs.existsSync(ps.a11y)?readJson(ps.a11y):null,resp=fs.existsSync(ps.responsive)?readJson(ps.responsive):null,states=fs.existsSync(ps.states)?readJson(ps.states):null;if(String(q.task_id||'').trim()==='')errors.push('task_id_required');const changed=(q.changed_files||[]).map(norm);if(changed.length>p.review.max_changed_files)errors.push('changed_file_limit_exceeded');const adrBad=validAdrRefs(root,q.adr_refs||[]);for(const id of adrBad)errors.push(`adr_ref_invalid_or_inactive:${id}`);const exceptions=new Map();for(const x of q.exceptions||[]){if(!x?.rule_id||!x?.approval_ref||!x?.reason)continue;const v=verifyAdr(root,String(x.approval_ref));if(v.valid&&v.active)exceptions.set(String(x.rule_id),String(x.approval_ref));else errors.push(`exception_adr_invalid:${x.rule_id}`)}
  const aReq=!!q.accessibility?.required;if(aReq&&a11y?.status!=='ACTIVE')errors.push('accessibility_policy_not_active');const aEv=validateEvidenceRefs(q.accessibility?.evidence,errors,'accessibility');if(aReq&&a11y?.status==='ACTIVE'){const got=new Set(aEv.map(x=>x.criterion));for(const k of p.accessibility.required_requirement_keys)if(!got.has(k))errors.push(`accessibility_evidence_missing:${k}`)}
  const rReq=!!q.responsive?.required;if(rReq&&resp?.status!=='ACTIVE')errors.push('responsive_policy_not_active');const rEv=validateEvidenceRefs(q.responsive?.evidence,errors,'responsive');if(rReq&&resp?.status==='ACTIVE'){const got=new Set(rEv.map(x=>x.viewport_id));for(const v of resp.viewports||[])if(!got.has(v.id))errors.push(`responsive_evidence_missing:${v.id}`)}
  let stReview={valid:true,status:'NOT_APPLICABLE',contract_sha256:null,errors:[]};if(q.states?.required){const cp=q.states.contract_path?path.resolve(root,q.states.contract_path):null;if(!cp||!inside(root,cp))errors.push('state_contract_path_invalid');else{stReview=verifyStateContract(root,cp);if(!stReview.valid)errors.push(...stReview.errors)}}
  if(refsOnly(q,'review:').length)errors.push('inline_sensitive_content_forbidden');
  const scan=scanSource(root,changed,resp);for(const b of scan.blockers){if(exceptions.has(b.rule_id))warnings.push({...b,message:`approved_exception:${b.message}`,approval_ref:exceptions.get(b.rule_id)});else blockers.push(b)}warnings.push(...scan.warnings);if(errors.length)blockers.push(...errors.map(e=>({rule_id:'PHASE6_EVIDENCE',message:e,file:null})));
  const dm=designManifest(root);const o={schema_version:'1.0',task_id:String(q.task_id||''),status:blockers.length?'UI_STANDARDS_BLOCKED':'UI_STANDARDS_PASS',blockers,warnings,dimensions:{responsive:rReq?(resp?.status==='ACTIVE'&&!(errors.some(x=>x.startsWith('responsive_')))?'VERIFIED':'UNVERIFIED'):'NOT_APPLICABLE',accessibility:aReq?(a11y?.status==='ACTIVE'&&!(errors.some(x=>x.startsWith('accessibility_')))?'VERIFIED':'UNVERIFIED'):'NOT_APPLICABLE',states:q.states?.required?(stReview.valid?'VERIFIED':'UNVERIFIED'):'NOT_APPLICABLE'},source_hashes:scan.hashes.sort((a,b)=>a.path.localeCompare(b.path)),accessibility_policy_sha256:fs.existsSync(ps.a11y)?fileSha(ps.a11y):'0'.repeat(64),responsive_policy_sha256:fs.existsSync(ps.responsive)?fileSha(ps.responsive):'0'.repeat(64),states_catalog_sha256:fs.existsSync(ps.states)?fileSha(ps.states):'0'.repeat(64),adr_index_sha256:fs.existsSync(ps.adrIndex)?fileSha(ps.adrIndex):'0'.repeat(64),design_context_sha256:dm.sha,state_contract_sha256:stReview.contract_sha256||null,review_sha256:''};o.review_sha256=sha(o);writeJson(out,o);return o}
function verifyReview(root,pth,expectedTask=null){const errors=[];if(!pth||!fs.existsSync(pth))return {valid:false,errors:['phase6_review_missing']};const o=readJson(pth);if(!validHash(o,'review_sha256'))errors.push('phase6_review_integrity_mismatch');if(expectedTask&&o.task_id!==expectedTask)errors.push('phase6_review_task_mismatch');const ps=paths(root),dm=designManifest(root);if(o.design_context_sha256!==dm.sha)errors.push('design_context_drift_since_phase6_review');for(const [k,p] of [['accessibility_policy_sha256',ps.a11y],['responsive_policy_sha256',ps.responsive],['states_catalog_sha256',ps.states],['adr_index_sha256',ps.adrIndex]])if(fs.existsSync(p)&&o[k]!==fileSha(p))errors.push(`${k.replace('_sha256','')}_drift_since_phase6_review`);for(const s of o.source_hashes||[]){const abs=path.join(root,s.path);if(!inside(root,abs)||!fs.existsSync(abs)||fileSha(abs)!==s.sha256)errors.push(`source_drift:${s.path}`)}return {valid:errors.length===0,errors,status:o.status,task_id:o.task_id,dimensions:o.dimensions,review_sha256:o.review_sha256}}

function usage(){console.error('ui-quality.mjs standards init|verify | accessibility approve|verify | responsive approve|verify | states approve|verify|seal|contract-verify | adr create|verify | review create|verify')}
if(group==='standards'&&cmd==='init'){
  const root=rootOf(take('--project-root'));const o=initStandards(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(110);
}else if(group==='standards'&&cmd==='verify'){
  const root=rootOf(take('--project-root'));const o=verifyStandards(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(111);
}else if(group==='accessibility'&&cmd==='approve'){
  const root=rootOf(take('--project-root')),inp=take('--input');if(!inp||!fs.existsSync(inp))fail('ACCESSIBILITY_INPUT_REQUIRED',112);const o=approveA11y(root,path.resolve(inp),take('--approval-ref'));process.stdout.write(JSON.stringify({status:'ACCESSIBILITY_ACTIVE',integrity_sha256:o.integrity_sha256},null,2)+'\n');
}else if(group==='accessibility'&&cmd==='verify'){
  const root=rootOf(take('--project-root'));const o=verifyA11y(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(113);
}else if(group==='responsive'&&cmd==='approve'){
  const root=rootOf(take('--project-root')),inp=take('--input');if(!inp||!fs.existsSync(inp))fail('RESPONSIVE_INPUT_REQUIRED',114);const o=approveResponsive(root,path.resolve(inp),take('--approval-ref'));process.stdout.write(JSON.stringify({status:'RESPONSIVE_ACTIVE',integrity_sha256:o.integrity_sha256},null,2)+'\n');
}else if(group==='responsive'&&cmd==='verify'){
  const root=rootOf(take('--project-root'));const o=verifyResponsive(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(115);
}else if(group==='states'&&cmd==='approve'){
  const root=rootOf(take('--project-root')),inp=take('--input');if(!inp||!fs.existsSync(inp))fail('STATES_INPUT_REQUIRED',116);const o=approveStates(root,path.resolve(inp),take('--approval-ref'));process.stdout.write(JSON.stringify({status:'UI_STATES_CATALOG_ACTIVE',integrity_sha256:o.integrity_sha256},null,2)+'\n');
}else if(group==='states'&&cmd==='verify'){
  const root=rootOf(take('--project-root'));const o=verifyStates(root);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(117);
}else if(group==='states'&&cmd==='seal'){
  const root=rootOf(take('--project-root')),inp=take('--input'),out=take('--out');if(!inp||!out||!fs.existsSync(inp))fail('STATE_CONTRACT_INPUT_REQUIRED',118);const o=sealStateContract(root,path.resolve(inp),path.resolve(out));process.stdout.write(JSON.stringify({status:'UI_STATE_CONTRACT_READY',contract_sha256:o.contract_sha256},null,2)+'\n');
}else if(group==='states'&&cmd==='contract-verify'){
  const root=rootOf(take('--project-root')),cp=take('--contract');const o=verifyStateContract(root,cp?path.resolve(cp):null);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(119);
}else if(group==='adr'&&cmd==='create'){
  const root=rootOf(take('--project-root')),inp=take('--input');if(!inp||!fs.existsSync(inp))fail('UI_ADR_INPUT_REQUIRED',120);const o=createAdr(root,path.resolve(inp));process.stdout.write(JSON.stringify({status:'UI_ADR_CREATED',id:o.id,record_sha256:o.record_sha256},null,2)+'\n');
}else if(group==='adr'&&cmd==='verify'){
  const root=rootOf(take('--project-root')),id=take('--id');if(!id)fail('UI_ADR_ID_REQUIRED',121);const o=verifyAdr(root,id);process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(122);
}else if(group==='review'&&cmd==='create'){
  const root=rootOf(take('--project-root')),inp=take('--input'),out=take('--out');if(!inp||!out||!fs.existsSync(inp))fail('PHASE6_REVIEW_INPUT_REQUIRED',123);const o=createReview(root,path.resolve(inp),path.resolve(out));process.stdout.write(JSON.stringify(o,null,2)+'\n');if(o.status!=='UI_STANDARDS_PASS')process.exit(124);
}else if(group==='review'&&cmd==='verify'){
  const root=rootOf(take('--project-root')),rp=take('--report');const o=verifyReview(root,rp?path.resolve(rp):null,take('--task-id'));process.stdout.write(JSON.stringify(o,null,2)+'\n');if(!o.valid)process.exit(125);
}else{usage();process.exit(2)}
