#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const argv=process.argv.slice(2), cmd=argv[0], sub=argv[1];
const take=(n,f=null)=>{const i=argv.indexOf(n);return i>=0&&argv[i+1]!==undefined?argv[i+1]:f};
const has=n=>argv.includes(n);
const fail=(m,c=1)=>{console.error(m);process.exit(c)};
const readJson=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const writeJson=(p,o)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(o,null,2)+'\n','utf8')};
const sha256Bytes=b=>crypto.createHash('sha256').update(b).digest('hex');
const sha256File=p=>sha256Bytes(fs.readFileSync(p));
const canonicalInstructionText=s=>String(s).replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');
const sha256InstructionFile=p=>sha256Bytes(Buffer.from(canonicalInstructionText(fs.readFileSync(p,'utf8')),'utf8'));
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o;}return v;}
const sha256Object=o=>sha256Bytes(Buffer.from(JSON.stringify(stable(o))));
const withoutIntegrity=o=>{const x=structuredClone(o);delete x.integrity;return x};
const inside=(r,p)=>{const rr=path.resolve(r),pp=path.resolve(p);return pp===rr||pp.startsWith(rr+path.sep)};
const normArr=xs=>[...new Set((xs||[]).map(String))].sort();
const validId=v=>typeof v==='string'&&/^[a-z0-9][a-z0-9._-]*$/.test(v);
const rel=(root,p)=>path.relative(root,p).replaceAll('\\','/');
const policyPath=r=>path.join(r,'.aledevos','skillsystem','policies','skill-policy.json');
const catalogsDir=r=>path.join(r,'.aledevos','skillsystem','catalogs');
const bindingPath=(r,a)=>path.join(r,'.aledevos','skillsystem','bindings',`${a}.json`);
const discoveryConfigPath=(r,a)=>path.join(r,'.aledevos','skillsystem','discovery',`${a}.json`);
const registryPath=(r,a)=>path.join(r,'.aledevos','skills','registries',`${a}.json`);
const discoveryPath=(r,a)=>path.join(r,'.aledevos','skills','discoveries',`${a}.json`);
const routesDir=r=>path.join(r,'.aledevos','state','skills','routes');
const compositionsDir=r=>path.join(r,'.aledevos','state','skills','compositions');
const loadPacketsDir=r=>path.join(r,'.aledevos','state','skills','loads');
const executionHandoffsDir=r=>path.join(r,'.aledevos','state','skills','execution-handoffs');
const governanceDir=r=>path.join(r,'.aledevos','state','skills','governance');
const executionReceiptsDir=r=>path.join(r,'.aledevos','state','skills','executions');
const skillTelemetryRoot=r=>path.join(r,'.aledevos','state','telemetry','skills');
const contextPolicyPath=r=>path.join(r,'.aledevos','contextos','policies','context-policy.json');
const safeTaskId=v=>String(v).replace(/[^a-zA-Z0-9._-]/g,'_');
const projectConfigPath=r=>path.join(r,'.aledevos','project.json');
function normalizeAdapter(a){const x=String(a||'').trim().toLowerCase();return x==='gemini'?'antigravity':x}
function installedAdapters(r){const p=projectConfigPath(r);if(!fs.existsSync(p))return[];const q=readJson(p),xs=Array.isArray(q.adapters)?q.adapters:(q.adapter?[q.adapter]:[]);return normArr(xs.map(normalizeAdapter).filter(Boolean))}
function resolveAdapter(r,a=null){const requested=normalizeAdapter(a);if(requested)return requested;const xs=installedAdapters(r);if(xs.length===1)return xs[0];if(xs.length===0)fail('SKILL_ADAPTER_NOT_CONFIGURED',30);fail('SKILL_ADAPTER_REQUIRED_FOR_MULTI_ADAPTER_PROJECT',31)}
const estimateTokensText=s=>Math.max(1,Math.ceil(Buffer.byteLength(String(s),'utf8')/4));
function loadPolicy(r){const p=policyPath(r);if(!fs.existsSync(p))fail(`SKILL_POLICY_NOT_FOUND: ${p}`,20);return readJson(p)}
function validateDescriptor(s,p){const e=[];for(const k of ['schema_version','id','domain','role','description','source_kind','provenance','capabilities','intents','dependencies','conflicts','context_loading','trust','declared_status'])if(s?.[k]===undefined)e.push(`missing:${k}`);if(s?.schema_version!=='1.0')e.push('schema_version');if(!validId(s?.id))e.push('id');for(const k of ['capabilities','intents','dependencies','conflicts'])if(!Array.isArray(s?.[k]))e.push(`${k}:array`);for(const x of [...(s?.capabilities||[]),...(s?.intents||[])])if(!validId(x))e.push(`token:${x}`);if(!p.allowed_source_kinds.includes(s?.source_kind))e.push('source_kind');if(!p.allowed_trust.includes(s?.trust))e.push('trust');if(!p.allowed_declared_status.includes(s?.declared_status))e.push('declared_status');if(s?.source_kind==='bundled-core'&&p.require_source_hash_for_bundled_skills){if(!/^[a-f0-9]{64}$/.test(s?.instruction_sha256||''))e.push('instruction_sha256');if(!s?.instruction_ref)e.push('instruction_ref')}if(s?.source_kind==='external-declared'&&s?.instruction_sha256)e.push('external_hash_must_be_null');return e;}
function loadCatalogs(r,p){const d=catalogsDir(r);if(!fs.existsSync(d))fail(`SKILL_CATALOG_DIR_NOT_FOUND: ${d}`,21);const skills=[],meta=[];for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.json')).sort()){const fp=path.join(d,f),c=readJson(fp);if(c?.schema_version!=='1.0'||!Array.isArray(c?.skills))fail(`INVALID_SKILL_CATALOG: ${f}`,22);meta.push({file:f,catalog_id:c.catalog_id||f,catalog_version:c.catalog_version||null,sha256:sha256File(fp)});for(const s of c.skills){const er=validateDescriptor(s,p);if(er.length)fail(`INVALID_SKILL_DESCRIPTOR ${s?.id||'?'}: ${er.join(',')}`,23);skills.push(structuredClone(s));}}const seen=new Set();for(const s of skills){if(seen.has(s.id))fail(`DUPLICATE_SKILL_ID: ${s.id}`,24);seen.add(s.id)}return{skills,catalogMeta:meta};}
function loadBindings(r,a){const p=bindingPath(r,a);if(!fs.existsSync(p))return{adapter:a,binding_version:null,bindings:[]};const b=readJson(p);if(b?.schema_version!=='1.0'||b?.adapter!==a||!Array.isArray(b?.bindings))fail(`INVALID_SKILL_BINDING_FILE: ${p}`,25);return b;}
function loadDiscoveryConfig(r,a){const p=discoveryConfigPath(r,a);if(!fs.existsSync(p))fail(`DISCOVERY_CONFIG_NOT_FOUND: ${p}`,40);const c=readJson(p);if(c?.schema_version!=='1.0'||c?.adapter!==a||!Array.isArray(c?.roots))fail(`INVALID_DISCOVERY_CONFIG: ${p}`,41);return c;}
function findInstruction(dir,names){for(const n of names||['SKILL.md']){const p=path.join(dir,n);if(fs.existsSync(p)&&fs.statSync(p).isFile())return p;}return null;}
function findSidecar(dir,names){for(const n of names||['aledevos-skill.json']){const p=path.join(dir,n);if(fs.existsSync(p)&&fs.statSync(p).isFile())return p;}return null;}
function scanDirs(root,recursive){if(!fs.existsSync(root)||!fs.statSync(root).isDirectory())return[];const out=[];const walk=d=>{for(const ent of fs.readdirSync(d,{withFileTypes:true})){if(!ent.isDirectory())continue;const p=path.join(d,ent.name);out.push(p);if(recursive)walk(p)}};walk(root);return out;}
function discoveryScan(projectRoot,adapter){const cfg=loadDiscoveryConfig(projectRoot,adapter),policy=loadPolicy(projectRoot),declared=loadCatalogs(projectRoot,policy).skills;const byId=new Map(declared.map(x=>[x.id,x]));const found=[],sources=[];for(const rootDef of cfg.roots){const abs=path.resolve(projectRoot,rootDef.path);if(!inside(projectRoot,abs)&&!cfg.allow_external_roots)fail(`EXTERNAL_DISCOVERY_ROOT_DENIED: ${abs}`,42);if(rootDef.required&&!fs.existsSync(abs))fail(`DISCOVERY_ROOT_MISSING: ${abs}`,43);sources.push({path:inside(projectRoot,abs)?rel(projectRoot,abs):abs,recursive:!!rootDef.recursive,exists:fs.existsSync(abs)});for(const d of scanDirs(abs,!!rootDef.recursive)){const inst=findInstruction(d,cfg.instruction_names);if(!inst)continue;const id=path.basename(d);if(!validId(id))continue;const side=findSidecar(d,cfg.sidecar_names);let sideMeta=null;if(side){sideMeta=readJson(side);if(sideMeta?.schema_version!=='1.0'||sideMeta?.id!==id)fail(`INVALID_SKILL_SIDECAR: ${side}`,44);}const seed=byId.get(id);const metadataSource=sideMeta?'sidecar':seed?'declared-catalog':'none';found.push({id,path:inside(projectRoot,inst)?rel(projectRoot,inst):inst,instruction_sha256:sha256InstructionFile(inst),sidecar_path:side?(inside(projectRoot,side)?rel(projectRoot,side):side):null,sidecar_sha256:side?sha256File(side):null,metadata_source:metadataSource,matched_declared:!!seed,can_register:!!seed||!!sideMeta});}}
found.sort((a,b)=>a.id.localeCompare(b.id));const snap={schema_version:'1.0',created_at:new Date().toISOString(),adapter,sources,skills:found,summary:{discovered:found.length,matched_declared:found.filter(x=>x.matched_declared).length,sidecar_backed:found.filter(x=>x.metadata_source==='sidecar').length,uncataloged:found.filter(x=>!x.can_register).length},integrity:{algorithm:'sha256',payload_sha256:''}};snap.integrity.payload_sha256=sha256Object(withoutIntegrity(snap));writeJson(discoveryPath(projectRoot,adapter),snap);return snap;}
function verifyDiscovery(projectRoot,adapter){const p=discoveryPath(projectRoot,adapter);if(!fs.existsSync(p))return{valid:false,errors:['discovery_snapshot_missing']};const d=readJson(p),e=[];if(d.adapter!==adapter)e.push('discovery_adapter_mismatch');if(d?.integrity?.payload_sha256!==sha256Object(withoutIntegrity(d)))e.push('discovery_integrity_mismatch');for(const s of d.skills||[]){const abs=path.resolve(projectRoot,s.path);if(!fs.existsSync(abs))e.push(`missing:${s.id}`);else if(sha256InstructionFile(abs)!==s.instruction_sha256)e.push(`drift:${s.id}`);if(s.sidecar_path){const sp=path.resolve(projectRoot,s.sidecar_path);if(!fs.existsSync(sp)||sha256File(sp)!==s.sidecar_sha256)e.push(`sidecar_drift:${s.id}`)}}return{valid:e.length===0,errors:e,summary:d.summary||{}};}
function runtimeDescriptorFromSidecar(projectRoot,item){const sp=path.resolve(projectRoot,item.sidecar_path),m=readJson(sp);return{schema_version:'1.0',id:m.id,display_name:m.display_name||m.id,domain:m.domain,role:m.role||'external-specialist',description:m.description||'',source_kind:'runtime-discovered',provenance:`runtime-sidecar:${item.sidecar_path}`,instruction_ref:item.path,instruction_sha256:item.instruction_sha256,capabilities:normArr(m.capabilities),intents:normArr(m.intents),dependencies:normArr(m.dependencies),conflicts:normArr(m.conflicts),context_loading:'on-demand',trust:'runtime-verified',declared_status:'DISCOVERED'};}
function mergeDiscovery(projectRoot,adapter,descriptors,policy){const p=discoveryPath(projectRoot,adapter);if(!fs.existsSync(p))return{descriptors,discovery:null,byId:new Map()};const v=verifyDiscovery(projectRoot,adapter);if(!v.valid&&policy.fail_closed_on_discovery_drift)fail(`SKILL_DISCOVERY_VALIDATION_FAILED: ${v.errors.join(', ')}`,45);const d=readJson(p),byId=new Map((d.skills||[]).map(x=>[x.id,x]));const out=descriptors.map(x=>structuredClone(x));const known=new Set(out.map(x=>x.id));for(const item of d.skills||[]){if(!known.has(item.id)&&item.sidecar_path){const x=runtimeDescriptorFromSidecar(projectRoot,item),er=validateDescriptor(x,policy);if(er.length)fail(`INVALID_DISCOVERED_SKILL ${x.id}: ${er.join(',')}`,46);out.push(x);known.add(x.id)}}return{descriptors:out,discovery:d,byId};}
function bindSkills(projectRoot,adapter,desc,bindingDoc,policy,discoveryById){const byBind=new Map((bindingDoc.bindings||[]).map(x=>[x.skill_id,x]));return desc.map(s=>{const x=structuredClone(s),b=byBind.get(s.id),di=discoveryById.get(s.id);let rt={adapter,path:null,status:'DECLARED_UNRESOLVED',usable:false,actual_sha256:null,expected_sha256:null,metadata_trust:s.source_kind==='bundled-core'?'bundled':s.source_kind==='runtime-discovered'?'runtime-verified':'declared'};if(b){const abs=path.resolve(projectRoot,b.path);rt.path=b.path.replaceAll('\\','/');rt.expected_sha256=b.expected_sha256;if(!inside(projectRoot,abs))rt.status='MISSING_SOURCE';else if(!fs.existsSync(abs))rt.status='MISSING_BINDING';else{rt.actual_sha256=sha256InstructionFile(abs);rt.status=rt.actual_sha256===b.expected_sha256?'AVAILABLE':'BINDING_DRIFT';rt.usable=rt.status==='AVAILABLE';}}else if(di&&di.can_register){const abs=path.resolve(projectRoot,di.path);rt.path=di.path;rt.expected_sha256=di.instruction_sha256;rt.actual_sha256=fs.existsSync(abs)?sha256InstructionFile(abs):null;rt.status=!fs.existsSync(abs)?'MISSING_SOURCE':rt.actual_sha256===di.instruction_sha256?'AVAILABLE':'DISCOVERY_DRIFT';rt.usable=rt.status==='AVAILABLE';rt.discovery={metadata_source:di.metadata_source,sidecar_path:di.sidecar_path};}else if(s.source_kind==='bundled-core')rt.status='MISSING_BINDING';if(!policy.allowed_runtime_status.includes(rt.status))fail(`UNSUPPORTED_RUNTIME_STATUS:${rt.status}`,28);x.capabilities=normArr(x.capabilities);x.intents=normArr(x.intents);x.dependencies=normArr(x.dependencies);x.conflicts=normArr(x.conflicts);x.runtime=rt;return x;}).sort((a,b)=>a.id.localeCompare(b.id));}
function capIndex(skills){const idx={};for(const s of skills)for(const c of s.capabilities){(idx[c]??=[]).push(s.id)}for(const k of Object.keys(idx))idx[k]=[...new Set(idx[k])].sort();return Object.fromEntries(Object.entries(idx).sort(([a],[b])=>a.localeCompare(b)));}
function buildRegistry(projectRoot,adapter){adapter=resolveAdapter(projectRoot,adapter);const p=loadPolicy(projectRoot),base=loadCatalogs(projectRoot,p),m=mergeDiscovery(projectRoot,adapter,base.skills,p),bind=loadBindings(projectRoot,adapter),bound=bindSkills(projectRoot,adapter,m.descriptors,bind,p,m.byId);const bad=bound.filter(x=>['BINDING_DRIFT','MISSING_BINDING','MISSING_SOURCE','DISCOVERY_DRIFT'].includes(x.runtime.status)&&x.source_kind==='bundled-core');if(p.fail_closed_on_binding_drift&&bad.length)fail(`SKILL_BINDING_VALIDATION_FAILED: ${bad.map(x=>`${x.id}:${x.runtime.status}`).join(', ')}`,29);const summary={total:bound.length,usable:bound.filter(x=>x.runtime.usable).length,bundled:bound.filter(x=>x.source_kind==='bundled-core').length,external_declared:bound.filter(x=>x.source_kind==='external-declared').length,runtime_discovered:bound.filter(x=>x.source_kind==='runtime-discovered').length,unresolved:bound.filter(x=>x.runtime.status==='DECLARED_UNRESOLVED').length,discovery_uncataloged:(m.discovery?.summary?.uncataloged)||0};const reg={schema_version:'1.0',registry_version:p.registry_version,created_at:new Date().toISOString(),adapter,catalogs:base.catalogMeta,discovery:m.discovery?{snapshot_sha256:m.discovery.integrity.payload_sha256,summary:m.discovery.summary}:null,skills:bound,capability_index:capIndex(bound),summary,phase_boundary:p.phase_boundary,integrity:{algorithm:'sha256',payload_sha256:''}};reg.integrity.payload_sha256=sha256Object(withoutIntegrity(reg));writeJson(registryPath(projectRoot,adapter),reg);return reg;}
function verifyRegistry(r,adapter){adapter=resolveAdapter(r,adapter);const p=registryPath(r,adapter);if(!fs.existsSync(p))return{valid:false,errors:['registry_missing'],adapter};const reg=readJson(p),e=[];if(reg.adapter!==adapter)e.push('registry_adapter_mismatch');if(reg.integrity?.payload_sha256!==sha256Object(withoutIntegrity(reg)))e.push('registry_integrity_mismatch');for(const s of reg.skills||[])if(s.runtime?.usable){const abs=path.resolve(r,s.runtime.path||'');if(!fs.existsSync(abs))e.push(`usable_missing:${s.id}`);else if(sha256InstructionFile(abs)!==s.runtime.expected_sha256)e.push(`usable_drift:${s.id}`)}return{valid:e.length===0,errors:e,summary:reg.summary,integrity:reg.integrity?.payload_sha256,adapter};}
function validateRouteRequest(q,p){const e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');for(const k of ['required_capabilities','preferred_capabilities','intents','domains'])if(!Array.isArray(q?.[k]))e.push(`${k}:array`);for(const x of [...(q?.required_capabilities||[]),...(q?.preferred_capabilities||[]),...(q?.intents||[])])if(!validId(x))e.push(`invalid_token:${x}`);const m=q?.max_skills??p.max_route_skills;if(!Number.isInteger(m)||m<1||m>p.max_route_skills)e.push('max_skills');return e;}
function scoreSkill(s,missing,req){const caps=new Set(s.capabilities||[]),ints=new Set(s.intents||[]);const newReq=[...missing].filter(x=>caps.has(x)).length,preferred=(req.preferred_capabilities||[]).filter(x=>caps.has(x)).length,intent=(req.intents||[]).filter(x=>ints.has(x)).length,domain=(req.domains||[]).includes(s.domain)?1:0;return{newReq,score:newReq*100+preferred*20+intent*10+domain*5};}
function planRoute(projectRoot,req){const adapter=resolveAdapter(projectRoot,req.adapter),p=loadPolicy(projectRoot),v=verifyRegistry(projectRoot,adapter);if(!v.valid)fail(`ROUTING_REGISTRY_INVALID: ${v.errors.join(',')}`,50);const reg=readJson(registryPath(projectRoot,adapter)),er=validateRouteRequest(req,p);if(er.length)fail(`INVALID_ROUTE_REQUEST: ${er.join(',')}`,51);const usable=(reg.skills||[]).filter(x=>x.runtime?.usable),unresolved=(reg.skills||[]).filter(x=>!x.runtime?.usable),missing=new Set(normArr(req.required_capabilities)),selected=[],max=req.max_skills??p.max_route_skills;while(missing.size&&selected.length<max){const scored=usable.filter(s=>!selected.some(x=>x.id===s.id)).map(s=>({s,...scoreSkill(s,missing,req)})).filter(x=>x.newReq>0).sort((a,b)=>b.newReq-a.newReq||b.score-a.score||a.s.id.localeCompare(b.s.id));if(!scored.length)break;const best=scored[0].s;selected.push(best);for(const c of best.capabilities||[])missing.delete(c)}if(selected.length===0&&missing.size===0){const scored=usable.map(s=>({s,...scoreSkill(s,new Set(),req)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.s.id.localeCompare(b.s.id));if(scored.length)selected.push(scored[0].s)}const missingArr=[...missing].sort();const suggestions=[];if(req.allow_unresolved_suggestions??p.routing_allow_unresolved_suggestions){for(const s of unresolved){const hits=(s.capabilities||[]).filter(c=>missing.has(c));if(hits.length)suggestions.push({id:s.id,status:s.runtime?.status,matching_capabilities:hits.sort()})}}let status=missingArr.length?'ROUTE_BLOCKED':selected.length?'ROUTE_READY':'NO_RELEVANT_SKILL';const result={schema_version:'1.0',task_id:req.task_id,adapter,status,selected:selected.map(s=>({id:s.id,domain:s.domain,capabilities:s.capabilities,intents:s.intents,runtime_status:s.runtime.status,metadata_trust:s.runtime.metadata_trust,instruction_ref:s.runtime.path,dependencies:s.dependencies,conflicts:s.conflicts})),missing_required_capabilities:missingArr,unresolved_suggestions:suggestions.sort((a,b)=>a.id.localeCompare(b.id)),composition_deferred:selected.flatMap(s=>(s.dependencies||[]).map(d=>({skill_id:s.id,dependency:d}))),instruction_bodies_loaded:false,execution_performed:false,integrity:{algorithm:'sha256',payload_sha256:''}};result.integrity.payload_sha256=sha256Object(withoutIntegrity(result));fs.mkdirSync(routesDir(projectRoot),{recursive:true});writeJson(path.join(routesDir(projectRoot),`${req.task_id.replace(/[^a-zA-Z0-9._-]/g,'_')}.json`),result);return result;}
function verifyRoute(projectRoot,taskId){const f=path.join(routesDir(projectRoot),`${String(taskId).replace(/[^a-zA-Z0-9._-]/g,'_')}.json`);if(!fs.existsSync(f))return{valid:false,errors:['route_missing']};const o=readJson(f),e=[];if(o?.integrity?.payload_sha256!==sha256Object(withoutIntegrity(o)))e.push('route_integrity_mismatch');const adapter=resolveAdapter(projectRoot,o.adapter),rv=verifyRegistry(projectRoot,adapter);if(!rv.valid)e.push('registry_invalid');else{const reg=readJson(registryPath(projectRoot,adapter)),by=new Map((reg.skills||[]).map(x=>[x.id,x]));for(const x of o.selected||[]){const s=by.get(x.id);if(!s||!s.runtime?.usable)e.push(`selected_skill_unavailable:${x.id}`)}}return{valid:e.length===0,errors:e,task_id:taskId,adapter,route:f};}

function artifactFile(dirFn,r,id){return path.join(dirFn(r),`${safeTaskId(id)}.json`)}
function verifySealedFile(fp,kind){if(!fs.existsSync(fp))return{valid:false,errors:[`${kind}_missing`]};const o=readJson(fp),e=[];if(o?.integrity?.payload_sha256!==sha256Object(withoutIntegrity(o)))e.push(`${kind}_integrity_mismatch`);return{valid:e.length===0,errors:e,artifact:o,path:fp};}
function loadContextPolicy(projectRoot){const p=contextPolicyPath(projectRoot);if(!fs.existsSync(p))fail(`CONTEXT_POLICY_NOT_FOUND: ${p}`,60);return readJson(p);}
function agentTargetBudget(ctx,profileName,agent){const rp=ctx?.runtime_profiles?.[profileName];if(!rp)fail(`UNKNOWN_CONTEXT_PROFILE: ${profileName}`,61);const ap=ctx?.agent_budgets?.[agent]||ctx?.agent_budgets?.default;if(!ap)fail(`UNKNOWN_AGENT_BUDGET: ${agent}`,62);const reserve=Math.max(Number(rp.max_output_tokens||0),Number(rp.native_compaction_buffer_tokens||0));const usable=Math.max(0,Number(rp.context_window||0)-reserve);const target=Math.min(Number(ap.max_target_tokens||usable),Math.floor(usable*Number(ap.target_ratio||1)));return{context_window:rp.context_window,reserve_tokens:reserve,usable_input_tokens:usable,agent_target_tokens:target};}
function compositionPolicy(p){return p.composition||{max_composed_skills:p.max_route_skills||8,expand_dependencies:true,fail_on_missing_dependency:true,fail_on_conflict:true,fail_on_cycle:true};}
function loadPolicy3(p){return p.instruction_loading||{max_ratio_of_agent_target:.35,max_instruction_tokens:8000,max_single_skill_tokens:5000,fail_closed_on_budget_exceeded:true,whole_skill_only:true};}
function topoSort(ids,byId){const state=new Map(),out=[];function visit(id,stack=[]){const st=state.get(id)||0;if(st===2)return;if(st===1)throw new Error(`DEPENDENCY_CYCLE:${[...stack,id].join('>')}`);state.set(id,1);const s=byId.get(id);for(const d of [...(s?.dependencies||[])].sort())if(ids.has(d))visit(d,[...stack,id]);state.set(id,2);out.push(id);}for(const id of [...ids].sort())visit(id);return out;}
function planComposition(projectRoot,taskId){const p=loadPolicy(projectRoot),cp=compositionPolicy(p),rv=verifyRoute(projectRoot,taskId);if(!rv.valid)fail(`COMPOSITION_ROUTE_INVALID: ${rv.errors.join(',')}`,63);const route=readJson(artifactFile(routesDir,projectRoot,taskId));if(route.status==='ROUTE_BLOCKED')fail('COMPOSITION_ROUTE_BLOCKED',64);const adapter=resolveAdapter(projectRoot,route.adapter),regv=verifyRegistry(projectRoot,adapter);if(!regv.valid)fail(`COMPOSITION_REGISTRY_INVALID:${regv.errors.join(',')}`,65);const reg=readJson(registryPath(projectRoot,adapter)),by=new Map((reg.skills||[]).map(x=>[x.id,x])),ids=new Set((route.selected||[]).map(x=>x.id)),missing=[];if(cp.expand_dependencies!==false){const q=[...ids];while(q.length){const id=q.shift(),s=by.get(id);for(const d of s?.dependencies||[]){const dep=by.get(d);if(!dep||!dep.runtime?.usable){missing.push({skill_id:id,dependency:d,reason:!dep?'NOT_REGISTERED':'NOT_USABLE'});continue;}if(!ids.has(d)){ids.add(d);q.push(d);}}}}
const conflicts=[];const arr=[...ids].sort();for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const a=by.get(arr[i]),b=by.get(arr[j]);if((a?.conflicts||[]).includes(b.id)||(b?.conflicts||[]).includes(a.id))conflicts.push({a:a.id,b:b.id});}
let order=[],cycle=null;try{order=topoSort(ids,by)}catch(e){cycle=String(e.message||e)}
const tooMany=ids.size>Number(cp.max_composed_skills||p.max_route_skills||8);const errors=[];if(missing.length&&cp.fail_on_missing_dependency!==false)errors.push('MISSING_DEPENDENCY');if(conflicts.length&&cp.fail_on_conflict!==false)errors.push('SKILL_CONFLICT');if(cycle&&cp.fail_on_cycle!==false)errors.push('DEPENDENCY_CYCLE');if(tooMany)errors.push('MAX_COMPOSED_SKILLS_EXCEEDED');const status=errors.length?'COMPOSITION_BLOCKED':'COMPOSITION_READY';const selectedSet=new Set((route.selected||[]).map(x=>x.id));const skills=order.map((id,index)=>{const s=by.get(id);return{id,index,role:selectedSet.has(id)?'ROUTED':'DEPENDENCY',dependencies:normArr(s.dependencies),conflicts:normArr(s.conflicts),instruction_ref:s.runtime.path,instruction_sha256:s.runtime.expected_sha256,metadata_trust:s.runtime.metadata_trust};});const out={schema_version:'1.0',task_id:taskId,adapter,status,route_integrity:route.integrity.payload_sha256,skills,missing_dependencies:missing,conflicts,cycle,errors,instruction_bodies_loaded:false,execution_performed:false,integrity:{algorithm:'sha256',payload_sha256:''}};out.integrity.payload_sha256=sha256Object(withoutIntegrity(out));fs.mkdirSync(compositionsDir(projectRoot),{recursive:true});writeJson(artifactFile(compositionsDir,projectRoot,taskId),out);return out;}
function verifyComposition(projectRoot,taskId){const v=verifySealedFile(artifactFile(compositionsDir,projectRoot,taskId),'composition');if(!v.valid)return v;const r=verifyRoute(projectRoot,taskId);if(!r.valid)v.errors.push('route_invalid');else{const route=readJson(artifactFile(routesDir,projectRoot,taskId));if(v.artifact.route_integrity!==route.integrity?.payload_sha256)v.errors.push('route_integrity_changed');if(v.artifact.adapter!==route.adapter)v.errors.push('route_adapter_changed')}const adapter=resolveAdapter(projectRoot,v.artifact.adapter),reg=verifyRegistry(projectRoot,adapter);if(!reg.valid)v.errors.push('registry_invalid');else{const rr=readJson(registryPath(projectRoot,adapter)),by=new Map((rr.skills||[]).map(x=>[x.id,x]));for(const x of v.artifact.skills||[]){const s=by.get(x.id);if(!s||!s.runtime?.usable)v.errors.push(`composed_skill_unavailable:${x.id}`);else if(s.runtime.expected_sha256!==x.instruction_sha256)v.errors.push(`composed_skill_hash_changed:${x.id}`)}}v.valid=v.errors.length===0;return v;}
function validateLoadRequest(q){const e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');if(!q?.target_agent)e.push('target_agent');if(!q?.runtime_profile)e.push('runtime_profile');if(q?.base_context_tokens!==undefined&&(!Number.isInteger(q.base_context_tokens)||q.base_context_tokens<0))e.push('base_context_tokens');return e;}
function createLoadPacket(projectRoot,req){const p=loadPolicy(projectRoot),lp=loadPolicy3(p),er=validateLoadRequest(req);if(er.length)fail(`INVALID_SKILL_LOAD_REQUEST:${er.join(',')}`,66);const cv=verifyComposition(projectRoot,req.task_id);if(!cv.valid)fail(`LOAD_COMPOSITION_INVALID:${cv.errors.join(',')}`,67);const comp=cv.artifact;if(comp.status!=='COMPOSITION_READY')fail('LOAD_COMPOSITION_NOT_READY',68);const adapter=resolveAdapter(projectRoot,comp.adapter),ctx=loadContextPolicy(projectRoot),b=agentTargetBudget(ctx,req.runtime_profile,req.target_agent),base=Number(req.base_context_tokens||0),ratioCap=Math.floor(b.agent_target_tokens*Number(lp.max_ratio_of_agent_target||1)),absoluteCap=Number(lp.max_instruction_tokens||ratioCap),remaining=Math.max(0,b.agent_target_tokens-base),budget=Math.max(0,Math.min(ratioCap,absoluteCap,remaining));const reg=readJson(registryPath(projectRoot,adapter)),by=new Map((reg.skills||[]).map(x=>[x.id,x])),instructions=[];let total=0;const errors=[];for(const x of comp.skills||[]){const s=by.get(x.id),fp=path.resolve(projectRoot,s.runtime.path||'');if(!inside(projectRoot,fp)||!fs.existsSync(fp)){errors.push(`SOURCE_MISSING:${x.id}`);continue;}const actual=sha256InstructionFile(fp);if(actual!==x.instruction_sha256||actual!==s.runtime.expected_sha256){errors.push(`SOURCE_DRIFT:${x.id}`);continue;}const body=fs.readFileSync(fp,'utf8'),tokens=estimateTokensText(body);if(tokens>Number(lp.max_single_skill_tokens||tokens))errors.push(`SINGLE_SKILL_BUDGET:${x.id}`);instructions.push({id:x.id,role:x.role,instruction_ref:s.runtime.path,instruction_sha256:actual,estimated_tokens:tokens,body});total+=tokens;}
if(total>budget)errors.push('INSTRUCTION_BUDGET_EXCEEDED');const status=errors.length?'LOAD_BLOCKED':'LOAD_READY';const out={schema_version:'1.0',task_id:req.task_id,adapter,status,target_agent:req.target_agent,runtime_profile:req.runtime_profile,composition_integrity:comp.integrity.payload_sha256,budget:{...b,base_context_tokens:base,max_instruction_tokens:budget,planned_instruction_tokens:total,remaining_after_load:Math.max(0,remaining-total)},skills:status==='LOAD_READY'?instructions:instructions.map(({body,...x})=>x),errors,instruction_bodies_loaded:status==='LOAD_READY',execution_performed:false,integrity:{algorithm:'sha256',payload_sha256:''}};out.integrity.payload_sha256=sha256Object(withoutIntegrity(out));fs.mkdirSync(loadPacketsDir(projectRoot),{recursive:true});writeJson(artifactFile(loadPacketsDir,projectRoot,req.task_id),out);return out;}
function verifyLoadPacket(projectRoot,taskId){const v=verifySealedFile(artifactFile(loadPacketsDir,projectRoot,taskId),'load');if(!v.valid)return v;const cv=verifyComposition(projectRoot,taskId);if(!cv.valid)v.errors.push('composition_invalid');else{if(v.artifact.composition_integrity!==cv.artifact.integrity.payload_sha256)v.errors.push('composition_integrity_changed');if(v.artifact.adapter!==cv.artifact.adapter)v.errors.push('composition_adapter_changed')}if(v.artifact.status==='LOAD_READY'){const adapter=resolveAdapter(projectRoot,v.artifact.adapter),reg=readJson(registryPath(projectRoot,adapter)),by=new Map((reg.skills||[]).map(x=>[x.id,x]));for(const x of v.artifact.skills||[]){const s=by.get(x.id),fp=s?path.resolve(projectRoot,s.runtime.path||''):null;if(!s||!fp||!fs.existsSync(fp))v.errors.push(`loaded_skill_missing:${x.id}`);else if(sha256InstructionFile(fp)!==x.instruction_sha256)v.errors.push(`loaded_skill_drift:${x.id}`);else if(typeof x.body!=='string')v.errors.push(`loaded_body_missing:${x.id}`)}}v.valid=v.errors.length===0;return v;}
function validateExecutionHandoffRequest(q){const e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');if(!q?.target_agent)e.push('target_agent');if(!Array.isArray(q?.input_refs))e.push('input_refs:array');if(!Array.isArray(q?.required_outputs)||!q.required_outputs.length)e.push('required_outputs:array');for(const r of q?.input_refs||[]){if(!r?.kind||!r?.ref)e.push('input_ref');if(r?.content!==undefined||r?.body!==undefined||r?.transcript!==undefined)e.push('inline_input_forbidden');}return e;}
function createExecutionHandoff(projectRoot,req){const p=loadPolicy(projectRoot),hp=p.execution_handoff||{},er=validateExecutionHandoffRequest(req);if(er.length)fail(`INVALID_EXECUTION_HANDOFF_REQUEST:${er.join(',')}`,69);if((req.input_refs||[]).length>Number(hp.max_input_refs||32))fail('TOO_MANY_INPUT_REFS',70);if((req.required_outputs||[]).length>Number(hp.max_required_outputs||16))fail('TOO_MANY_REQUIRED_OUTPUTS',71);const lv=verifyLoadPacket(projectRoot,req.task_id);if(!lv.valid)fail(`HANDOFF_LOAD_INVALID:${lv.errors.join(',')}`,72);if(lv.artifact.status!=='LOAD_READY')fail('HANDOFF_LOAD_NOT_READY',73);if(lv.artifact.target_agent!==req.target_agent)fail('HANDOFF_AGENT_MISMATCH',74);const out={schema_version:'1.0',task_id:req.task_id,adapter:lv.artifact.adapter,status:'EXECUTION_HANDOFF_READY',target_agent:req.target_agent,load_packet_ref:rel(projectRoot,artifactFile(loadPacketsDir,projectRoot,req.task_id)),load_packet_integrity:lv.artifact.integrity.payload_sha256,skill_ids:(lv.artifact.skills||[]).map(x=>x.id),input_contract:{reference_only:true,input_refs:req.input_refs,transcript_allowed:false},output_contract:{required_outputs:normArr(req.required_outputs),optional_outputs:normArr(req.optional_outputs||[]),max_estimated_tokens:Number(req.max_output_tokens||hp.default_max_output_tokens||4000),transcript_allowed:false},execution_performed:false,integrity:{algorithm:'sha256',payload_sha256:''}};out.integrity.payload_sha256=sha256Object(withoutIntegrity(out));fs.mkdirSync(executionHandoffsDir(projectRoot),{recursive:true});writeJson(artifactFile(executionHandoffsDir,projectRoot,req.task_id),out);return out;}
function verifyExecutionHandoff(projectRoot,taskId){const v=verifySealedFile(artifactFile(executionHandoffsDir,projectRoot,taskId),'execution_handoff');if(!v.valid)return v;const lv=verifyLoadPacket(projectRoot,taskId);if(!lv.valid)v.errors.push('load_invalid');else if(v.artifact.load_packet_integrity!==lv.artifact.integrity.payload_sha256)v.errors.push('load_integrity_changed');if(v.artifact?.input_contract?.transcript_allowed!==false)v.errors.push('transcript_policy');if(v.artifact?.execution_performed!==false)v.errors.push('execution_flag');v.valid=v.errors.length===0;return v;}


const SKILL_TELEMETRY_FORBIDDEN_KEY_RE=/^(prompt|prompt_text|completion|completion_text|transcript|conversation|messages|file_content|raw_content|body|secret|secrets|api[_-]?key|password|authorization|cookie|access[_-]?token|refresh[_-]?token)$/i;
function assertSkillTelemetrySafe(v,p='root'){if(Array.isArray(v)){for(let i=0;i<v.length;i++)assertSkillTelemetrySafe(v[i],`${p}[${i}]`);return;}if(!v||typeof v!=='object')return;for(const [k,x] of Object.entries(v)){if(SKILL_TELEMETRY_FORBIDDEN_KEY_RE.test(k))fail(`SKILL_TELEMETRY_SENSITIVE_FIELD_FORBIDDEN:${p}.${k}`,80);assertSkillTelemetrySafe(x,`${p}.${k}`)}}
function skillTelemetryEventsPath(r){return path.join(skillTelemetryRoot(r),'events.jsonl')}
function skillEventPayload(e){const x=structuredClone(e);delete x.event_sha256;return x}
function readSkillEvents(r){const p=skillTelemetryEventsPath(r);if(!fs.existsSync(p))return[];return fs.readFileSync(p,'utf8').split(/\r?\n/).filter(Boolean).map((x,i)=>{try{return JSON.parse(x)}catch{fail(`SKILL_TELEMETRY_JSON_INVALID:${i+1}`,81)}})}
function appendSkillEvent(r,event){assertSkillTelemetrySafe(event);const p=loadPolicy(r),cfg=p.skill_telemetry||{},xs=readSkillEvents(r);if(xs.length>=Number(cfg.max_events||10000))fail('SKILL_TELEMETRY_MAX_EVENTS_EXCEEDED',82);const prev=xs.length?xs[xs.length-1].event_sha256:null;const e={schema_version:'1.0',sequence:xs.length+1,timestamp:new Date().toISOString(),previous_event_sha256:prev,...event,event_sha256:''};e.event_sha256=sha256Object(skillEventPayload(e));fs.mkdirSync(path.dirname(skillTelemetryEventsPath(r)),{recursive:true});fs.appendFileSync(skillTelemetryEventsPath(r),JSON.stringify(e)+'\n','utf8');return e;}
function verifySkillTelemetry(r){const xs=readSkillEvents(r),errors=[];let prev=null;for(let i=0;i<xs.length;i++){const e=xs[i];try{assertSkillTelemetrySafe(e)}catch(err){errors.push(String(err?.message||err))}if(e.sequence!==i+1)errors.push(`sequence:${i+1}`);if(e.previous_event_sha256!==prev)errors.push(`chain:${i+1}`);const expected=sha256Object(skillEventPayload(e));if(e.event_sha256!==expected)errors.push(`hash:${i+1}`);prev=e.event_sha256;}return{valid:errors.length===0,errors,event_count:xs.length,tail_sha256:prev};}
function summarizeSkillTelemetry(r){const v=verifySkillTelemetry(r);if(!v.valid)fail(`SKILL_TELEMETRY_INVALID:${v.errors.join(',')}`,83);const xs=readSkillEvents(r),by={};const skillIds=e=>Array.isArray(e.skill_ids)?e.skill_ids:[];for(const e of xs){for(const id of skillIds(e)){const a=by[id]??={governed:0,approved:0,blocked:0,attempts:0,successes:0,failures:0,retries:0,output_contract_failures:0,duration_ms:0,duration_samples:0,input_tokens:0,output_tokens:0,input_tokens_samples:0,output_tokens_samples:0};if(e.kind==='GOVERNANCE'){a.governed++;if(e.status==='GOVERNANCE_APPROVED')a.approved++;else a.blocked++;}if(e.kind==='EXECUTION_ATTEMPT'){a.attempts++;if(e.attempt>1)a.retries++;if(e.status==='SUCCEEDED')a.successes++;else a.failures++;if(typeof e.duration_ms==='number'){a.duration_ms+=e.duration_ms;a.duration_samples++;}if(typeof e.input_tokens==='number'){a.input_tokens+=e.input_tokens;a.input_tokens_samples++;}if(typeof e.output_tokens==='number'){a.output_tokens+=e.output_tokens;a.output_tokens_samples++;}}if(e.kind==='OUTPUT_VALIDATION'&&e.contract_satisfied===false)a.output_contract_failures++;}}
for(const a of Object.values(by)){a.success_rate=a.attempts?a.successes/a.attempts:null;a.avg_duration_ms=a.duration_samples?a.duration_ms/a.duration_samples:null;if(!a.input_tokens_samples)a.input_tokens=null;if(!a.output_tokens_samples)a.output_tokens=null;delete a.duration_samples;delete a.input_tokens_samples;delete a.output_tokens_samples;}
const out={schema_version:'1.0',generated_at:new Date().toISOString(),attribution:'composition-correlated-not-causal',skills:by,event_count:xs.length,integrity:{algorithm:'sha256',event_chain_tail:v.tail_sha256}};writeJson(path.join(skillTelemetryRoot(r),'summary.json'),out);return out;}
function trustRank(p,t){return Number((p.governance?.trust_rank||{})[t]??-1)}
function governanceFile(r,id){return artifactFile(governanceDir,r,id)}
function executionAttemptFile(r,id,n){return path.join(executionReceiptsDir(r),safeTaskId(id),`attempt-${n}.json`)}
function validateGovernanceRequest(q,p){const e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');if(!q?.requested_by_agent)e.push('requested_by_agent');if(!q?.adapter)e.push('adapter');if(!p.governance?.risk_levels?.includes(q?.risk_level))e.push('risk_level');if(q?.allowed_domains!==undefined&&!Array.isArray(q.allowed_domains))e.push('allowed_domains:array');if(q?.required_trust!==undefined&&q.required_trust!==null&&!Object.hasOwn(p.governance?.trust_rank||{},q.required_trust))e.push('required_trust');if(q?.runtime_permissions_attested!==undefined&&typeof q.runtime_permissions_attested!=='boolean')e.push('runtime_permissions_attested:boolean');return e;}
function evaluateGovernance(r,q){const p=loadPolicy(r),g=p.governance||{},er=validateGovernanceRequest(q,p);if(er.length)fail(`INVALID_GOVERNANCE_REQUEST:${er.join(',')}`,84);const hv=verifyExecutionHandoff(r,q.task_id);if(!hv.valid)fail(`GOVERNANCE_HANDOFF_INVALID:${hv.errors.join(',')}`,85);const h=hv.artifact;if(h.adapter!==q.adapter)fail('GOVERNANCE_ADAPTER_MISMATCH',86);const reg=readJson(registryPath(r,q.adapter));if(reg.adapter!==q.adapter)fail('GOVERNANCE_ADAPTER_MISMATCH',86);const by=new Map((reg.skills||[]).map(x=>[x.id,x])),errors=[],assess=[];const floor=q.required_trust||g.min_trust_by_risk?.[q.risk_level]||'runtime-verified';const floorRank=trustRank(p,floor);const forbidden=new Set(g.forbidden_capabilities||[]),allowedDomains=new Set(q.allowed_domains||[]);if((g.require_runtime_permission_attestation_for||[]).includes(q.risk_level)&&q.runtime_permissions_attested!==true)errors.push('RUNTIME_PERMISSION_ATTESTATION_REQUIRED');for(const id of h.skill_ids||[]){const s=by.get(id),reasons=[];if(!s||!s.runtime?.usable)reasons.push('SKILL_NOT_USABLE');else{if(trustRank(p,s.trust)<floorRank)reasons.push(`TRUST_BELOW_REQUIRED:${s.trust}<${floor}`);if(allowedDomains.size&&!allowedDomains.has(s.domain))reasons.push(`DOMAIN_NOT_ALLOWED:${s.domain}`);for(const c of s.capabilities||[])if(forbidden.has(c))reasons.push(`FORBIDDEN_CAPABILITY:${c}`);}if(reasons.length)errors.push(...reasons.map(x=>`${id}:${x}`));assess.push({id,domain:s?.domain||null,trust:s?.trust||null,capabilities:s?.capabilities||[],decision:reasons.length?'BLOCK':'ALLOW',reasons});}
const status=errors.length?'GOVERNANCE_BLOCKED':'GOVERNANCE_APPROVED';const out={schema_version:'1.0',task_id:q.task_id,status,risk_level:q.risk_level,requested_by_agent:q.requested_by_agent,adapter:q.adapter,runtime_permissions_attested:q.runtime_permissions_attested===true,required_trust:floor,handoff_integrity:h.integrity.payload_sha256,skill_ids:[...(h.skill_ids||[])],skills:assess,retry_budget:Number(g.max_retries??0),errors:[...new Set(errors)],direct_engine_execution:false,adapter_execution_authorized:status==='GOVERNANCE_APPROVED',integrity:{algorithm:'sha256',payload_sha256:''}};out.integrity.payload_sha256=sha256Object(withoutIntegrity(out));fs.mkdirSync(governanceDir(r),{recursive:true});writeJson(governanceFile(r,q.task_id),out);appendSkillEvent(r,{kind:'GOVERNANCE',task_id:q.task_id,skill_ids:out.skill_ids,status,risk_level:q.risk_level});return out;}
function verifyGovernance(r,id){const v=verifySealedFile(governanceFile(r,id),'governance');if(!v.valid)return v;const hv=verifyExecutionHandoff(r,id);if(!hv.valid)v.errors.push('handoff_invalid');else if(v.artifact.handoff_integrity!==hv.artifact.integrity.payload_sha256)v.errors.push('handoff_integrity_changed');const rv=verifyRegistry(r,v.artifact.adapter);if(!rv.valid)v.errors.push('registry_invalid');v.valid=v.errors.length===0;return v;}
function validateExecutionReceiptRequest(q){const e=[];if(q?.schema_version!=='1.0')e.push('schema_version');if(!q?.task_id)e.push('task_id');if(!Number.isInteger(q?.attempt)||q.attempt<1)e.push('attempt');if(!['SUCCEEDED','FAILED','BLOCKED'].includes(q?.status))e.push('status');if(!Array.isArray(q?.output_refs))e.push('output_refs:array');if(!Array.isArray(q?.outputs_present))e.push('outputs_present:array');if(typeof q?.contract_satisfied!=='boolean')e.push('contract_satisfied:boolean');for(const x of q?.output_refs||[]){if(!x?.kind||!x?.ref)e.push('output_ref');if(x?.content!==undefined||x?.body!==undefined||x?.transcript!==undefined)e.push('inline_output_forbidden');}for(const k of ['duration_ms','input_tokens','output_tokens'])if(q?.[k]!==undefined&&q[k]!==null&&(typeof q[k]!=='number'||!Number.isFinite(q[k])||q[k]<0))e.push(`${k}:nonnegative`);return [...new Set(e)];}
function listExecutionAttempts(r,id){const d=path.join(executionReceiptsDir(r),safeTaskId(id));if(!fs.existsSync(d))return[];return fs.readdirSync(d).filter(x=>/^attempt-\d+\.json$/.test(x)).map(x=>Number(x.match(/\d+/)[0])).sort((a,b)=>a-b)}
function recordExecutionReceipt(r,q){const p=loadPolicy(r),ep=p.execution_lifecycle||{},er=validateExecutionReceiptRequest(q);if(er.length)fail(`INVALID_EXECUTION_RECEIPT:${er.join(',')}`,87);const gv=verifyGovernance(r,q.task_id);if(!gv.valid)fail(`EXECUTION_GOVERNANCE_INVALID:${gv.errors.join(',')}`,88);const g=gv.artifact;if(g.status!=='GOVERNANCE_APPROVED')fail('EXECUTION_NOT_AUTHORIZED',89);if(q.adapter&&q.adapter!==g.adapter)fail('EXECUTION_ADAPTER_MISMATCH',89);const attempts=listExecutionAttempts(r,q.task_id),expected=attempts.length+1;if(q.attempt!==expected)fail(`EXECUTION_ATTEMPT_SEQUENCE:${q.attempt}!=${expected}`,90);if(q.attempt>1+Number(g.retry_budget||0))fail('EXECUTION_RETRY_BUDGET_EXHAUSTED',91);if(attempts.length){const prev=readJson(executionAttemptFile(r,q.task_id,attempts[attempts.length-1]));if(prev.status==='SUCCEEDED'&&prev.validation?.accepted===true)fail('EXECUTION_ALREADY_SUCCEEDED',92)}const h=readJson(artifactFile(executionHandoffsDir,r,q.task_id)),required=new Set(h.output_contract?.required_outputs||[]),present=new Set(q.outputs_present||[]),missing=[...required].filter(x=>!present.has(x)).sort();let accepted=true,validationErrors=[];if(q.status==='SUCCEEDED'){if(!q.contract_satisfied)validationErrors.push('CONTRACT_NOT_SATISFIED');if(missing.length)validationErrors.push(`MISSING_REQUIRED_OUTPUTS:${missing.join(',')}`);}if((q.output_refs||[]).length>Number(ep.max_output_refs||32))validationErrors.push('TOO_MANY_OUTPUT_REFS');if(validationErrors.length)accepted=false;const out={schema_version:'1.0',task_id:q.task_id,attempt:q.attempt,status:q.status,adapter:q.adapter||g.adapter,runtime:q.runtime||null,skill_ids:g.skill_ids,output_refs:q.output_refs,outputs_present:normArr(q.outputs_present),contract_satisfied:q.contract_satisfied,duration_ms:q.duration_ms??null,input_tokens:q.input_tokens??null,output_tokens:q.output_tokens??null,error_code:q.error_code??null,validation:{accepted,missing_required_outputs:missing,errors:validationErrors},governance_integrity:g.integrity.payload_sha256,handoff_integrity:h.integrity.payload_sha256,integrity:{algorithm:'sha256',payload_sha256:''}};assertSkillTelemetrySafe(out);out.integrity.payload_sha256=sha256Object(withoutIntegrity(out));writeJson(executionAttemptFile(r,q.task_id,q.attempt),out);appendSkillEvent(r,{kind:'EXECUTION_ATTEMPT',task_id:q.task_id,skill_ids:g.skill_ids,attempt:q.attempt,status:q.status,duration_ms:q.duration_ms??null,input_tokens:q.input_tokens??null,output_tokens:q.output_tokens??null});if(q.attempt>1)appendSkillEvent(r,{kind:'RETRY',task_id:q.task_id,skill_ids:g.skill_ids,attempt:q.attempt,status:q.status});appendSkillEvent(r,{kind:'OUTPUT_VALIDATION',task_id:q.task_id,skill_ids:g.skill_ids,attempt:q.attempt,status:accepted?'PASS':'FAIL',contract_satisfied:q.contract_satisfied&&missing.length===0,missing_required_outputs:missing});return{...out,record_status:accepted?'EXECUTION_RECEIPT_ACCEPTED':'EXECUTION_RECEIPT_REJECTED'};}
function verifyExecutionReceipts(r,id){const gv=verifyGovernance(r,id),errors=[];if(!gv.valid)errors.push('governance_invalid');const ns=listExecutionAttempts(r,id);let prevStatus=null;for(let i=0;i<ns.length;i++){const n=ns[i],f=executionAttemptFile(r,id,n),o=readJson(f);if(n!==i+1)errors.push(`attempt_sequence:${n}`);if(o.integrity?.payload_sha256!==sha256Object(withoutIntegrity(o)))errors.push(`attempt_integrity:${n}`);if(o.task_id!==id)errors.push(`task_id:${n}`);if(gv.valid&&o.governance_integrity!==gv.artifact.integrity.payload_sha256)errors.push(`governance_changed:${n}`);if(prevStatus==='SUCCEEDED')errors.push(`attempt_after_success:${n}`);prevStatus=o.validation?.accepted&&o.status==='SUCCEEDED'?'SUCCEEDED':o.status;}const tv=verifySkillTelemetry(r);if(!tv.valid)errors.push(...tv.errors.map(x=>`telemetry:${x}`));return{valid:errors.length===0,errors,task_id:id,attempts:ns.length,final_status:ns.length?readJson(executionAttemptFile(r,id,ns[ns.length-1])).status:null};}

function listRegistry(r){const adapter=resolveAdapter(r,take('--adapter'));const reg=readJson(registryPath(r,adapter));let xs=reg.skills||[];if(has('--usable-only'))xs=xs.filter(x=>x.runtime?.usable);const cap=take('--capability');if(cap)xs=xs.filter(x=>x.capabilities.includes(cap));console.log(JSON.stringify(xs.map(x=>({id:x.id,domain:x.domain,adapter,status:x.runtime.status,usable:x.runtime.usable,capabilities:x.capabilities})),null,2));}
function doctor(r){const adapter=resolveAdapter(r,take('--adapter')),v=verifyRegistry(r,adapter),rp=registryPath(r,adapter),reg=fs.existsSync(rp)?readJson(rp):null;console.log(JSON.stringify({status:v.valid?'SKILL_REGISTRY_HEALTHY':'SKILL_REGISTRY_FAILED',adapter,...v,unresolved:(reg?.skills||[]).filter(x=>!x.runtime?.usable).map(x=>x.id),phase_boundary:reg?.phase_boundary},null,2));if(!v.valid)process.exit(32)}
const projectRoot=path.resolve(take('--project-root',process.cwd()));
if(cmd==='discovery'&&sub==='scan'){const a=take('--adapter','opencode');const o=discoveryScan(projectRoot,a);console.log(JSON.stringify({status:'SKILL_DISCOVERY_COMPLETE',summary:o.summary,integrity:o.integrity.payload_sha256},null,2));}
else if(cmd==='discovery'&&sub==='verify'){const a=resolveAdapter(projectRoot,take('--adapter'));const o=verifyDiscovery(projectRoot,a);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(47)}
else if(cmd==='registry'&&sub==='build'){const a=take('--adapter','opencode'),o=buildRegistry(projectRoot,a);console.log(JSON.stringify({status:'SKILL_REGISTRY_BUILT',summary:o.summary,integrity:o.integrity.payload_sha256},null,2));}
else if(cmd==='registry'&&sub==='verify'){const a=resolveAdapter(projectRoot,take('--adapter'));const o=verifyRegistry(projectRoot,a);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(33)}
else if(cmd==='registry'&&sub==='list')listRegistry(projectRoot);
else if(cmd==='registry'&&sub==='doctor')doctor(projectRoot);
else if(cmd==='route'&&sub==='plan'){const f=take('--request');if(!f)fail('Missing --request',2);const o=planRoute(projectRoot,readJson(path.resolve(f)));console.log(JSON.stringify(o,null,2));if(o.status==='ROUTE_BLOCKED')process.exit(52)}
else if(cmd==='route'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyRoute(projectRoot,id);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(53)}
else if(cmd==='compose'&&sub==='plan'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=planComposition(projectRoot,id);console.log(JSON.stringify(o,null,2));if(o.status==='COMPOSITION_BLOCKED')process.exit(64)}
else if(cmd==='compose'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyComposition(projectRoot,id);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(65)}
else if(cmd==='load'&&sub==='plan'){const f=take('--request');if(!f)fail('Missing --request',2);const o=createLoadPacket(projectRoot,readJson(path.resolve(f)));console.log(JSON.stringify({...o,skills:(o.skills||[]).map(({body,...x})=>x)},null,2));if(o.status==='LOAD_BLOCKED')process.exit(66)}
else if(cmd==='load'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyLoadPacket(projectRoot,id);console.log(JSON.stringify({valid:o.valid,errors:o.errors,task_id:id},null,2));if(!o.valid)process.exit(67)}
else if(cmd==='handoff'&&sub==='create'){const f=take('--request');if(!f)fail('Missing --request',2);const o=createExecutionHandoff(projectRoot,readJson(path.resolve(f)));console.log(JSON.stringify(o,null,2));}
else if(cmd==='handoff'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyExecutionHandoff(projectRoot,id);console.log(JSON.stringify({valid:o.valid,errors:o.errors,task_id:id},null,2));if(!o.valid)process.exit(68)}
else if(cmd==='governance'&&sub==='evaluate'){const f=take('--request');if(!f)fail('Missing --request',2);const o=evaluateGovernance(projectRoot,readJson(path.resolve(f)));console.log(JSON.stringify(o,null,2));if(o.status!=='GOVERNANCE_APPROVED')process.exit(84)}
else if(cmd==='governance'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyGovernance(projectRoot,id);console.log(JSON.stringify({valid:o.valid,errors:o.errors,task_id:id},null,2));if(!o.valid)process.exit(85)}
else if(cmd==='execute'&&sub==='record'){const f=take('--request');if(!f)fail('Missing --request',2);const o=recordExecutionReceipt(projectRoot,readJson(path.resolve(f)));console.log(JSON.stringify(o,null,2));if(o.record_status!=='EXECUTION_RECEIPT_ACCEPTED')process.exit(86)}
else if(cmd==='execute'&&sub==='verify'){const id=take('--task-id');if(!id)fail('Missing --task-id',2);const o=verifyExecutionReceipts(projectRoot,id);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(87)}
else if(cmd==='telemetry'&&sub==='verify'){const o=verifySkillTelemetry(projectRoot);console.log(JSON.stringify(o,null,2));if(!o.valid)process.exit(88)}
else if(cmd==='telemetry'&&sub==='summarize'){const o=summarizeSkillTelemetry(projectRoot);console.log(JSON.stringify(o,null,2));}
else {console.log(`AleDevOS Skill System Phase 4

Commands:
  discovery scan --project-root <path> --adapter opencode
  discovery verify --project-root <path>
  registry build --project-root <path> --adapter opencode
  registry verify --project-root <path>
  registry doctor --project-root <path>
  registry list --project-root <path> [--usable-only] [--capability X]
  route plan --project-root <path> --request <request.json>
  route verify --project-root <path> --task-id <task-id>
  compose plan --project-root <path> --task-id <task-id>
  compose verify --project-root <path> --task-id <task-id>
  load plan --project-root <path> --request <request.json>
  load verify --project-root <path> --task-id <task-id>
  handoff create --project-root <path> --request <request.json>
  handoff verify --project-root <path> --task-id <task-id>
  governance evaluate --project-root <path> --request <request.json>
  governance verify --project-root <path> --task-id <task-id>
  execute record --project-root <path> --request <receipt.json>
  execute verify --project-root <path> --task-id <task-id>
  telemetry verify --project-root <path>
  telemetry summarize --project-root <path>

Phase 4 adds fail-closed skill governance, adapter execution authorization, output-contract validation, retry limits and privacy-safe skill telemetry. AleDevOS Core does not directly invoke runtime-specific skills; adapters execute only after governance approval and return sealed receipts.`);if(cmd)process.exit(2)}
