import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const mm=path.join(root,'advanced-execution','multimachine','multimachine-manager.mjs');
const p1=path.join(root,'advanced-execution','worktrees','worktree-manager.mjs');
const p2=path.join(root,'advanced-execution','workers','worker-manager.mjs');
const p3=path.join(root,'advanced-execution','concurrency','concurrency-manager.mjs');
const p4=path.join(root,'advanced-execution','dispatcher','dispatcher-manager.mjs');
const certs=[1,2,3,4].map(n=>path.join(root,'release','certifications',`advanced-execution-p${n}.json`));
const temps=[];
const tmp=()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-p5-'));temps.push(d);return d};
after(()=>{for(const d of temps)try{fs.rmSync(d,{recursive:true,force:true})}catch{}});
const run=(argv,cwd=root)=>spawnSync(process.execPath,[mm,...argv],{cwd,encoding:'utf8',windowsHide:true});
const runScript=(script,argv,cwd=root)=>spawnSync(process.execPath,[script,...argv],{cwd,encoding:'utf8',windowsHide:true});
const j=r=>{try{return JSON.parse(r.stdout||'{}')}catch{return{}}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v,null,2)+'\n')};
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const sleep=ms=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);
const stable=(v,omit=new Set())=>Array.isArray(v)?v.map(x=>stable(x,omit)):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!omit.has(k)).sort().map(k=>[k,stable(v[k],omit)])):v;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const hashObj=(v,...omit)=>sha(Buffer.from(JSON.stringify(stable(v,new Set(omit)))));

function caps(d,name='caps.json',extra={}){const f=path.join(d,name);write(f,{adapters:['codex'],modalities:['text','image'],features:['git','playwright'],max_workers:4,...extra});return f}
function env(){const d=tmp(),repo=path.join(d,'repo'),a=path.join(d,'node-a'),b=path.join(d,'node-b');fs.mkdirSync(repo,{recursive:true});assert.equal(run(['coordinator','init','--repo',repo]).status,0);const ci=path.join(d,'coordinator.json');assert.equal(run(['coordinator','export-identity','--repo',repo,'--out',ci]).status,0);for(const [n,id] of [[a,'node-a'],[b,'node-b']]){assert.equal(run(['identity','create','--node-dir',n,'--machine-id',id,'--capabilities',caps(d,`${id}.json`)]).status,0);assert.equal(run(['trust','add','--node-dir',n,'--coordinator-identity',ci]).status,0);assert.equal(run(['node','enroll','--repo',repo,'--identity',path.join(n,'identity','identity.json')]).status,0);assert.equal(run(['node','approve','--repo',repo,'--machine-id',id]).status,0);const h=path.join(d,`${id}-heartbeat.json`);assert.equal(run(['heartbeat','create','--node-dir',n,'--out',h]).status,0);assert.equal(run(['heartbeat','accept','--repo',repo,'--heartbeat',h]).status,0)}return{d,repo,a,b,ci}}
function submit(e,id='task-a',opts=[]){const f=path.join(e.d,`${id}-payload.bin`);write(f,Buffer.from(`payload-${id}`));const r=run(['task','submit','--repo',e.repo,'--task-id',id,'--payload',f,'--adapter','codex','--modality','text','--feature','git',...opts]);return{r,data:j(r),payload:f}}
function assign(e,id='task-a',node='node-a',nodeDir=e.a,lease=2000,reassign=false){const f=path.join(e.d,`${id}-${node}-${reassign?'re':'a'}.json`);const r=run(['task',reassign?'reassign':'assign','--repo',e.repo,'--task-id',id,'--machine-id',node,'--lease-ms',String(lease),'--out',f]);return{r,data:j(r),file:f,nodeDir}}
function importAck(e,a){const ir=run(['bundle','import','--node-dir',a.nodeDir,'--bundle',a.file]);const af=path.join(e.d,`ack-${path.basename(a.file)}`);let ar=null,aa=null;if(ir.status===0){ar=run(['ack','create','--node-dir',a.nodeDir,'--task-id',j(ir).task_id,'--out',af]);if(ar.status===0)aa=run(['ack','accept','--repo',e.repo,'--ack',af])}return{ir,ar,aa,ack:af}}
function result(e,a,id='task-a',content='ok'){const rf=path.join(e.d,`result-${id}-${Math.random()}.bin`);write(rf,Buffer.from(content));const out=path.join(e.d,`result-envelope-${id}-${Math.random()}.json`);const cr=run(['result','create','--node-dir',a.nodeDir,'--task-id',id,'--result',rf,'--out',out]);const ac=cr.status===0?run(['result','accept','--repo',e.repo,'--result',out]):null;return{cr,ac,file:out}}

// Policy and identity.
test('P5 policy verifies',()=>{const r=run(['policy','verify']);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'MULTIMACHINE_POLICY_VALID')});
test('policy requires Ed25519',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).identity.algorithm,'ed25519'));
test('policy requires explicit approval',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).identity.explicit_node_approval_required,true));
test('policy requires coordinator trust anchor',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).identity.coordinator_trust_anchor_required,true));
test('policy caps reassignments at two',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).tasks.max_reassignments,2));
test('policy does not claim physical duplicate compute prevention under partition',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).boundaries.physical_duplicate_compute_under_partition_claimed_prevented,false));
test('policy claims authoritative duplicate acceptance prevention',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).boundaries.authoritative_duplicate_acceptance_prevented,true));
test('network transport remains deferred',()=>assert.equal(read(path.join(root,'advanced-execution/policies/multimachine-policy.json')).transport.network_transport_implemented,false));
test('machine identity creation works',()=>{const d=tmp(),n=path.join(d,'n'),r=run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);assert.equal(r.status,0,r.stdout);assert.ok(fs.existsSync(path.join(n,'identity','private-key.pem')))});
test('machine identity is self-verifiable',()=>{const d=tmp(),n=path.join(d,'n');run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);const r=run(['identity','verify','--identity',path.join(n,'identity','identity.json')]);assert.equal(r.status,0,r.stdout)});
test('invalid machine id is rejected',()=>{const d=tmp(),r=run(['identity','create','--node-dir',path.join(d,'n'),'--machine-id','../escape','--capabilities',caps(d)]);assert.notEqual(r.status,0);assert.equal(j(r).status,'MACHINE_ID_INVALID')});
test('identity cannot be overwritten silently',()=>{const d=tmp(),n=path.join(d,'n'),c=caps(d);run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',c]);const r=run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',c]);assert.notEqual(r.status,0);assert.equal(j(r).status,'MACHINE_IDENTITY_EXISTS')});
test('tampered identity fails verification',()=>{const d=tmp(),n=path.join(d,'n');run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);const f=path.join(n,'identity','identity.json'),x=read(f);x.capabilities.max_workers=99;write(f,x);const r=run(['identity','verify','--identity',f]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('IDENTITY_HASH_INVALID'))});
test('private key is 0600 on unix',()=>{if(process.platform==='win32')return;const d=tmp(),n=path.join(d,'n');run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);assert.equal(fs.statSync(path.join(n,'identity','private-key.pem')).mode&0o777,0o600)});

// Coordinator, enrollment and heartbeats.
test('coordinator initializes with persistent identity',()=>{const d=tmp(),r=path.join(d,'r');fs.mkdirSync(r);const x=run(['coordinator','init','--repo',r]);assert.equal(x.status,0,x.stdout);assert.ok(fs.existsSync(path.join(r,'.aledevos/state/execution/phase5/coordinator/identity.json')))});
test('coordinator cannot initialize twice',()=>{const d=tmp(),r=path.join(d,'r');fs.mkdirSync(r);run(['coordinator','init','--repo',r]);const x=run(['coordinator','init','--repo',r]);assert.notEqual(x.status,0);assert.equal(j(x).status,'MULTIMACHINE_COORDINATOR_EXISTS')});
test('enrollment starts pending',()=>{const d=tmp(),repo=path.join(d,'r'),n=path.join(d,'n');fs.mkdirSync(repo);run(['coordinator','init','--repo',repo]);run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);const r=run(['node','enroll','--repo',repo,'--identity',path.join(n,'identity','identity.json')]);assert.equal(j(r).node.state,'PENDING')});
test('pending node heartbeat is rejected',()=>{const d=tmp(),repo=path.join(d,'r'),n=path.join(d,'n');fs.mkdirSync(repo);run(['coordinator','init','--repo',repo]);run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(d)]);run(['node','enroll','--repo',repo,'--identity',path.join(n,'identity','identity.json')]);const h=path.join(d,'h.json');run(['heartbeat','create','--node-dir',n,'--out',h]);const r=run(['heartbeat','accept','--repo',repo,'--heartbeat',h]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('NODE_NOT_APPROVED'))});
test('approved node accepts signed heartbeat',()=>{const e=env(),r=run(['node','status','--repo',e.repo]);assert.equal(j(r).nodes['node-a'].state,'ACTIVE')});
test('heartbeat replay is rejected',()=>{const e=env(),h=path.join(e.d,'replay.json');run(['heartbeat','create','--node-dir',e.a,'--out',h]);assert.equal(run(['heartbeat','accept','--repo',e.repo,'--heartbeat',h]).status,0);const r=run(['heartbeat','accept','--repo',e.repo,'--heartbeat',h]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HEARTBEAT_REPLAY'))});
test('tampered heartbeat signature is rejected',()=>{const e=env(),h=path.join(e.d,'bad-h.json');run(['heartbeat','create','--node-dir',e.a,'--out',h]);const x=read(h);x.sequence+=100;write(h,x);const r=run(['heartbeat','accept','--repo',e.repo,'--heartbeat',h]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HEARTBEAT_HASH_INVALID')||j(r).errors.includes('HEARTBEAT_SIGNATURE_INVALID'))});
test('identity conflict for same machine id is rejected',()=>{const e=env(),n=path.join(e.d,'evil');run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',caps(e.d,'evilcaps.json')]);const r=run(['node','enroll','--repo',e.repo,'--identity',path.join(n,'identity','identity.json')]);assert.notEqual(r.status,0);assert.equal(j(r).status,'MACHINE_IDENTITY_CONFLICT')});
test('revoked node cannot be assigned new task',()=>{const e=env();submit(e);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);const a=assign(e);assert.notEqual(a.r.status,0);assert.ok(j(a.r).errors.some(x=>x.startsWith('NODE_NOT_ACTIVE')))});

// Tasks and capability admission.
test('task payload is snapshotted',()=>{const e=env(),s=submit(e);assert.equal(s.r.status,0,s.r.stdout);const p=path.join(e.repo,'.aledevos/state/execution/phase5/tasks/task-a/payload.bin');assert.ok(fs.existsSync(p));write(s.payload,'changed');assert.equal(fs.readFileSync(p,'utf8'),'payload-task-a')});
test('duplicate task id is rejected',()=>{const e=env();submit(e);const s=submit(e);assert.notEqual(s.r.status,0);assert.equal(j(s.r).status,'REMOTE_TASK_EXISTS')});
test('assignment requires capability match',()=>{const d=tmp(),repo=path.join(d,'r'),n=path.join(d,'n');fs.mkdirSync(repo);run(['coordinator','init','--repo',repo]);const cf=caps(d,'c.json',{adapters:['claude-code'],modalities:['text'],features:['git']});run(['identity','create','--node-dir',n,'--machine-id','node-a','--capabilities',cf]);run(['node','enroll','--repo',repo,'--identity',path.join(n,'identity','identity.json')]);run(['node','approve','--repo',repo,'--machine-id','node-a']);const h=path.join(d,'h');run(['heartbeat','create','--node-dir',n,'--out',h]);run(['heartbeat','accept','--repo',repo,'--heartbeat',h]);const f=path.join(d,'p');write(f,'x');run(['task','submit','--repo',repo,'--task-id','t','--payload',f,'--adapter','codex']);const r=run(['task','assign','--repo',repo,'--task-id','t','--machine-id','node-a','--out',path.join(d,'a')]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('CAPABILITY_MISSING:adapter:codex'))});
test('assignment requires fresh active node',()=>{const e=env();submit(e);const reg=path.join(e.repo,'.aledevos/state/execution/phase5/registry.json'),x=read(reg);x.nodes['node-a'].last_heartbeat_at='2000-01-01T00:00:00.000Z';x.registry_sha256=hashObj(x,'registry_sha256');write(reg,x);const a=assign(e);assert.notEqual(a.r.status,0);assert.ok(j(a.r).errors.some(x=>x.startsWith('NODE_NOT_ACTIVE:STALE')))});
test('lease below minimum is rejected',()=>{const e=env();submit(e);const a=assign(e,'task-a','node-a',e.a,1);assert.notEqual(a.r.status,0);assert.ok(j(a.r).errors.includes('LEASE_DURATION_INVALID'))});
test('assignment bundle targets exact machine',()=>{const e=env();submit(e);const a=assign(e);assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.data.assignment.target_machine_id,'node-a');assert.equal(a.data.assignment.lease.fence_token,1)});
test('untrusted coordinator bundle is rejected',()=>{const e=env();submit(e);const a=assign(e);const n=path.join(e.d,'untrusted');run(['identity','create','--node-dir',n,'--machine-id','node-c','--capabilities',caps(e.d,'node-c.json')]);const r=run(['bundle','import','--node-dir',n,'--bundle',a.file]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('COORDINATOR_NOT_TRUSTED'))});
test('wrong target machine rejects valid signed bundle',()=>{const e=env();submit(e);const a=assign(e);const r=run(['bundle','import','--node-dir',e.b,'--bundle',a.file]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WRONG_TARGET_MACHINE'))});
test('tampered assignment is rejected even if envelope hash is recomputed',()=>{const e=env();submit(e);const a=assign(e),x=read(a.file);x.requirements.features.push('evil');x.envelope_sha256=hashObj(x,'envelope_sha256','signature');write(a.file,x);const r=run(['bundle','import','--node-dir',e.a,'--bundle',a.file]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('ASSIGNMENT_SIGNATURE_INVALID'))});
test('tampered payload is rejected',()=>{const e=env();submit(e);const a=assign(e),x=read(a.file);x.payload_base64=Buffer.from('evil').toString('base64');write(a.file,x);const r=run(['bundle','import','--node-dir',e.a,'--bundle',a.file]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('ASSIGNMENT_HASH_INVALID')||j(r).errors.includes('PAYLOAD_INTEGRITY_INVALID'))});
test('valid assignment bundle imports and preserves payload',()=>{const e=env();submit(e);const a=assign(e),r=run(['bundle','import','--node-dir',e.a,'--bundle',a.file]);assert.equal(r.status,0,r.stdout);assert.equal(fs.readFileSync(j(r).payload_path,'utf8'),'payload-task-a')});
test('same fence cannot be imported twice',()=>{const e=env();submit(e);const a=assign(e);assert.equal(run(['bundle','import','--node-dir',e.a,'--bundle',a.file]).status,0);const r=run(['bundle','import','--node-dir',e.a,'--bundle',a.file]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('STALE_FENCE_TOKEN'))});

// Ack/result and fencing.
test('ack roundtrip marks lease ACKED',()=>{const e=env();submit(e);const a=assign(e);const z=importAck(e,a);assert.equal(z.aa.status,0,z.aa.stdout);assert.equal(j(z.aa).task.state,'ACKED')});
test('result cannot be created before bundle import',()=>{const e=env(),f=path.join(e.d,'r');write(f,'x');const r=run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',f,'--out',path.join(e.d,'o')]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('TASK_NOT_IMPORTED'))});
test('result cannot be accepted before ack',()=>{const e=env();submit(e);const a=assign(e);run(['bundle','import','--node-dir',e.a,'--bundle',a.file]);const rf=path.join(e.d,'r');write(rf,'x');const out=path.join(e.d,'res.json');run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',rf,'--out',out]);const r=run(['result','accept','--repo',e.repo,'--result',out]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('LEASE_NOT_ACKED'))});
test('valid result becomes authoritative completion',()=>{const e=env();submit(e);const a=assign(e);importAck(e,a);const z=result(e,a);assert.equal(z.ac.status,0,z.ac.stdout);assert.equal(j(z.ac).task.state,'COMPLETED');assert.equal(j(z.ac).task.authoritative_result.machine_id,'node-a')});
test('same accepted result is idempotent',()=>{const e=env();submit(e);const a=assign(e);importAck(e,a);const rf=path.join(e.d,'r');write(rf,'same');const out=path.join(e.d,'res.json');run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',rf,'--out',out]);assert.equal(run(['result','accept','--repo',e.repo,'--result',out]).status,0);const r=run(['result','accept','--repo',e.repo,'--result',out]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'REMOTE_RESULT_ALREADY_ACCEPTED')});
test('different second authoritative result is rejected',()=>{const e=env();submit(e);const a=assign(e);importAck(e,a);const first=result(e,a,'task-a','one');assert.equal(first.ac.status,0);const rf=path.join(e.d,'r2');write(rf,'two');const out=path.join(e.d,'res2.json');assert.equal(run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',rf,'--out',out]).status,0);const r=run(['result','accept','--repo',e.repo,'--result',out]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('AUTHORITATIVE_RESULT_ALREADY_EXISTS'))});
test('tampered result signature is rejected',()=>{const e=env();submit(e);const a=assign(e);importAck(e,a);const rf=path.join(e.d,'r');write(rf,'x');const out=path.join(e.d,'res');run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',rf,'--out',out]);const x=read(out);x.result_payload_size+=1;x.result_sha256=hashObj(x,'result_sha256','signature');write(out,x);const r=run(['result','accept','--repo',e.repo,'--result',out]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('RESULT_SIGNATURE_INVALID'))});

test('reassignment before lease expiry is blocked',()=>{const e=env();submit(e);assign(e,'task-a','node-a',e.a,2000);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);const b=assign(e,'task-a','node-b',e.b,2000,true);assert.notEqual(b.r.status,0);assert.ok(j(b.r).errors.includes('LEASE_NOT_EXPIRED'))});
test('expired lease plus revoked owner can reassign with higher fence',()=>{const e=env();submit(e);assign(e,'task-a','node-a',e.a,100);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);sleep(140);const b=assign(e,'task-a','node-b',e.b,1000,true);assert.equal(b.r.status,0,b.r.stdout);assert.equal(b.data.assignment.lease.fence_token,2)});
test('late result from old fence is rejected after reassignment',()=>{const e=env();submit(e);const a=assign(e,'task-a','node-a',e.a,700);importAck(e,a);const rf=path.join(e.d,'old');write(rf,'old');const old=path.join(e.d,'old-result.json');assert.equal(run(['result','create','--node-dir',e.a,'--task-id','task-a','--result',rf,'--out',old]).status,0);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);sleep(760);const b=assign(e,'task-a','node-b',e.b,1000,true);assert.equal(b.r.status,0,b.r.stdout);const r=run(['result','accept','--repo',e.repo,'--result',old]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('STALE_FENCE_TOKEN')||j(r).errors.includes('LEASE_ID_MISMATCH')||j(r).errors.includes('LEASE_OWNER_MISMATCH'))});
test('new fence result succeeds after reassignment',()=>{const e=env();submit(e);assign(e,'task-a','node-a',e.a,100);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);sleep(140);const b=assign(e,'task-a','node-b',e.b,1000,true);importAck(e,b);const z=result(e,b);assert.equal(z.ac.status,0,z.ac.stdout);assert.equal(j(z.ac).task.authoritative_result.fence_token,2)});
test('reassignment limit is enforced',()=>{const e=env();submit(e);assign(e,'task-a','node-a',e.a,100);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);sleep(130);let b=assign(e,'task-a','node-b',e.b,100,true);assert.equal(b.r.status,0);run(['node','revoke','--repo',e.repo,'--machine-id','node-b']);sleep(130);run(['node','enroll','--repo',e.repo,'--identity',path.join(e.a,'identity','identity.json')]);run(['node','approve','--repo',e.repo,'--machine-id','node-a']);const h=path.join(e.d,'ha2');run(['heartbeat','create','--node-dir',e.a,'--out',h]);run(['heartbeat','accept','--repo',e.repo,'--heartbeat',h]);let a2=assign(e,'task-a','node-a',e.a,100,true);assert.equal(a2.r.status,0,a2.r.stdout);run(['node','revoke','--repo',e.repo,'--machine-id','node-a']);sleep(130);run(['node','enroll','--repo',e.repo,'--identity',path.join(e.b,'identity','identity.json')]);run(['node','approve','--repo',e.repo,'--machine-id','node-b']);const hb=path.join(e.d,'hb2');run(['heartbeat','create','--node-dir',e.b,'--out',hb]);run(['heartbeat','accept','--repo',e.repo,'--heartbeat',hb]);const third=assign(e,'task-a','node-b',e.b,100,true);assert.notEqual(third.r.status,0);assert.ok(j(third.r).errors.includes('REASSIGNMENT_LIMIT_REACHED'))});

// State integrity and locking.
test('tasks registry tamper is detected',()=>{const e=env();submit(e);const f=path.join(e.repo,'.aledevos/state/execution/phase5/tasks.json'),x=read(f);x.tasks['task-a'].payload_size=999;write(f,x);const r=run(['task','status','--repo',e.repo,'--task-id','task-a']);assert.notEqual(r.status,0);assert.equal(j(r).status,'MULTIMACHINE_TASKS_INVALID')});
test('rehashing outer tasks registry cannot hide per-task drift',()=>{const e=env();submit(e);const f=path.join(e.repo,'.aledevos/state/execution/phase5/tasks.json'),x=read(f);x.tasks['task-a'].payload_size=999;x.tasks_sha256=hashObj(x,'tasks_sha256');write(f,x);const r=run(['task','status','--repo',e.repo,'--task-id','task-a']);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(x=>x.startsWith('TASK_INTEGRITY_MISMATCH')))});
test('live coordinator lock blocks mutation',()=>{const e=env(),f=path.join(e.repo,'.aledevos/state/execution/phase5/control.lock');write(f,{pid:process.pid,created_at:new Date().toISOString()});const p=path.join(e.d,'x');write(p,'x');const r=run(['task','submit','--repo',e.repo,'--task-id','blocked','--payload',p]);assert.notEqual(r.status,0);assert.equal(j(r).status,'MULTIMACHINE_CONTROL_BUSY')});
test('stale dead coordinator lock is recovered',()=>{const e=env(),f=path.join(e.repo,'.aledevos/state/execution/phase5/control.lock');write(f,{pid:999999999,created_at:new Date(Date.now()-60000).toISOString()});const p=path.join(e.d,'x');write(p,'x');const r=run(['task','submit','--repo',e.repo,'--task-id','ok','--payload',p]);assert.equal(r.status,0,r.stdout);assert.equal(fs.existsSync(f),false)});

// Freeze, installed layout and certification.
test('P1 certificate remains valid',()=>assert.equal(runScript(p1,['certify','verify','--certificate',certs[0]]).status,0));
test('P2 certificate remains valid',()=>assert.equal(runScript(p2,['certify','verify','--certificate',certs[1]]).status,0));
test('P3 certificate remains valid',()=>assert.equal(runScript(p3,['certify','verify','--certificate',certs[2]]).status,0));
test('P4 certificate remains valid',()=>assert.equal(runScript(p4,['certify','verify','--certificate',certs[3]]).status,0));
test('recursive installer already covers P5 without shared-installer change',()=>{const s=fs.readFileSync(path.join(root,'scripts/05-install-into-project.ps1'),'utf8');assert.match(s,/advanced-execution/);assert.match(s,/Recurse/)});
test('installed execution layout verifies P5 policy',()=>{const d=tmp(),ale=path.join(d,'.aledevos','execution');fs.cpSync(path.join(root,'advanced-execution'),ale,{recursive:true});const r=spawnSync(process.execPath,[path.join(ale,'multimachine','multimachine-manager.mjs'),'policy','verify'],{cwd:d,encoding:'utf8'});assert.equal(r.status,0,r.stdout)});
test('P5 package certificate can be generated and verified',()=>{const d=tmp(),f=path.join(d,'p5cert.json'),r=run(['certify','run','--out',f]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'ADVANCED_EXECUTION_P5_PACKAGE_CERTIFIED');const v=run(['certify','verify','--certificate',f]);assert.equal(v.status,0,v.stdout)});
test('P5 certificate claims signed fencing but not network transport',()=>{const d=tmp(),f=path.join(d,'p5cert.json');run(['certify','run','--out',f]);const c=read(f);assert.equal(c.claims.lease_fencing,true);assert.equal(c.claims.authoritative_duplicate_acceptance_prevented,true);assert.equal(c.claims.physical_duplicate_compute_under_partition_claimed_prevented,false);assert.equal(c.claims.network_transport_implemented,false)});
test('P5 certificate tamper is detected',()=>{const d=tmp(),f=path.join(d,'p5cert.json');run(['certify','run','--out',f]);const c=read(f);c.claims.network_transport_implemented=true;write(f,c);const r=run(['certify','verify','--certificate',f]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('CERTIFICATE_INTEGRITY_MISMATCH'))});
test('rehashing forged P5 certificate cannot hide input drift',()=>{const d=tmp(),f=path.join(d,'p5cert.json');run(['certify','run','--out',f]);const c=read(f);c.inputs[0].sha256='0'.repeat(64);c.evidence_sha256=hashObj(c,'evidence_sha256');write(f,c);const r=run(['certify','verify','--certificate',f]);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(x=>x.startsWith('INPUT_DRIFT:')))});
