import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const p1=path.join(root,'advanced-execution/worktrees/worktree-manager.mjs');
const mgr=path.join(root,'advanced-execution/workers/worker-manager.mjs');
const runtime=path.join(root,'advanced-execution/workers/worker-runtime.mjs');
const policyFile=path.join(root,'advanced-execution/policies/worker-policy.json');
const p1Cert=path.join(root,'release/certifications/advanced-execution-p1.json');
const run=(script,argv,cwd=root,env=process.env)=>spawnSync(process.execPath,[script,...argv],{cwd,encoding:'utf8',env});
const j=r=>{try{return JSON.parse(r.stdout||'{}')}catch{return{}}};
const g=(cwd,args)=>spawnSync('git',args,{cwd,encoding:'utf8'});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')};
const tempRoots=[];const livePids=new Set();
const tmp=()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-ae-p2-'));tempRoots.push(d);return d};
const stable=(v,omit)=>Array.isArray(v)?v.map(x=>stable(x,omit)):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!omit.has(k)).sort().map(k=>[k,stable(v[k],omit)])):v;
const hashObj=(v,...omit)=>crypto.createHash('sha256').update(JSON.stringify(stable(v,new Set(omit)))).digest('hex');
afterEach(()=>{for(const pid of [...livePids]){try{process.kill(pid,'SIGKILL')}catch{}livePids.delete(pid)}for(const d of tempRoots.splice(0)){try{fs.rmSync(d,{recursive:true,force:true})}catch{}}});
function repo({ignoreState=true,protectedPaths=[]}={}){const d=tmp(),r=path.join(d,'repo');fs.mkdirSync(path.join(r,'src'),{recursive:true});fs.mkdirSync(path.join(r,'docs'),{recursive:true});assert.equal(g(r,['init','-q']).status,0);g(r,['config','user.email','test@example.com']);g(r,['config','user.name','AleDevOS Test']);fs.writeFileSync(path.join(r,'src','app.txt'),'base\n');fs.writeFileSync(path.join(r,'docs','readme.txt'),'docs\n');if(ignoreState)fs.writeFileSync(path.join(r,'.gitignore'),'.aledevos/state/\n');if(protectedPaths.length){fs.mkdirSync(path.join(r,'.aledevos'),{recursive:true});write(path.join(r,'.aledevos','project.json'),{protected_paths:protectedPaths})}g(r,['add','.']);assert.equal(g(r,['commit','-qm','initial']).status,0);return{d,r}}
function worktree(x,task='task-1'){const req=path.join(x.d,`${task}-wt-request.json`),receipt=path.join(x.d,`${task}-wt-receipt.json`);let r=run(p1,['request','prepare','--repo',x.r,'--task-id',task,'--out',req]);assert.equal(r.status,0,r.stdout+r.stderr);r=run(p1,['worktree','create','--repo',x.r,'--request',req,'--out',receipt]);assert.equal(r.status,0,r.stdout+r.stderr);const wr=read(receipt);return{task,req,receipt,wt:wr.worktree.path,wr}}
function taskContract(x,task='task-1',{inScope=['src/**'],type='FEATURE'}={}){const f=path.join(x.d,`${task}-task.json`);write(f,{task_id:task,type,risk:'LOW',objective:`Objective ${task}`,in_scope:inScope,out_of_scope:['do-not-touch/**'],acceptance_criteria:[{id:'AC1',text:'Observable result'}],invariants:['Primary stays unchanged'],verification:['src/app.txt']});return f}
function assignment(x,w,{role='builder',readScopes=[],writeScopes=['src/**'],taskFile=null}={}){const tf=taskFile||taskContract(x,w.task,{inScope:[...new Set([...writeScopes.filter(s=>s!=='**'),'src/**','docs/**'])]});const argv=['assignment','prepare','--repo',x.r,'--worktree-receipt',w.receipt,'--task-contract',tf,'--role',role];for(const s of readScopes)argv.push('--read-scope',s);for(const s of writeScopes)argv.push('--write-scope',s);const r=run(mgr,argv);return{r,data:j(r),taskFile:tf}}
function provision(x,a){const r=run(mgr,['worker','provision','--repo',x.r,'--assignment',a.data.path]);return{r,data:j(r),session:j(r).session_path}}
function start(x,p){const r=run(mgr,['worker','start','--repo',x.r,'--session',p.session]);const d=j(r);if(d.pid)livePids.add(d.pid);return{r,data:d,pid:d.pid}}
function stop(x,p){const r=run(mgr,['worker','stop','--repo',x.r,'--session',p.session]);if(p.pid)livePids.delete(p.pid);return{r,data:j(r)}}
function setup({task='task-1',role='builder',readScopes=[],writeScopes=['src/**'],inScope=null,ignoreState=true}={}){const x=repo({ignoreState}),w=worktree(x,task),tf=taskContract(x,task,{inScope:inScope||[...new Set([...writeScopes.filter(s=>s!=='**'),'src/**','docs/**'])]}),a=assignment(x,w,{role,readScopes,writeScopes,taskFile:tf});assert.equal(a.r.status,0,a.r.stdout+a.r.stderr);const p=provision(x,a);assert.equal(p.r.status,0,p.r.stdout+p.r.stderr);return{x,w,tf,a,p}}
function startSetup(opts={}){const z=setup(opts),s=start(z.x,z.p);assert.equal(s.r.status,0,s.r.stdout+s.r.stderr);z.s=s;z.p.pid=s.pid;return z}
function commit(wt,rel,content='changed\n'){const f=path.join(wt,...rel.split('/'));fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,content);g(wt,['add','-A']);assert.equal(g(wt,['commit','-qm',`change ${rel}`]).status,0)}
function handoffInput(x,name,{outcome='READY_FOR_VERIFICATION',summary='done',evidence=['src/app.txt']}={}){const f=path.join(x.d,`${name}-handoff-input.json`);write(f,{outcome,summary,evidence_refs:evidence});return f}
function sealHandoff(z,input){const r=run(mgr,['handoff','seal','--repo',z.x.r,'--session',z.p.session,'--input',input]);return{r,data:j(r),path:j(r).handoff_path}}

// Policy / boundaries.
test('P2 policy verifies',()=>assert.equal(run(mgr,['policy','verify']).status,0));
test('P2 phase is exact',()=>assert.equal(read(policyFile).phase,'ADVANCED_EXECUTION_P2_ISOLATED_WORKERS'));
test('P1 receipt is mandatory',()=>assert.equal(read(policyFile).rules.require_p1_worktree_receipt,true));
test('task contract is mandatory',()=>assert.equal(read(policyFile).rules.require_task_contract,true));
test('worker identity is derived',()=>assert.equal(read(policyFile).rules.derive_worker_id,true));
test('one worker owns one worktree',()=>{const p=read(policyFile).rules;assert.equal(p.one_worker_per_worktree,true);assert.equal(p.one_worktree_per_worker,true)});
test('worker state paths are canonical',()=>assert.equal(read(policyFile).rules.canonical_state_paths,true));
test('cross-worktree access is disabled',()=>assert.equal(read(policyFile).rules.cross_worktree_access_allowed,false));
test('external path access is disabled',()=>assert.equal(read(policyFile).rules.external_path_access_allowed,false));
test('arbitrary shell is disabled',()=>assert.equal(read(policyFile).rules.arbitrary_shell_allowed,false));
test('network is disabled in P2',()=>assert.equal(read(policyFile).rules.network_used,false));
test('supervisor process is enabled while target agent runtime remains deferred',()=>{const p=read(policyFile).rules;assert.equal(p.worker_supervisor_process_enabled,true);assert.equal(p.target_agent_runtime_binding,'DEFERRED_MASTER_VALIDATION')});
test('handoff is mandatory for completion and worker-owned',()=>{const p=read(policyFile).rules;assert.equal(p.handoff_required_for_completion,true);assert.equal(p.handoff_owned_by_worker,true);assert.equal(p.evidence_owned_by_worker,true)});
test('recovery is enabled but bounded',()=>{const p=read(policyFile);assert.equal(p.rules.recovery_enabled,true);assert.equal(p.max_recovery_count,1)});
test('P2 concurrency remains disabled',()=>{const p=read(policyFile).rules;assert.equal(p.concurrency_enabled,false);assert.equal(p.max_active_workers,1)});
test('dispatcher queue and multi-machine remain disabled',()=>{const p=read(policyFile).rules;assert.equal(p.dispatcher_enabled,false);assert.equal(p.queue_enabled,false);assert.equal(p.multi_machine_enabled,false)});
test('P1 keeps worktree cleanup ownership',()=>assert.equal(read(policyFile).rules.worktree_cleanup_owned_by_p1,true));
test('global write scope is forbidden',()=>assert.equal(read(policyFile).rules.allow_global_write_scope,false));
test('git and AleDevOS state are always protected',()=>{const p=read(policyFile).always_protected_paths;assert.ok(p.includes('.git/**'));assert.ok(p.includes('.aledevos/**'))});

// Assignment contract.
test('valid writer assignment binds a live P1 worktree and task contract',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task),a=assignment(x,w,{taskFile:tf});assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.data.assignment.task_id,w.task);assert.equal(a.data.assignment.worktree.receipt_sha256,w.wr.receipt_sha256)});
test('default read scope is whole assigned worktree',()=>{const x=repo(),w=worktree(x),a=assignment(x,w);assert.deepEqual(a.data.assignment.permissions.read_scope,['**'])});
test('writer assignment uses explicit task-contract write scope',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task,{inScope:['src/**','tests/**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['src/**','tests/**']});assert.equal(a.r.status,0);assert.deepEqual(a.data.assignment.permissions.write_scope,['src/**','tests/**'])});
test('task id mismatch fails closed',()=>{const x=repo(),w=worktree(x,'alpha'),tf=taskContract(x,'beta'),a=assignment(x,w,{taskFile:tf});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('TASK_ID_MISMATCH'))});
test('unknown worker role is rejected',()=>{const x=repo(),w=worktree(x),a=assignment(x,w,{role:'root-god-mode'});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('WORKER_ROLE_INVALID'))});
test('read-only role cannot receive write scope',()=>{const x=repo(),w=worktree(x),a=assignment(x,w,{role:'auditor',writeScopes:['src/**']});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('READ_ONLY_ROLE_HAS_WRITE_SCOPE'))});
test('product writer requires non-empty write scope',()=>{const x=repo(),w=worktree(x),a=assignment(x,w,{role:'builder',writeScopes:[]});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('PRODUCT_WRITER_WRITE_SCOPE_REQUIRED'))});
test('global write scope is rejected even if task asks for it',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task,{inScope:['**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['**']});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('GLOBAL_WRITE_SCOPE_FORBIDDEN'))});
test('write scope not present in task contract is rejected',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task,{inScope:['src/**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['docs/**']});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.some(e=>e.startsWith('WRITE_SCOPE_NOT_IN_TASK_CONTRACT')))});
test('absolute scope is rejected',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task,{inScope:['/tmp/**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['/tmp/**']});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('SCOPE_INVALID_OR_LIMIT_EXCEEDED'))});
test('scope traversal is rejected',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task,{inScope:['../**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['../**']});assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('SCOPE_INVALID_OR_LIMIT_EXCEEDED'))});
test('P2 state path must already be gitignored',()=>{const x=repo({ignoreState:false}),w=worktree(x),a=assignment(x,w);assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('STATE_PATH_NOT_GITIGNORED'))});
test('dirty task worktree blocks assignment',()=>{const x=repo(),w=worktree(x);fs.appendFileSync(path.join(w.wt,'src','app.txt'),'dirty\n');const a=assignment(x,w);assert.notEqual(a.r.status,0);assert.ok(a.data.errors.includes('WORKTREE_NOT_CLEAN_AT_ASSIGNMENT'))});
test('assignment path is canonical under primary worker state',()=>{const x=repo(),w=worktree(x),a=assignment(x,w);assert.equal(a.r.status,0);assert.ok(a.data.path.startsWith(path.join(x.r,'.aledevos','state','execution','phase2','assignments')))});
test('same assignment preparation is idempotent',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task),a1=assignment(x,w,{taskFile:tf}),a2=assignment(x,w,{taskFile:tf});assert.equal(a1.r.status,0);assert.equal(a2.r.status,0);assert.equal(a2.data.idempotent,true);assert.equal(a1.data.assignment.assignment_sha256,a2.data.assignment.assignment_sha256)});
test('worker id is deterministic for the same sealed inputs',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task),a1=assignment(x,w,{taskFile:tf}),a2=assignment(x,w,{taskFile:tf});assert.equal(a1.data.assignment.worker_id,a2.data.assignment.worker_id)});
test('assignment tamper is detected',()=>{const x=repo(),w=worktree(x),a=assignment(x,w),f=a.data.path,q=read(f);q.worker_role='auditor';write(f,q);const r=run(mgr,['assignment','verify','--repo',x.r,'--assignment',f]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('ASSIGNMENT_INTEGRITY_MISMATCH'))});
test('task-contract source drift is detected when source is supplied',()=>{const x=repo(),w=worktree(x),tf=taskContract(x,w.task),a=assignment(x,w,{taskFile:tf});fs.appendFileSync(tf,' ');const r=run(mgr,['assignment','verify','--repo',x.r,'--assignment',a.data.path,'--task-contract',tf]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('TASK_CONTRACT_SOURCE_DRIFT'))});
test('P1 receipt drift invalidates worker assignment',()=>{const x=repo(),w=worktree(x),a=assignment(x,w),q=read(w.receipt);q.task_id='evil';write(w.receipt,q);const r=run(mgr,['assignment','verify','--repo',x.r,'--assignment',a.data.path]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('P1_RECEIPT_FILE_DRIFT'))});

// Provisioning and ownership.
test('worker provision creates a PROVISIONED sealed session',()=>{const z=setup();assert.equal(z.p.data.session.state,'PROVISIONED');assert.match(z.p.data.session.session_sha256,/^[0-9a-f]{64}$/)});
test('worker state is stored in primary ignored control state, not task worktree',()=>{const z=setup();assert.ok(z.p.session.startsWith(path.join(z.x.r,'.aledevos','state','execution','phase2')));assert.equal(fs.existsSync(path.join(z.w.wt,'.aledevos','state','execution','phase2')),false)});
test('primary checkout remains clean after assignment and provision',()=>{const z=setup();assert.equal(g(z.x.r,['status','--porcelain']).stdout.trim(),'')});
test('registry records exclusive worktree ownership',()=>{const z=setup(),reg=read(path.join(z.x.r,'.aledevos/state/execution/phase2/registry.json'));assert.equal(reg.ownership[z.a.data.assignment.worktree.receipt_sha256],z.a.data.assignment.worker_id)});
test('same worker cannot be provisioned twice',()=>{const z=setup(),r=run(mgr,['worker','provision','--repo',z.x.r,'--assignment',z.a.data.path]);assert.notEqual(r.status,0);assert.equal(j(r).status,'WORKER_ALREADY_PROVISIONED')});
test('same worktree cannot be owned by a second worker identity',()=>{const z=setup(),a2=assignment(z.x,z.w,{role:'auditor',writeScopes:[],taskFile:z.tf});assert.equal(a2.r.status,0);const r=run(mgr,['worker','provision','--repo',z.x.r,'--assignment',a2.data.path]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WORKTREE_ALREADY_OWNED'))});
test('dirty worktree after assignment blocks provision',()=>{const x=repo(),w=worktree(x),a=assignment(x,w);assert.equal(a.r.status,0);fs.appendFileSync(path.join(w.wt,'src','app.txt'),'dirty\n');const r=run(mgr,['worker','provision','--repo',x.r,'--assignment',a.data.path]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WORKTREE_NOT_CLEAN_AT_PROVISION'))});
test('session tamper is detected',()=>{const z=setup(),q=read(z.p.session);q.state='RUNNING';write(z.p.session,q);const r=run(mgr,['session','verify','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('SESSION_INTEGRITY_MISMATCH'))});
test('session must remain at its canonical worker-owned path',()=>{const z=setup(),copy=path.join(z.x.d,'session-copy.json');fs.copyFileSync(z.p.session,copy);const r=run(mgr,['session','verify','--repo',z.x.r,'--session',copy]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('SESSION_NONCANONICAL_PATH'))});

// Real worker supervisor process and path isolation.
test('worker start launches a real supervisor process in RUNNING state',()=>{const z=startSetup();assert.equal(z.s.data.session.state,'RUNNING');assert.equal(typeof z.s.pid,'number');assert.equal(z.s.data.session.boundaries.worker_supervisor_started,true)});
test('heartbeat proves supervisor cwd is exactly the assigned worktree',()=>{const z=startSetup();assert.equal(path.resolve(z.s.data.heartbeat.cwd),path.resolve(z.w.wt))});
test('target agent runtime is not falsely claimed as started',()=>{const z=startSetup();assert.equal(z.s.data.session.boundaries.target_agent_runtime_started,false)});
test('supervisor environment strips arbitrary secret variables',()=>{process.env.ALEDEVOS_TEST_SECRET_SHOULD_NOT_LEAK='top-secret';try{const z=startSetup();assert.equal(z.s.data.heartbeat.visible_env_keys.includes('ALEDEVOS_TEST_SECRET_SHOULD_NOT_LEAK'),false)}finally{delete process.env.ALEDEVOS_TEST_SECRET_SHOULD_NOT_LEAK}});
test('worker status verifies live PID and heartbeat',()=>{const z=startSetup(),r=run(mgr,['worker','status','--repo',z.x.r,'--session',z.p.session]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'WORKER_RUNNING')});
test('P2 blocks a second simultaneously running worker',()=>{const x=repo(),w1=worktree(x,'one'),t1=taskContract(x,'one'),a1=assignment(x,w1,{taskFile:t1}),p1x=provision(x,a1),s1=start(x,p1x);assert.equal(s1.r.status,0);p1x.pid=s1.pid;const w2=worktree(x,'two'),t2=taskContract(x,'two'),a2=assignment(x,w2,{taskFile:t2}),p2x=provision(x,a2),r=run(mgr,['worker','start','--repo',x.r,'--session',p2x.session]);assert.equal(r.status,7);assert.ok(j(r).errors.includes('CONCURRENCY_DISABLED_ACTIVE_WORKER_EXISTS'))});
test('read inside assigned worktree is allowed',()=>{const z=startSetup(),r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path','src/app.txt']);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'WORKER_PATH_ALLOWED')});
test('write inside granted scope is allowed',()=>{const z=startSetup(),r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','write','--path','src/new.txt']);assert.equal(r.status,0,r.stdout)});
test('write outside granted scope is blocked',()=>{const z=startSetup(),r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','write','--path','docs/readme.txt']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WRITE_SCOPE_DENIED'))});
test('absolute external path is blocked',()=>{const z=startSetup(),outside=path.join(z.x.d,'outside.txt');fs.writeFileSync(outside,'x');const r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path',outside]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PATH_OUTSIDE_ASSIGNED_WORKTREE'))});
test('worker A cannot access worker B worktree',()=>{const x=repo(),w1=worktree(x,'one'),t1=taskContract(x,'one'),a1=assignment(x,w1,{taskFile:t1}),p1x=provision(x,a1),s1=start(x,p1x);assert.equal(s1.r.status,0);p1x.pid=s1.pid;const w2=worktree(x,'two'),r=run(mgr,['scope','check','--repo',x.r,'--session',p1x.session,'--operation','read','--path',path.join(w2.wt,'src','app.txt')]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PATH_OUTSIDE_ASSIGNED_WORKTREE'))});
test('.git is protected even though read scope defaults to all',()=>{const z=startSetup(),r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path','.git']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PROTECTED_PATH'))});
test('.aledevos is protected even if created inside worktree',()=>{const z=startSetup();fs.mkdirSync(path.join(z.w.wt,'.aledevos'),{recursive:true});const r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path','.aledevos']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PROTECTED_PATH'))});
test('symlink escape outside worktree is blocked',()=>{const z=startSetup(),outside=path.join(z.x.d,'outside.txt');fs.writeFileSync(outside,'secret');fs.symlinkSync(outside,path.join(z.w.wt,'src','escape-link'));const r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path','src/escape-link']);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(e=>e.includes('SYMLINK')||e.includes('REALPATH')))});
test('broken symlink path is blocked fail-closed',()=>{const z=startSetup();fs.symlinkSync(path.join(z.x.d,'missing-target'),path.join(z.w.wt,'src','broken'));const r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','write','--path','src/broken/new.txt']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PATH_SYMLINK_UNRESOLVABLE'))});
test('worker stop is cooperative and transitions to STOPPED',()=>{const z=startSetup(),r=stop(z.x,z.p);assert.equal(r.r.status,0,r.r.stdout);assert.equal(r.data.session.state,'STOPPED')});
test('stopped worker no longer authorizes path operations',()=>{const z=startSetup();stop(z.x,z.p);const r=run(mgr,['scope','check','--repo',z.x.r,'--session',z.p.session,'--operation','read','--path','src/app.txt']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WORKER_NOT_RUNNING'))});
test('primary checkout remains clean while worker supervisor runs',()=>{const z=startSetup();assert.equal(g(z.x.r,['status','--porcelain']).stdout.trim(),'')});

// Recovery semantics.
test('killed supervisor is detected as WORKER_PROCESS_LOST',()=>{const z=startSetup();process.kill(z.s.pid,'SIGKILL');livePids.delete(z.s.pid);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,150);const r=run(mgr,['worker','status','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.equal(j(r).status,'WORKER_PROCESS_LOST')});
test('lost worker recovers to STOPPED under same identity',()=>{const z=startSetup(),id=z.s.data.worker_id;process.kill(z.s.pid,'SIGKILL');livePids.delete(z.s.pid);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,150);const r=run(mgr,['worker','recover','--repo',z.x.r,'--session',z.p.session]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'WORKER_RECOVERED_TO_STOPPED');assert.equal(j(r).worker_id,id)});
test('healthy worker refuses unnecessary recovery',()=>{const z=startSetup(),r=run(mgr,['worker','recover','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.equal(j(r).status,'WORKER_RECOVERY_NOT_REQUIRED')});
test('recovered worker can start once again with same worker id',()=>{const z=startSetup(),id=z.s.data.worker_id;process.kill(z.s.pid,'SIGKILL');livePids.delete(z.s.pid);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,150);assert.equal(run(mgr,['worker','recover','--repo',z.x.r,'--session',z.p.session]).status,0);const r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]);const d=j(r);if(d.pid)livePids.add(d.pid);assert.equal(r.status,0,r.stdout);assert.equal(d.worker_id,id)});
test('second process loss exhausts single recovery allowance and marks FAILED',()=>{const z=startSetup();process.kill(z.s.pid,'SIGKILL');livePids.delete(z.s.pid);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,120);assert.equal(run(mgr,['worker','recover','--repo',z.x.r,'--session',z.p.session]).status,0);let r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]),d=j(r);assert.equal(r.status,0);livePids.add(d.pid);process.kill(d.pid,'SIGKILL');livePids.delete(d.pid);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,120);r=run(mgr,['worker','recover','--repo',z.x.r,'--session',z.p.session]);assert.equal(r.status,7);assert.equal(j(r).status,'WORKER_RECOVERY_EXHAUSTED');assert.equal(j(r).session.state,'FAILED')});
test('worker start count prevents unbounded restart loops',()=>{const z=startSetup();stop(z.x,z.p);let r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]),d=j(r);assert.equal(r.status,0);livePids.add(d.pid);z.p.pid=d.pid;stop(z.x,z.p);r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('WORKER_START_LIMIT_REACHED'))});

// Handoff and finalization.
test('handoff derives changed paths from Git and seals worker-owned evidence',()=>{const z=startSetup({writeScopes:['src/**']}),wt=z.w.wt;commit(wt,'src/app.txt','changed\n');const input=handoffInput(z.x,'ok',{evidence:['src/app.txt']}),h=sealHandoff(z,input);assert.equal(h.r.status,0,h.r.stdout);assert.deepEqual(h.data.handoff.changed_paths,['src/app.txt']);assert.equal(h.data.handoff.boundaries.worker_supplied_changed_paths,false);assert.equal(h.data.handoff.ownership.handoff_owner_worker_id,z.a.data.assignment.worker_id)});
test('dirty worktree blocks handoff sealing',()=>{const z=startSetup();fs.appendFileSync(path.join(z.w.wt,'src','app.txt'),'dirty\n');const h=sealHandoff(z,handoffInput(z.x,'dirty',{evidence:['src/app.txt']}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.includes('WORKTREE_DIRTY_AT_HANDOFF'))});
test('committed change outside write scope blocks handoff',()=>{const z=startSetup({writeScopes:['src/**'],inScope:['src/**','docs/**']}),wt=z.w.wt;commit(wt,'docs/readme.txt','bad\n');const h=sealHandoff(z,handoffInput(z.x,'scope',{evidence:['src/app.txt']}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.some(e=>e.startsWith('CHANGED_PATH_OUT_OF_SCOPE')))});
test('read-only worker cannot hand off committed product changes',()=>{const z=startSetup({role:'auditor',writeScopes:[],inScope:['src/**']}),wt=z.w.wt;commit(wt,'src/app.txt','bad\n');const h=sealHandoff(z,handoffInput(z.x,'readonly',{evidence:[],outcome:'FAILED'}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.includes('READ_ONLY_WORKER_CHANGED_FILES'))});
test('READY handoff requires at least one evidence ref',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'noevidence',{evidence:[]}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.includes('HANDOFF_EVIDENCE_REQUIRED'))});
test('missing evidence file blocks handoff',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'missing',{evidence:['src/missing.txt']}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.some(e=>e.startsWith('EVIDENCE_FILE_MISSING')))});
test('external evidence path is blocked',()=>{const z=startSetup(),outside=path.join(z.x.d,'outside.txt');fs.writeFileSync(outside,'x');const h=sealHandoff(z,handoffInput(z.x,'outside',{evidence:[outside]}));assert.notEqual(h.r.status,0);assert.ok(h.data.errors.some(e=>e.startsWith('EVIDENCE_PATH_DENIED')))});
test('handoff is immutable once sealed',()=>{const z=startSetup(),h1=sealHandoff(z,handoffInput(z.x,'one',{evidence:['src/app.txt']}));assert.equal(h1.r.status,0);const h2=sealHandoff(z,handoffInput(z.x,'two',{evidence:['src/app.txt']}));assert.notEqual(h2.r.status,0);assert.equal(h2.data.status,'WORKER_HANDOFF_IMMUTABLE')});
test('handoff content tamper is detected',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'tamper',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);const q=read(h.path);q.summary='forged';write(h.path,q);const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HANDOFF_INTEGRITY_MISMATCH'))});
test('rehashing forged handoff still fails semantic evidence checks',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'rehash',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);const q=read(h.path);q.changed_paths=['docs/readme.txt'];q.handoff_sha256=hashObj(q,'handoff_sha256');write(h.path,q);const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HANDOFF_CHANGED_PATHS_DRIFT'))});
test('evidence drift after sealing invalidates handoff',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'drift',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);fs.writeFileSync(path.join(z.w.wt,'src','app.txt'),'drift\n');const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(e=>e.startsWith('HANDOFF_EVIDENCE_DRIFT')))});
test('new commit after handoff causes Git head drift',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'head',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);commit(z.w.wt,'src/new.txt','new\n');const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HANDOFF_GIT_HEAD_DRIFT'))});
test('READY handoff finalizes worker to COMPLETED and stops process',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'complete',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);const r=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(r.status,0,r.stdout);assert.equal(j(r).state,'COMPLETED');assert.equal(j(r).session.lifecycle.handoff_sha256,h.data.handoff.handoff_sha256)});
test('BLOCKED handoff finalizes worker to BLOCKED',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'blocked',{outcome:'BLOCKED',evidence:[]}));assert.equal(h.r.status,0);const r=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(r.status,0);assert.equal(j(r).state,'BLOCKED')});
test('FAILED handoff finalizes worker to FAILED',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'failed',{outcome:'FAILED',evidence:[]}));assert.equal(h.r.status,0);const r=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(r.status,0);assert.equal(j(r).state,'FAILED')});
test('finalization without a handoff fails closed',()=>{const z=startSetup(),missing=path.join(z.x.d,'missing-handoff.json'),r=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',missing]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('HANDOFF_MISSING'))});
test('completed worker cannot restart',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'terminal',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);let r=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(r.status,0);r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('SESSION_STATE_NOT_STARTABLE:COMPLETED'))});
test('handoff remains valid after finalization via sealed source-session binding',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'finalverify',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);const f=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(f.status,0);const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'WORKER_HANDOFF_VALID')});
test('P2 completion never removes the P1 worktree or task branch',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'preserve',{evidence:['src/app.txt']}));assert.equal(h.r.status,0);const f=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(f.status,0);assert.equal(fs.existsSync(z.w.wt),true);assert.equal(g(z.x.r,['show-ref','--verify',`refs/heads/${z.w.wr.worktree.branch}`]).status,0)});

// Final P2 hardening: project protection, serialized mutations, durable evidence.
test('project protected paths override task write scope',()=>{const x=repo({protectedPaths:['docs/**']}),w=worktree(x),tf=taskContract(x,w.task,{inScope:['docs/**']}),a=assignment(x,w,{taskFile:tf,writeScopes:['docs/**']});assert.equal(a.r.status,0,a.r.stdout);const p=provision(x,a);assert.equal(p.r.status,0,p.r.stdout);const st=start(x,p);assert.equal(st.r.status,0,st.r.stdout);p.pid=st.pid;const r=run(mgr,['scope','check','--repo',x.r,'--session',p.session,'--operation','write','--path','docs/readme.txt']);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PROTECTED_PATH'))});
test('project protection config drift invalidates assignment',()=>{const x=repo({protectedPaths:['docs/**']}),w=worktree(x),a=assignment(x,w);assert.equal(a.r.status,0,a.r.stdout);const pf=path.join(x.r,'.aledevos','project.json'),q=read(pf);q.protected_paths=['src/**'];write(pf,q);const r=run(mgr,['assignment','verify','--repo',x.r,'--assignment',a.data.path]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('PROJECT_PROTECTION_CONFIG_DRIFT'))});
test('control-plane mutation lock fails closed',()=>{const z=setup(),lock=path.join(z.x.r,'.aledevos','state','execution','phase2','control.lock');fs.mkdirSync(path.dirname(lock),{recursive:true});fs.writeFileSync(lock,JSON.stringify({pid:process.pid})+'\n');const r=run(mgr,['worker','start','--repo',z.x.r,'--session',z.p.session]);assert.notEqual(r.status,0);assert.equal(j(r).status,'WORKER_CONTROL_BUSY');assert.ok(j(r).errors.includes('CONTROL_MUTATION_ALREADY_IN_PROGRESS'));fs.rmSync(lock,{force:true})});
test('handoff snapshots evidence into primary worker-owned state',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'snapshot',{evidence:['src/app.txt']}));assert.equal(h.r.status,0,h.r.stdout);const e=h.data.handoff.evidence[0];assert.equal(e.source_sha256,e.snapshot_sha256);const sp=path.join(z.x.r,...e.snapshot_path.split('/'));assert.equal(fs.existsSync(sp),true);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(sp)).digest('hex'),e.snapshot_sha256)});
test('tampered evidence snapshot invalidates handoff',()=>{const z=startSetup(),h=sealHandoff(z,handoffInput(z.x,'snapshot-tamper',{evidence:['src/app.txt']}));assert.equal(h.r.status,0,h.r.stdout);const e=h.data.handoff.evidence[0],sp=path.join(z.x.r,...e.snapshot_path.split('/'));fs.writeFileSync(sp,'tampered\n');const r=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(x=>x.startsWith('HANDOFF_EVIDENCE_SNAPSHOT_DRIFT')))});
test('completed handoff remains verifiable after P1 worktree cleanup',()=>{const z=startSetup();commit(z.w.wt,'src/app.txt','after-cleanup\n');const h=sealHandoff(z,handoffInput(z.x,'cleanup-verify',{evidence:['src/app.txt']}));assert.equal(h.r.status,0,h.r.stdout);const f=run(mgr,['worker','finalize','--repo',z.x.r,'--session',z.p.session,'--handoff',h.path]);livePids.delete(z.s.pid);assert.equal(f.status,0,f.stdout);const cleanup=path.join(z.x.d,'cleanup.json'),c=run(p1,['worktree','cleanup','--receipt',z.w.receipt,'--repo',z.x.r,'--out',cleanup]);assert.equal(c.status,0,c.stdout+c.stderr);assert.equal(fs.existsSync(z.w.wt),false);const v=run(mgr,['handoff','verify','--repo',z.x.r,'--handoff',h.path,'--session',z.p.session]);assert.equal(v.status,0,v.stdout+v.stderr);assert.equal(j(v).status,'WORKER_HANDOFF_VALID')});

// Package / installed layout / certification.
test('P1 frozen certificate remains valid',()=>assert.equal(run(p1,['certify','verify','--certificate',p1Cert]).status,0));
test('worker manager and runtime do not contain adapter-specific provider names',()=>{const text=(fs.readFileSync(mgr,'utf8')+'\n'+fs.readFileSync(runtime,'utf8')).toLowerCase();for(const n of ['opencode','codex','claude','antigravity','gemini'])assert.equal(text.includes(n),false,n)});
test('worker runtime does not import network or shell modules',()=>{const text=fs.readFileSync(runtime,'utf8');for(const n of ["node:http","node:https","node:net","node:dgram","node:child_process"])assert.equal(text.includes(n),false,n)});
test('advanced execution recursive installer projection remains present for P2+',()=>{const text=fs.readFileSync(path.join(root,'scripts/05-install-into-project.ps1'),'utf8');assert.match(text,/advanced-execution/);assert.match(text,/execution/);assert.match(text,/Recurse/)});
test('installed .aledevos execution layout can run P2 policy verification',()=>{const d=tmp(),ale=path.join(d,'.aledevos','execution');fs.cpSync(path.join(root,'advanced-execution'),ale,{recursive:true});const im=path.join(ale,'workers','worker-manager.mjs'),r=run(im,['policy','verify'],d);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(j(r).status,'WORKER_POLICY_VALID')});
test('P2 JSON schemas and templates parse',()=>{for(const f of ['worker-policy.json','../schemas/worker-assignment.schema.json','../schemas/worker-session.schema.json','../schemas/worker-handoff.schema.json','../schemas/worker-handoff-input.schema.json','../templates/worker-assignment.example.json','../templates/worker-handoff-input.example.json']){const p=f.startsWith('worker-policy')?path.join(root,'advanced-execution/policies',f):path.join(root,'advanced-execution/policies',f);assert.doesNotThrow(()=>read(path.normalize(p)),p)}});
test('P2 package certification can be generated and verified',()=>{const d=tmp(),cert=path.join(d,'p2.json'),r=run(mgr,['certify','run','--out',cert]);assert.equal(r.status,0,r.stdout);assert.equal(j(r).status,'ADVANCED_EXECUTION_P2_PACKAGE_CERTIFIED');const v=run(mgr,['certify','verify','--certificate',cert]);assert.equal(v.status,0,v.stdout);assert.equal(j(v).status,'ADVANCED_EXECUTION_P2_CERTIFICATE_VALID')});
test('P2 certificate truthfully defers target agent runtime binding',()=>{const d=tmp(),cert=path.join(d,'p2.json');assert.equal(run(mgr,['certify','run','--out',cert]).status,0);const c=read(cert);assert.equal(c.target_runtime_validation,'DEFERRED');assert.equal(c.claims.real_worker_supervisor_process,true);assert.equal(c.claims.target_agent_runtime_binding,false);assert.equal(c.claims.concurrency_disabled,true)});
test('P2 certificate tamper is detected',()=>{const d=tmp(),cert=path.join(d,'p2.json');assert.equal(run(mgr,['certify','run','--out',cert]).status,0);const c=read(cert);c.claims.network_disabled=false;write(cert,c);const r=run(mgr,['certify','verify','--certificate',cert]);assert.notEqual(r.status,0);assert.ok(j(r).errors.includes('CERTIFICATE_INTEGRITY_MISMATCH'))});
test('rehashing forged certificate cannot hide input drift',()=>{const d=tmp(),cert=path.join(d,'p2.json');assert.equal(run(mgr,['certify','run','--out',cert]).status,0);const c=read(cert);c.inputs[0].sha256='0'.repeat(64);c.evidence_sha256=hashObj(c,'evidence_sha256');write(cert,c);const r=run(mgr,['certify','verify','--certificate',cert]);assert.notEqual(r.status,0);assert.ok(j(r).errors.some(e=>e.startsWith('INPUT_DRIFT:')))});
