import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const runtime=path.resolve('core/engine/aledevos.mjs');
const run=(cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-'));
const statePath=cwd=>path.join(cwd,'.aledevos/state/current.json');
function setCompleteGates(cwd){const p=statePath(cwd);const s=JSON.parse(fs.readFileSync(p,'utf8'));s.gates={scope:{status:'PASS'},integrity:{status:'PASS'},canonical:{status:'PASS'},quality_engineering:{status:'PASS'}};fs.writeFileSync(p,JSON.stringify(s,null,2));}
function git(cwd,...a){return spawnSync('git',a,{cwd,encoding:'utf8'});}
function initGit(cwd){git(cwd,'init');git(cwd,'config','user.email','test@unit.invalid');git(cwd,'config','user.name','Test');}

test('repair cap stops third repair',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});assert.equal(run(cwd,'state','init','--task-id','T1','--scope','src/**','--criterion','AC1').status,0);assert.equal(run(cwd,'state','repair-start').status,0);assert.equal(run(cwd,'state','repair-start').status,0);const x=run(cwd,'state','repair-start');assert.equal(x.status,4);assert.match(x.stdout,/MAX_REPAIRS_REACHED/)});

test('finalize PASS only with complete gates, judges and criteria',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T2','--scope','src/**','--criterion','AC1');run(cwd,'state','criterion','--id','AC1','--status','VERIFIED');setCompleteGates(cwd);for(const j of ['requirements','regression','quality'])run(cwd,'state','judge','--judge',j,'--score','95','--blockers','0','--unverified','0');const x=run(cwd,'state','finalize');assert.equal(x.status,0);assert.match(x.stdout,/PASS/)});
test('Codex finalization requires completed Builder, Verifier and Judges',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T2-codex','--adapter','codex','--scope','src/**','--criterion','AC1');run(cwd,'state','criterion','--id','AC1','--status','VERIFIED');setCompleteGates(cwd);let x=run(cwd,'state','judge','--judge','requirements','--score','95','--blockers','0','--unverified','0');assert.equal(x.status,48);for(const a of ['builder','verifier']){run(cwd,'state','agent','--name',a,'--status','STARTED');run(cwd,'state','agent','--name',a,'--status','COMPLETED')}for(const j of ['requirements','regression','quality']){run(cwd,'state','agent','--name',`judge-${j}`,'--status','STARTED');run(cwd,'state','judge','--judge',j,'--score','95','--blockers','0','--unverified','0');run(cwd,'state','agent','--name',`judge-${j}`,'--status','COMPLETED')}x=run(cwd,'state','finalize');assert.equal(x.status,0);assert.match(x.stdout,/PASS/)});

test('Codex runtime rejects out-of-order specialist transitions',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T2-order','--adapter','codex','--scope','src/**','--criterion','AC1');let x=run(cwd,'state','agent','--name','verifier','--status','STARTED');assert.equal(x.status,44);x=run(cwd,'state','agent','--name','judge-quality','--status','STARTED');assert.equal(x.status,45);x=run(cwd,'state','agent','--name','regression','--status','STARTED');assert.equal(x.status,42)});
test('Codex scope approval updates the task contract and prevents role reopening',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T2-contract','--adapter','codex','--scope','src/**','--criterion','AC1');let x=run(cwd,'state','scope-approve','--add','test/**');assert.equal(x.status,0);const s=JSON.parse(fs.readFileSync(statePath(cwd),'utf8'));const c=JSON.parse(fs.readFileSync(path.join(cwd,s.task_contract_path),'utf8'));assert.deepEqual(c.approved_scope,['src/**','test/**']);run(cwd,'state','agent','--name','builder','--status','STARTED');run(cwd,'state','agent','--name','builder','--status','COMPLETED');x=run(cwd,'state','agent','--name','builder','--status','STARTED');assert.equal(x.status,50)});

test('unresolved task becomes FAILED after two repairs',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T3','--scope','src/**','--criterion','AC1');setCompleteGates(cwd);run(cwd,'state','repair-start');run(cwd,'state','repair-start');const x=run(cwd,'state','finalize');assert.equal(x.status,7);assert.match(x.stdout,/FAILED/)});

test('blocked reason finalizes BLOCKED',()=>{const cwd=temp();fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});run(cwd,'state','init','--task-id','T4','--scope','src/**','--criterion','AC1');run(cwd,'state','block','--reason','contradictory requirements');const x=run(cwd,'state','finalize');assert.equal(x.status,6);assert.match(x.stdout,/BLOCKED/)});

test('scope check emits escalation for out-of-scope change and records FAIL',()=>{const cwd=temp();initGit(cwd);fs.mkdirSync(path.join(cwd,'src'),{recursive:true});fs.writeFileSync(path.join(cwd,'src/a.txt'),'a');git(cwd,'add','.');git(cwd,'commit','-m','base');fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});fs.writeFileSync(path.join(cwd,'.aledevos/project.json'),JSON.stringify({protected_paths:[]},null,2));run(cwd,'state','init','--task-id','T5','--scope','src/a.txt','--criterion','AC1');fs.writeFileSync(path.join(cwd,'src/b.txt'),'b');const x=run(cwd,'scope','check');assert.equal(x.status,9);assert.match(x.stdout,/SCOPE_ESCALATION/);const s=JSON.parse(fs.readFileSync(statePath(cwd),'utf8'));assert.equal(s.gates.scope.status,'FAIL')});

test('canonical gate refuses package script drift',()=>{const cwd=temp();initGit(cwd);fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});fs.mkdirSync(path.join(cwd,'.aledevos'),{recursive:true});fs.writeFileSync(path.join(cwd,'package.json'),JSON.stringify({scripts:{test:'node -e "process.exit(0)"'}},null,2));fs.writeFileSync(path.join(cwd,'.aledevos/project.json'),JSON.stringify({version:1,configured:true,gates:[{id:'tests',command:'npm test',required:true}],protected_paths:[],test_patterns:[],gate_integrity:{package_scripts:{test:'vitest run'},files:{}}},null,2));run(cwd,'state','init','--task-id','T6','--scope','src/**','--criterion','AC1');const x=run(cwd,'gate','run');assert.equal(x.status,14);assert.match(x.stdout,/GATE_INTEGRITY_DRIFT/);const s=JSON.parse(fs.readFileSync(statePath(cwd),'utf8'));assert.equal(s.gates.canonical.status,'FAIL')});

test('integrity scan blocks newly added test.only',()=>{const cwd=temp();initGit(cwd);fs.mkdirSync(path.join(cwd,'tests'),{recursive:true});fs.writeFileSync(path.join(cwd,'tests/a.test.js'),'test("a",()=>{});\n');fs.writeFileSync(path.join(cwd,'.gitignore'),'.aledevos/state/\n');git(cwd,'add','.');git(cwd,'commit','-m','base');fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});fs.writeFileSync(path.join(cwd,'.aledevos/project.json'),JSON.stringify({protected_paths:[],test_patterns:['tests/**']},null,2));run(cwd,'state','init','--task-id','T7','--scope','tests/a.test.js','--criterion','AC1');fs.appendFileSync(path.join(cwd,'tests/a.test.js'),'test.only("b",()=>{});\n');const x=run(cwd,'integrity','scan');assert.equal(x.status,10);assert.match(x.stdout,/TEST_INTEGRITY_FAIL/);const s=JSON.parse(fs.readFileSync(statePath(cwd),'utf8'));assert.equal(s.gates.integrity.status,'FAIL')});

test('canonical gate pass records deterministic PASS',()=>{const cwd=temp();initGit(cwd);fs.mkdirSync(path.join(cwd,'.aledevos/state'),{recursive:true});fs.mkdirSync(path.join(cwd,'.aledevos'),{recursive:true});fs.writeFileSync(path.join(cwd,'package.json'),JSON.stringify({scripts:{test:'node -e "process.exit(0)"'}},null,2));fs.writeFileSync(path.join(cwd,'.aledevos/project.json'),JSON.stringify({version:1,configured:true,gates:[{id:'tests',command:'npm test',required:true}],protected_paths:[],test_patterns:[],gate_integrity:{package_scripts:{test:'node -e "process.exit(0)"'},files:{}}},null,2));run(cwd,'state','init','--task-id','T8','--scope','src/**','--criterion','AC1');const x=run(cwd,'gate','run');assert.equal(x.status,0);assert.match(x.stdout,/GATE_PASS/);const s=JSON.parse(fs.readFileSync(statePath(cwd),'utf8'));assert.equal(s.gates.canonical.status,'PASS')});
