import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const engine=path.join(root,'efficiency/engine/efficiency-governor.mjs');
const release=path.join(root,'release/engine/v1-release.mjs');
const policy=JSON.parse(fs.readFileSync(path.join(root,'efficiency/policies/efficiency-policy.json'),'utf8'));
const run=(bin,a)=>{const r=spawnSync(process.execPath,[bin,...a],{cwd:root,encoding:'utf8',windowsHide:true,shell:false});let q=null;try{q=JSON.parse((r.stdout||'').trim())}catch{}return{status:r.status,stdout:r.stdout||'',stderr:r.stderr||'',q}};
const write=(p,q)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(q,null,2)+'\n');return p};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const rel=p=>path.relative(root,p).replaceAll('\\','/');
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())o[k]=stable(v[k]);return o}return v}
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
function tmp(){const p=path.join(root,'.aledevos','state','p7-tests',`${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`);fs.mkdirSync(p,{recursive:true});return p}
function task(o={}){return {task_id:o.task_id||'P7-TASK',type:o.type||'BUGFIX',risk:o.risk||'LOW',objective:'Do the requested work',in_scope:o.in_scope||['src/a.js'],out_of_scope:[],acceptance_criteria:o.acceptance_criteria||[{id:'AC1',text:'done'}]}}
const signalNames=['cross_domain','security_sensitive','database_affecting','external_integration','ui_affecting','visual_validation_required','unknown_requirements','migration_or_destructive','multi_machine','requires_research','knowledge_stale','repair_required'];
function signals(domains=['backend'],over={}){return {schema_version:'1.0',domains,signals:Object.fromEntries(signalNames.map(k=>[k,over[k]===true]))}}
function createPlan(b,t=task(),s=signals()){const tp=write(path.join(b,'task.json'),t),sp=write(path.join(b,'signals.json'),s),pp=path.join(b,'plan.json'),r=run(engine,['plan','create','--root',root,'--task',tp,'--signals',sp,'--out',pp]);assert.equal(r.status,0,r.stdout+r.stderr);return{tp,sp,pp,plan:read(pp)}}
function telemetry({taskId='P7-TASK',key='p7-key',input=10000,output=1200,context=12000,tools=20,files=12,handoff=800,repairs=0,calls=10,agentCount=4}={}){const agents=Object.fromEntries(Array.from({length:agentCount},(_,i)=>[`agent-${i+1}`,{calls:Math.floor(calls/agentCount)+(i<calls%agentCount?1:0),input_tokens:null,output_tokens:null,duration_ms:null,generation_ms:null,context_peak_tokens:null,tool_calls:null,files_read:null,bytes_read:null,reported_decode_tps_samples:[],derived_decode_tps:null}]));const q={version:'1.0.0',run_id:`run-${input}-${tools}`,task_id:taskId,benchmark_key:key,totals:{input_tokens:input,output_tokens:output,tool_calls:tools,files_read:files,bytes_read:5000,handoff_tokens:handoff,checkpoint_tokens:null,resume_tokens:null,compactions:0,checkpoints:0,resumes:0,handoffs:1,repairs},context:{peak_tokens:context,samples:1,pressure_bands:{NORMAL:1}},research_cache:{hit:0,miss:0,stale:0,invalid:0,hit_rate:null},knowledge:{refreshes:0,reparsed_files:0,reused_files:0,scanned_files:0,research_invalidated:0},gates:{pass:3,fail:0,blocked:0,skipped:0},judges:{count:3,min_score:95,avg_score:96,total_blockers:0,scores:[96,96,96]},agents,final_state:'PASS',integrity:{algorithm:'sha256',event_chain_tail:'a'.repeat(64),payload_sha256:''}};const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);return q}
function state({taskId='P7-TASK',scores=[96,96,96],repair=0,final='PASS',blockers=[]}={}){return {version:1,task_id:taskId,approved_scope:['src/a.js'],scope_version:1,acceptance_criteria:[{id:'AC1',status:'VERIFIED'}],gates:{scope:{status:'PASS'},integrity:{status:'PASS'},canonical:{status:'PASS'}},judges:{requirements:{score:scores[0],blockers:0,unverified:0},regression:{score:scores[1],blockers:0,unverified:0},quality:{score:scores[2],blockers:0,unverified:0}},blockers,repair_count:repair,max_repairs:2,blocked_reason:null,final_state:final,history:[]}}
function benchFixture(opts={}){const b=tmp(),pl=createPlan(b,opts.task||task(),opts.signals||signals());const bs=write(path.join(b,'base.summary.json'),telemetry(opts.baseTelemetry||{}));const cs=write(path.join(b,'cand.summary.json'),telemetry({input:6000,output:900,context:10000,tools:16,files:8,handoff:400,calls:7,agentCount:3,...(opts.candTelemetry||{})}));const bg=write(path.join(b,'base.state.json'),state(opts.baseState||{}));const cg=write(path.join(b,'cand.state.json'),state(opts.candState||{}));const iv=write(path.join(b,'interventions.json'),{schema_version:'1.0',task_id:'P7-TASK',events:opts.events||[]});const bp=write(path.join(b,'benchmark.json'),{schema_version:'1.0',phase:'GLOBAL_EFFICIENCY_P7_BENCHMARK',plan:rel(pl.pp),baseline:{telemetry_summary:rel(bs),global_state:rel(bg)},candidate:{telemetry_summary:rel(cs),global_state:rel(cg)},interventions:rel(iv)});return{b,...pl,bs,cs,bg,cg,iv,bp,receipt:path.join(b,'receipt.json')}}
function assess(f){return run(engine,['benchmark','assess','--root',root,'--profile',f.bp,'--out',f.receipt])}

test('P7 policy makes user goal owner rather than project manager',()=>assert.ok(policy.principles.includes('user_is_goal_owner_not_project_manager')));
test('P7 policy makes minimum necessary intelligence explicit',()=>assert.ok(policy.principles.includes('minimum_necessary_intelligence')));
test('P7 policy protects required evidence from truncation',()=>assert.ok(policy.principles.includes('required_evidence_is_never_truncated')));
test('P7 defines four adaptive profiles',()=>assert.deepEqual(Object.keys(policy.profiles),['MICRO','STANDARD','DEEP','CRITICAL']));
test('P7 forbids operational project-management requests to user',()=>{for(const x of ['CHOOSE_AGENT','CHOOSE_NEXT_STEP','MANUALLY_COORDINATE_WORKERS','MANUALLY_SELECT_SKILLS','MANUALLY_SELECT_TEST_ORDER','REPEAT_KNOWN_CONTEXT'])assert.ok(policy.user_intervention.forbidden_operational_requests.includes(x))});
test('P7 ACTL is explicitly not an evidence truncation mechanism',()=>assert.ok(policy.compact_technical_language.rules.includes('do_not_compress_required_evidence')));
test('small LOW one-file bugfix is MICRO and skips Researcher Architect Auditor',()=>{const b=tmp(),q=createPlan(b).plan;assert.equal(q.profile,'MICRO');for(const a of ['researcher','architect','auditor'])assert.ok(!q.agents.some(x=>x.id===a),a)});
test('MICRO bugfix still retains verifier and three core Judges',()=>{const q=createPlan(tmp()).plan;for(const a of ['verifier','judge-requirements','judge-regression','judge-quality'])assert.ok(q.agents.some(x=>x.id===a),a)});
test('single backend domain routes to editor-backend',()=>assert.ok(createPlan(tmp()).plan.agents.some(x=>x.id==='editor-backend')));
test('cross-domain write routes to Builder instead of pretending one specialist owns all',()=>{const q=createPlan(tmp(),task(),signals(['backend','frontend'],{cross_domain:true})).plan;assert.ok(q.agents.some(x=>x.id==='builder'));assert.ok(!q.agents.some(x=>x.id==='editor-backend'))});
test('normal LOW feature escalates above MICRO when complexity requires it',()=>assert.equal(createPlan(tmp(),task({type:'FEATURE'})).plan.profile,'STANDARD'));
test('MEDIUM risk can never be MICRO',()=>assert.notEqual(createPlan(tmp(),task({risk:'MEDIUM'})).plan.profile,'MICRO'));
test('HIGH risk is at least DEEP',()=>assert.ok(['DEEP','CRITICAL'].includes(createPlan(tmp(),task({risk:'HIGH'})).plan.profile)));
test('security-sensitive work is always CRITICAL',()=>assert.equal(createPlan(tmp(),task(),signals(['backend'],{security_sensitive:true})).plan.profile,'CRITICAL'));
test('migration/destructive work is always CRITICAL',()=>assert.equal(createPlan(tmp(),task(),signals(['database'],{migration_or_destructive:true,database_affecting:true})).plan.profile,'CRITICAL'));
test('CRITICAL write work activates Auditor',()=>assert.ok(createPlan(tmp(),task(),signals(['backend'],{security_sensitive:true})).plan.agents.some(x=>x.id==='auditor')));
test('knowledge stale activates Researcher even for otherwise MICRO task',()=>assert.ok(createPlan(tmp(),task(),signals(['backend'],{knowledge_stale:true})).plan.agents.some(x=>x.id==='researcher')));
test('unknown requirements activate Architect',()=>assert.ok(createPlan(tmp(),task(),signals(['backend'],{unknown_requirements:true})).plan.agents.some(x=>x.id==='architect')));
test('UI work activates Design System Guardian and UXUI Judge',()=>{const q=createPlan(tmp(),task({type:'FEATURE'}),signals(['frontend'],{ui_affecting:true})).plan;for(const a of ['design-system-guardian','judge-uxui'])assert.ok(q.agents.some(x=>x.id===a),a)});
test('visual-required UI work activates all rendered Visual QA specialists',()=>{const q=createPlan(tmp(),task({type:'FEATURE'}),signals(['frontend'],{ui_affecting:true,visual_validation_required:true})).plan;for(const a of policy.agent_activation.visual_specialists)assert.ok(q.agents.some(x=>x.id===a),a)});
test('security signal activates security-check skill',()=>assert.ok(createPlan(tmp(),task(),signals(['backend'],{security_sensitive:true})).plan.skills.includes('security-check')));
test('repair signal activates repair-loop skill',()=>assert.ok(createPlan(tmp(),task(),signals(['backend'],{repair_required:true})).plan.skills.includes('repair-loop')));
test('LOW QUESTION uses Orchestrator only by default',()=>assert.deepEqual(createPlan(tmp(),task({type:'QUESTION',in_scope:[],acceptance_criteria:[]}),signals([])).plan.agents.map(x=>x.id),['orchestrator']));
test('AUDIT has no writer',()=>{const q=createPlan(tmp(),task({type:'AUDIT'}),signals([])).plan;assert.ok(!q.agents.some(x=>['builder','editor-backend','editor-frontend','editor-database','editor-tests','editor-config'].includes(x.id)))});
test('LOW audit uses only Orchestrator plus Researcher by default',()=>{const q=createPlan(tmp(),task({type:'AUDIT',in_scope:['src/a.js'],acceptance_criteria:[{id:'AC1',text:'analysis'}]}),signals([])).plan;assert.deepEqual(q.agents.map(x=>x.id),['orchestrator','researcher'])});
test('HIGH audit escalates to Auditor without adding Verifier by default',()=>{const q=createPlan(tmp(),task({type:'AUDIT',risk:'HIGH'}),signals([])).plan;assert.ok(q.agents.some(x=>x.id==='auditor'));assert.ok(!q.agents.some(x=>x.id==='verifier'))});
test('cross-domain audit escalates to Auditor',()=>{const q=createPlan(tmp(),task({type:'AUDIT'}),signals(['backend','frontend'],{cross_domain:true})).plan;assert.ok(q.agents.some(x=>x.id==='auditor'))});
test('Verifier reasoning is LOW even when task profile is CRITICAL',()=>{const q=createPlan(tmp(),task(),signals(['backend'],{security_sensitive:true})).plan;assert.equal(q.agents.find(x=>x.id==='verifier').reasoning_effort,'LOW')});
test('Architect reasoning remains HIGH',()=>{const q=createPlan(tmp(),task({type:'FEATURE'})).plan;assert.equal(q.agents.find(x=>x.id==='architect').reasoning_effort,'HIGH')});
test('plan integrity verifies',()=>{const f=createPlan(tmp()),r=run(engine,['plan','verify','--root',root,'--plan',f.pp,'--task',f.tp,'--signals',f.sp]);assert.equal(r.status,0);assert.equal(r.q.valid,true)});
test('plan tampering is rejected',()=>{const f=createPlan(tmp()),q=read(f.pp);q.profile='CRITICAL';write(f.pp,q);const r=run(engine,['plan','verify','--root',root,'--plan',f.pp,'--task',f.tp,'--signals',f.sp]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('plan_integrity_mismatch'))});
test('rehashing a semantically manipulated plan still fails recomputation',()=>{const f=createPlan(tmp()),q=read(f.pp);q.profile='CRITICAL';const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.pp,q);const r=run(engine,['plan','verify','--root',root,'--plan',f.pp,'--task',f.tp,'--signals',f.sp]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('plan_semantic_drift:profile'))});
test('task drift invalidates a sealed plan',()=>{const f=createPlan(tmp()),q=read(f.tp);q.objective='changed';write(f.tp,q);const r=run(engine,['plan','verify','--root',root,'--plan',f.pp,'--task',f.tp,'--signals',f.sp]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('plan_semantic_drift:inputs'))});
test('signals drift invalidates a sealed plan',()=>{const f=createPlan(tmp()),q=read(f.sp);q.signals.security_sensitive=true;write(f.sp,q);const r=run(engine,['plan','verify','--root',root,'--plan',f.pp,'--task',f.tp,'--signals',f.sp]);assert.notEqual(r.status,0)});
test('plan output cannot escape project root',()=>{const b=tmp(),tp=write(path.join(b,'t.json'),task()),sp=write(path.join(b,'s.json'),signals()),r=run(engine,['plan','create','--root',root,'--task',tp,'--signals',sp,'--out',path.join(path.dirname(root),'escape.json')]);assert.notEqual(r.status,0);assert.match(r.q.error,/plan_output_external_path/)});
test('closed decision accepts finite valid choice',()=>{const b=tmp(),f=write(path.join(b,'d.json'),{schema_version:'1.0',contract_id:'BOOLEAN_NEED',choice:'NO',reason_codes:['FRESH'],evidence_refs:['ref:1']}),r=run(engine,['decision','validate','--root',root,'--file',f]);assert.equal(r.status,0);assert.equal(r.q.valid,true)});
test('closed decision rejects invalid choice',()=>{const b=tmp(),f=write(path.join(b,'d.json'),{schema_version:'1.0',contract_id:'BOOLEAN_NEED',choice:'MAYBE',reason_codes:[],evidence_refs:[]}),r=run(engine,['decision','validate','--root',root,'--file',f]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('decision_choice_invalid'))});
test('closed decision rejects freeform explanation field',()=>{const b=tmp(),f=write(path.join(b,'d.json'),{schema_version:'1.0',contract_id:'BOOLEAN_NEED',choice:'NO',reason_codes:[],evidence_refs:[],explanation:'long prose'}),r=run(engine,['decision','validate','--root',root,'--file',f]);assert.notEqual(r.status,0);assert.ok(r.q.errors.some(x=>x.includes('decision_freeform_field_forbidden')))});
test('comparable MICRO benchmark with 40 percent input reduction passes',()=>{const f=benchFixture(),r=assess(f);assert.equal(r.status,0,r.stdout);assert.equal(r.q.status,'EFFICIENCY_PASS')});
test('MICRO benchmark below 35 percent target is blocked',()=>{const f=benchFixture({candTelemetry:{input:7000}}),r=assess(f);assert.equal(r.status,4);assert.equal(r.q.status,'EFFICIENCY_BLOCKED');assert.ok(r.q.errors.includes('input_token_reduction_below_profile_target'))});
test('candidate final-state regression is FAIL',()=>{const f=benchFixture({candState:{final:'FAILED'}}),r=assess(f);assert.equal(r.status,7);assert.equal(r.q.status,'EFFICIENCY_FAIL')});
test('judge quality regression beyond tolerance is FAIL',()=>{const f=benchFixture({baseState:{scores:[98,98,98]},candState:{scores:[94,94,94]}}),r=assess(f);assert.equal(r.status,7);assert.ok(r.q.errors.includes('judge_quality_regression'))});
test('repair count increase is FAIL even if token usage drops',()=>{const f=benchFixture({candState:{repair:1},candTelemetry:{repairs:1}}),r=assess(f);assert.equal(r.status,7);assert.ok(r.q.errors.includes('repair_count_increased'))});
test('asking user to choose agent blocks efficiency',()=>{const f=benchFixture({events:[{reason:'CHOOSE_AGENT',required:true,decision_ref:null}]}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.some(x=>x.includes('forbidden_operational_intervention')))});
test('unknown user intervention reason blocks rather than being silently accepted',()=>{const f=benchFixture({events:[{reason:'PLEASE_DEBUG_THIS_FOR_ME',required:true,decision_ref:null}]}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.some(x=>x.includes('intervention_reason_not_allowed')))});
test('legitimate product decision intervention is allowed',()=>{const f=benchFixture({events:[{reason:'AMBIGUOUS_PRODUCT_DECISION',required:true,decision_ref:'DEC-1'}]}),r=assess(f);assert.equal(r.status,0,r.stdout);assert.equal(r.q.project_manager_independence.operational_interventions,0)});
test('benchmark-key mismatch blocks comparison',()=>{const f=benchFixture(),q=read(f.cs);q.benchmark_key='other';const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.cs,q);const r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('benchmark_key_mismatch'))});
test('unmeasured input tokens cannot become an efficiency PASS',()=>{const f=benchFixture(),q=read(f.cs);q.totals.input_tokens=null;const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.cs,q);const r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('input_tokens_unmeasured'))});
test('MICRO context growth is blocked',()=>{const f=benchFixture({candTelemetry:{context:13000}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('context_peak_growth_excessive'))});
test('MICRO tool-call growth is blocked',()=>{const f=benchFixture({candTelemetry:{tools:21}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('tool_call_growth_excessive'))});
test('P7 benchmark requires all global efficiency measurement channels',()=>{for(const x of ['input_tokens','output_tokens','context_peak','tool_calls','files_read','handoff_tokens','model_calls','active_agents'])assert.ok(policy.required_benchmark_measurements.includes(x),x)});
test('unmeasured output tokens cannot become an efficiency PASS',()=>{const f=benchFixture(),q=read(f.cs);q.totals.output_tokens=null;const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.cs,q);const r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('output_tokens_unmeasured'))});
test('total token reduction target is enforced in addition to input reduction',()=>{const f=benchFixture({candTelemetry:{input:6000,output:3500}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('total_token_reduction_below_profile_target'))});
test('output token explosion is blocked even when input tokens improve',()=>{const f=benchFixture({candTelemetry:{output:1400}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('output_token_growth_excessive'))});
test('unnecessary model-call growth is blocked',()=>{const f=benchFixture({candTelemetry:{calls:11}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('model_call_growth_excessive'))});
test('file rereading growth proxy is blocked for MICRO work',()=>{const f=benchFixture({candTelemetry:{files:13}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('file_read_growth_excessive'))});
test('handoff token growth is blocked for MICRO work',()=>{const f=benchFixture({candTelemetry:{handoff:900}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('handoff_growth_excessive'))});
test('waking more agents than baseline is blocked for MICRO work',()=>{const f=benchFixture({candTelemetry:{agentCount:5,calls:7}}),r=assess(f);assert.equal(r.status,4);assert.ok(r.q.errors.includes('active_agent_growth_excessive'))});
test('benchmark receipt verifies against source profile',()=>{const f=benchFixture();assert.equal(assess(f).status,0);const r=run(engine,['benchmark','verify','--root',root,'--receipt',f.receipt,'--profile',f.bp]);assert.equal(r.status,0,r.stdout);assert.equal(r.q.valid,true)});
test('receipt byte tampering is rejected',()=>{const f=benchFixture();assess(f);const q=read(f.receipt);q.profile='CRITICAL';write(f.receipt,q);const r=run(engine,['benchmark','verify','--root',root,'--receipt',f.receipt,'--profile',f.bp]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('receipt_integrity_mismatch'))});
test('rehashing a manipulated receipt cannot defeat semantic recomputation',()=>{const f=benchFixture();assess(f);const q=read(f.receipt);q.metrics.input_tokens.reduction_ratio=.99;const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.receipt,q);const r=run(engine,['benchmark','verify','--root',root,'--receipt',f.receipt,'--profile',f.bp]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('receipt_semantic_drift:metrics'))});
test('drift of an artifact referenced by receipt is rejected',()=>{const f=benchFixture();assess(f);const q=read(f.cs);q.totals.output_tokens=1;write(f.cs,q);const r=run(engine,['benchmark','verify','--root',root,'--receipt',f.receipt]);assert.notEqual(r.status,0);assert.ok(r.q.errors.some(x=>x.includes('receipt_artifact_drift')))});
test('benchmark output cannot escape project root',()=>{const f=benchFixture(),r=run(engine,['benchmark','assess','--root',root,'--profile',f.bp,'--out',path.join(path.dirname(root),'escape-receipt.json')]);assert.notEqual(r.status,0);assert.match(r.q.error,/receipt_output_external_path/)});
test('Master policy contains four P7 efficiency checks',()=>{const q=read(path.join(root,'release/policies/v1-release-policy.json')).master_validation.checks.filter(x=>x.validator==='EFFICIENCY');assert.deepEqual(q.map(x=>x.id),['adaptive_execution_governor_real','context_token_efficiency_real','quality_preservation_real','user_project_manager_independence_real']);assert.ok(q.every(x=>x.validator_phase==='P7'))});
test('P8 fail-closed placeholder prevents premature V1 freeze',()=>{const q=read(path.join(root,'release/policies/v1-release-policy.json')).master_validation.checks.find(x=>x.id==='security_reliability_assurance_real');assert.equal(q.validator,'SECURITY_RELIABILITY');assert.equal(q.validator_phase,'P8')});
test('P7 and successor P8 master validators coexist without changing P7 authority',()=>{assert.ok(fs.existsSync(path.join(root,'release/templates/master-validator-efficiency.mjs')));assert.ok(fs.existsSync(path.join(root,'release/templates/master-validator-security-reliability.mjs')))});
test('installer projects P7 engine policy schemas templates contracts and state',()=>{const s=fs.readFileSync(path.join(root,'scripts/05-install-into-project.ps1'),'utf8');for(const x of ['efficiency-governor.mjs','efficiency-policy.json','state\\efficiency\\plans','state\\efficiency\\decisions','state\\efficiency\\benchmarks'])assert.ok(s.includes(x),x)});
test('OpenCode Orchestrator can invoke only governed P7 runtime command',()=>{const s=fs.readFileSync(path.join(root,'adapters/opencode/.opencode/agents/orchestrator.md'),'utf8');assert.ok(s.includes('node .aledevos/efficiency/runtime/efficiency-governor.mjs *'));assert.ok(s.includes('## Global Efficiency P7'))});
test('Claude Code pretool guard allows governed P7 runtime',()=>assert.ok(fs.readFileSync(path.join(root,'adapters/claude-code/hooks/pretool-guard.mjs'),'utf8').includes('.aledevos/efficiency/runtime/efficiency-governor.mjs')));
test('Antigravity pretool guard allows governed P7 runtime',()=>assert.ok(fs.readFileSync(path.join(root,'adapters/antigravity/hooks/pretool-guard.mjs'),'utf8').includes('efficiency-governor')));
test('all canonical Orchestrators carry user-not-project-manager contract',()=>{for(const f of ['core/agents/orchestrator.md','adapters/opencode/.opencode/agents/orchestrator.md','adapters/codex/.codex/agents/orchestrator.toml','adapters/claude-code/.claude/agents/orchestrator.md','adapters/antigravity/.agents/agents/orchestrator.md']){const s=fs.readFileSync(path.join(root,f),'utf8');assert.ok(s.includes('## Global Efficiency P7'),f);assert.ok(s.includes('Do not ask the user to choose agents'),f)}});
test('P7 target script has inventory plan benchmark and four evidence checks',()=>{const s=fs.readFileSync(path.join(root,'scripts/63-master-validation-p7-target-efficiency.ps1'),'utf8');for(const x of ['InventoryOnly','PlanOnly','benchmark assess','adaptive_execution_governor_real','context_token_efficiency_real','quality_preservation_real','user_project_manager_independence_real'])assert.ok(s.includes(x),x)});
test('P7 inventory never declares Master PASS',()=>{const r=run(engine,['inventory','--root',root]);assert.equal(r.status,0);assert.equal(r.q.status,'EFFICIENCY_P7_INVENTORY_ONLY_NO_MASTER_PASS')});
test('P7 certifier binds P6 certificate and frozen subsystem runtimes',()=>{const s=fs.readFileSync(path.join(root,'release/templates/master-validation-p7-certifier.mjs'),'utf8');for(const x of ['master-validation-p6.json','contextos/engine/contextos.mjs','skillsystem/engine/skillsystem.mjs','model-router.mjs','dispatcher-manager.mjs','core/engine/aledevos.mjs'])assert.ok(s.includes(x),x)});
test('P7 certifier explicitly refuses to claim P8',()=>assert.match(fs.readFileSync(path.join(root,'release/templates/master-validation-p7-certifier.mjs'),'utf8'),/p8_security_reliability_not_claimed:true/));

test('Master adaptive efficiency PASS cannot be sealed without plan/task/signals artifacts',()=>{const b=tmp(),i=write(path.join(b,'master.json'),{schema_version:'1.0',check_id:'adaptive_execution_governor_real',status:'PASS',target:{},artifacts:[],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',path.join(b,'e.json')]);assert.notEqual(r.status,0);assert.match(r.q.status,/MASTER_EVIDENCE_VALIDATION_FAILED/);assert.ok(r.q.errors.some(x=>x.includes('artifact_missing:efficiency_plan')))});
test('Master adaptive efficiency validator accepts a recomputable real P7 plan',()=>{const b=tmp(),f=createPlan(b),i=write(path.join(b,'master.json'),{schema_version:'1.0',check_id:'adaptive_execution_governor_real',status:'PASS',target:{},artifacts:[{role:'task_contract',path:rel(f.tp)},{role:'efficiency_signals',path:rel(f.sp)},{role:'efficiency_plan',path:rel(f.pp)}],claims:{},notes:[]}),o=path.join(b,'e.json'),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',o]);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(read(o).status,'PASS')});
test('Master context-token efficiency validator recomputes a PASS benchmark',()=>{const f=benchFixture();assert.equal(assess(f).status,0);const i=write(path.join(f.b,'master.json'),{schema_version:'1.0',check_id:'context_token_efficiency_real',status:'PASS',target:{},artifacts:[{role:'efficiency_benchmark_profile',path:rel(f.bp)},{role:'efficiency_benchmark_receipt',path:rel(f.receipt)}],claims:{},notes:[]}),o=path.join(f.b,'e.json'),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',o]);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(read(o).validation.ok,true)});
test('Master quality-preservation validator requires the same recomputable PASS receipt',()=>{const f=benchFixture();assess(f);const i=write(path.join(f.b,'master.json'),{schema_version:'1.0',check_id:'quality_preservation_real',status:'PASS',target:{},artifacts:[{role:'efficiency_benchmark_profile',path:rel(f.bp)},{role:'efficiency_benchmark_receipt',path:rel(f.receipt)}],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',path.join(f.b,'e.json')]);assert.equal(r.status,0,r.stdout+r.stderr)});
test('Master project-manager-independence validator rejects operational user coordination',()=>{const f=benchFixture({events:[{reason:'CHOOSE_NEXT_STEP',required:true,decision_ref:null}]});assess(f);const i=write(path.join(f.b,'master.json'),{schema_version:'1.0',check_id:'user_project_manager_independence_real',status:'PASS',target:{},artifacts:[{role:'efficiency_benchmark_profile',path:rel(f.bp)},{role:'efficiency_benchmark_receipt',path:rel(f.receipt)}],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',path.join(f.b,'e.json')]);assert.notEqual(r.status,0);assert.ok(r.q.errors.some(x=>x.includes('efficiency_receipt_not_pass')||x.includes('project_manager_independence')))});
test('Master efficiency validator defeats receipt rehash fraud through profile recomputation',()=>{const f=benchFixture();assess(f);const q=read(f.receipt);q.metrics.input_tokens.reduction_ratio=.99;const x=structuredClone(q);delete x.integrity;q.integrity.payload_sha256=hash(x);write(f.receipt,q);const i=write(path.join(f.b,'master.json'),{schema_version:'1.0',check_id:'context_token_efficiency_real',status:'PASS',target:{},artifacts:[{role:'efficiency_benchmark_profile',path:rel(f.bp)},{role:'efficiency_benchmark_receipt',path:rel(f.receipt)}],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',path.join(f.b,'e.json')]);assert.notEqual(r.status,0);assert.ok(r.q.errors.some(x=>x.includes('receipt_semantic_drift:metrics')))});
test('P8 successor cannot accept PASS without required security evidence',()=>{const b=tmp(),i=write(path.join(b,'master.json'),{schema_version:'1.0',check_id:'security_reliability_assurance_real',status:'PASS',target:{},artifacts:[],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--project-root',root,'--input',i,'--out',path.join(b,'e.json')]);assert.notEqual(r.status,0);assert.equal(r.q.status,'MASTER_EVIDENCE_VALIDATION_FAILED')});
