import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const validator=path.join(root,'release','templates','master-validator-end-to-end.mjs');
const certifier=path.join(root,'release','templates','master-validation-p6-certifier.mjs');
const release=path.join(root,'release','engine','v1-release.mjs');
const policy=path.join(root,'release','policies','v1-release-policy.json');
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
const run=(script,args,cwd=root)=>spawnSync(process.execPath,[script,...args],{cwd,encoding:'utf8',windowsHide:true,shell:false});
const out=r=>{try{return JSON.parse(r.stdout||'{}')}catch{return{}}};
const fsha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const requiredRoles=['user_request','task_contract','context_handoff','orchestration_trace','skill_route','skill_composition','skill_load','skill_execution_handoff','skill_governance','skill_execution_receipt','model_binding','model_route','worktree_receipt','worker_assignment','worker_session','worker_handoff','dispatcher_queue','dispatcher_started_receipt','phase2_receipt','phase4_report','visual_acceptance','primary_judge_evidence','secondary_judge_evidence','judge_comparison','diversity_decision','global_state','telemetry_summary'];
const stages=['ORCHESTRATOR','CONTEXTOS','SKILL_DISCOVERY','RESEARCHER','ARCHITECT','AUDITOR','MODEL_ROUTER','DISPATCHER','BUILDER_OR_EDITOR','VERIFIER','BROWSER','VISUAL_QA','JUDGE_REQUIREMENTS','JUDGE_REGRESSION','JUDGE_QUALITY','FINAL_GATE'];
const modelStages=new Set(['ORCHESTRATOR','RESEARCHER','ARCHITECT','AUDITOR','BUILDER_OR_EDITOR','JUDGE_REQUIREMENTS','JUDGE_REGRESSION','JUDGE_QUALITY']);
function tempInRoot(){const p=path.join(root,'.aledevos','state','release','master','p6-tests',crypto.randomBytes(6).toString('hex'));fs.mkdirSync(p,{recursive:true});return p}
function rel(p){return path.relative(root,p).replaceAll('\\','/')}
function write(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');return p}
function traceDraft(base,{badOrder=false,missingModel=false,badHash=false}={}){const xs=[];for(let i=0;i<stages.length;i++){const ep=write(path.join(base,`stage-${i+1}.txt`),`evidence-${i+1}\n`);xs.push({sequence:i+1,stage:stages[i],agent:stages[i].toLowerCase(),invocation_kind:modelStages.has(stages[i])?'MODEL':'DETERMINISTIC',runtime_invoked:true,runtime:modelStages.has(stages[i])?'fixture-model':'fixture-runtime',provider_id:modelStages.has(stages[i])?'fixture-provider':null,model_id:modelStages.has(stages[i])?'fixture-model-id':null,started_at:new Date(1700000000000+i*2000).toISOString(),finished_at:new Date(1700000001000+i*2000).toISOString(),evidence_path:rel(ep),evidence_sha256:badHash&&i===0?'0'.repeat(64):fsha(ep)})}if(badOrder)[xs[3].stage,xs[4].stage]=[xs[4].stage,xs[3].stage];if(missingModel){xs[0].provider_id=null;xs[0].model_id=null}return{schema_version:'1.0',phase:'MASTER_VALIDATION_P6_ORCHESTRATION_TRACE',task_id:'P6-T',project_path:rel(base),stages:xs,trace_sha256:''}}
function profile(base,artifacts){return{schema_version:'1.0',phase:'MASTER_VALIDATION_P6_TARGET_PROFILE',target_runtime:'fixture',project_path:rel(base),task_id:'P6-T',run_id:'P6-R',adapter:'opencode',artifacts}}

test('P6 end-to-end validator module is packaged',()=>assert.ok(fs.existsSync(validator)));
test('P6 certifier module is packaged',()=>assert.ok(fs.existsSync(certifier)));
test('P6 owns exactly the full_stack_real_project Master check',()=>{const q=json(policy).master_validation.checks.filter(x=>x.validator==='END_TO_END');assert.deepEqual(q.map(x=>x.id),['full_stack_real_project']);assert.equal(q[0].validator_phase,'P6')});
test('P6 target profile schema is strict and phase-pinned',()=>{const q=json(path.join(root,'release/schemas/master-end-to-end-target-profile.schema.json'));assert.equal(q.additionalProperties,false);assert.equal(q.properties.phase.const,'MASTER_VALIDATION_P6_TARGET_PROFILE')});
test('P6 receipt schema pins full-stack phase',()=>assert.equal(json(path.join(root,'release/schemas/master-end-to-end-target-receipt.schema.json')).properties.phase.const,'MASTER_VALIDATION_P6_FULL_STACK_REAL_PROJECT'));
test('P6 orchestration trace schema requires exactly sixteen stages',()=>{const q=json(path.join(root,'release/schemas/master-end-to-end-orchestration-trace.schema.json'));assert.equal(q.properties.stages.minItems,16);assert.equal(q.properties.stages.maxItems,16)});
test('P6 target profile template enumerates every required artifact role',()=>{const a=json(path.join(root,'release/templates/MASTER_END_TO_END_TARGET_PROFILE.example.json')).artifacts;for(const k of requiredRoles)assert.ok(k in a,k)});
test('P6 trace template enumerates the complete pipeline stage order',()=>{const a=json(path.join(root,'release/templates/MASTER_END_TO_END_ORCHESTRATION_TRACE.example.json')).stages;assert.deepEqual(a.map(x=>x.stage),stages)});
test('P6 inventory never declares PASS and sees frozen runtimes',()=>{const r=run(validator,['inventory','--root',root]);assert.equal(r.status,0,r.stdout);const q=out(r);assert.equal(q.status,'INVENTORY_ONLY_NO_MASTER_PASS');for(const k of ['core','context','skills','mm','router','diversity','wt','worker','dispatch','browser','audit','visual'])assert.equal(q.checks[k].present,true,k)});
test('P6 inventory of missing project remains non-authoritative',()=>{const r=run(validator,['inventory','--root',root,'--project','.aledevos/no-such-p6-project']);assert.equal(r.status,0);const q=out(r);assert.equal(q.project.present,false);assert.notEqual(q.status,'PASS')});
test('trace seal rejects missing referenced evidence',()=>{const b=tempInRoot();try{const q=traceDraft(b);q.stages[0].evidence_path=rel(path.join(b,'missing.txt'));const i=write(path.join(b,'draft.json'),q),r=run(validator,['trace-seal','--root',root,'--input',i,'--out',path.join(b,'trace.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/trace_stage_evidence_file_missing/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('trace seal rejects wrong pipeline order',()=>{const b=tempInRoot();try{const i=write(path.join(b,'draft.json'),traceDraft(b,{badOrder:true})),r=run(validator,['trace-seal','--root',root,'--input',i,'--out',path.join(b,'trace.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/trace_stage_order_invalid/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('trace seal rejects model stage without provider and model identity',()=>{const b=tempInRoot();try{const i=write(path.join(b,'draft.json'),traceDraft(b,{missingModel:true})),r=run(validator,['trace-seal','--root',root,'--input',i,'--out',path.join(b,'trace.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/trace_model_identity_missing/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('trace seal rejects referenced evidence hash drift',()=>{const b=tempInRoot();try{const i=write(path.join(b,'draft.json'),traceDraft(b,{badHash:true})),r=run(validator,['trace-seal','--root',root,'--input',i,'--out',path.join(b,'trace.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/trace_stage_evidence_drift/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('trace seal creates integrity-sealed trace for a complete controlled trace',()=>{const b=tempInRoot();try{const i=write(path.join(b,'draft.json'),traceDraft(b)),o=path.join(b,'trace.json'),r=run(validator,['trace-seal','--root',root,'--input',i,'--out',o]);assert.equal(r.status,0,r.stdout);assert.match(json(o).trace_sha256,/^[a-f0-9]{64}$/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('P6 compile rejects project outside package evidence root',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-p6-external-'));try{const arts=Object.fromEntries(requiredRoles.map(x=>[x,null])),p=write(path.join(d,'p.json'),{schema_version:'1.0',phase:'MASTER_VALIDATION_P6_TARGET_PROFILE',target_runtime:'x',project_path:d,task_id:'x',run_id:'x',adapter:'opencode',artifacts:arts}),r=run(validator,['compile','--root',root,'--profile',p,'--out',path.join(d,'o.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/p6_project_missing_or_external/)}finally{fs.rmSync(d,{recursive:true,force:true})}});
test('P6 compile rejects profile missing required artifact keys',()=>{const b=tempInRoot();try{const p=write(path.join(b,'p.json'),profile(b,{})),r=run(validator,['compile','--root',root,'--profile',p,'--out',path.join(b,'o.json')]);assert.notEqual(r.status,0);assert.match(out(r).error,/p6_profile_artifact_set_incomplete/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('P6 compile records incomplete target without manufacturing PASS',()=>{const b=tempInRoot();try{const arts=Object.fromEntries(requiredRoles.map(x=>[x,null])),p=write(path.join(b,'p.json'),profile(b,arts)),o=path.join(b,'o.json'),r=run(validator,['compile','--root',root,'--profile',p,'--out',o]);assert.equal(r.status,0,r.stdout);const q=json(o);assert.equal(q.status,'END_TO_END_TARGET_RECEIPT_COLLECTED');assert.equal(q.artifacts.length,0)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('P6 receipt binds target fingerprint',()=>{const b=tempInRoot();try{const arts=Object.fromEntries(requiredRoles.map(x=>[x,null])),p=write(path.join(b,'p.json'),profile(b,arts)),o=path.join(b,'o.json');run(validator,['compile','--root',root,'--profile',p,'--out',o]);assert.match(json(o).target.target_fingerprint_sha256,/^[a-f0-9]{64}$/)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('P6 explicitly does not claim P7 or P8 completion',()=>{const b=tempInRoot();try{const arts=Object.fromEntries(requiredRoles.map(x=>[x,null])),p=write(path.join(b,'p.json'),profile(b,arts)),o=path.join(b,'o.json');run(validator,['compile','--root',root,'--profile',p,'--out',o]);const q=json(o);assert.equal(q.claims.p7_efficiency_not_claimed,true);assert.equal(q.claims.p8_security_reliability_not_claimed,true)}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('Master matrix now exposes END_TO_END validator as implemented',()=>{const r=run(release,['master','matrix','--project-root',root]),q=out(r),x=q.checks.find(x=>x.id==='full_stack_real_project');assert.equal(r.status,0,r.stdout);assert.equal(x.validator_implemented,true);assert.equal(x.status,'PENDING')});
test('PASS evidence without P6 receipt fails closed',()=>{const b=tempInRoot();try{const i=write(path.join(b,'input.json'),{schema_version:'1.0',check_id:'full_stack_real_project',status:'PASS',target:{},artifacts:[],claims:{},notes:[]}),r=run(release,['master-evidence','seal','--input',i,'--project-root',root]);assert.notEqual(r.status,0);assert.equal(out(r).status,'MASTER_EVIDENCE_VALIDATION_FAILED');assert.ok(out(r).errors.includes('artifact_missing:end_to_end_target_receipt'))}finally{fs.rmSync(b,{recursive:true,force:true})}});
test('P6 PowerShell supports inventory trace sealing and final evidence seal',()=>{const s=read(path.join(root,'scripts/61-master-validation-p6-target-full-stack.ps1'));for(const x of ['InventoryOnly','TraceDraft','trace-seal','full_stack_real_project','all_required_artifacts_present'])assert.ok(s.includes(x),x)});
test('P6 target script cannot attempt PASS until every required role is present',()=>{const s=read(path.join(root,'scripts/61-master-validation-p6-target-full-stack.ps1'));for(const x of requiredRoles)assert.ok(s.includes(x),x);assert.match(s,/if\(\$all\)\{'PASS'\}else\{'BLOCKED'\}/)});
test('P6 validator revalidates ContextOS structured handoff and telemetry',()=>{const s=read(validator);assert.match(s,/\['handoff','validate'/);assert.match(s,/\['telemetry','verify'/)});
test('P6 validator revalidates Skill discovery registry route composition load governance and execution',()=>{const s=read(validator);for(const x of ["['discovery','verify'","['registry','verify'","['route','verify'","['compose','verify'","['load','verify'","['governance','verify'","['execute','verify'"])assert.ok(s.includes(x),x)});
test('P6 validator revalidates model binding routing pair evidence and diversity',()=>{const s=read(validator);for(const x of ["['binding','verify'","['route','verify'","['evidence','verify'","['pair','verify'","judge_diversity_verify"])assert.ok(s.includes(x),x)});
test('P6 validator revalidates worktree worker handoff and dispatcher queue',()=>{const s=read(validator);for(const x of ["['worktree','verify'","['assignment','verify'","['session','verify'","['handoff','verify'","['queue','verify'","dr.event!=='STARTED'","dispatcher_started_receipt_integrity_mismatch"])assert.ok(s.includes(x),x)});
test('P6 validator revalidates browser runtime audit and final Visual QA acceptance',()=>{const s=read(validator);for(const x of ["['run','verify'","['audit','verify'","['acceptance','verify'"])assert.ok(s.includes(x),x)});
test('P6 final state requires all deterministic gates judges and acceptance criteria',()=>{const s=read(validator);for(const x of ["['scope','integrity','canonical']","['requirements','regression','quality']",'acceptance_criteria_not_all_verified','full_stack_final_state_not_pass'])assert.ok(s.includes(x),x)});
test('P6 verifies implementation changed paths remain inside globally approved scope',()=>assert.match(read(validator),/worker_change_outside_global_scope/));
test('P6 certifier binds P5 plus frozen Core ContextOS Skills MultiModel Execution and VisualQA runtimes',()=>{const s=read(certifier);for(const x of ['master-validation-p5.json','core/engine/aledevos.mjs','contextos/engine/contextos.mjs','skillsystem/engine/skillsystem.mjs','multimodel/router/model-router.mjs','worktree-manager.mjs','dispatcher-manager.mjs','browser-runner.mjs','visual-judge.mjs'])assert.ok(s.includes(x),x);assert.match(s,/p7_efficiency_not_claimed:true/);assert.match(s,/p8_security_reliability_not_claimed:true/)});
