import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sec=path.join(root,'security-reliability/engine/security-assurance.mjs');
const reg=path.join(root,'security-reliability/engine/reliability-registry.mjs');
const release=path.join(root,'release/engine/v1-release.mjs');
const validator=path.join(root,'release/templates/master-validator-security-reliability.mjs');
const policy=JSON.parse(fs.readFileSync(path.join(root,'security-reliability/policies/security-reliability-policy.json'),'utf8'));
const run=(bin,a,cwd=root)=>{const r=spawnSync(process.execPath,[bin,...a],{cwd,encoding:'utf8',windowsHide:true,shell:false});let q=null;try{q=JSON.parse((r.stdout||'').trim())}catch{}return{status:r.status,q,stdout:r.stdout||'',stderr:r.stderr||''}};
const write=(p,q)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(q,null,2)+'\n');return p};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const rel=p=>path.relative(root,p).replaceAll('\\','/');
function stable(v,drop=[]){if(Array.isArray(v))return v.map(x=>stable(x,drop));if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())if(!drop.includes(k))o[k]=stable(v[k],drop);return o}return v}
const h=(v,drop=[])=>crypto.createHash('sha256').update(JSON.stringify(stable(v,drop))).digest('hex');
const fh=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function tmp(){const p=path.join(root,'.aledevos','state','p8-tests',`${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`);fs.mkdirSync(p,{recursive:true});return p}
function project(){const p=tmp();fs.mkdirSync(path.join(p,'src'),{recursive:true});fs.mkdirSync(path.join(p,'tests'),{recursive:true});write(path.join(p,'package.json'),{name:'p8-fixture',version:'1.0.0'});write(path.join(p,'package-lock.json'),{name:'p8-fixture',lockfileVersion:3,packages:{}});fs.writeFileSync(path.join(p,'src/app.js'),'export function add(a,b){return a+b}\n');fs.writeFileSync(path.join(p,'tests/app.test.js'),'test("ok",()=>{})\n');return p}
function nativeScan(r=root,outDir=tmp()){const p=path.join(outDir,'native.json'),x=run(sec,['scan','run','--root',r,'--out',p],r);assert.equal(x.status,0,x.stdout+x.stderr);return p}
function submission(dir,over={}){return write(path.join(dir,'submission.json'),{schema_version:'1.0',status:'SECURITY_REVIEW_PASS',agent_id:'security-reviewer',runtime_invoked:true,provider_id:'fixture-provider',model_id:'fixture-model',threat_model:{assets:['code'],trust_boundaries:['input'],entry_points:['api'],threats:[],residual_risk:'LOW'},findings:[],...over})}
function review(scan,dir,over={}){const sub=submission(dir,over),p=path.join(dir,'review.json'),x=run(sec,['review','seal','--root',root,'--scan',scan,'--submission',sub,'--out',p]);return{p,sub,x}}
function external(dir,pass=true){const prof=write(path.join(dir,'external-profile.json'),{schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_EXTERNAL_SCANNERS',scanners:[{id:'dep',kind:'DEPENDENCY',binary:process.execPath,args:[path.join(root,'tests/fixtures',pass?'p8-scanner-pass.mjs':'p8-scanner-fail.mjs')],required:true,acceptable_exit_codes:[0]}]}),receipt=path.join(dir,'external.json'),x=run(sec,['external','run','--root',root,'--profile',prof,'--out',receipt]);return{prof,receipt,x}}
function health(dir,over={}){const input=write(path.join(dir,'health-input.json'),{tests_total:10,tests_passed:10,tests_failed:0,tests_skipped:0,focused_tests:0,flaky_critical:0,...over}),summary=path.join(dir,'health.json'),x=run(sec,['test-health','seal','--root',root,'--input',input,'--out',summary]);return{input,summary,x}}
function regOpen(kind,dir,obj){const input=write(path.join(dir,`${kind}-${Math.random()}.json`),obj),x=run(reg,[kind,'open','--root',root,'--input',input]);assert.equal(x.status,0,x.stdout+x.stderr);return x.q.record}
function update(kind,id,op,dir,obj={}){const input=Object.keys(obj).length?write(path.join(dir,`${op}-${Math.random()}.json`),obj):null,a=[kind,op,'--root',root,'--id',id];if(input)a.push('--input',input);return run(reg,a)}
function fakeProbe(dir){const role=path.join(root,'adapters/opencode/.opencode/agents/security-reviewer.md');const q={schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_REVIEWER_PROBE',status:'SECURITY_REVIEWER_PROBE_PASS',adapter:'opencode',provider_id:'fixture-provider',model_id:'fixture-model',invocation_model_id:'fixture-model',target_fingerprint_sha256:'a'.repeat(64),role_path:rel(role),role_sha256:fh(role),explicit_model_selector:true,marker_observed:true,finding_observed:true,exit_code:0,stdout_sha256:'b'.repeat(64),stderr_sha256:'c'.repeat(64),observed_at:new Date().toISOString(),probe_sha256:''};q.probe_sha256=h(q,['probe_sha256']);return write(path.join(dir,'probe.json'),q)}
function master(id,status,arts,dir){const input=write(path.join(dir,`${id}.input.json`),{schema_version:'1.0',check_id:id,status,target:{phase:'P8_TEST'},artifacts:arts.map(([role,p])=>({role,path:rel(p)})),claims:{},notes:[]}),outp=path.join(dir,`${id}.evidence.json`);return run(release,['master-evidence','seal','--project-root',root,'--input',input,'--out',outp])}

test('P8 policy is defense in depth',()=>assert.ok(policy.principles.includes('defense_in_depth')));
test('P8 makes model opinion subordinate to deterministic scan',()=>assert.ok(policy.principles.includes('deterministic_scan_before_model_opinion')));
test('P8 requires regression evidence for fixed bugs',()=>assert.ok(policy.principles.includes('every_fixed_bug_requires_regression_evidence')));
test('P8 refuses perfect-security claim',()=>assert.ok(policy.non_claims.includes('perfect_security')));
test('dedicated Core Security Reviewer exists',()=>assert.ok(fs.existsSync(path.join(root,'core/agents/security-reviewer.md'))));
test('all four canonical adapters contain security-reviewer',()=>{for(const p of ['adapters/opencode/.opencode/agents/security-reviewer.md','adapters/codex/.codex/agents/security-reviewer.toml','adapters/claude-code/.claude/agents/security-reviewer.md','adapters/antigravity/.agents/agents/security-reviewer.md'])assert.ok(fs.existsSync(path.join(root,p)),p)});
test('OpenCode Security Reviewer is read-only',()=>{const s=fs.readFileSync(path.join(root,'adapters/opencode/.opencode/agents/security-reviewer.md'),'utf8');assert.match(s,/action: edit[\s\S]*?effect: deny/);assert.match(s,/action: shell[\s\S]*?effect: deny/)});
test('Claude Security Reviewer has no edit shell or web tools',()=>{const s=fs.readFileSync(path.join(root,'adapters/claude-code/.claude/agents/security-reviewer.md'),'utf8');assert.match(s,/tools: Read, Grep, Glob, Skill/);assert.match(s,/disallowedTools: WebFetch, WebSearch/)});
test('P7 security-sensitive plan activates Security Reviewer',()=>{const d=tmp(),task=write(path.join(d,'task.json'),{task_id:'SEC',type:'FEATURE',risk:'HIGH',objective:'x',in_scope:['src/a.js'],out_of_scope:[],acceptance_criteria:[{id:'A',text:'x'}]}),sig=write(path.join(d,'sig.json'),{schema_version:'1.0',domains:['backend'],signals:{cross_domain:false,security_sensitive:true,database_affecting:false,external_integration:false,ui_affecting:false,visual_validation_required:false,unknown_requirements:false,migration_or_destructive:false,multi_machine:false,requires_research:false,knowledge_stale:false,repair_required:false}}),outp=path.join(d,'plan.json'),r=run(path.join(root,'efficiency/engine/efficiency-governor.mjs'),['plan','create','--root',root,'--task',task,'--signals',sig,'--out',outp]);assert.equal(r.status,0);assert.ok(read(outp).agents.some(x=>x.id==='security-reviewer'))});

test('native scanner completes on clean project',()=>{const p=project(),o=path.join(p,'scan.json'),r=run(sec,['scan','run','--root',p,'--out',o],p);assert.equal(r.status,0);assert.equal(read(o).status,'SECURITY_NATIVE_SCAN_COMPLETE');assert.equal(read(o).summary.blocking,0)});
test('native scanner detects private key material',()=>{const p=project();fs.writeFileSync(path.join(p,'src/key.js'),'const x=`-----BEGIN ' + 'PRIVATE KEY-----`;\n');const o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);assert.ok(read(o).findings.some(x=>x.id==='private_key'&&x.severity==='CRITICAL'))});
test('native scanner detects eval',()=>{const p=project();fs.writeFileSync(path.join(p,'src/eval.js'),'eval(userInput)\n');const o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);assert.ok(read(o).findings.some(x=>x.id==='eval_call'))});
test('native scanner detects real focused test',()=>{const p=project();fs.writeFileSync(path.join(p,'tests/app.test.js'),'test.only("oops",()=>{})\n');const o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);assert.ok(read(o).findings.some(x=>x.id==='test_only'))});
test('native scanner does not confuse prose mentioning test.only with focused test',()=>{const p=project();fs.writeFileSync(path.join(p,'tests/app.test.js'),'test("detect test.only text",()=>{})\n');const o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);assert.ok(!read(o).findings.some(x=>x.id==='test_only'))});
test('native scan verify recomputes semantics',()=>{const p=project(),o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);assert.equal(run(sec,['scan','verify','--root',p,'--receipt',o],p).status,0)});
test('native scan tamper is rejected',()=>{const p=project(),o=path.join(p,'scan.json');run(sec,['scan','run','--root',p,'--out',o],p);const q=read(o);q.summary.total=99;write(o,q);assert.notEqual(run(sec,['scan','verify','--root',p,'--receipt',o],p).status,0)});

test('security review PASS seals against exact scan and submission',()=>{const d=tmp(),scan=nativeScan(root,d),x=review(scan,d);assert.equal(x.x.status,0);assert.equal(read(x.p).status,'SECURITY_REVIEW_PASS')});
test('security review cannot PASS with HIGH model finding',()=>{const d=tmp(),scan=nativeScan(root,d),x=review(scan,d,{findings:[{id:'X',severity:'HIGH',title:'bad',evidence_refs:['a']} ]});assert.notEqual(x.x.status,0);assert.equal(read(x.p).status,'SECURITY_REVIEW_INVALID')});
test('security review source drift is rejected',()=>{const d=tmp(),scan=nativeScan(root,d),x=review(scan,d);const s=read(x.sub);s.model_id='changed';write(x.sub,s);assert.notEqual(run(sec,['review','verify','--root',root,'--receipt',x.p]).status,0)});

test('external dependency scanner can PASS with real process execution',()=>{const d=tmp(),x=external(d,true);assert.equal(x.x.status,0);assert.equal(read(x.receipt).dependency_scan_satisfied,true)});
test('required external scanner failure blocks',()=>{const d=tmp(),x=external(d,false);assert.notEqual(x.x.status,0);assert.equal(read(x.receipt).status,'EXTERNAL_SECURITY_SCAN_BLOCKED')});
test('external scan verify recomputes command result',()=>{const d=tmp(),x=external(d,true);assert.equal(run(sec,['external','verify','--root',root,'--receipt',x.receipt,'--profile',x.prof]).status,0)});

test('bug opening deduplicates same fingerprint',()=>{const d=tmp(),a=regOpen('bugs',d,{severity:'MEDIUM',component:'router',symptom:'crash X'}),b=regOpen('bugs',d,{severity:'MEDIUM',component:'router',symptom:'crash X'});assert.equal(a.id,b.id);assert.equal(b.occurrences,a.occurrences+1)});
test('bug fix without verified regression is rejected',()=>{const d=tmp(),b=regOpen('bugs',d,{severity:'HIGH',component:'x',symptom:'y'}),r=update('bugs',b.id,'fix',d,{fix_ref:'abc'});assert.notEqual(r.status,0)});
test('bug becomes VERIFIED only after regression evidence',()=>{const d=tmp(),b=regOpen('bugs',d,{severity:'HIGH',component:'x2',symptom:'y2'});assert.equal(update('bugs',b.id,'fix',d,{fix_ref:'abc',regression_test:'tests/regression.test.js',regression_verified:true}).status,0);const v=update('bugs',b.id,'verify',d);assert.equal(v.status,0);assert.equal(v.q.record.status,'VERIFIED')});
test('accepted vulnerability risk requires approval',()=>{const d=tmp(),v=regOpen('vulnerabilities',d,{severity:'HIGH',component:'auth',title:'risk'});assert.notEqual(update('vulnerabilities',v.id,'accept-risk',d,{}).status,0);assert.equal(update('vulnerabilities',v.id,'accept-risk',d,{approval_ref:'ADR-1',rationale:'controlled'}).status,0)});
test('incident can be durably closed',()=>{const d=tmp(),i=regOpen('incidents',d,{severity:'MEDIUM',component:'worker',title:'crash'}),r=update('incidents',i.id,'close',d);assert.equal(r.status,0);assert.equal(r.q.record.status,'CLOSED')});
test('rehashing cannot make bug VERIFIED without regression because verifier checks semantics',()=>{const d=tmp(),b=regOpen('bugs',d,{severity:'MEDIUM',component:'rehash',symptom:'x'}),p=path.join(root,policy.registry.bugs,`${b.id}.json`),q=read(p);q.status='VERIFIED';q.record_sha256=h(q,['record_sha256']);write(p,q);const r=run(reg,['record','verify','--root',root,'--path',p]);assert.notEqual(r.status,0);assert.ok(r.q.errors.includes('bug_verified_without_regression'))});

test('test-health PASS requires no failures skips focused or critical flaky',()=>{const d=tmp(),x=health(d);assert.equal(x.x.status,0);assert.equal(read(x.summary).status,'TEST_HEALTH_PASS')});
test('test-health blocks skipped tests',()=>{const d=tmp(),x=health(d,{tests_total:11,tests_skipped:1});assert.notEqual(x.x.status,0);assert.equal(read(x.summary).status,'TEST_HEALTH_BLOCKED')});
test('test-health blocks focused tests',()=>{const d=tmp(),x=health(d,{focused_tests:1});assert.notEqual(x.x.status,0)});
test('test-health source drift is rejected',()=>{const d=tmp(),x=health(d);const q=read(x.input);q.tests_passed=9;write(x.input,q);assert.notEqual(run(sec,['test-health','verify','--root',root,'--summary',x.summary]).status,0)});

test('Security Reviewer probe receipt is integrity protected by Master validator',()=>{const d=tmp(),scan=nativeScan(root,d),rv=review(scan,d),probe=fakeProbe(d),m=master('security_reviewer_real','PASS',[['security_review_receipt',rv.p],['security_reviewer_probe',probe]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('tampered Security Reviewer probe is rejected',()=>{const d=tmp(),scan=nativeScan(root,d),rv=review(scan,d),probe=fakeProbe(d),q=read(probe);q.marker_observed=false;write(probe,q);const m=master('security_reviewer_real','PASS',[['security_review_receipt',rv.p],['security_reviewer_probe',probe]],d);assert.notEqual(m.status,0)});
test('Master native scan accepts only recomputable COMPLETE receipt',()=>{const d=tmp(),scan=nativeScan(root,d),m=master('security_native_scan_real','PASS',[['security_native_scan',scan]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('Master dependency scan requires dependency scan satisfied',()=>{const d=tmp(),x=external(d,true),m=master('dependency_security_scan_real','PASS',[['external_security_scan',x.receipt],['external_security_profile',x.prof]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('Master bug registry requires VERIFIED regression-linked bug',()=>{const d=tmp(),b=regOpen('bugs',d,{severity:'MEDIUM',component:'masterbug',symptom:'bug'});update('bugs',b.id,'fix',d,{fix_ref:'x',regression_test:'tests/r.js',regression_verified:true});const v=update('bugs',b.id,'verify',d),p=v.q.path||path.join(root,policy.registry.bugs,`${b.id}.json`),m=master('bug_regression_registry_real','PASS',[['bug_record',p]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('Master incident/vulnerability registry requires both record types',()=>{const d=tmp(),v=regOpen('vulnerabilities',d,{severity:'LOW',component:'v',title:'v'}),vr=update('vulnerabilities',v.id,'mitigate',d,{mitigation:'fixed'}),i=regOpen('incidents',d,{severity:'LOW',component:'i',title:'i'}),ir=update('incidents',i.id,'close',d),m=master('incident_vulnerability_registry_real','PASS',[['vulnerability_record',vr.q.path],['incident_record',ir.q.path]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('Master test health requires TEST_HEALTH_PASS',()=>{const d=tmp(),x=health(d),m=master('test_health_real','PASS',[['test_health_summary',x.summary]],d);assert.equal(m.status,0,m.stdout+m.stderr)});

test('assurance gate blocks unresolved HIGH native finding',()=>{const d=tmp(),scan=nativeScan(root,d),rv=review(scan,d),ex=external(d,true),th=health(d),prof=write(path.join(d,'gate-profile.json'),{schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_ASSURANCE_PROFILE',native_scan:rel(scan),security_review:rel(rv.p),external_scan:rel(ex.receipt),external_profile:rel(ex.prof),test_health:rel(th.summary),registry_records:[]}),outp=path.join(d,'gate.json'),r=run(sec,['gate','assess','--root',root,'--profile',prof,'--out',outp]);assert.notEqual(r.status,0);assert.ok(read(outp).errors.some(x=>x.startsWith('unresolved_native_finding:'))) });
test('assurance gate passes when severe native finding has approved mitigation record',()=>{const d=tmp(),scan=nativeScan(root,d),sq=read(scan),f=sq.findings.find(x=>['HIGH','CRITICAL'].includes(x.severity));assert.ok(f);const v=regOpen('vulnerabilities',d,{severity:f.severity,component:'aledevos-core',title:f.id,source_finding_id:`${f.id}:${f.path}:${f.line}`}),vr=update('vulnerabilities',v.id,'accept-risk',d,{approval_ref:'P8-CONTROLLED-REVIEW',rationale:'controlled canonical command boundary'});const b=regOpen('bugs',d,{severity:'LOW',component:'fixture',symptom:'fixture bug'});update('bugs',b.id,'fix',d,{fix_ref:'x',regression_test:'tests/r.js',regression_verified:true});const br=update('bugs',b.id,'verify',d);const i=regOpen('incidents',d,{severity:'LOW',component:'fixture',title:'fixture incident'}),ir=update('incidents',i.id,'close',d),rv=review(scan,d),ex=external(d,true),th=health(d),prof=write(path.join(d,'gate-profile.json'),{schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_ASSURANCE_PROFILE',native_scan:rel(scan),security_review:rel(rv.p),external_scan:rel(ex.receipt),external_profile:rel(ex.prof),test_health:rel(th.summary),registry_records:[rel(vr.q.path),rel(br.q.path),rel(ir.q.path)]}),outp=path.join(d,'gate.json'),r=run(sec,['gate','assess','--root',root,'--profile',prof,'--out',outp]);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(read(outp).status,'SECURITY_RELIABILITY_PASS')});
test('Master final P8 assurance recomputes gate receipt',()=>{const d=tmp(),scan=nativeScan(root,d),sq=read(scan),f=sq.findings.find(x=>['HIGH','CRITICAL'].includes(x.severity)),v=regOpen('vulnerabilities',d,{severity:f.severity,component:'final',title:f.id,source_finding_id:`${f.id}:${f.path}:${f.line}`}),vr=update('vulnerabilities',v.id,'accept-risk',d,{approval_ref:'P8-TEST'}),rv=review(scan,d),ex=external(d,true),th=health(d),prof=write(path.join(d,'gate-profile.json'),{schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_ASSURANCE_PROFILE',native_scan:rel(scan),security_review:rel(rv.p),external_scan:rel(ex.receipt),external_profile:rel(ex.prof),test_health:rel(th.summary),registry_records:[rel(vr.q.path)]}),receipt=path.join(d,'gate.json');assert.equal(run(sec,['gate','assess','--root',root,'--profile',prof,'--out',receipt]).status,0);const m=master('security_reliability_assurance_real','PASS',[['security_assurance_profile',prof],['security_assurance_receipt',receipt]],d);assert.equal(m.status,0,m.stdout+m.stderr)});
test('Master final P8 assurance defeats rehashed semantic drift',()=>{const d=tmp(),scan=nativeScan(root,d),sq=read(scan),f=sq.findings.find(x=>['HIGH','CRITICAL'].includes(x.severity)),v=regOpen('vulnerabilities',d,{severity:f.severity,component:'drift',title:f.id,source_finding_id:`${f.id}:${f.path}:${f.line}`}),vr=update('vulnerabilities',v.id,'accept-risk',d,{approval_ref:'P8-TEST'}),rv=review(scan,d),ex=external(d,true),th=health(d),prof=write(path.join(d,'gate-profile.json'),{schema_version:'1.0',phase:'SECURITY_RELIABILITY_P8_ASSURANCE_PROFILE',native_scan:rel(scan),security_review:rel(rv.p),external_scan:rel(ex.receipt),external_profile:rel(ex.prof),test_health:rel(th.summary),registry_records:[rel(vr.q.path)]}),receipt=path.join(d,'gate.json');run(sec,['gate','assess','--root',root,'--profile',prof,'--out',receipt]);const q=read(receipt);q.registry_summary.records=999;q.gate_sha256=h(q,['gate_sha256']);write(receipt,q);const m=master('security_reliability_assurance_real','PASS',[['security_assurance_profile',prof],['security_assurance_receipt',receipt]],d);assert.notEqual(m.status,0)});
test('P8 validator is now implemented in Master Matrix',()=>{const r=run(release,['master','matrix','--project-root',root]);const ids=new Map(r.q.checks.map(x=>[x.id,x]));for(const id of ['security_native_scan_real','security_reviewer_real','dependency_security_scan_real','bug_regression_registry_real','incident_vulnerability_registry_real','test_health_real','security_reliability_assurance_real'])assert.equal(ids.get(id)?.validator_implemented,true,id)});
test('P8 keeps perfect security as explicit non-claim',()=>{const q=JSON.parse(fs.readFileSync(path.join(root,'release/policies/v1-release-policy.json'),'utf8'));assert.equal(q.master_validation.non_claims.perfect_security_guarantee,true)});
