import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const skillRuntime=path.resolve('skillsystem/engine/skillsystem.mjs');
const acqRuntime=path.resolve('skillsystem/engine/acquisition.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-skills-p5-'));
function cp(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});}
function project(){const p=tmp();cp('skillsystem/catalogs',path.join(p,'.aledevos/skillsystem/catalogs'));cp('skillsystem/policies',path.join(p,'.aledevos/skillsystem/policies'));cp('skillsystem/bindings',path.join(p,'.aledevos/skillsystem/bindings'));cp('skillsystem/discovery',path.join(p,'.aledevos/skillsystem/discovery'));cp('skillsystem/acquisition',path.join(p,'.aledevos/skillsystem/acquisition'));cp('adapters/opencode/.opencode/skills',path.join(p,'.opencode/skills'));return p;}
function scanBuild(p){let r=run(skillRuntime,p,'discovery','scan','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);r=run(skillRuntime,p,'registry','build','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);}
function plan(p,id){return run(acqRuntime,p,'acquire','plan','--project-root',p,'--adapter','opencode','--skill-id',id)}

test('Phase 5 enables acquisition with project scope and fail-closed staging',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json','utf8'));assert.equal(p.phase_boundary.acquisition_enabled,true);assert.equal(p.acquisition.install_scope,'project');assert.equal(p.acquisition.global_install,false);assert.equal(p.acquisition.staging_required,true);assert.equal(p.acquisition.execute_before_verification,false)});
test('already usable bundled skill does not download again',()=>{const p=project();scanBuild(p);const r=plan(p,'task-contract');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).status,'ALREADY_AVAILABLE')});
test('trusted catalog source is auto-approved for acquisition',()=>{const p=project();scanBuild(p);const r=plan(p,'frontend-design');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.status,'ACQUISITION_AUTO_APPROVED');assert.equal(o.approval_required,false);assert.equal(o.source.source_class,'official')});
test('missing source mapping requires resolution instead of guessing',()=>{const p=project();scanBuild(p);const r=plan(p,'design');assert.equal(r.status,41);assert.equal(jout(r).status,'ACQUISITION_SOURCE_RESOLUTION_REQUIRED')});
test('acquisition plan tampering is detected',()=>{const p=project();scanBuild(p);plan(p,'frontend-design');const f=path.join(p,'.aledevos/state/skills/acquisition/frontend-design.plan.json');const o=JSON.parse(fs.readFileSync(f,'utf8'));o.approval_required=true;fs.writeFileSync(f,JSON.stringify(o));const r=run(acqRuntime,p,'acquire','verify-plan','--project-root',p,'--adapter','opencode','--skill-id','frontend-design');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('plan_integrity_mismatch'))});
test('recording acquisition requires post-install registry usability',()=>{const p=project();scanBuild(p);plan(p,'frontend-design');const req=path.join(p,'receipt.json');fs.writeFileSync(req,JSON.stringify({skill_id:'frontend-design',adapter:'opencode',status:'INSTALLED',approved:true,instruction_path:'.opencode/skills/frontend-design/SKILL.md'}));const r=run(acqRuntime,p,'acquire','record','--project-root',p,'--adapter','opencode','--request',req);assert.notEqual(r.status,0);assert.match(r.stderr,/INSTALLED_SKILL_SOURCE_MISSING|REGISTRY_NOT_USABLE/)});
test('local simulated install can be sealed only after rediscovery and registry rebuild',()=>{const p=project();scanBuild(p);plan(p,'frontend-design');const d=path.join(p,'.opencode/skills/frontend-design');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),'---\nname: frontend-design\ndescription: fixture\n---\n# frontend\n');let r=run(skillRuntime,p,'discovery','scan','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);r=run(skillRuntime,p,'registry','build','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);const req=path.join(p,'receipt.json');fs.writeFileSync(req,JSON.stringify({skill_id:'frontend-design',adapter:'opencode',status:'INSTALLED',approved:true,source:{source:'fixture',source_class:'official'},instruction_path:'.opencode/skills/frontend-design/SKILL.md'}));r=run(acqRuntime,p,'acquire','record','--project-root',p,'--adapter','opencode','--request',req);assert.equal(r.status,0,r.stderr);assert.equal(jout(r).status,'ACQUISITION_VERIFIED');r=run(acqRuntime,p,'acquire','verify','--project-root',p,'--adapter','opencode','--skill-id','frontend-design');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).valid,true)});
test('acquisition receipt detects installed skill drift',()=>{const p=project();scanBuild(p);plan(p,'frontend-design');const d=path.join(p,'.opencode/skills/frontend-design');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),'# one\n');let r=run(skillRuntime,p,'discovery','scan','--project-root',p,'--adapter','opencode');assert.equal(r.status,0);r=run(skillRuntime,p,'registry','build','--project-root',p,'--adapter','opencode');assert.equal(r.status,0);const req=path.join(p,'receipt.json');fs.writeFileSync(req,JSON.stringify({skill_id:'frontend-design',adapter:'opencode',status:'INSTALLED',approved:true,instruction_path:'.opencode/skills/frontend-design/SKILL.md'}));r=run(acqRuntime,p,'acquire','record','--project-root',p,'--adapter','opencode','--request',req);assert.equal(r.status,0,r.stderr);fs.appendFileSync(path.join(d,'SKILL.md'),'tamper\n');r=run(acqRuntime,p,'acquire','verify','--project-root',p,'--adapter','opencode','--skill-id','frontend-design');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('installed_source_drift'))});
test('OpenCode adapter installer stages third-party install and disables skills CLI telemetry',()=>{const s=fs.readFileSync('adapters/opencode/scripts/acquire-skill.ps1','utf8');assert.match(s,/DISABLE_TELEMETRY/);assert.match(s,/GetTempPath/);assert.match(s,/--copy/);assert.match(s,/-a opencode/);assert.doesNotMatch(s,/\s-g\s/);assert.match(s,/discovery scan/);assert.match(s,/registry build/);assert.match(s,/registry verify/)});
test('OpenCode acquisition script never installs third-party CLI output directly into project',()=>{const s=fs.readFileSync('adapters/opencode/scripts/acquire-skill.ps1','utf8');assert.match(s,/Push-Location \$temp/);assert.match(s,/Copy-Item \$staged \$pending/);assert.match(s,/Move-Item \$pending \$target/)});
test('installer deploys acquisition runtime, source catalog, adapter policy and adapter installer',()=>{const s=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(s,/acquisition\.mjs/);assert.match(s,/source-catalog\.json/);assert.match(s,/acquire-skill\.ps1/);assert.match(s,/state\\skills\\acquisition/);assert.match(s,/skills\\acquisitions/);assert.match(s,/Skill System Phase 5/)});
test('unknown/untrusted sources are approval-gated by adapter',()=>{const s=fs.readFileSync('adapters/opencode/scripts/acquire-skill.ps1','utf8');assert.match(s,/ApproveUntrustedSource/);assert.match(s,/requires approval before download/)});
test('acquisition schemas, configs and policy parse cleanly',()=>{for(const d of ['skillsystem/schemas','skillsystem/acquisition','skillsystem/policies'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join(d,f),'utf8')),`${d}/${f}`)});
test('all Core and OpenCode agents know missing skills must be acquired and reverified before use',()=>{for(const d of ['core/agents','adapters/opencode/.opencode/agents'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.md'))){const t=fs.readFileSync(path.join(d,f),'utf8');assert.match(t,/## Skill Acquisition/,`${d}/${f}`);assert.match(t,/re-discover/i,`${d}/${f}`);assert.match(t,/untrusted/i,`${d}/${f}`)}});
