import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const runtime=path.resolve('skillsystem/engine/skillsystem.mjs');
const run=(cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-skills-p3-'));
function cp(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});}
function project(){const p=tmp();cp('skillsystem/catalogs',path.join(p,'.aledevos/skillsystem/catalogs'));cp('skillsystem/policies',path.join(p,'.aledevos/skillsystem/policies'));cp('skillsystem/bindings',path.join(p,'.aledevos/skillsystem/bindings'));cp('skillsystem/discovery',path.join(p,'.aledevos/skillsystem/discovery'));cp('adapters/opencode/.opencode/skills',path.join(p,'.opencode/skills'));cp('contextos/policies',path.join(p,'.aledevos/contextos/policies'));fs.writeFileSync(path.join(p,'.aledevos/project.json'),JSON.stringify({adapter:'opencode'}));return p;}
function addSkill(p,id,{body='# skill\n',capabilities=[],dependencies=[],conflicts=[],intents=[]}={}){const d=path.join(p,'.opencode/skills',id);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),body);fs.writeFileSync(path.join(d,'aledevos-skill.json'),JSON.stringify({schema_version:'1.0',id,domain:'fixture',role:'specialist',description:'fixture',capabilities,intents,dependencies,conflicts}));}
function scanBuild(p){let r=run(p,'discovery','scan','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);r=run(p,'registry','build','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);}
function route(p,task='t1',caps=['task.contract']){const f=path.join(p,'route.json');fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,required_capabilities:caps,preferred_capabilities:[],intents:[],domains:[]}));return run(p,'route','plan','--project-root',p,'--request',f);}
function compose(p,task='t1'){return run(p,'compose','plan','--project-root',p,'--task-id',task);}
function load(p,task='t1',over={}){const f=path.join(p,'load.json');fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,target_agent:'builder',runtime_profile:'opencode-qwen64k',base_context_tokens:0,...over}));return run(p,'load','plan','--project-root',p,'--request',f);}
function handoff(p,task='t1',over={}){const f=path.join(p,'handoff.json');fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,target_agent:'builder',input_refs:[{kind:'task_contract',ref:'.aledevos/task.json'}],required_outputs:['summary','evidence'],...over}));return run(p,'handoff','create','--project-root',p,'--request',f);}
function prep(p,task='t1',caps=['task.contract']){scanBuild(p);const rr=route(p,task,caps);assert.equal(rr.status,0,rr.stderr);const cr=compose(p,task);assert.equal(cr.status,0,cr.stderr);return {rr,cr};}

test('phase 3 guarantees remain enabled under later governance phases',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json'));assert.equal(p.phase_boundary.composition_enabled,true);assert.equal(p.phase_boundary.instruction_loading_enabled,true);assert.equal(p.phase_boundary.execution_handoff_enabled,true)});
test('composition expands dependencies and orders dependency before routed skill',()=>{const p=project();addSkill(p,'dep',{capabilities:['fixture.dep']});addSkill(p,'root',{capabilities:['fixture.root'],dependencies:['dep']});scanBuild(p);assert.equal(route(p,'dep-order',['fixture.root']).status,0);const r=compose(p,'dep-order');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.deepEqual(o.skills.map(x=>x.id),['dep','root']);assert.equal(o.skills[0].role,'DEPENDENCY');assert.equal(o.skills[1].role,'ROUTED')});
test('missing dependency blocks composition',()=>{const p=project();addSkill(p,'root',{capabilities:['fixture.root'],dependencies:['does-not-exist']});scanBuild(p);route(p,'missing',['fixture.root']);const r=compose(p,'missing');assert.notEqual(r.status,0);const o=jout(r);assert.equal(o.status,'COMPOSITION_BLOCKED');assert.ok(o.errors.includes('MISSING_DEPENDENCY'))});
test('declared conflicts block composition',()=>{const p=project();addSkill(p,'a',{capabilities:['fixture.a'],conflicts:['b']});addSkill(p,'b',{capabilities:['fixture.b']});scanBuild(p);route(p,'conflict',['fixture.a','fixture.b']);const r=compose(p,'conflict');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('SKILL_CONFLICT'))});
test('dependency cycles block composition',()=>{const p=project();addSkill(p,'a',{capabilities:['fixture.a'],dependencies:['b']});addSkill(p,'b',{capabilities:['fixture.b'],dependencies:['a']});scanBuild(p);route(p,'cycle',['fixture.a']);const r=compose(p,'cycle');assert.notEqual(r.status,0);const o=jout(r);assert.ok(o.errors.includes('DEPENDENCY_CYCLE'));assert.match(o.cycle,/DEPENDENCY_CYCLE/)});
test('composition artifact remains metadata-only and sealed',()=>{const p=project();addSkill(p,'secret',{body:'SECRET_SKILL_BODY',capabilities:['fixture.secret']});scanBuild(p);route(p,'meta',['fixture.secret']);const r=compose(p,'meta');assert.equal(r.status,0);assert.doesNotMatch(r.stdout,/SECRET_SKILL_BODY/);assert.match(jout(r).integrity.payload_sha256,/^[a-f0-9]{64}$/)});
test('composition tampering is detected',()=>{const p=project();prep(p,'tamper');const f=path.join(p,'.aledevos/state/skills/compositions/tamper.json'),o=JSON.parse(fs.readFileSync(f));o.status='COMPOSITION_BLOCKED';fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'compose','verify','--project-root',p,'--task-id','tamper');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('composition_integrity_mismatch'))});
test('on-demand load stores body only in sealed load packet, not CLI output',()=>{const p=project();prep(p,'load-ok');const r=load(p,'load-ok');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).status,'LOAD_READY');assert.doesNotMatch(r.stdout,/# Task Contract/);const f=path.join(p,'.aledevos/state/skills/loads/load-ok.json'),o=JSON.parse(fs.readFileSync(f));assert.equal(o.instruction_bodies_loaded,true);assert.equal(typeof o.skills[0].body,'string');assert.ok(o.skills[0].body.length>0)});
test('loader reads only composed skills',()=>{const p=project();prep(p,'only-one');const r=load(p,'only-one');assert.equal(r.status,0);const f=path.join(p,'.aledevos/state/skills/loads/only-one.json'),o=JSON.parse(fs.readFileSync(f));assert.deepEqual(o.skills.map(x=>x.id),['task-contract'])});
test('load packet exposes deterministic ContextOS budget math',()=>{const p=project();prep(p,'budget-math');const r=load(p,'budget-math',{target_agent:'verifier'});assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.budget.context_window,65536);assert.equal(o.budget.reserve_tokens,20000);assert.equal(o.budget.agent_target_tokens,8000);assert.equal(o.budget.max_instruction_tokens,2800)});
test('base context can make required instruction set fail closed instead of truncating',()=>{const p=project();prep(p,'budget-block');const r=load(p,'budget-block',{target_agent:'verifier',base_context_tokens:8000});assert.notEqual(r.status,0);const o=jout(r);assert.equal(o.status,'LOAD_BLOCKED');assert.ok(o.errors.includes('INSTRUCTION_BUDGET_EXCEEDED'));const f=path.join(p,'.aledevos/state/skills/loads/budget-block.json'),saved=JSON.parse(fs.readFileSync(f));assert.equal(saved.skills.some(x=>Object.hasOwn(x,'body')),false)});
test('oversized single skill fails closed',()=>{const p=project();addSkill(p,'huge',{body:'x'.repeat(25000),capabilities:['fixture.huge']});scanBuild(p);route(p,'huge',['fixture.huge']);compose(p,'huge');const r=load(p,'huge');assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.startsWith('SINGLE_SKILL_BUDGET:huge')))});
test('source drift after composition blocks loading',()=>{const p=project();prep(p,'drift');fs.appendFileSync(path.join(p,'.opencode/skills/task-contract/SKILL.md'),'\ndrift');const r=load(p,'drift');assert.notEqual(r.status,0);assert.match(r.stderr,/LOAD_COMPOSITION_INVALID|registry_invalid|usable_drift/)});
test('load packet tampering is detected',()=>{const p=project();prep(p,'load-tamper');load(p,'load-tamper');const f=path.join(p,'.aledevos/state/skills/loads/load-tamper.json'),o=JSON.parse(fs.readFileSync(f));o.budget.planned_instruction_tokens=999999;fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'load','verify','--project-root',p,'--task-id','load-tamper');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('load_integrity_mismatch'))});
test('source drift after loading is detected at load verification',()=>{const p=project();prep(p,'post-load-drift');load(p,'post-load-drift');fs.appendFileSync(path.join(p,'.opencode/skills/task-contract/SKILL.md'),'\ndrift');const r=run(p,'load','verify','--project-root',p,'--task-id','post-load-drift');assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.includes('loaded_skill_drift')||x==='composition_invalid'))});
test('execution handoff is reference-only and points to sealed load packet',()=>{const p=project();prep(p,'handoff-ok');load(p,'handoff-ok');const r=handoff(p,'handoff-ok');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.status,'EXECUTION_HANDOFF_READY');assert.equal(o.input_contract.reference_only,true);assert.equal(o.input_contract.transcript_allowed,false);assert.equal(o.execution_performed,false);assert.deepEqual(o.skill_ids,['task-contract'])});
test('execution handoff rejects inline content and transcript-shaped input',()=>{const p=project();prep(p,'inline');load(p,'inline');const r=handoff(p,'inline',{input_refs:[{kind:'task_contract',ref:'x',content:'raw prompt'}]});assert.notEqual(r.status,0);assert.match(r.stderr,/inline_input_forbidden/)});
test('execution handoff rejects target-agent mismatch',()=>{const p=project();prep(p,'agent-mismatch');load(p,'agent-mismatch',{target_agent:'builder'});const r=handoff(p,'agent-mismatch',{target_agent:'verifier'});assert.notEqual(r.status,0);assert.match(r.stderr,/HANDOFF_AGENT_MISMATCH/)});
test('execution handoff tampering is detected',()=>{const p=project();prep(p,'handoff-tamper');load(p,'handoff-tamper');handoff(p,'handoff-tamper');const f=path.join(p,'.aledevos/state/skills/execution-handoffs/handoff-tamper.json'),o=JSON.parse(fs.readFileSync(f));o.output_contract.required_outputs=[];fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'handoff','verify','--project-root',p,'--task-id','handoff-tamper');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('execution_handoff_integrity_mismatch'))});
test('direct runtime-specific execution is still not performed by the core engine',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json'));assert.equal(p.execution_lifecycle.engine_direct_execution,false);assert.equal(p.execution_lifecycle.adapter_executes,true)});
test('installer preserves Phase 3 runtime-state directories and still installs ContextOS policy',()=>{const s=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(s,/state\\skills\\compositions/);assert.match(s,/state\\skills\\loads/);assert.match(s,/state\\skills\\execution-handoffs/);assert.match(s,/contextos\\policies\\context-policy\.json/)});
test('phase 3 schemas and policy parse cleanly',()=>{for(const d of ['skillsystem/schemas','skillsystem/catalogs','skillsystem/policies','skillsystem/bindings','skillsystem/discovery'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join(d,f),'utf8')),`${d}/${f}`)});
