import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const runtime=path.resolve('skillsystem/engine/skillsystem.mjs');
const run=(cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-skills-p2-'));
function cp(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});}
function project(){const p=tmp();cp('skillsystem/catalogs',path.join(p,'.aledevos/skillsystem/catalogs'));cp('skillsystem/policies',path.join(p,'.aledevos/skillsystem/policies'));cp('skillsystem/bindings',path.join(p,'.aledevos/skillsystem/bindings'));cp('skillsystem/discovery',path.join(p,'.aledevos/skillsystem/discovery'));cp('adapters/opencode/.opencode/skills',path.join(p,'.opencode/skills'));fs.writeFileSync(path.join(p,'.aledevos/project.json'),JSON.stringify({adapter:'opencode'}));return p;}
function scan(p){return run(p,'discovery','scan','--project-root',p,'--adapter','opencode')}
function build(p){return run(p,'registry','build','--project-root',p,'--adapter','opencode')}
function route(p,q){const f=path.join(p,'route.json');fs.writeFileSync(f,JSON.stringify(q));return run(p,'route','plan','--project-root',p,'--request',f)}
const rq=(over={})=>({schema_version:'1.0',task_id:'t1',required_capabilities:[],preferred_capabilities:[],intents:[],domains:[],...over});
function addSkill(p,id,body='# real skill\n',sidecar=null){const d=path.join(p,'.opencode/skills',id);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),body);if(sidecar)fs.writeFileSync(path.join(d,'aledevos-skill.json'),JSON.stringify(sidecar));}

test('phase 2 discovery/routing guarantees remain enabled under later governance phases',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json'));assert.equal(p.phase_boundary.discovery_enabled,true);assert.equal(p.phase_boundary.routing_enabled,true);assert.equal(p.execution_lifecycle.engine_direct_execution,false)});
test('default OpenCode discovery config is project-local and fail-closed for external roots',()=>{const d=JSON.parse(fs.readFileSync('skillsystem/discovery/opencode.json'));assert.equal(d.allow_external_roots,false);assert.equal(d.roots[0].path,'.opencode/skills')});
test('discovery scan finds real core skill instruction files without embedding bodies',()=>{const p=project(),r=scan(p);assert.equal(r.status,0,r.stderr);const d=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/discoveries/opencode.json')));assert.ok(d.summary.discovered>=13);assert.ok(d.skills.some(x=>x.id==='task-contract'));assert.doesNotMatch(JSON.stringify(d),/# Task Contract/)});
test('discovery snapshot verifies intact',()=>{const p=project();assert.equal(scan(p).status,0);const r=run(p,'discovery','verify','--project-root',p);assert.equal(r.status,0);assert.equal(jout(r).valid,true)});
test('discovery integrity tampering is detected',()=>{const p=project();scan(p);const f=path.join(p,'.aledevos/skills/discoveries/opencode.json'),d=JSON.parse(fs.readFileSync(f));d.summary.discovered=999;fs.writeFileSync(f,JSON.stringify(d));const r=run(p,'discovery','verify','--project-root',p);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('discovery_integrity_mismatch'))});
test('instruction drift after discovery is detected',()=>{const p=project();scan(p);fs.appendFileSync(path.join(p,'.opencode/skills/task-contract/SKILL.md'),'\ndrift');const r=run(p,'discovery','verify','--project-root',p);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('drift:task-contract'))});
test('declared external skill becomes usable only after real source discovery',()=>{const p=project();addSkill(p,'design-system','# actual design system skill');assert.equal(scan(p).status,0);assert.equal(build(p).status,0);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/registries/opencode.json')));const s=reg.skills.find(x=>x.id==='design-system');assert.equal(s.runtime.status,'AVAILABLE');assert.equal(s.runtime.usable,true);assert.equal(s.runtime.metadata_trust,'declared')});
test('unresolved external skill remains unusable when source is absent',()=>{const p=project();scan(p);build(p);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/registries/opencode.json')));const s=reg.skills.find(x=>x.id==='animate');assert.equal(s.runtime.status,'DECLARED_UNRESOLVED');assert.equal(s.runtime.usable,false)});
test('unknown discovered skill without sidecar is inventory-only and not registered',()=>{const p=project();addSkill(p,'mystery-skill');scan(p);build(p);const d=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/discoveries/opencode.json')));assert.ok(d.skills.find(x=>x.id==='mystery-skill'&&!x.can_register));const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/registries/opencode.json')));assert.equal(reg.skills.some(x=>x.id==='mystery-skill'),false)});
test('unknown discovered skill with valid sidecar enters registry as runtime-discovered',()=>{const p=project();addSkill(p,'special-ux','# real',{schema_version:'1.0',id:'special-ux',domain:'ux',role:'specialist',description:'fixture',capabilities:['ux.special'],intents:['specialist-task'],dependencies:[],conflicts:[]});scan(p);build(p);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/skills/registries/opencode.json')));const s=reg.skills.find(x=>x.id==='special-ux');assert.equal(s.source_kind,'runtime-discovered');assert.equal(s.runtime.usable,true);assert.equal(s.runtime.metadata_trust,'runtime-verified')});
test('invalid sidecar ID mismatch fails closed',()=>{const p=project();addSkill(p,'special-ux','# real',{schema_version:'1.0',id:'wrong',domain:'ux',capabilities:[],intents:[],dependencies:[],conflicts:[]});const r=scan(p);assert.notEqual(r.status,0);assert.match(r.stderr,/INVALID_SKILL_SIDECAR/)});
test('router selects discovered design-system for required ux.design',()=>{const p=project();addSkill(p,'design-system','# actual');scan(p);build(p);const r=route(p,rq({required_capabilities:['ux.design']}));assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.status,'ROUTE_READY');assert.deepEqual(o.selected.map(x=>x.id),['design-system']);assert.equal(o.instruction_bodies_loaded,false);assert.equal(o.execution_performed,false)});
test('router never selects unresolved skills',()=>{const p=project();scan(p);build(p);const r=route(p,rq({required_capabilities:['ux.motion']}));assert.notEqual(r.status,0);const o=jout(r);assert.equal(o.status,'ROUTE_BLOCKED');assert.equal(o.selected.some(x=>x.id==='animate'),false);assert.ok(o.unresolved_suggestions.some(x=>x.id==='animate'))});
test('router fails closed when required capability has no usable provider',()=>{const p=project();scan(p);build(p);const r=route(p,rq({required_capabilities:['capability.does-not-exist']}));assert.notEqual(r.status,0);assert.deepEqual(jout(r).missing_required_capabilities,['capability.does-not-exist'])});
test('router chooses minimal skill covering multiple required capabilities',()=>{const p=project();addSkill(p,'combo','# combo',{schema_version:'1.0',id:'combo',domain:'x',role:'specialist',description:'fixture',capabilities:['cap.a','cap.b'],intents:[],dependencies:[],conflicts:[]});addSkill(p,'one','# one',{schema_version:'1.0',id:'one',domain:'x',role:'specialist',description:'fixture',capabilities:['cap.a'],intents:[],dependencies:[],conflicts:[]});scan(p);build(p);const r=route(p,rq({required_capabilities:['cap.a','cap.b']}));assert.equal(r.status,0);assert.deepEqual(jout(r).selected.map(x=>x.id),['combo'])});
test('router is deterministic on ties using logical ID',()=>{const p=project();for(const id of ['zz-skill','aa-skill'])addSkill(p,id,'# x',{schema_version:'1.0',id,domain:'x',role:'specialist',description:'fixture',capabilities:['cap.tie'],intents:[],dependencies:[],conflicts:[]});scan(p);build(p);const r=route(p,rq({required_capabilities:['cap.tie']}));assert.equal(jout(r).selected[0].id,'aa-skill')});
test('max_skills is a hard route bound',()=>{const p=project();for(const [id,c] of [['a-one','cap.one'],['b-two','cap.two']])addSkill(p,id,'# x',{schema_version:'1.0',id,domain:'x',role:'specialist',description:'fixture',capabilities:[c],intents:[],dependencies:[],conflicts:[]});scan(p);build(p);const r=route(p,rq({required_capabilities:['cap.one','cap.two'],max_skills:1}));assert.notEqual(r.status,0);assert.equal(jout(r).selected.length,1);assert.equal(jout(r).missing_required_capabilities.length,1)});
test('route result is sealed and contains only metadata references, not skill bodies',()=>{const p=project();addSkill(p,'design-system','SECRET_INSTRUCTION_BODY');scan(p);build(p);const r=route(p,rq({required_capabilities:['ux.design']}));const raw=r.stdout;assert.doesNotMatch(raw,/SECRET_INSTRUCTION_BODY/);assert.match(jout(r).integrity.payload_sha256,/^[a-f0-9]{64}$/)});
test('route artifacts are persisted per task',()=>{const p=project();scan(p);build(p);route(p,rq({task_id:'abc',required_capabilities:['workflow.task-contract']}));assert.ok(fs.existsSync(path.join(p,'.aledevos/state/skills/routes/abc.json')))});
test('persisted route verifies when intact',()=>{const p=project();scan(p);build(p);route(p,rq({task_id:'route-ok',required_capabilities:[]}));const r=run(p,'route','verify','--project-root',p,'--task-id','route-ok');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).valid,true)});
test('route artifact tampering is detected',()=>{const p=project();scan(p);build(p);route(p,rq({task_id:'route-bad',required_capabilities:[]}));const f=path.join(p,'.aledevos/state/skills/routes/route-bad.json'),o=JSON.parse(fs.readFileSync(f));o.status='ROUTE_BLOCKED';fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'route','verify','--project-root',p,'--task-id','route-bad');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('route_integrity_mismatch'))});
test('runtime invocation remains adapter-owned after governance is introduced',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json'));assert.equal(p.execution_lifecycle.engine_direct_execution,false);assert.equal(p.execution_lifecycle.adapter_executes,true)});
test('installer scans discovery before building registry',()=>{const s=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');const a=s.indexOf('discovery scan'),b=s.indexOf('registry build');assert.ok(a>=0&&b>a);assert.match(s,/Skill System Phase 4/);assert.match(s,/skillsystem\\discovery/)});
test('phase 2 schemas configs and catalogs parse cleanly',()=>{for(const d of ['skillsystem/schemas','skillsystem/catalogs','skillsystem/policies','skillsystem/bindings','skillsystem/discovery'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join(d,f),'utf8')),`${d}/${f}`)});
