import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const runtime=path.resolve('skillsystem/engine/skillsystem.mjs');
const run=(cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-skills-p4-'));
function cp(src,dst){fs.mkdirSync(path.dirname(dst),{recursive:true});fs.cpSync(src,dst,{recursive:true});}
function configureAdapter(p){const d=path.join(p,'.aledevos');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'project.json'),JSON.stringify({schema_version:'1.0',adapter:'opencode',adapters:['opencode']},null,2));}
function project(){const p=tmp();cp('skillsystem/catalogs',path.join(p,'.aledevos/skillsystem/catalogs'));cp('skillsystem/policies',path.join(p,'.aledevos/skillsystem/policies'));cp('skillsystem/bindings',path.join(p,'.aledevos/skillsystem/bindings'));cp('skillsystem/discovery',path.join(p,'.aledevos/skillsystem/discovery'));cp('adapters/opencode/.opencode/skills',path.join(p,'.opencode/skills'));cp('contextos/policies',path.join(p,'.aledevos/contextos/policies'));configureAdapter(p);return p;}
function addSkill(p,id,{body='# skill\n',capabilities=[],dependencies=[],conflicts=[],intents=[],domain='fixture'}={}){const d=path.join(p,'.opencode/skills',id);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'SKILL.md'),body);fs.writeFileSync(path.join(d,'aledevos-skill.json'),JSON.stringify({schema_version:'1.0',id,domain,role:'specialist',description:'fixture',capabilities,intents,dependencies,conflicts}));}
function scanBuild(p){let r=run(p,'discovery','scan','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);r=run(p,'registry','build','--project-root',p,'--adapter','opencode');assert.equal(r.status,0,r.stderr);}
function route(p,task='t1',caps=['task.contract']){const f=path.join(p,`${task}-route.json`);fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,required_capabilities:caps,preferred_capabilities:[],intents:[],domains:[]}));return run(p,'route','plan','--project-root',p,'--request',f);}
function compose(p,task='t1'){return run(p,'compose','plan','--project-root',p,'--task-id',task);}
function load(p,task='t1',over={}){const f=path.join(p,`${task}-load.json`);fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,target_agent:'builder',runtime_profile:'opencode-qwen64k',base_context_tokens:0,...over}));return run(p,'load','plan','--project-root',p,'--request',f);}
function handoff(p,task='t1',over={}){const f=path.join(p,`${task}-handoff.json`);fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,target_agent:'builder',input_refs:[{kind:'task_contract',ref:'.aledevos/task.json'}],required_outputs:['summary','evidence'],...over}));return run(p,'handoff','create','--project-root',p,'--request',f);}
function prep(p,task='t1',caps=['task.contract']){scanBuild(p);let r=route(p,task,caps);assert.equal(r.status,0,r.stderr);r=compose(p,task);assert.equal(r.status,0,r.stderr);r=load(p,task);assert.equal(r.status,0,r.stderr);r=handoff(p,task);assert.equal(r.status,0,r.stderr);}
function governance(p,task='t1',over={}){const f=path.join(p,`${task}-gov.json`);fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,risk_level:'LOW',requested_by_agent:'builder',adapter:'opencode',runtime_permissions_attested:false,...over}));return run(p,'governance','evaluate','--project-root',p,'--request',f);}
function receipt(p,task='t1',attempt=1,over={}){const f=path.join(p,`${task}-receipt-${attempt}.json`);fs.writeFileSync(f,JSON.stringify({schema_version:'1.0',task_id:task,attempt,status:'SUCCEEDED',output_refs:[{kind:'artifact',ref:`.aledevos/results/${task}.json`}],outputs_present:['summary','evidence'],contract_satisfied:true,duration_ms:100,input_tokens:10,output_tokens:20,adapter:'opencode',runtime:'qwen-local',...over}));return run(p,'execute','record','--project-root',p,'--request',f);}

test('phase 4 enables governance, execution lifecycle and telemetry while direct engine execution stays disabled',()=>{const p=JSON.parse(fs.readFileSync('skillsystem/policies/skill-policy.json'));assert.equal(p.phase_boundary.governance_enabled,true);assert.equal(p.phase_boundary.execution_enabled,true);assert.equal(p.phase_boundary.skill_telemetry_enabled,true);assert.equal(p.execution_lifecycle.engine_direct_execution,false);assert.equal(p.execution_lifecycle.adapter_executes,true)});
test('LOW-risk bundled skill is governance-approved',()=>{const p=project();prep(p,'low');const r=governance(p,'low');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.status,'GOVERNANCE_APPROVED');assert.equal(o.skills[0].decision,'ALLOW')});
test('HIGH-risk execution requires runtime permission attestation',()=>{const p=project();prep(p,'high-no-attest');const r=governance(p,'high-no-attest',{risk_level:'HIGH'});assert.notEqual(r.status,0);const o=jout(r);assert.equal(o.status,'GOVERNANCE_BLOCKED');assert.ok(o.errors.includes('RUNTIME_PERMISSION_ATTESTATION_REQUIRED'))});
test('HIGH-risk bundled execution is approved with permission attestation',()=>{const p=project();prep(p,'high-ok');const r=governance(p,'high-ok',{risk_level:'HIGH',runtime_permissions_attested:true});assert.equal(r.status,0,r.stderr);assert.equal(jout(r).status,'GOVERNANCE_APPROVED')});
test('CRITICAL risk rejects runtime-discovered skill below bundled trust',()=>{const p=project();addSkill(p,'runtime-skill',{capabilities:['fixture.runtime']});prep(p,'critical',['fixture.runtime']);const r=governance(p,'critical',{risk_level:'CRITICAL',runtime_permissions_attested:true});assert.notEqual(r.status,0);const o=jout(r);assert.ok(o.errors.some(x=>x.includes('TRUST_BELOW_REQUIRED:runtime-verified<bundled')))});
test('forbidden capability is blocked even when skill is otherwise usable',()=>{const p=project();addSkill(p,'unsafe',{capabilities:['security.bypass']});prep(p,'unsafe',['security.bypass']);const r=governance(p,'unsafe');assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.includes('FORBIDDEN_CAPABILITY:security.bypass')))});
test('allowed domain restriction fails closed',()=>{const p=project();prep(p,'domain');const r=governance(p,'domain',{allowed_domains:['motion']});assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.includes('DOMAIN_NOT_ALLOWED')))});
test('governance artifact is metadata-only and sealed',()=>{const p=project();prep(p,'meta');const r=governance(p,'meta');assert.equal(r.status,0);assert.doesNotMatch(r.stdout,/# Task Contract/);assert.match(jout(r).integrity.payload_sha256,/^[a-f0-9]{64}$/)});
test('governance tampering is detected',()=>{const p=project();prep(p,'gov-tamper');governance(p,'gov-tamper');const f=path.join(p,'.aledevos/state/skills/governance/gov-tamper.json'),o=JSON.parse(fs.readFileSync(f));o.retry_budget=99;fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'governance','verify','--project-root',p,'--task-id','gov-tamper');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('governance_integrity_mismatch'))});
test('execution receipt cannot be recorded without governance approval',()=>{const p=project();prep(p,'nogov');const r=receipt(p,'nogov');assert.notEqual(r.status,0);assert.match(r.stderr,/governance|GOVERNANCE/i)});
test('successful execution receipt with complete output contract is accepted',()=>{const p=project();prep(p,'success');governance(p,'success');const r=receipt(p,'success');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.record_status,'EXECUTION_RECEIPT_ACCEPTED');assert.equal(o.validation.accepted,true)});
test('successful declaration missing required output is rejected',()=>{const p=project();prep(p,'missing-output');governance(p,'missing-output');const r=receipt(p,'missing-output',1,{outputs_present:['summary']});assert.notEqual(r.status,0);const o=jout(r);assert.equal(o.record_status,'EXECUTION_RECEIPT_REJECTED');assert.ok(o.validation.errors.some(x=>x.includes('MISSING_REQUIRED_OUTPUTS:evidence')))});
test('inline output bodies are forbidden',()=>{const p=project();prep(p,'inline-output');governance(p,'inline-output');const r=receipt(p,'inline-output',1,{output_refs:[{kind:'artifact',ref:'x',content:'secret'}]});assert.notEqual(r.status,0);assert.match(r.stderr,/inline_output_forbidden/)});
test('one retry after a failed attempt is accepted within policy',()=>{const p=project();prep(p,'retry');governance(p,'retry');let r=receipt(p,'retry',1,{status:'FAILED',outputs_present:[],contract_satisfied:false,error_code:'TEMP'});assert.equal(r.status,0,r.stderr);r=receipt(p,'retry',2);assert.equal(r.status,0,r.stderr);assert.equal(jout(r).attempt,2)});
test('retry budget blocks a third attempt',()=>{const p=project();prep(p,'retry-limit');governance(p,'retry-limit');assert.equal(receipt(p,'retry-limit',1,{status:'FAILED',outputs_present:[],contract_satisfied:false}).status,0);assert.equal(receipt(p,'retry-limit',2,{status:'FAILED',outputs_present:[],contract_satisfied:false}).status,0);const r=receipt(p,'retry-limit',3);assert.notEqual(r.status,0);assert.match(r.stderr,/RETRY_BUDGET_EXHAUSTED/)});
test('no execution attempt is allowed after an accepted success',()=>{const p=project();prep(p,'after-success');governance(p,'after-success');assert.equal(receipt(p,'after-success',1).status,0);const r=receipt(p,'after-success',2);assert.notEqual(r.status,0);assert.match(r.stderr,/ALREADY_SUCCEEDED/)});
test('execution receipt tampering is detected',()=>{const p=project();prep(p,'receipt-tamper');governance(p,'receipt-tamper');receipt(p,'receipt-tamper',1);const f=path.join(p,'.aledevos/state/skills/executions/receipt-tamper/attempt-1.json'),o=JSON.parse(fs.readFileSync(f));o.duration_ms=9999;fs.writeFileSync(f,JSON.stringify(o));const r=run(p,'execute','verify','--project-root',p,'--task-id','receipt-tamper');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('attempt_integrity:1'))});
test('skill telemetry chain verifies after governance and execution events',()=>{const p=project();prep(p,'tele');governance(p,'tele');receipt(p,'tele',1);const r=run(p,'telemetry','verify','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.valid,true);assert.ok(o.event_count>=3)});
test('skill telemetry tampering is detected',()=>{const p=project();prep(p,'tele-tamper');governance(p,'tele-tamper');receipt(p,'tele-tamper',1);const f=path.join(p,'.aledevos/state/telemetry/skills/events.jsonl'),lines=fs.readFileSync(f,'utf8').trim().split(/\r?\n/),o=JSON.parse(lines[0]);o.status='GOVERNANCE_BLOCKED';lines[0]=JSON.stringify(o);fs.writeFileSync(f,lines.join('\n')+'\n');const r=run(p,'telemetry','verify','--project-root',p);assert.notEqual(r.status,0);assert.equal(jout(r).valid,false)});
test('telemetry summary records attempts, successes, retries and non-causal attribution',()=>{const p=project();prep(p,'summary');governance(p,'summary');receipt(p,'summary',1,{status:'FAILED',outputs_present:[],contract_satisfied:false});receipt(p,'summary',2);const r=run(p,'telemetry','summarize','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r),a=o.skills['task-contract'];assert.equal(o.attribution,'composition-correlated-not-causal');assert.equal(a.attempts,2);assert.equal(a.successes,1);assert.equal(a.failures,1);assert.equal(a.retries,1);assert.equal(a.success_rate,0.5)});
test('skill telemetry never stores instruction bodies or raw prompt fields',()=>{const p=project();prep(p,'privacy');governance(p,'privacy');receipt(p,'privacy',1);const raw=fs.readFileSync(path.join(p,'.aledevos/state/telemetry/skills/events.jsonl'),'utf8');assert.doesNotMatch(raw,/# Task Contract/);assert.doesNotMatch(raw,/"body"/);assert.doesNotMatch(raw,/"prompt"/)});
test('execution verifier validates a clean multi-attempt lifecycle',()=>{const p=project();prep(p,'verify-life');governance(p,'verify-life');receipt(p,'verify-life',1,{status:'FAILED',outputs_present:[],contract_satisfied:false});receipt(p,'verify-life',2);const r=run(p,'execute','verify','--project-root',p,'--task-id','verify-life');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).valid,true)});
test('installer preserves Phase 4 governance/execution/telemetry state directories',()=>{const s=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(s,/Skill System Phase 5/);assert.match(s,/state\\skills\\governance/);assert.match(s,/state\\skills\\executions/);assert.match(s,/state\\telemetry\\skills/)});
test('all Core and OpenCode agents carry Phase 4 Skill governance discipline',()=>{for(const d of ['core/agents','adapters/opencode/.opencode/agents'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.md'))){const t=fs.readFileSync(path.join(d,f),'utf8');assert.match(t,/## Skill System Phase 4/,`${d}/${f}`);assert.match(t,/GOVERNANCE_APPROVED/,`${d}/${f}`);assert.match(t,/reference-only/i,`${d}/${f}`)}});
test('receipt adapter mismatch is rejected',()=>{const p=project();prep(p,'adapter-mismatch');governance(p,'adapter-mismatch');const r=receipt(p,'adapter-mismatch',1,{adapter:'other-runtime'});assert.notEqual(r.status,0);assert.match(r.stderr,/EXECUTION_ADAPTER_MISMATCH/)});
test('phase 4 schemas and policy parse cleanly',()=>{for(const d of ['skillsystem/schemas','skillsystem/catalogs','skillsystem/policies','skillsystem/bindings','skillsystem/discovery'])for(const f of fs.readdirSync(d).filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join(d,f),'utf8')),`${d}/${f}`)});
