import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'),cr=path.resolve('uxui/engine/component-registry.mjs'),boot=path.resolve('uxui/engine/design-bootstrap.mjs'),review=path.resolve('uxui/engine/design-review.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});const jout=r=>JSON.parse(r.stdout);const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p4-'));const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};const h=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);assert.equal(run(cr,p,'registry','init','--project-root',p).status,0);return p}
function ev(p,{task='t',changed=['src/pages/Home.tsx'],responsive='VERIFIED',accessibility='VERIFIED',states='VERIFIED',decisions=[],exceptions=[]}={}){for(const f of changed)if(!fs.existsSync(path.join(p,f)))w(p,f,'export const Home=()=>null');const q={schema_version:'1.0',task_id:task,visual_task:true,changed_files:changed,reuse_decisions:decisions,responsive:{status:responsive,evidence:responsive==='VERIFIED'?['viewport-check']:[]},accessibility:{status:accessibility,evidence:accessibility==='VERIFIED'?['a11y-check']:[]},states:{status:states,covered:states==='VERIFIED'?['loading','empty','error','success']:[]},interaction:{status:'VERIFIED',evidence:['interaction-check']},exceptions};return w(p,`${task}-evidence.json`,JSON.stringify(q,null,2))}
function guardian(p,e,task='t'){const f=path.join(p,`${task}-guardian.json`);const r=run(review,p,'guardian','review','--project-root',p,'--evidence',e,'--out',f);return {r,f,o:jout(r)}}
function judge(p,e,g,task='t'){const f=path.join(p,`${task}-judge.json`);const r=run(review,p,'judge','score','--project-root',p,'--evidence',e,'--guardian',g,'--out',f);return {r,f,o:jout(r)}}
function makeColorCanonical(p){const a=w(p,'artifacts/color-system.md','# Color System\nUse semantic tokens only.\n');const q=w(p,'color-evidence.json',JSON.stringify({schema_version:'1.0',task_id:'color',source_kind:'human_approved_design_context',source_ref:'review:color',artifacts:[{section:'color_system',path:'artifacts/color-system.md',sha256:h(a)}]}));const r=run(boot,p,'evidence','apply','--project-root',p,'--input',q,'--approve');assert.equal(r.status,0,r.stderr)}

test('clean UI evidence passes Guardian',()=>{const p=init(),e=ev(p);const g=guardian(p,e);assert.equal(g.r.status,0,g.r.stderr);assert.equal(g.o.status,'GUARDIAN_PASS');assert.equal(g.o.blockers.length,0)});
test('clean verified visual task scores 100 and passes UXUI Judge',()=>{const p=init(),e=ev(p),g=guardian(p,e),j=judge(p,e,g.f);assert.equal(j.r.status,0,j.r.stderr);assert.equal(j.o.score,100);assert.equal(j.o.verdict,'PASS')});
test('UNVERIFIED responsive evidence fails UXUI Judge',()=>{const p=init(),e=ev(p,{responsive:'UNVERIFIED'}),g=guardian(p,e),j=judge(p,e,g.f);assert.notEqual(j.r.status,0);assert.equal(j.o.score,85);assert.equal(j.o.verdict,'FAIL');assert.deepEqual(j.o.unverified,['responsive'])});
test('tampered Design Context blocks Guardian',()=>{const p=init(),m=path.join(p,'.aledevos/design/design-context.json'),o=JSON.parse(fs.readFileSync(m));o.context_version++;fs.writeFileSync(m,JSON.stringify(o));const g=guardian(p,ev(p));assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.message==='design_context_integrity_mismatch'))});
test('tampered Component Registry blocks Guardian',()=>{const p=init(),f=path.join(p,'.aledevos/design/component-registry.json'),o=JSON.parse(fs.readFileSync(f));o.version++;fs.writeFileSync(f,JSON.stringify(o));const g=guardian(p,ev(p));assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.message==='component_registry_integrity_mismatch'))});
test('Guardian report tampering is detected',()=>{const p=init(),e=ev(p),g=guardian(p,e),o=JSON.parse(fs.readFileSync(g.f));o.status='GUARDIAN_BLOCKED';fs.writeFileSync(g.f,JSON.stringify(o));const r=run(review,p,'guardian','verify','--project-root',p,'--report',g.f);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('guardian_report_integrity_mismatch'))});
test('Design Context drift after Guardian invalidates report',()=>{const p=init(),e=ev(p),g=guardian(p,e),m=path.join(p,'.aledevos/design/design-context.json');fs.appendFileSync(m,' ');const r=run(review,p,'guardian','verify','--project-root',p,'--report',g.f);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('design_context_drift_since_guardian'))});
test('Judge report tampering is detected',()=>{const p=init(),e=ev(p),g=guardian(p,e),j=judge(p,e,g.f),o=JSON.parse(fs.readFileSync(j.f));o.score=99;fs.writeFileSync(j.f,JSON.stringify(o));const r=run(review,p,'judge','verify','--report',j.f,'--guardian',g.f);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('judge_report_integrity_mismatch'))});
test('new reusable component without reuse decision is blocked',()=>{const p=init(),e=ev(p,{changed:['src/components/Badge.tsx']});const g=guardian(p,e);assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.rule_id==='REUSE_BEFORE_CREATE'))});
test('approved CREATE_NEW_JUSTIFIED decision allows new reusable component',()=>{const p=init();w(p,'src/components/Badge.tsx','export const Badge=()=>null');const req=w(p,'reuse-request.json',JSON.stringify({requested_name:'Badge',category:'display',required_capabilities:['label'],required_variants:[],proposed_path:'src/components/Badge.tsx',reusable:true,justification:'No canonical badge exists and this component is shared across multiple screens.'}));const d=path.join(p,'reuse-decision.json');const rr=run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',d);assert.equal(rr.status,0,rr.stderr);assert.equal(jout(rr).action,'CREATE_NEW_JUSTIFIED');const e=ev(p,{changed:['src/components/Badge.tsx'],decisions:[{path:'src/components/Badge.tsx',decision_path:'reuse-decision.json'}]});const g=guardian(p,e);assert.equal(g.r.status,0,JSON.stringify(g.o));});
test('invalid reuse decision hash is blocked',()=>{const p=init();w(p,'src/components/Badge.tsx','export const Badge=()=>null');const req=w(p,'reuse-request.json',JSON.stringify({requested_name:'Badge',category:'display',required_capabilities:[],required_variants:[],proposed_path:'src/components/Badge.tsx',reusable:true,justification:'No canonical badge exists and this is intentionally reusable.'}));const d=path.join(p,'reuse-decision.json');run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',d);const o=JSON.parse(fs.readFileSync(d));o.reason='tampered';fs.writeFileSync(d,JSON.stringify(o));const e=ev(p,{changed:['src/components/Badge.tsx'],decisions:[{path:'src/components/Badge.tsx',decision_path:'reuse-decision.json'}]});const g=guardian(p,e);assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.message==='reuse_decision_integrity_mismatch'))});
test('canonical component source drift is a blocker',()=>{const p=init();w(p,'src/components/Button.tsx','export const Button=()=>null');const c=w(p,'component.json',JSON.stringify({component_id:'component:button',name:'Button',canonical_path:'src/components/Button.tsx',category:'action',capabilities:['press'],variants:['default'],aliases:[],ownership:'GLOBAL',domain:null,reusable:true,source:'verified_runtime_discovery',notes:'existing'}));assert.equal(run(cr,p,'registry','register','--project-root',p,'--input',c,'--approve-existing').status,0);w(p,'src/components/Button.tsx','export const Button=()=>42');const g=guardian(p,ev(p,{changed:['src/pages/Home.tsx']}));assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>String(x.message).includes('canonical_source_drift')))});
test('hardcoded color is blocked when canonical color system exists',()=>{const p=init();makeColorCanonical(p);const e=ev(p,{changed:['src/pages/Home.tsx']});w(p,'src/pages/Home.tsx',`export const Home=()=> <div style={{color:'#ff0000'}}>x</div>`);const g=guardian(p,e);assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.rule_id==='HARDCODED_COLOR'))});
test('approved hardcoded color exception becomes warning not blocker',()=>{const p=init();makeColorCanonical(p);const e=ev(p,{changed:['src/pages/Home.tsx'],exceptions:[{rule_id:'HARDCODED_COLOR',reason:'Third-party brand swatch required by approved campaign.',approval_ref:'UI-ADR-9'}]});w(p,'src/pages/Home.tsx',`export const Home=()=> <div style={{color:'#ff0000'}}>x</div>`);const g=guardian(p,e);assert.equal(g.r.status,0,JSON.stringify(g.o));assert.ok(g.o.warnings.some(x=>x.rule_id==='HARDCODED_COLOR'))});
test('missing changed file is fail-closed',()=>{const p=init(),e=ev(p,{changed:[]});const o=JSON.parse(fs.readFileSync(e));o.changed_files=['src/pages/Missing.tsx'];fs.writeFileSync(e,JSON.stringify(o));const g=guardian(p,e);assert.notEqual(g.r.status,0);assert.ok(g.o.blockers.some(x=>x.rule_id==='CHANGE_EVIDENCE'))});
test('specialist skills cannot override Guardian blockers by policy',()=>{const p=JSON.parse(fs.readFileSync('uxui/policies/uxui-policy.json'));assert.equal(p.phase4.skill_role.specialist_outputs_are_evidence_only,true);assert.equal(p.phase4.skill_role.skills_cannot_override_guardian_blockers,true)});
test('UXUI Judge threshold and dimensions equal 100',()=>{const p=JSON.parse(fs.readFileSync('uxui/policies/uxui-policy.json'));assert.equal(p.phase4.judge.threshold,90);assert.equal(Object.values(p.phase4.judge.weights).reduce((a,b)=>a+b,0),100);assert.equal(p.phase4.judge.blockers_must_be_zero,true);assert.equal(p.phase4.judge.critical_unverified_must_be_zero,true)});
test('Phase 4 schemas parse cleanly',()=>{for(const f of ['ui-change-evidence.schema.json','design-guardian-report.schema.json','uxui-judge-report.schema.json'])assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('uxui/schemas',f))))});
test('Phase 4 contract preserves boundary with later Visual QA',()=>{const t=fs.readFileSync('core/design/contracts/DESIGN_GUARDIAN_UXUI_JUDGE.md','utf8');assert.match(t,/Visual QA/i);assert.match(t,/cannot override a deterministic Guardian blocker/i);assert.match(t,/score >= 90/i)});
test('OpenCode gets dedicated read-only Guardian and UXUI Judge agents',()=>{for(const n of ['design-system-guardian','judge-uxui']){const t=fs.readFileSync(path.join('adapters/opencode/.opencode/agents',`${n}.md`),'utf8');assert.match(t,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(t,/action: shell[\s\S]*resource: "\*"[\s\S]*effect: deny/)}});
test('orchestrator may delegate to Design System Guardian',()=>{const t=fs.readFileSync('adapters/opencode/.opencode/agents/orchestrator.md','utf8');assert.match(t,/resource: "design-system-guardian"[\s\S]*effect: allow/)});
test('installer deploys Phase 4 review engine and state directories',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/design-review\.mjs/);assert.match(t,/phase4\\guardian/);assert.match(t,/phase4\\judges/);assert.match(t,/v1\.19 UXUI-P4/)});
test('UI-relevant agents carry Phase 4 discipline',()=>{for(const base of ['core/agents','adapters/opencode/.opencode/agents'])for(const n of ['orchestrator','researcher','architect','auditor','builder','editor-frontend','verifier','judge-quality','repairer'])assert.match(fs.readFileSync(path.join(base,`${n}.md`),'utf8'),/UX\/UI Phase 4 discipline/)});
