import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'), motion=path.resolve('uxui/engine/motion.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});const jout=r=>JSON.parse(r.stdout);const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p5-'));const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);assert.equal(run(motion,p,'language','init','--project-root',p).status,0);return p}
function proposal(over={}){return {schema_version:'1.0',source_kind:'human_approved_design_context',source_ref:'UI-ADR-MOTION-001',durations:{micro:{min_ms:100,max_ms:160},standard:{min_ms:160,max_ms:240},large:{min_ms:240,max_ms:360}},easings:{enter:'ease-out',exit:'ease-in',emphasis:'spring'},semantic_roles:{feedback:{duration_token:'micro',easing_token:'enter'},navigation:{duration_token:'standard',easing_token:'enter'}},reduced_motion:{required:true,default_behavior:'SIMPLIFY'},rules:{exit_faster_than_enter:true},platform_overrides:{},...over}}
function activate(p,q=proposal()){const f=w(p,'motion-proposal.json',JSON.stringify(q,null,2));const r=run(motion,p,'language','apply','--project-root',p,'--input',f,'--approve');assert.equal(r.status,0,r.stderr||r.stdout);return jout(r)}
function contract(over={}){return {schema_version:'1.0',task_id:'motion-task',motion_required:true,rationale:'The overlay intentionally animates between visible states.',changed_files:['src/components/Panel.tsx'],interactions:[{id:'panel.enter',intent:'enter',duration_token:'standard',easing_token:'enter',reduced_motion_behavior:'SIMPLIFY',loop:false,essential:false}],skill_evidence:[],exceptions:[],...over}}
function sealC(p,q=contract()){w(p,'src/components/Panel.tsx','export const Panel=()=>null');const f=w(p,'contract-input.json',JSON.stringify(q,null,2)),out=path.join(p,'contract-sealed.json');const r=run(motion,p,'contract','seal','--project-root',p,'--input',f,'--out',out);return {r,o:r.stdout?jout(r):null,out}}

test('Motion Language initializes UNSET without invented project tokens',()=>{const p=init(),o=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/motion-language.json')));assert.equal(o.status,'UNSET');assert.deepEqual(o.durations,{});assert.deepEqual(o.easings,{})});
test('UNSET Motion Language verifies as structurally valid',()=>{const p=init(),r=run(motion,p,'language','verify','--project-root',p);assert.equal(r.status,0);assert.equal(jout(r).status,'UNSET')});
test('Motion Language activation requires explicit approval',()=>{const p=init(),f=w(p,'p.json',JSON.stringify(proposal()));const r=run(motion,p,'language','apply','--project-root',p,'--input',f);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('explicit_approval_required'))});
test('reduced motion is mandatory in Motion Language',()=>{const p=init(),f=w(p,'p.json',JSON.stringify(proposal({reduced_motion:{required:false,default_behavior:'SIMPLIFY'}})));const r=run(motion,p,'language','apply','--project-root',p,'--input',f,'--approve');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('reduced_motion_must_be_required'))});
test('duration scale must remain monotonic',()=>{const p=init(),q=proposal();q.durations.standard.max_ms=99;const f=w(p,'p.json',JSON.stringify(q));const r=run(motion,p,'language','apply','--project-root',p,'--input',f,'--approve');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('duration_scale_not_monotonic'))});
test('approved Motion Language becomes ACTIVE and updates Design Context',()=>{const p=init(),a=activate(p),v=run(motion,p,'language','verify','--project-root',p);assert.equal(v.status,0);assert.equal(jout(v).status,'ACTIVE');const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json')));assert.equal(m.sections.motion_language.status,'PRESENT');assert.equal(m.sections.motion_language.source_sha256,a.language_integrity)});
test('tampered machine Motion Language is detected',()=>{const p=init();activate(p);const f=path.join(p,'.aledevos/design/motion-language.json'),o=JSON.parse(fs.readFileSync(f));o.durations.micro.max_ms=999;fs.writeFileSync(f,JSON.stringify(o));const r=run(motion,p,'language','verify','--project-root',p);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('motion_language_integrity_mismatch'))});
test('human-readable Motion Language drift is detected',()=>{const p=init();activate(p);fs.appendFileSync(path.join(p,'.aledevos/design/motion-language.md'),'tamper');const r=run(motion,p,'language','verify','--project-root',p);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('motion_language_human_artifact_drift'))});
test('generic Motion Director plan is sealed and references motion capability only',()=>{const p=init(),r=run(motion,p,'plan','create','--project-root',p,'--task-id','t1','--platform','generic');assert.equal(r.status,0);const o=jout(r);assert.deepEqual(o.skill_route_request.required_capabilities,['ux.motion']);assert.ok(o.skill_route_request.preferred_skills.includes('animation-vocabulary'));assert.equal(JSON.stringify(o).includes('SKILL.md'),false)});
test('Expo plan prefers animate-expo without loading instructions',()=>{const p=init(),o=jout(run(motion,p,'plan','create','--project-root',p,'--task-id','t2','--platform','expo'));assert.ok(o.skill_route_request.preferred_skills.includes('animate-expo'));assert.equal(o.skill_route_request.missing_skill_policy,'ACQUIRE_IF_TRUSTED_ELSE_APPROVAL')});
test('unsupported motion platform fails closed',()=>{const p=init(),r=run(motion,p,'plan','create','--project-root',p,'--task-id','t','--platform','unknown');assert.notEqual(r.status,0);assert.equal(jout(r).status,'MOTION_PLATFORM_UNSUPPORTED')});
test('motion plan invalidates after Design Context changes',()=>{const p=init(),out=path.join(p,'plan.json');assert.equal(run(motion,p,'plan','create','--project-root',p,'--task-id','t','--out',out).status,0);activate(p);const r=run(motion,p,'plan','verify','--project-root',p,'--plan',out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('design_context_drift_since_motion_plan'))});
test('NO_MOTION_REQUIRED contract can be sealed while language is UNSET',()=>{const p=init(),q=contract({motion_required:false,rationale:'This task has no animated or transitional behavior.',interactions:[]});w(p,'src/components/Panel.tsx','export const Panel=()=>null');const f=w(p,'c.json',JSON.stringify(q)),r=run(motion,p,'contract','seal','--project-root',p,'--input',f);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'NO_MOTION_REQUIRED')});
test('NO_MOTION_REQUIRED cannot hide supplied interactions',()=>{const p=init(),q=contract({motion_required:false});const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('interactions_present_when_motion_not_required'))});
test('motion-required contract blocks while Motion Language is UNSET',()=>{const p=init(),x=sealC(p);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('motion_language_not_active'))});
test('valid motion contract seals against active language',()=>{const p=init();activate(p);const x=sealC(p);assert.equal(x.r.status,0,x.r.stdout);assert.equal(x.o.status,'MOTION_CONTRACT_READY');assert.match(x.o.contract_sha256,/^[a-f0-9]{64}$/)});
test('invalid duration token is blocked',()=>{const p=init();activate(p);const q=contract();q.interactions[0].duration_token='magic';const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('duration_token_invalid:panel.enter'))});
test('invalid easing token is blocked',()=>{const p=init();activate(p);const q=contract();q.interactions[0].easing_token='magic';const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('easing_token_invalid:panel.enter'))});
test('missing reduced-motion behavior is blocked',()=>{const p=init();activate(p);const q=contract();delete q.interactions[0].reduced_motion_behavior;const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('reduced_motion_missing:panel.enter'))});
test('raw duration literal is blocked by default',()=>{const p=init();activate(p);const q=contract();q.interactions[0].duration_ms=173;const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('raw_duration_literal:panel.enter'))});
test('approved raw motion literal exception is allowed',()=>{const p=init();activate(p);const q=contract({exceptions:[{rule_id:'RAW_MOTION_LITERAL',reason:'Third-party API requires a fixed literal for interoperability.',approval_ref:'UI-ADR-77'}]});q.interactions[0].duration_ms=173;const x=sealC(p,q);assert.equal(x.r.status,0,x.r.stdout)});
test('decorative infinite motion is blocked',()=>{const p=init();activate(p);const q=contract();q.interactions[0].loop=true;q.interactions[0].essential=false;const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('decorative_infinite_loop:panel.enter'))});
test('approved decorative infinite motion exception is explicit',()=>{const p=init();activate(p);const q=contract({exceptions:[{rule_id:'DECORATIVE_INFINITE_MOTION',reason:'Approved ambient status indicator for this kiosk experience.',approval_ref:'UI-ADR-88'}]});q.interactions[0].loop=true;q.interactions[0].essential=false;const x=sealC(p,q);assert.equal(x.r.status,0,x.r.stdout)});
test('Skill evidence is reference-only',()=>{const p=init();activate(p);const q=contract({skill_evidence:[{skill_id:'animate',receipt_ref:'.aledevos/skills/receipt.json',prompt:'secret'}]});const x=sealC(p,q);assert.notEqual(x.r.status,0);assert.ok(jout(x.r).errors.includes('skill_evidence_inline_forbidden:prompt'))});
test('sealed Motion Contract tampering is detected',()=>{const p=init();activate(p);const x=sealC(p);assert.equal(x.r.status,0);const o=JSON.parse(fs.readFileSync(x.out));o.rationale='tampered';fs.writeFileSync(x.out,JSON.stringify(o));const r=run(motion,p,'contract','verify','--project-root',p,'--contract',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('motion_contract_integrity_mismatch'))});
test('Motion Language drift invalidates an existing contract',()=>{const p=init();activate(p);const x=sealC(p);activate(p,proposal({source_ref:'UI-ADR-MOTION-002'}));const r=run(motion,p,'contract','verify','--project-root',p,'--contract',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('motion_language_drift_since_motion_contract'))});
test('valid contract produces MOTION_PASS review',()=>{const p=init();activate(p);const x=sealC(p),out=path.join(p,'review.json');const r=run(motion,p,'review','create','--project-root',p,'--contract',x.out,'--out',out);assert.equal(r.status,0,r.stdout);const o=jout(r);assert.equal(o.status,'MOTION_PASS');assert.equal(o.reduced_motion_covered,true)});
test('Motion Review tampering is detected',()=>{const p=init();activate(p);const x=sealC(p),out=path.join(p,'review.json');run(motion,p,'review','create','--project-root',p,'--contract',x.out,'--out',out);const o=JSON.parse(fs.readFileSync(out));o.status='MOTION_BLOCKED';fs.writeFileSync(out,JSON.stringify(o));const r=run(motion,p,'review','verify','--project-root',p,'--report',out,'--contract',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('motion_review_integrity_mismatch'))});
test('Design Context drift after Motion Review invalidates evidence',()=>{const p=init();activate(p);const x=sealC(p),out=path.join(p,'review.json');run(motion,p,'review','create','--project-root',p,'--contract',x.out,'--out',out);const m=path.join(p,'.aledevos/design/design-context.json'),o=JSON.parse(fs.readFileSync(m));o.context_version++;fs.writeFileSync(m,JSON.stringify(o));const r=run(motion,p,'review','verify','--project-root',p,'--report',out,'--contract',x.out);assert.notEqual(r.status,0);const j=jout(r);assert.ok(j.status==='DESIGN_CONTEXT_INVALID'||(j.errors||[]).includes('design_context_drift_since_motion_review'))});
test('deterministic motion detection finds animation signals in bounded source files',()=>{const p=init();w(p,'src/components/Fade.tsx',`export const x={transition:'opacity 200ms ease'}`);const r=run(motion,p,'detect','scan','--project-root',p,'--files','src/components/Fade.tsx');assert.equal(r.status,0);const o=jout(r);assert.equal(o.motion_detected,true);assert.equal(o.files[0].path,'src/components/Fade.tsx')});

test('installer deploys and initializes Phase 5 Motion runtime',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/motion\.mjs/);assert.match(t,/phase5\\plans/);assert.match(t,/phase5\\contracts/);assert.match(t,/phase5\\reviews/);assert.match(t,/language init --project-root/);assert.match(t,/v1\.20 UXUI-P5/)});
test('OpenCode orchestrator may delegate to Motion Director',()=>{const t=fs.readFileSync('adapters/opencode/.opencode/agents/orchestrator.md','utf8');assert.match(t,/resource: "motion-director"[\s\S]*effect: allow/)});
test('Motion Director is read-only in OpenCode adapter',()=>{const t=fs.readFileSync('adapters/opencode/.opencode/agents/motion-director.md','utf8');assert.match(t,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(t,/action: shell[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(t,/motion\.mjs/)});
