import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'),cr=path.resolve('uxui/engine/component-registry.mjs'),quality=path.resolve('uxui/engine/ui-quality.mjs'),review=path.resolve('uxui/engine/design-review.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});const jout=r=>JSON.parse(r.stdout);const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p6-'));const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);assert.equal(run(cr,p,'registry','init','--project-root',p).status,0);assert.equal(run(quality,p,'standards','init','--project-root',p).status,0);return p}
function a11y(p){const f=w(p,'a11y.json',JSON.stringify({standard:'WCAG_2_2_AA',requirements:{semantics:'Use semantic elements and roles that match behavior.',keyboard:'All interactive controls must be keyboard operable.',focus:'Visible focus and logical focus order are required.',labels:'Controls and inputs require accessible names.',contrast:'Rendered contrast must meet the approved project target.',reduced_motion:'Respect canonical reduced-motion behavior.'},source_ref:'UI-ADR-1000'}));return run(quality,p,'accessibility','approve','--project-root',p,'--input',f,'--approval-ref','human:approved')}
function responsive(p){const f=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow and primary actions remain usable.'},{id:'wide',width:1440,height:900,expectation:'Use approved wide layout without excessive stretching.'}],container_policy:'Use the approved container system.',overflow_policy:'Horizontal overflow is not allowed unless approved.',source_ref:'UI-ADR-1001'}));return run(quality,p,'responsive','approve','--project-root',p,'--input',f,'--approval-ref','human:approved')}
function states(p){const f=w(p,'states.json',JSON.stringify({conventions:{LOADING:'Show progress while preserving task context.',EMPTY:'Explain empty condition and next action.',ERROR:'Explain failure and safe recovery.',SUCCESS:'Confirm completed actions when feedback is needed.'},source_ref:'UI-ADR-1002'}));return run(quality,p,'states','approve','--project-root',p,'--input',f,'--approval-ref','human:approved')}
function adr(p,id='UI-ADR-1000',extra={}){const f=w(p,`${id}.input.json`,JSON.stringify({id,title:'Canonical UI behavior decision',context:'This interaction requires one reusable documented behavior across multiple product surfaces.',decision:'Use the canonical interaction pattern and do not introduce a page-local alternative.',consequences:'Future changes update the canonical pattern and all consumers inherit the same behavior.',scope:['src/pages/Home.tsx'],source_refs:['design-context'],approval_ref:'human:approved',...extra}));const r=run(quality,p,'adr','create','--project-root',p,'--input',f);return {r,f,o:jout(r)}}
function stateContract(p,complete=true){const ev=complete?[{state:'LOADING',evidence_ref:'e/loading'},{state:'EMPTY',evidence_ref:'e/empty'},{state:'ERROR',evidence_ref:'e/error'},{state:'CONTENT',evidence_ref:'e/content'}]:[{state:'LOADING',evidence_ref:'e/loading'}];const f=w(p,'state-contract-input.json',JSON.stringify({task_id:'task-1',surfaces:[{id:'home-data',kind:'DATA_SURFACE',required_states:[],evidence:ev}]}));const out=path.join(p,'.aledevos/state/uxui/phase6/state-contracts/task-1.json');const r=run(quality,p,'states','seal','--project-root',p,'--input',f,'--out',out);return {r,out,o:jout(r)}}
function activate(p){assert.equal(a11y(p).status,0);assert.equal(responsive(p).status,0);assert.equal(states(p).status,0)}
function reviewReq(p,{file='src/pages/Home.tsx',exceptions=[],a11yEvidence=true,respEvidence=true,statesRequired=true,adrRefs=[]}={}){if(!fs.existsSync(path.join(p,file)))w(p,file,'export const Home=()=> <main><h1>Home</h1></main>');const st=stateContract(p,true);assert.equal(st.r.status,0,st.r.stdout);const ae=a11yEvidence?['semantics','keyboard','focus','labels','contrast','reduced_motion'].map(criterion=>({criterion,evidence_ref:`e/a11y/${criterion}`})):[];const re=respEvidence?[{viewport_id:'narrow',evidence_ref:'e/viewport/narrow'},{viewport_id:'wide',evidence_ref:'e/viewport/wide'}]:[];return w(p,'review-request.json',JSON.stringify({task_id:'task-1',changed_files:[file],accessibility:{required:true,evidence:ae},responsive:{required:true,evidence:re},states:{required:statesRequired,contract_path:'.aledevos/state/uxui/phase6/state-contracts/task-1.json'},adr_refs:adrRefs,exceptions}))}
function createReview(p,opts={}){const inp=reviewReq(p,opts),out=path.join(p,'.aledevos/state/uxui/phase6/reviews/task-1.json');const r=run(quality,p,'review','create','--project-root',p,'--input',inp,'--out',out);return {r,out,o:jout(r)}}

test('Phase 6 standards initialize UNSET without invented project values',()=>{const p=init(),d=path.join(p,'.aledevos/design');const a=JSON.parse(fs.readFileSync(path.join(d,'accessibility-policy.json'))),r=JSON.parse(fs.readFileSync(path.join(d,'responsive-policy.json'))),s=JSON.parse(fs.readFileSync(path.join(d,'ui-states.json')));assert.equal(a.status,'UNSET');assert.equal(a.standard,null);assert.equal(r.status,'UNSET');assert.deepEqual(r.viewports,[]);assert.equal(s.status,'UNSET')});
test('standards verify cleanly after init',()=>{const p=init(),r=run(quality,p,'standards','verify','--project-root',p);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'UI_STANDARDS_VALID')});
test('accessibility approval activates all required requirement domains',()=>{const p=init(),r=a11y(p);assert.equal(r.status,0,r.stdout);const v=run(quality,p,'accessibility','verify','--project-root',p);assert.equal(v.status,0);assert.equal(jout(v).status,'ACTIVE')});
test('accessibility approval fails closed when a required domain is missing',()=>{const p=init();const f=w(p,'bad.json',JSON.stringify({standard:'WCAG_2_2_AA',requirements:{semantics:'x',keyboard:'x',focus:'x',labels:'x',contrast:'x'},source_ref:'x'}));const r=run(quality,p,'accessibility','approve','--project-root',p,'--input',f,'--approval-ref','approved');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('requirement_missing:reduced_motion'))});
test('responsive approval requires explicit approved viewport profiles',()=>{const p=init(),r=responsive(p);assert.equal(r.status,0,r.stdout);const v=run(quality,p,'responsive','verify','--project-root',p);assert.equal(v.status,0);assert.equal(jout(v).viewports.length,2)});
test('responsive approval blocks a single viewport',()=>{const p=init();const f=w(p,'bad-r.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'only',width:800,expectation:'x'}],container_policy:'x',overflow_policy:'x'}));const r=run(quality,p,'responsive','approve','--project-root',p,'--input',f,'--approval-ref','approved');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('viewport_count_invalid'))});
test('responsive approval blocks duplicate viewport IDs',()=>{const p=init();const f=w(p,'bad-r.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'same',width:390,expectation:'x'},{id:'same',width:1440,expectation:'y'}],container_policy:'x',overflow_policy:'x'}));const r=run(quality,p,'responsive','approve','--project-root',p,'--input',f,'--approval-ref','approved');assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('duplicate_viewport_id:same'))});
test('Phase 6 safely migrates the Windows legacy decisions placeholder file into a directory',()=>{const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);const d=path.join(p,'.aledevos','design','decisions');fs.rmSync(d,{recursive:true,force:true});fs.writeFileSync(d,'# UI Decision Records\n\nNo decisions recorded yet.\n','utf8');const r=run(quality,p,'standards','init','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(fs.statSync(d).isDirectory(),true);assert.equal(fs.existsSync(path.join(d,'README.md')),false)});
test('Phase 6 refuses to delete a non-placeholder decisions file on path collision',()=>{const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);const d=path.join(p,'.aledevos','design','decisions');fs.rmSync(d,{recursive:true,force:true});fs.writeFileSync(d,'user data - do not delete','utf8');const r=run(quality,p,'standards','init','--project-root',p);assert.equal(r.status,126,r.stdout+r.stderr);assert.equal(jout(r).status,'UI_DECISIONS_PATH_COLLISION');assert.equal(fs.readFileSync(d,'utf8'),'user data - do not delete')});
test('UI state contract derives DATA_SURFACE baseline deterministically',()=>{const p=init(),x=stateContract(p,true);assert.equal(x.r.status,0,x.r.stdout);const o=JSON.parse(fs.readFileSync(x.out));assert.deepEqual(o.surfaces[0].required_states,['CONTENT','EMPTY','ERROR','LOADING'])});
test('UI state contract verification blocks missing required state evidence',()=>{const p=init(),x=stateContract(p,false);assert.equal(x.r.status,0);const r=run(quality,p,'states','contract-verify','--project-root',p,'--contract',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.startsWith('state_evidence_missing:home-data:')))});
test('complete UI state contract verifies',()=>{const p=init(),x=stateContract(p,true);const r=run(quality,p,'states','contract-verify','--project-root',p,'--contract',x.out);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'UI_STATES_PASS')});
test('inline state evidence bodies are forbidden',()=>{const p=init();const f=w(p,'bad-state.json',JSON.stringify({task_id:'task-1',surfaces:[{id:'x',kind:'STATIC_SURFACE',evidence:[{state:'DEFAULT',evidence_ref:'e/x',content:'secret'}]}]}));const out=path.join(p,'x.json'),r=run(quality,p,'states','seal','--project-root',p,'--input',f,'--out',out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('state_evidence_inline_forbidden:x:DEFAULT'))});
test('UI ADR create and verify are integrity sealed',()=>{const p=init(),x=adr(p);assert.equal(x.r.status,0,x.r.stdout);const v=run(quality,p,'adr','verify','--project-root',p,'--id','UI-ADR-1000');assert.equal(v.status,0);assert.equal(jout(v).active,true)});
test('UI ADR IDs are immutable and duplicate creation is blocked',()=>{const p=init();assert.equal(adr(p).r.status,0);const x=adr(p);assert.notEqual(x.r.status,0);assert.equal(jout(x.r).status,'UI_ADR_ALREADY_EXISTS')});
test('UI ADR supersede keeps history and deactivates old decision',()=>{const p=init();assert.equal(adr(p,'UI-ADR-1000').r.status,0);const x=adr(p,'UI-ADR-1001',{supersedes:'UI-ADR-1000'});assert.equal(x.r.status,0,x.r.stdout);const old=jout(run(quality,p,'adr','verify','--project-root',p,'--id','UI-ADR-1000')),neu=jout(run(quality,p,'adr','verify','--project-root',p,'--id','UI-ADR-1001'));assert.equal(old.active,false);assert.equal(old.superseded_by,'UI-ADR-1001');assert.equal(neu.active,true)});
test('UI ADR record tampering is detected',()=>{const p=init();adr(p);const f=path.join(p,'.aledevos/design/decisions/UI-ADR-1000.json'),o=JSON.parse(fs.readFileSync(f));o.decision='tampered';fs.writeFileSync(f,JSON.stringify(o));const v=run(quality,p,'adr','verify','--project-root',p,'--id','UI-ADR-1000');assert.notEqual(v.status,0);assert.ok(jout(v).errors.includes('adr_record_integrity_mismatch:UI-ADR-1000'))});
test('Phase 6 review blocks while accessibility/responsive policies remain UNSET',()=>{const p=init(),x=createReview(p);assert.notEqual(x.r.status,0);assert.ok(x.o.blockers.some(b=>b.message==='accessibility_policy_not_active'));assert.ok(x.o.blockers.some(b=>b.message==='responsive_policy_not_active'))});
test('complete Phase 6 evidence produces UI_STANDARDS_PASS',()=>{const p=init();activate(p);const x=createReview(p);assert.equal(x.r.status,0,JSON.stringify(x.o));assert.equal(x.o.status,'UI_STANDARDS_PASS');assert.deepEqual(x.o.dimensions,{responsive:'VERIFIED',accessibility:'VERIFIED',states:'VERIFIED'})});
test('missing img alt is a deterministic accessibility blocker',()=>{const p=init();activate(p);w(p,'src/pages/Home.tsx',`export const Home=()=> <img src="x.png" />`);const x=createReview(p);assert.notEqual(x.r.status,0);assert.ok(x.o.blockers.some(b=>b.rule_id==='A11Y_IMG_ALT'))});
test('nonsemantic click target without keyboard affordance is blocked',()=>{const p=init();activate(p);w(p,'src/pages/Home.tsx',`export const Home=()=> <div onClick={()=>1}>Go</div>`);const x=createReview(p);assert.notEqual(x.r.status,0);assert.ok(x.o.blockers.some(b=>b.rule_id==='A11Y_INTERACTIVE_SEMANTICS'))});
test('focus outline removal without visible replacement is blocked',()=>{const p=init();activate(p);w(p,'src/pages/Home.tsx',`export const css='button { outline: none; }'`);const x=createReview(p);assert.notEqual(x.r.status,0);assert.ok(x.o.blockers.some(b=>b.rule_id==='A11Y_FOCUS_VISIBLE'))});
test('min-width above narrowest approved viewport is blocked',()=>{const p=init();activate(p);w(p,'src/pages/Home.tsx',`export const css='.x { min-width: 900px; }'`);const x=createReview(p);assert.notEqual(x.r.status,0);assert.ok(x.o.blockers.some(b=>b.rule_id==='RESPONSIVE_MIN_WIDTH'))});
test('active ADR can approve a deterministic Phase 6 exception',()=>{const p=init();activate(p);assert.equal(adr(p,'UI-ADR-1000').r.status,0);w(p,'src/pages/Home.tsx',`export const css='.x { min-width: 900px; }'`);const x=createReview(p,{exceptions:[{rule_id:'RESPONSIVE_MIN_WIDTH',approval_ref:'UI-ADR-1000',reason:'Approved fixed-width specialist canvas for this surface.'}],adrRefs:['UI-ADR-1000']});assert.equal(x.r.status,0,JSON.stringify(x.o));assert.ok(x.o.warnings.some(b=>b.rule_id==='RESPONSIVE_MIN_WIDTH'))});
test('Phase 6 review tampering is detected',()=>{const p=init();activate(p);const x=createReview(p);const o=JSON.parse(fs.readFileSync(x.out));o.status='UI_STANDARDS_BLOCKED';fs.writeFileSync(x.out,JSON.stringify(o));const v=run(quality,p,'review','verify','--project-root',p,'--report',x.out,'--task-id','task-1');assert.notEqual(v.status,0);assert.ok(jout(v).errors.includes('phase6_review_integrity_mismatch'))});
test('source drift invalidates a sealed Phase 6 review',()=>{const p=init();activate(p);const x=createReview(p);w(p,'src/pages/Home.tsx','export const Home=()=> <main>changed</main>');const v=run(quality,p,'review','verify','--project-root',p,'--report',x.out,'--task-id','task-1');assert.notEqual(v.status,0);assert.ok(jout(v).errors.includes('source_drift:src/pages/Home.tsx'))});
test('phase6 review task mismatch is rejected',()=>{const p=init();activate(p);const x=createReview(p);const v=run(quality,p,'review','verify','--project-root',p,'--report',x.out,'--task-id','other-task');assert.notEqual(v.status,0);assert.ok(jout(v).errors.includes('phase6_review_task_mismatch'))});
test('Design Guardian requires Phase 6 review for evidence schema 1.1',()=>{const p=init();activate(p);w(p,'src/pages/Home.tsx','export const Home=()=> <main />');const e=w(p,'ui-e.json',JSON.stringify({schema_version:'1.1',task_id:'task-1',visual_task:true,changed_files:['src/pages/Home.tsx'],reuse_decisions:[],responsive:{status:'UNVERIFIED',evidence:[]},accessibility:{status:'UNVERIFIED',evidence:[]},states:{status:'UNVERIFIED',covered:[]},interaction:{status:'VERIFIED',evidence:[]},exceptions:[]}));const g=run(review,p,'guardian','review','--project-root',p,'--evidence',e,'--out',path.join(p,'g.json'));assert.notEqual(g.status,0);assert.ok(jout(g).blockers.some(b=>b.message==='phase6_review_required'))});
test('Phase 6 review feeds Guardian and UXUI Judge dimensions for schema 1.1',()=>{const p=init();activate(p);const x=createReview(p);const e=w(p,'ui-e.json',JSON.stringify({schema_version:'1.1',task_id:'task-1',visual_task:true,changed_files:['src/pages/Home.tsx'],reuse_decisions:[],responsive:{status:'UNVERIFIED',evidence:[]},accessibility:{status:'UNVERIFIED',evidence:[]},states:{status:'UNVERIFIED',covered:[]},interaction:{status:'VERIFIED',evidence:[]},exceptions:[],phase6_review_path:'.aledevos/state/uxui/phase6/reviews/task-1.json'}));const gf=path.join(p,'g.json'),jf=path.join(p,'j.json');const g=run(review,p,'guardian','review','--project-root',p,'--evidence',e,'--out',gf);assert.equal(g.status,0,g.stdout);assert.equal(jout(g).checks.phase6_review_valid,true);const j=run(review,p,'judge','score','--project-root',p,'--evidence',e,'--guardian',gf,'--out',jf);assert.equal(j.status,0,j.stdout);assert.equal(jout(j).score,100);assert.equal(jout(j).verdict,'PASS')});
test('Phase 6 schemas parse cleanly',()=>{for(const f of ['accessibility-policy.schema.json','responsive-policy.schema.json','ui-states-catalog.schema.json','ui-state-contract.schema.json','ui-decision-record.schema.json','ui-decision-index.schema.json','ui-standards-review.schema.json','ui-change-evidence.schema.json'])assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('uxui/schemas',f))))});
test('Phase 6 contract preserves boundary with Visual QA',()=>{const t=fs.readFileSync('core/design/contracts/ACCESSIBILITY_RESPONSIVE_STATES_UI_ADRS.md','utf8');assert.match(t,/Visual QA/i);assert.match(t,/must never be invented/i);assert.match(t,/supersede rather than rewrite/i)});
test('UI-relevant agents carry Phase 6 discipline',()=>{for(const base of ['core/agents','adapters/opencode/.opencode/agents'])for(const n of ['orchestrator','researcher','architect','auditor','builder','editor-frontend','verifier','design-system-guardian','judge-uxui','judge-quality','repairer'])assert.match(fs.readFileSync(path.join(base,`${n}.md`),'utf8'),/UX\/UI Phase 6 discipline/)});
test('OpenCode Guardian and UXUI Judge remain read-only and get narrow Phase 6 verification commands',()=>{for(const n of ['design-system-guardian','judge-uxui']){const t=fs.readFileSync(path.join('adapters/opencode/.opencode/agents',`${n}.md`),'utf8');assert.match(t,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(t,/ui-quality\.mjs standards verify/);assert.match(t,/ui-quality\.mjs review verify/)}const g=fs.readFileSync('adapters/opencode/.opencode/agents/design-system-guardian.md','utf8');assert.match(g,/ui-quality\.mjs review create/)});
test('installer deploys Phase 6 runtime, state dirs and truthful UNSET initialization',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/ui-quality\.mjs/);assert.match(t,/phase6\\reviews/);assert.match(t,/phase6\\state-contracts/);assert.match(t,/standards init --project-root/);assert.match(t,/v1\.21 UXUI-P6/)});
