import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'),boot=path.resolve('uxui/engine/design-bootstrap.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});const jout=r=>JSON.parse(r.stdout);const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p3-'));const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};const h=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function initGreen(){const p=tmp();w(p,'package.json','{}');let r=run(ux,p,'context','init','--project-root',p);assert.equal(r.status,0,r.stderr);return p}
function initBrown(hybrid=false){const p=tmp();w(p,'src/components/Button.tsx','export const Button=()=>null');w(p,'src/pages/Home.tsx','export const Home=()=>null');w(p,'src/styles/theme.css',`:root{--space-2:8px;--brand:#3366ff;--radius:8px}\n.card{color:#3366ff;padding:8px;border-radius:8px;box-shadow:0 2px 8px #0003;font-family:Inter,sans-serif;transition:opacity 160ms ease}\n@media (max-width: 768px){.card{padding:4px}}`);if(hybrid)w(p,'request.json',JSON.stringify({visual_intent:'major_visual_overhaul'}));const args=['context','init','--project-root',p];if(hybrid)args.push('--request',path.join(p,'request.json'));const r=run(ux,p,...args);assert.equal(r.status,0,r.stderr);return p}

test('GREENFIELD plan routes Design Genesis through on-demand specialist skills',()=>{const p=initGreen();const r=run(boot,p,'workflow','plan','--project-root',p,'--task-id','g1');assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.workflow,'DESIGN_GENESIS');assert.ok(o.skill_route_requests.length>=3);assert.ok(o.skill_route_requests.some(x=>x.preferred_skills.includes('brand')));assert.ok(o.invariants.includes('MISSING_SKILLS_USE_SAFE_ACQUISITION'));assert.equal(o.canonicalization.automatic,false)});
test('BROWNFIELD plan begins with deterministic discovery before interpretation',()=>{const p=initBrown();const o=jout(run(boot,p,'workflow','plan','--project-root',p,'--task-id','b1'));assert.equal(o.workflow,'DESIGN_SYSTEM_DISCOVERY');assert.equal(o.stages[0].id,'deterministic-discovery');assert.equal(o.stages[0].preferred_skills.length,0)});
test('HYBRID plan preserves existing evidence and adds new visual direction',()=>{const p=initBrown(true);const o=jout(run(boot,p,'workflow','plan','--project-root',p,'--task-id','h1'));assert.equal(o.workflow,'DESIGN_AUDIT_AND_CONSOLIDATE');assert.ok(o.stages.some(x=>x.id==='preserve-and-audit'));assert.ok(o.stages.some(x=>x.id==='new-visual-direction'))});
test('workflow plan is sealed and context drift invalidates it',()=>{const p=initGreen(),f=path.join(p,'plan.json');run(boot,p,'workflow','plan','--project-root',p,'--task-id','g2','--out',f);let r=run(boot,p,'workflow','verify','--project-root',p,'--plan',f);assert.equal(r.status,0);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));m.context_version++;fs.writeFileSync(path.join(p,'.aledevos/design/design-context.json'),JSON.stringify(m));r=run(boot,p,'workflow','verify','--project-root',p,'--plan',f);assert.notEqual(r.status,0)});
test('brownfield discovery records design evidence without canonicalizing it',()=>{const p=initBrown();const r=run(boot,p,'discovery','scan','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.source,'verified_runtime_discovery');assert.ok(o.aggregates.colors.some(x=>x.value.toLowerCase()==='#3366ff'));assert.ok(o.aggregates.css_variables.some(x=>x.value.includes('--brand')));assert.ok(o.component_candidates.some(x=>x.endsWith('Button.tsx')));const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.sections.tokens.status,'UNSET')});
test('discovery source drift is detected',()=>{const p=initBrown(),f=path.join(p,'d.json');run(boot,p,'discovery','scan','--project-root',p,'--out',f);w(p,'src/styles/theme.css','changed');const r=run(boot,p,'discovery','verify','--project-root',p,'--artifact',f);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.includes('source_drift')))});
test('greenfield deterministic design discovery is rejected as not applicable',()=>{const p=initGreen();const r=run(boot,p,'discovery','scan','--project-root',p);assert.equal(r.status,65)});
test('design evidence cannot become canonical without explicit approval',()=>{const p=initGreen(),a=w(p,'artifacts/brand.md','# Brand\nVerified proposal\n'),q=w(p,'e.json',JSON.stringify({schema_version:'1.0',task_id:'e1',source_kind:'verified_skill_output',source_ref:'skill:e1',artifacts:[{section:'brand',path:'artifacts/brand.md',sha256:h(a)}]}));const r=run(boot,p,'evidence','apply','--project-root',p,'--input',q);assert.equal(r.status,66);assert.ok(jout(r).errors.includes('explicit_approval_required'))});
test('approved evidence updates canonical Design Context and keeps integrity valid',()=>{const p=initGreen(),a=w(p,'artifacts/brand.md','# Brand\nHuman-approved foundation\n'),q=w(p,'e.json',JSON.stringify({schema_version:'1.0',task_id:'e2',source_kind:'human_approved_design_context',source_ref:'review:e2',artifacts:[{section:'brand',path:'artifacts/brand.md',sha256:h(a)}]}));let r=run(boot,p,'evidence','apply','--project-root',p,'--input',q,'--approve');assert.equal(r.status,0,r.stderr);r=run(ux,p,'context','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.sections.brand.status,'PRESENT');assert.equal(m.sections.brand.source,'human_approved_design_context')});
test('artifact hash mismatch blocks canonicalization',()=>{const p=initGreen(),a=w(p,'artifacts/brand.md','# Brand'),q=w(p,'e.json',JSON.stringify({schema_version:'1.0',task_id:'e3',source_kind:'human_approved_design_context',artifacts:[{section:'brand',path:'artifacts/brand.md',sha256:'0'.repeat(64)}]}));const r=run(boot,p,'evidence','apply','--project-root',p,'--input',q,'--approve');assert.equal(r.status,66);assert.ok(jout(r).errors.includes('artifact_hash_mismatch:brand'))});
test('Phase 3 cannot bypass Component Registry governance',()=>{const p=initGreen(),a=w(p,'artifacts/c.json','{}'),q=w(p,'e.json',JSON.stringify({schema_version:'1.0',task_id:'e4',source_kind:'human_approved_design_context',artifacts:[{section:'component_registry',path:'artifacts/c.json',sha256:h(a)}]}));const r=run(boot,p,'evidence','apply','--project-root',p,'--input',q,'--approve');assert.equal(r.status,66);assert.ok(jout(r).errors.includes('section_not_canonicalizable:component_registry'))});
test('evidence source must remain project-local',()=>{const p=initGreen(),outside=w(tmp(),'brand.md','# x'),q=w(p,'e.json',JSON.stringify({schema_version:'1.0',task_id:'e5',source_kind:'human_approved_design_context',artifacts:[{section:'brand',path:outside,sha256:h(outside)}]}));const r=run(boot,p,'evidence','validate','--project-root',p,'--input',q);assert.equal(r.status,73);assert.ok(jout(r).errors.includes('artifact_external:brand'))});
test('Phase 3 policy explicitly uses Safe Acquisition for missing skills',()=>{const p=JSON.parse(fs.readFileSync('uxui/policies/uxui-policy.json','utf8'));assert.equal(p.phase3.missing_skill_policy,'ACQUIRE_IF_TRUSTED_ELSE_APPROVAL');assert.equal(p.phase3.skill_outputs_are_proposals,true);assert.equal(p.phase3.canonicalization_requires_approval,true)});
test('Phase 3 contract uses Skills but forbids automatic canonicalization',()=>{const t=fs.readFileSync('core/design/contracts/DESIGN_GENESIS_DISCOVERY.md','utf8');assert.match(t,/Safe Acquisition/i);assert.match(t,/never becomes canonical/i);assert.match(t,/Deterministic repository discovery happens before model interpretation/i)});
test('Phase 3 schemas parse cleanly',()=>{for(const f of ['design-workflow-plan.schema.json','design-discovery-evidence.schema.json','design-evidence-pack.schema.json'])assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('uxui/schemas',f),'utf8'))) });
test('workflow plan contains no Skill instruction bodies',()=>{const p=initGreen(),o=jout(run(boot,p,'workflow','plan','--project-root',p,'--task-id','g3'));const s=JSON.stringify(o);assert.doesNotMatch(s,/SKILL\.md|instruction_body|full_prompt|transcript/i)});
test('discovery is bounded by configured file and byte limits',()=>{const p=JSON.parse(fs.readFileSync('uxui/policies/uxui-policy.json','utf8'));assert.ok(p.phase3.discovery.max_files>0);assert.ok(p.phase3.discovery.max_total_bytes>0);assert.ok(p.phase3.discovery.max_single_file_bytes>0)});
test('installer deploys Phase 3 engine and state directories',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/design-bootstrap\.mjs/);assert.match(t,/state\\uxui\\phase3/);assert.match(t,/UXUI-P[34]/)});
test('UI-relevant Core and OpenCode agents carry Phase 3 discipline',()=>{for(const base of ['core/agents','adapters/opencode/.opencode/agents'])for(const n of ['orchestrator','researcher','architect','auditor','builder','editor-frontend','verifier','judge-quality','repairer'])assert.match(fs.readFileSync(path.join(base,`${n}.md`),'utf8'),/UX\/UI Phase 3/) });
