import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const ux=path.resolve('uxui/engine/uxui.mjs');
const cr=path.resolve('uxui/engine/component-registry.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p2-'));
const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
const j=(p,r,o)=>w(p,r,JSON.stringify(o,null,2));
function project(){const p=tmp();w(p,'package.json','{}');let r=run(ux,p,'context','init','--project-root',p);assert.equal(r.status,0,r.stderr);return p}
function init(p){const r=run(cr,p,'registry','init','--project-root',p);assert.equal(r.status,0,r.stderr);return r}
function buttonInput(extra={}){return {name:'Button',canonical_path:'src/components/Button.tsx',category:'control',capabilities:['action.trigger','form.submit'],variants:['primary','secondary'],aliases:['ActionButton'],ownership:'GLOBAL',domain:null,reusable:true,source:'existing_canonical_design_system',notes:'Existing canonical design-system button.',...extra}}
function bootstrapButton(p,extra={}){w(p,'src/components/Button.tsx','export const Button=()=>null\n');init(p);const f=j(p,'button.json',buttonInput(extra));const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,0,r.stderr);return jout(r)}
function request(p,o,name='request.json'){return j(p,name,o)}

test('registry init upgrades Phase 1 UNSET skeleton and preserves Design Context validity',()=>{const p=project();let r=run(cr,p,'registry','init','--project-root',p);assert.equal(r.status,0,r.stderr);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/component-registry.json'),'utf8'));assert.equal(reg.status,'PRESENT');assert.equal(reg.policy,'REUSE_BEFORE_CREATE');assert.deepEqual(reg.components,[]);r=run(ux,p,'context','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr)});

test('discovery finds component candidates but never auto-registers them',()=>{const p=project();w(p,'src/components/Button.tsx','x');w(p,'src/components/Input.test.tsx','x');w(p,'src/pages/Home.tsx','x');w(p,'node_modules/lib/components/Bad.tsx','x');init(p);const r=run(cr,p,'registry','discover','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.auto_registered,false);assert.deepEqual(o.candidates.map(x=>x.path),['src/components/Button.tsx']);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/component-registry.json'),'utf8'));assert.equal(reg.components.length,0)});

test('runtime-discovered/existing component registration requires explicit bootstrap approval',()=>{const p=project();w(p,'src/components/Button.tsx','x');init(p);const f=j(p,'b.json',buttonInput({source:'verified_runtime_discovery'}));let r=run(cr,p,'registry','register','--project-root',p,'--input',f);assert.equal(r.status,47);assert.ok(jout(r).errors.includes('existing_candidate_requires_approval'));r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,0,r.stderr)});

test('bootstrap registration stores canonical source hash and verifies cleanly',()=>{const p=project();bootstrapButton(p);const r=run(cr,p,'registry','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr);const reg=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/component-registry.json'),'utf8'));assert.match(reg.components[0].source_sha256,/^[a-f0-9]{64}$/);assert.match(reg.integrity_sha256,/^[a-f0-9]{64}$/)});

test('duplicate canonical names and paths are blocked',()=>{const p=project();bootstrapButton(p);w(p,'src/components/Button2.tsx','x');const f=j(p,'dup.json',buttonInput({component_id:'component:button2',canonical_path:'src/components/Button2.tsx',aliases:[]}));const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,48)});

test('alias collision is blocked',()=>{const p=project();bootstrapButton(p);w(p,'src/components/Link.tsx','x');const f=j(p,'link.json',{name:'Link',canonical_path:'src/components/Link.tsx',category:'navigation',capabilities:['navigation.link'],variants:[],aliases:['ActionButton'],ownership:'GLOBAL',reusable:true,source:'existing_canonical_design_system'});const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,49)});

test('canonical source drift invalidates registry',()=>{const p=project();bootstrapButton(p);fs.appendFileSync(path.join(p,'src/components/Button.tsx'),'// changed\n');const r=run(cr,p,'registry','verify','--project-root',p);assert.equal(r.status,56);assert.ok(jout(r).errors.some(x=>x.startsWith('canonical_source_drift:')))});

test('approved canonical sync requires reason and restores validity',()=>{const p=project();bootstrapButton(p);fs.appendFileSync(path.join(p,'src/components/Button.tsx'),'// approved variant\n');let r=run(cr,p,'registry','sync','--project-root',p,'--component-id','component:button');assert.equal(r.status,50);r=run(cr,p,'registry','sync','--project-root',p,'--component-id','component:button','--reason','approved canonical variant extension');assert.equal(r.status,0,r.stderr);r=run(cr,p,'registry','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr)});

test('exact canonical match returns REUSE_CANONICAL',()=>{const p=project();bootstrapButton(p);const f=request(p,{requested_name:'Button',category:'control',required_capabilities:['action.trigger'],required_variants:['primary'],proposed_path:'src/components/Button.tsx'});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',f);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.action,'REUSE_CANONICAL');assert.equal(o.target_component_id,'component:button')});

test('aliases participate in canonical reuse',()=>{const p=project();bootstrapButton(p);const f=request(p,{requested_name:'ActionButton',required_capabilities:['action.trigger'],required_variants:['secondary']});const o=jout(run(cr,p,'reuse','decide','--project-root',p,'--request',f));assert.equal(o.action,'REUSE_CANONICAL')});

test('missing variant routes to EXTEND_CANONICAL rather than duplicate creation',()=>{const p=project();bootstrapButton(p);const f=request(p,{requested_name:'Button',required_capabilities:['action.trigger'],required_variants:['danger']});const o=jout(run(cr,p,'reuse','decide','--project-root',p,'--request',f));assert.equal(o.action,'EXTEND_CANONICAL');assert.deepEqual(o.missing_variants,['danger']);assert.equal(o.canonical_path,'src/components/Button.tsx')});

test('missing capability on named canonical component routes to EXTEND_CANONICAL',()=>{const p=project();bootstrapButton(p);const f=request(p,{requested_name:'Button',required_capabilities:['loading.state'],required_variants:[]});const o=jout(run(cr,p,'reuse','decide','--project-root',p,'--request',f));assert.equal(o.action,'EXTEND_CANONICAL');assert.deepEqual(o.missing_capabilities,['loading.state'])});

test('page-local fork is deterministically blocked when canonical component exists',()=>{const p=project();bootstrapButton(p);const f=request(p,{requested_name:'Button',required_capabilities:['action.trigger'],required_variants:['primary'],proposed_path:'src/pages/checkout/Button.tsx'});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',f);assert.equal(r.status,57);assert.equal(jout(r).action,'BLOCK_LOCAL_FORK')});

test('new reusable component without justification is blocked',()=>{const p=project();init(p);const f=request(p,{requested_name:'Popover',category:'overlay',required_capabilities:['overlay.anchor'],proposed_path:'src/components/Popover.tsx',reusable:true});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',f);assert.equal(r.status,57);assert.equal(jout(r).action,'CREATE_BLOCKED_JUSTIFICATION_REQUIRED')});

test('new reusable component outside canonical root is blocked even with justification',()=>{const p=project();init(p);const f=request(p,{requested_name:'Popover',category:'overlay',required_capabilities:['overlay.anchor'],proposed_path:'src/pages/home/Popover.tsx',reusable:true,justification:'No existing overlay component covers anchored popovers.'});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',f);assert.equal(r.status,57);assert.equal(jout(r).action,'CREATE_BLOCKED_NONCANONICAL_PATH')});

test('justified new canonical component gets CREATE_NEW_JUSTIFIED',()=>{const p=project();init(p);const f=request(p,{requested_name:'Popover',category:'overlay',required_capabilities:['overlay.anchor'],proposed_path:'src/components/Popover.tsx',reusable:true,justification:'No existing canonical overlay component covers anchored contextual popovers.'});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',f);assert.equal(r.status,0,r.stderr);assert.equal(jout(r).action,'CREATE_NEW_JUSTIFIED')});

test('new component registration fails closed without prior creation decision',()=>{const p=project();init(p);w(p,'src/components/Popover.tsx','x');const f=j(p,'pop.json',{name:'Popover',canonical_path:'src/components/Popover.tsx',category:'overlay',capabilities:['overlay.anchor'],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'human_approved_design_context'});const r=run(cr,p,'registry','register','--project-root',p,'--input',f);assert.equal(r.status,47);assert.ok(jout(r).errors.includes('creation_decision_required'))});

test('new component registers only with matching sealed CREATE_NEW_JUSTIFIED decision',()=>{const p=project();init(p);const req=request(p,{requested_name:'Popover',category:'overlay',required_capabilities:['overlay.anchor'],proposed_path:'src/components/Popover.tsx',reusable:true,justification:'No canonical component provides anchored contextual overlay behavior.'});const decision=path.join(p,'decision.json');let r=run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',decision);assert.equal(r.status,0,r.stderr);w(p,'src/components/Popover.tsx','export const Popover=()=>null');const f=j(p,'pop.json',{name:'Popover',canonical_path:'src/components/Popover.tsx',category:'overlay',capabilities:['overlay.anchor'],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'human_approved_design_context'});r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--decision',decision);assert.equal(r.status,0,r.stdout+r.stderr);r=run(cr,p,'registry','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr)});

test('creation decision path mismatch blocks registration',()=>{const p=project();init(p);const req=request(p,{requested_name:'Popover',category:'overlay',required_capabilities:['overlay.anchor'],proposed_path:'src/components/Popover.tsx',reusable:true,justification:'No canonical component provides anchored contextual overlay behavior.'});const decision=path.join(p,'decision.json');run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',decision);w(p,'src/components/Flyout.tsx','x');const f=j(p,'fly.json',{name:'Flyout',canonical_path:'src/components/Flyout.tsx',category:'overlay',capabilities:['overlay.anchor'],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'human_approved_design_context'});const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--decision',decision);assert.equal(r.status,47);assert.ok(jout(r).errors.includes('creation_decision_path_mismatch'))});

test('tampered reuse decision is rejected',()=>{const p=project();bootstrapButton(p);const req=request(p,{requested_name:'Button',required_capabilities:['action.trigger']});const d=path.join(p,'d.json');run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',d);const o=JSON.parse(fs.readFileSync(d,'utf8'));o.action='CREATE_NEW_JUSTIFIED';fs.writeFileSync(d,JSON.stringify(o));const r=run(cr,p,'reuse','verify','--project-root',p,'--decision',d);assert.equal(r.status,59);assert.ok(jout(r).errors.includes('decision_integrity_mismatch'))});

test('registry change invalidates an older reuse decision',()=>{const p=project();bootstrapButton(p);const req=request(p,{requested_name:'Button',required_capabilities:['action.trigger']});const d=path.join(p,'d.json');run(cr,p,'reuse','decide','--project-root',p,'--request',req,'--out',d);w(p,'src/components/Input.tsx','x');const f=j(p,'input.json',{name:'Input',canonical_path:'src/components/Input.tsx',category:'input',capabilities:['input.text'],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'existing_canonical_design_system'});run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');const r=run(cr,p,'reuse','verify','--project-root',p,'--decision',d);assert.equal(r.status,59);assert.ok(jout(r).errors.includes('registry_drift_since_decision'))});

test('equally ranked capability matches require review, not guessing',()=>{const p=project();init(p);for(const [name,file] of [['Badge','Badge.tsx'],['Pill','Pill.tsx']]){w(p,`src/components/${file}`,'x');const f=j(p,`${name}.json`,{name,canonical_path:`src/components/${file}`,category:'status',capabilities:['status.display'],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'existing_canonical_design_system'});const rr=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(rr.status,0,rr.stdout+rr.stderr)}const req=request(p,{category:'status',required_capabilities:['status.display']});const r=run(cr,p,'reuse','decide','--project-root',p,'--request',req);assert.equal(r.status,0,r.stderr);assert.equal(jout(r).action,'REVIEW_REQUIRED_AMBIGUOUS');assert.equal(jout(r).status,'REVIEW_REQUIRED')});

test('global reusable component outside canonical roots cannot be registered',()=>{const p=project();init(p);w(p,'src/features/a/Thing.tsx','x');const f=j(p,'thing.json',{name:'Thing',canonical_path:'src/features/a/Thing.tsx',category:'misc',capabilities:[],variants:[],aliases:[],ownership:'GLOBAL',reusable:true,source:'existing_canonical_design_system'});const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,47);assert.ok(jout(r).errors.includes('global_reusable_component_requires_canonical_root'))});

test('domain-owned component can be explicitly registered outside global canonical roots',()=>{const p=project();init(p);w(p,'src/features/billing/InvoiceRow.tsx','x');const f=j(p,'row.json',{name:'InvoiceRow',canonical_path:'src/features/billing/InvoiceRow.tsx',category:'billing',capabilities:['invoice.row'],variants:[],aliases:[],ownership:'DOMAIN',domain:'billing',reusable:true,source:'existing_canonical_design_system'});const r=run(cr,p,'registry','register','--project-root',p,'--input',f,'--approve-existing');assert.equal(r.status,0,r.stdout+r.stderr)});

test('registry mutation keeps Design Context integrity synchronized',()=>{const p=project();bootstrapButton(p);let r=run(ux,p,'context','verify','--project-root',p);assert.equal(r.status,0,r.stdout+r.stderr);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.sections.component_registry.status,'PRESENT');assert.equal(m.context_version,2)});

test('tampering Phase 1 registry skeleton before Phase 2 init is rejected',()=>{const p=project();fs.writeFileSync(path.join(p,'.aledevos/design/component-registry.json'),'{"tampered":true}\n');const r=run(cr,p,'registry','init','--project-root',p);assert.equal(r.status,42)});

test('Phase 2 schemas and policies parse cleanly',()=>{for(const f of fs.readdirSync('uxui/schemas').filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('uxui/schemas',f),'utf8')));assert.doesNotThrow(()=>JSON.parse(fs.readFileSync('core/design/ui-reuse-policy.json','utf8')))});

test('Phase 2 contract contains reuse, extension, justified creation and local-fork denial',()=>{const t=fs.readFileSync('core/design/contracts/COMPONENT_REGISTRY_REUSE.md','utf8');for(const x of ['REUSE_CANONICAL','EXTEND_CANONICAL','CREATE_NEW_JUSTIFIED','BLOCK_LOCAL_FORK'])assert.match(t,new RegExp(x));assert.match(t,/never auto-registers/i)});

test('UI-relevant Core and OpenCode agents carry Phase 2 discipline',()=>{for(const base of ['core/agents','adapters/opencode/.opencode/agents'])for(const n of ['orchestrator','architect','auditor','builder','editor-frontend','verifier','judge-quality','repairer'])assert.match(fs.readFileSync(path.join(base,`${n}.md`),'utf8'),/UX\/UI Phase 2/)});

test('installer deploys and initializes Component Registry runtime',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/component-registry\.mjs/);assert.match(t,/registry init --project-root/);assert.match(t,/registry verify --project-root/);assert.match(t,/UXUI-P[234]/)});
