import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const runtime=path.resolve('uxui/engine/uxui.mjs');
const run=(cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-uxui-p1-'));
const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8')};

function green(){const p=tmp();w(p,'package.json','{}');return p}
function brown(){const p=tmp();w(p,'src/components/Button.tsx','export const Button=()=>null');w(p,'src/pages/Home.tsx','export const Home=()=>null');w(p,'src/styles/app.css','body{}');return p}

 test('greenfield repo is detected deterministically',()=>{const p=green();const r=run(p,'mode','detect','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.mode,'GREENFIELD');assert.equal(o.workflow,'DESIGN_GENESIS');assert.equal(o.decision_source,'DETERMINISTIC_REPO_SCAN')});
 test('existing UI becomes brownfield',()=>{const p=brown();const r=run(p,'mode','detect','--project-root',p);assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.mode,'BROWNFIELD');assert.equal(o.workflow,'DESIGN_SYSTEM_DISCOVERY');assert.ok(o.evidence.ui_file_count>=2)});
 test('hybrid requires explicit redesign intent',()=>{const p=brown();w(p,'request.json',JSON.stringify({visual_intent:'major_visual_overhaul'}));const r=run(p,'mode','detect','--project-root',p,'--request',path.join(p,'request.json'));assert.equal(r.status,0,r.stderr);const o=jout(r);assert.equal(o.mode,'HYBRID');assert.equal(o.workflow,'DESIGN_AUDIT_AND_CONSOLIDATE');assert.equal(o.decision_source,'EXPLICIT_INTENT')});
 test('repo size alone never guesses hybrid',()=>{const p=brown();for(let i=0;i<20;i++)w(p,`src/components/C${i}.tsx`,'x');const r=run(p,'mode','detect','--project-root',p);assert.equal(jout(r).mode,'BROWNFIELD')});
 test('greenfield override conflicts with existing UI unless explicitly allowed',()=>{const p=brown();let r=run(p,'mode','detect','--project-root',p,'--override','GREENFIELD');assert.equal(r.status,23);assert.equal(jout(r).status,'MODE_OVERRIDE_CONFLICT');r=run(p,'mode','detect','--project-root',p,'--override','GREENFIELD','--allow-override');assert.equal(r.status,0,r.stderr);assert.equal(jout(r).decision_source,'HUMAN_OVERRIDE')});
 test('node_modules and runtime state are ignored as evidence',()=>{const p=green();w(p,'node_modules/x/Button.tsx','x');w(p,'.aledevos/old/Page.tsx','x');const r=run(p,'mode','detect','--project-root',p);assert.equal(jout(r).mode,'GREENFIELD')});
 test('mode decision integrity is sealed',()=>{const p=green();const f=path.join(p,'d.json');let r=run(p,'mode','detect','--project-root',p,'--out',f);assert.equal(r.status,0);const o=JSON.parse(fs.readFileSync(f,'utf8'));assert.match(o.integrity_sha256,/^[a-f0-9]{64}$/);o.mode='BROWNFIELD';fs.writeFileSync(f,JSON.stringify(o));r=run(p,'context','init','--project-root',p,'--decision',f);assert.equal(r.status,27)});
 test('context init creates canonical skeleton without inventing design decisions',()=>{const p=green();const r=run(p,'context','init','--project-root',p);assert.equal(r.status,0,r.stderr);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.project_mode,'GREENFIELD');for(const s of Object.values(m.sections))assert.equal(s.status,'UNSET');const brand=fs.readFileSync(path.join(p,'.aledevos/design/brand.md'),'utf8');assert.match(brand,/Status: UNSET/);assert.doesNotMatch(brand,/#ffffff|Inter|Roboto|primary color/i)});

 test('decisions canonical section is created as a directory without path-separator heuristics',()=>{const p=green();const r=run(p,'context','init','--project-root',p);assert.equal(r.status,0,r.stderr);const d=path.join(p,'.aledevos','design','decisions');assert.equal(fs.statSync(d).isDirectory(),true);assert.equal(fs.existsSync(path.join(d,'README.md')),true);const src=fs.readFileSync('uxui/engine/uxui.mjs','utf8');assert.match(src,/directorySections=new Set\(\['decisions'\]\)/);assert.doesNotMatch(src,/target\.endsWith\('\/'\)/)});
 test('design context includes every canonical section',()=>{const p=green();run(p,'context','init','--project-root',p);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));const expected=['product_personality','brand','ux_principles','design_system','tokens','typography','color_system','spacing','radii','shadows','layouts','responsive','motion_language','interaction_patterns','accessibility','iconography','component_registry','decisions'];for(const k of expected)assert.ok(m.sections[k],k)});
 test('tokens and component registry start empty and explicit UNSET',()=>{const p=green();run(p,'context','init','--project-root',p);const t=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/tokens.json'),'utf8'));const c=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/component-registry.json'),'utf8'));assert.equal(t.status,'UNSET');assert.deepEqual(t.tokens,{});assert.equal(c.status,'UNSET');assert.deepEqual(c.components,[])});
 test('context source precedence is fixed and human evidence wins',()=>{const p=green();run(p,'context','init','--project-root',p);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.source_precedence[0],'human_approved_design_context');assert.equal(m.source_precedence.at(-1),'model_inference')});
 test('skill policy is on-demand and acquisition aware',()=>{const p=green();run(p,'context','init','--project-root',p);const m=JSON.parse(fs.readFileSync(path.join(p,'.aledevos/design/design-context.json'),'utf8'));assert.equal(m.skill_policy.on_demand,true);assert.equal(m.skill_policy.acquire_missing,true);assert.equal(m.skill_policy.untrusted_requires_approval,true);assert.equal(m.skill_policy.phase1_instruction_loading,false)});
 test('context verify passes for untouched context',()=>{const p=green();run(p,'context','init','--project-root',p);const r=run(p,'context','verify','--project-root',p);assert.equal(r.status,0,r.stderr);assert.equal(jout(r).valid,true)});
 test('context tampering is detected',()=>{const p=green();run(p,'context','init','--project-root',p);const f=path.join(p,'.aledevos/design/design-context.json');const m=JSON.parse(fs.readFileSync(f,'utf8'));m.project_mode='BROWNFIELD';fs.writeFileSync(f,JSON.stringify(m));const r=run(p,'context','verify','--project-root',p);assert.equal(r.status,28);assert.ok(jout(r).errors.includes('context_integrity_mismatch'))});
 test('mode decision tampering is detected',()=>{const p=green();run(p,'context','init','--project-root',p);const f=path.join(p,'.aledevos/design/project-mode.json');const m=JSON.parse(fs.readFileSync(f,'utf8'));m.workflow='DESIGN_SYSTEM_DISCOVERY';fs.writeFileSync(f,JSON.stringify(m));const r=run(p,'context','verify','--project-root',p);assert.equal(r.status,28);assert.ok(jout(r).errors.includes('mode_integrity_mismatch'))});

 test('section artifact tampering is detected independently of manifest integrity',()=>{const p=green();run(p,'context','init','--project-root',p);fs.appendFileSync(path.join(p,'.aledevos/design/brand.md'),'invented drift\n');const r=run(p,'context','verify','--project-root',p);assert.equal(r.status,28);assert.ok(jout(r).errors.includes('section_integrity_mismatch:brand'))});
 test('existing design context is preserved by default',()=>{const p=green();let r=run(p,'context','init','--project-root',p);assert.equal(r.status,0);r=run(p,'context','init','--project-root',p);assert.equal(r.status,24)});
 test('status reports unset sections and does not load skills',()=>{const p=green();run(p,'context','init','--project-root',p);const r=run(p,'context','status','--project-root',p);const o=jout(r);assert.equal(o.section_status.UNSET,18);assert.equal(o.skill_instruction_loading,false)});
 test('policy and schemas parse cleanly',()=>{assert.doesNotThrow(()=>JSON.parse(fs.readFileSync('uxui/policies/uxui-policy.json','utf8')));for(const f of fs.readdirSync('uxui/schemas').filter(x=>x.endsWith('.json')))assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('uxui/schemas',f),'utf8')))});
 test('phase 1 contract explicitly forbids invention and routes missing skills through acquisition',()=>{const t=fs.readFileSync('core/design/contracts/PROJECT_MODE_DESIGN_CONTEXT.md','utf8');assert.match(t,/Never fabricate/i);assert.match(t,/trusted\/allowlisted sources may auto-acquire/i);assert.match(t,/untrusted sources require approval/i)});
 test('installer deploys UXUI runtime, policy, schemas and templates',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(t,/uxui\\engine\\uxui\.mjs/);assert.match(t,/uxui-policy\.json/);assert.match(t,/state\\uxui/);assert.match(t,/UXUI-P/)});
 test('Phase 1 never loads external skill instruction bodies',()=>{const t=fs.readFileSync('uxui/policies/uxui-policy.json','utf8');assert.match(t,/phase1_never_loads_skill_instruction_bodies/);assert.doesNotMatch(fs.readFileSync('uxui/engine/uxui.mjs','utf8'),/SKILL\.md/)});
