import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';

const ux=path.resolve('uxui/engine/uxui.mjs');
const quality=path.resolve('uxui/engine/ui-quality.mjs');
const vqa=path.resolve('visualqa/engine/visualqa.mjs');
const run=(runtime,cwd,...a)=>spawnSync(process.execPath,[runtime,...a],{cwd,encoding:'utf8'});
const jout=r=>JSON.parse(r.stdout);
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-vqa-p1-'));
const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
const pngBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
const wpng=(p,r)=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,pngBytes);return f};
function init({active=true}={}){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,'context','init','--project-root',p).status,0);assert.equal(run(quality,p,'standards','init','--project-root',p).status,0);if(active){const f=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow.'},{id:'wide',width:1440,height:900,expectation:'Use approved wide layout.'}],container_policy:'Use canonical containers.',overflow_policy:'No horizontal overflow unless approved.',source_ref:'UI-ADR-1001'}));const r=run(quality,p,'responsive','approve','--project-root',p,'--input',f,'--approval-ref','human:approved');assert.equal(r.status,0,r.stdout)}w(p,'src/pages/Home.tsx','export const Home=()=> <main>Home</main>');return p}
function request(p,overrides={}){const base={task_id:'task-ui-001',base_url:'http://127.0.0.1:3000',changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route:'/',viewport_ids:['narrow','wide'],states:['DEFAULT'],state_contract_path:null}]};const q={...base,...overrides};return w(p,'capture-request.json',JSON.stringify(q))}
function mkPlan(p,overrides={}){const input=request(p,overrides),out=path.join(p,'.aledevos/state/visualqa/phase1/plans/task-ui-001.json');const r=run(vqa,p,'plan','create','--project-root',p,'--input',input,'--out',out);return {r,out,o:r.stdout?jout(r):null}}
function captureResults(p,plan,opts={}){const results=[];for(const c of plan.cases){if(opts.skip===c.case_id)continue;const rel=opts.pathOverride?.[c.case_id]||c.expected_screenshot_path;if(!opts.noWrite?.includes(c.case_id)){if(opts.nonPng===c.case_id)w(p,rel,'not a png');else wpng(p,rel)}results.push({case_id:c.case_id,screenshot_path:rel})}for(const x of opts.extra||[])results.push(x);return w(p,'capture-results.json',JSON.stringify({task_id:opts.taskId||plan.task_id,results}))}
function seal(p,planInfo,opts={}){const input=captureResults(p,planInfo.o.plan,opts),out=path.join(p,'.aledevos/state/visualqa/phase1/runs/task-ui-001.json');const r=run(vqa,p,'run','seal','--project-root',p,'--plan',planInfo.out,'--input',input,'--out',out);return {r,out,o:r.stdout?jout(r):null}}

test('system status is truthful before responsive policy activation',()=>{const p=init({active:false});const r=run(vqa,p,'system','status','--project-root',p);assert.equal(r.status,0);const o=jout(r);assert.equal(o.responsive_status,'UNSET');assert.equal(o.render_execution,'DEFERRED_PHASE2')});
test('plan creation blocks when responsive policy is UNSET',()=>{const p=init({active:false}),r=run(vqa,p,'plan','create','--project-root',p,'--input',request(p));assert.notEqual(r.status,0);assert.equal(jout(r).status,'RESPONSIVE_POLICY_NOT_ACTIVE')});
test('plan expands explicit surface state and approved viewports deterministically',()=>{const p=init(),x=mkPlan(p);assert.equal(x.r.status,0,x.r.stdout);assert.equal(x.o.status,'CAPTURE_PLAN_READY');assert.deepEqual(x.o.plan.cases.map(c=>c.case_id),['home--default--narrow','home--default--wide']);assert.equal(x.o.plan.claims.visual_quality_verified,false);assert.equal(x.o.plan.runner_status,'NOT_EXECUTED_PHASE1')});
test('unknown viewport is blocked rather than invented',()=>{const p=init(),x=mkPlan(p,{surfaces:[{id:'home',route:'/',viewport_ids:['tablet-magic'],states:['DEFAULT'],state_contract_path:null}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('viewport_unknown:home:tablet-magic'))});
test('external capture host is blocked by default',()=>{const p=init(),x=mkPlan(p,{base_url:'https://example.com'});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('base_url_host_not_allowlisted'))});
test('non-http protocol is blocked',()=>{const p=init(),x=mkPlan(p,{base_url:'file:///tmp/app'});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('base_url_protocol_forbidden'))});
test('base URL credentials are blocked',()=>{const p=init(),x=mkPlan(p,{base_url:['http',':','//','user',':','pass','@','127.0.0.1:3000'].join('')});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('base_url_credentials_forbidden'))});
test('surface route must be a local absolute route',()=>{const p=init(),x=mkPlan(p,{surfaces:[{id:'home',route:'https://evil.invalid/',viewport_ids:['narrow'],states:['DEFAULT'],state_contract_path:null}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('route_invalid:home'))});
test('duplicate surface IDs are blocked',()=>{const p=init(),s={id:'home',route:'/',viewport_ids:['narrow'],states:['DEFAULT'],state_contract_path:null},x=mkPlan(p,{surfaces:[s,{...s,route:'/other'}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('surface_duplicate:home'))});
test('duplicate viewport IDs inside a surface are blocked',()=>{const p=init(),x=mkPlan(p,{surfaces:[{id:'home',route:'/',viewport_ids:['narrow','narrow'],states:['DEFAULT'],state_contract_path:null}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('viewport_duplicate:home'))});
test('duplicate states inside a surface are blocked',()=>{const p=init(),x=mkPlan(p,{surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['DEFAULT','DEFAULT'],state_contract_path:null}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('state_duplicate:home'))});
test('missing changed source file blocks evidence planning',()=>{const p=init(),x=mkPlan(p,{changed_files:['src/pages/Missing.tsx']});assert.notEqual(x.r.status,0);assert.equal(x.o.status,'CHANGED_FILE_MISSING')});
test('source path traversal is blocked',()=>{const p=init(),x=mkPlan(p,{changed_files:['../outside.tsx']});assert.notEqual(x.r.status,0);assert.equal(x.o.status,'CHANGED_FILE_PATH_INVALID')});
test('state not present in supplied state contract is blocked',()=>{const p=init();w(p,'.aledevos/state/uxui/phase6/state-contracts/task-ui-001.json',JSON.stringify({contract_sha256:'a'.repeat(64),surfaces:[{id:'home',required_states:['LOADING'],evidence:[]}]}));const x=mkPlan(p,{surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['ERROR'],state_contract_path:'.aledevos/state/uxui/phase6/state-contracts/task-ui-001.json'}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('state_not_in_contract:home:ERROR'))});
test('state present in supplied state contract is accepted',()=>{const p=init();w(p,'.aledevos/state/uxui/phase6/state-contracts/task-ui-001.json',JSON.stringify({contract_sha256:'a'.repeat(64),surfaces:[{id:'home',required_states:['LOADING'],evidence:[]}]}));const x=mkPlan(p,{surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['LOADING'],state_contract_path:'.aledevos/state/uxui/phase6/state-contracts/task-ui-001.json'}]});assert.equal(x.r.status,0,x.r.stdout);assert.equal(x.o.plan.cases[0].state,'LOADING')});
test('plan tampering is detected',()=>{const p=init(),x=mkPlan(p);const o=JSON.parse(fs.readFileSync(x.out));o.base_url='http://localhost:9999';fs.writeFileSync(x.out,JSON.stringify(o));const r=run(vqa,p,'plan','verify','--project-root',p,'--plan',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('plan_integrity_mismatch'))});
test('responsive policy drift invalidates a sealed plan',()=>{const p=init(),x=mkPlan(p),rp=path.join(p,'.aledevos/design/responsive-policy.json'),o=JSON.parse(fs.readFileSync(rp));o.viewports[0].width=400;fs.writeFileSync(rp,JSON.stringify(o));const r=run(vqa,p,'plan','verify','--project-root',p,'--plan',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('responsive_policy_drift'))});
test('source drift invalidates a sealed plan',()=>{const p=init(),x=mkPlan(p);w(p,'src/pages/Home.tsx','export const Home=()=> <main>changed</main>');const r=run(vqa,p,'plan','verify','--project-root',p,'--plan',x.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('source_drift:src/pages/Home.tsx'))});
test('complete PNG capture set seals evidence without claiming visual PASS',()=>{const p=init(),x=mkPlan(p),s=seal(p,x);assert.equal(s.r.status,0,s.r.stdout);assert.equal(s.o.status,'CAPTURE_EVIDENCE_COMPLETE');assert.equal(s.o.run.captures.length,2);assert.equal(s.o.run.claims.visual_quality_verified,false);assert.equal(s.o.run.claims.visual_regression_verified,false)});
test('missing capture blocks sealing',()=>{const p=init(),x=mkPlan(p),s=seal(p,x,{skip:x.o.plan.cases[0].case_id});assert.notEqual(s.r.status,0);assert.ok(s.o.errors.some(e=>e.startsWith('capture_missing:')))});
test('unexpected capture blocks sealing',()=>{const p=init(),x=mkPlan(p),s=seal(p,x,{extra:[{case_id:'ghost--default--narrow',screenshot_path:'.aledevos/state/visualqa/phase1/artifacts/task-ui-001/ghost.png'}]});assert.notEqual(s.r.status,0);assert.ok(s.o.errors.includes('unexpected_capture:ghost--default--narrow'))});
test('capture path must match deterministic plan path',()=>{const p=init(),x=mkPlan(p),cid=x.o.plan.cases[0].case_id,s=seal(p,x,{pathOverride:{[cid]:'.aledevos/state/visualqa/phase1/artifacts/task-ui-001/renamed.png'}});assert.notEqual(s.r.status,0);assert.ok(s.o.errors.includes(`capture_path_mismatch:${cid}`))});
test('non-PNG evidence is blocked',()=>{const p=init(),x=mkPlan(p),cid=x.o.plan.cases[0].case_id,s=seal(p,x,{nonPng:cid});assert.notEqual(s.r.status,0);assert.ok(s.o.errors.includes(`capture_not_png:${cid}`))});
test('run tampering is detected',()=>{const p=init(),x=mkPlan(p),s=seal(p,x);const o=JSON.parse(fs.readFileSync(s.out));o.status='CAPTURE_EVIDENCE_BLOCKED';fs.writeFileSync(s.out,JSON.stringify(o));const r=run(vqa,p,'run','verify','--project-root',p,'--run',s.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('run_integrity_mismatch'))});
test('screenshot drift invalidates a sealed run',()=>{const p=init(),x=mkPlan(p),s=seal(p,x),cap=s.o.run.captures[0];fs.appendFileSync(path.join(p,cap.screenshot_path),Buffer.from([0]));const r=run(vqa,p,'run','verify','--project-root',p,'--run',s.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes(`capture_drift:${cap.case_id}`))});
test('source drift invalidates a sealed run',()=>{const p=init(),x=mkPlan(p),s=seal(p,x);w(p,'src/pages/Home.tsx','export const Home=()=> <main>later</main>');const r=run(vqa,p,'run','verify','--project-root',p,'--run',s.out);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(e=>e.includes('source_drift:src/pages/Home.tsx')))});
test('Phase 1 schemas parse cleanly',()=>{for(const f of ['capture-request.schema.json','capture-plan.schema.json','capture-results.schema.json','capture-run.schema.json'])assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(path.join('visualqa/schemas',f))))});
test('Phase 1 contract preserves non-claim boundary',()=>{const t=fs.readFileSync('core/design/contracts/VISUAL_QA_CAPTURE_EVIDENCE.md','utf8');assert.match(t,/Never invent/i);assert.match(t,/does not assert/i);assert.match(t,/later Visual QA phases/i)});
test('UI-relevant agents carry Visual QA Phase 1 discipline',()=>{for(const base of ['core/agents','adapters/opencode/.opencode/agents'])for(const n of ['orchestrator','researcher','architect','auditor','builder','editor-frontend','verifier','design-system-guardian','judge-uxui','judge-quality','repairer'])assert.match(fs.readFileSync(path.join(base,`${n}.md`),'utf8'),/Visual QA Phase 1 discipline/) });
test('installer deploys Visual QA runtime policy schemas contracts and state roots',()=>{const t=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');for(const needle of ['visualqa\\engine\\visualqa.mjs','visualqa\\policies\\visualqa-policy.json','state\\visualqa\\phase1\\plans','state\\visualqa\\phase1\\runs','v1.22 VisualQA-P1'])assert.match(t,new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
