import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {decodePng} from '../visualqa/engine/png-codec.mjs';

const ux=path.resolve('uxui/engine/uxui.mjs');
const quality=path.resolve('uxui/engine/ui-quality.mjs');
const vqa=path.resolve('visualqa/engine/visualqa.mjs');
const runner=path.resolve('visualqa/engine/browser-runner.mjs');
const regression=path.resolve('visualqa/engine/regression.mjs');
const fixture=path.resolve('tests/fixtures/vqa-test-provider.mjs');
const serverScript=path.resolve('tests/fixtures/vqa-server.mjs');
let server,baseUrl;
const jout=r=>JSON.parse(r.stdout||'{}');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-vqa-p3-'));
const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function run(runtime,cwd,args=[],env={}){return spawnSync(process.execPath,[runtime,...args],{cwd,encoding:'utf8',env:{...process.env,...env}})}
async function startServer(){server=spawn(process.execPath,[serverScript],{stdio:['ignore','pipe','pipe']});let buf='';server.stdout.setEncoding('utf8');server.stdout.on('data',d=>buf+=d);for(let i=0;i<100&&!buf.includes('\n');i++)await new Promise(r=>setTimeout(r,20));assert.ok(buf.includes('\n'),'server did not start');baseUrl=`http://127.0.0.1:${Number(buf.trim())}`}
before(startServer);after(()=>{if(server&&!server.killed)server.kill('SIGTERM')});
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,['context','init','--project-root',p]).status,0);assert.equal(run(quality,p,['standards','init','--project-root',p]).status,0);const rf=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow.'},{id:'wide',width:1440,height:900,expectation:'Wide.'}],container_policy:'canonical',overflow_policy:'none',source_ref:'UI-ADR-1001'}));assert.equal(run(quality,p,['responsive','approve','--project-root',p,'--input',rf,'--approval-ref','human:approved']).status,0);w(p,'src/pages/Home.tsx','export const Home=()=> <main>Home</main>');const tp=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');fs.mkdirSync(path.dirname(tp),{recursive:true});fs.copyFileSync(fixture,tp);return p}
function makeReceipt(p,{mode='',task='task-ui-p3',route='/',viewports=['narrow'],states=['DEFAULT']}={}){const req=w(p,`capture-request-${Date.now()}-${Math.random()}.json`,JSON.stringify({task_id:task,base_url:baseUrl,changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route,viewport_ids:viewports,states,state_contract_path:null}]}));const planPath=path.join(p,`.aledevos/state/visualqa/phase1/plans/${task}.json`);let r=run(vqa,p,['plan','create','--project-root',p,'--input',req,'--out',planPath]);assert.equal(r.status,0,r.stdout);const plan=jout(r).plan;const bindings=plan.cases.filter(c=>c.state!=='DEFAULT').map(c=>({case_id:c.case_id,route_suffix:`?vqaState=${c.state.toLowerCase()}`,ready_selector:`[data-vqa-state="${c.state}"]`}));const spec=w(p,`browser-spec-${Date.now()}-${Math.random()}.json`,JSON.stringify({task_id:task,provider:'playwright',browser:'chromium',stable_ms:0,case_bindings:bindings}));const receipt=path.join(p,`.aledevos/state/visualqa/phase2/receipts/${task}.json`);const provider=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');r=run(runner,p,['run','execute','--project-root',p,'--plan',planPath,'--spec',spec,'--out',receipt,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1',VQA_FIXTURE_MODE:mode});assert.equal(r.status,0,r.stdout);return {receipt,plan,output:jout(r)}}
function approve(p,receipt,id='base-001',profile='strict',supersedes=null,approval='human:visual-approved'){const a=['baseline','approve','--project-root',p,'--receipt',receipt,'--baseline-id',id,'--approval-ref',approval,'--tolerance-profile',profile];if(supersedes)a.push('--supersedes',supersedes);const r=run(regression,p,a);return {r,o:jout(r),manifest:path.join(p,'.aledevos/visualqa/baselines',id,'manifest.json')}}
function compare(p,receipt,baseline='base-001',outPath=null,extra=[]){const out=outPath||path.join(p,'.aledevos/state/visualqa/phase3/reports/report.json');const r=run(regression,p,['compare','run','--project-root',p,'--receipt',receipt,'--baseline',baseline,'--out',out,...extra]);return {r,o:jout(r),out}}

test('PNG codec decodes the Phase 2 fixture PNG',()=>{const p=init(),x=makeReceipt(p);const f=path.join(p,x.output.receipt.captures[0].screenshot_path);const im=decodePng(f);assert.equal(im.width,1);assert.equal(im.height,1);assert.equal(im.rgba.length,4)});
test('PNG codec rejects CRC tampering',()=>{const p=init(),x=makeReceipt(p);const f=path.join(p,x.output.receipt.captures[0].screenshot_path);const b=fs.readFileSync(f);b[Math.max(12,b.length-8)]^=1;assert.throws(()=>decodePng(b))});
test('approved baseline copies immutable screenshot evidence',()=>{const p=init(),x=makeReceipt(p),a=approve(p,x.receipt);assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.o.status,'VISUAL_BASELINE_APPROVED');assert.ok(fs.existsSync(path.join(p,'.aledevos/visualqa/baselines/base-001/cases/home--default--narrow.png')))});
test('baseline approval requires explicit approval reference',()=>{const p=init(),x=makeReceipt(p);const r=run(regression,p,['baseline','approve','--project-root',p,'--receipt',x.receipt,'--baseline-id','base-001']);assert.notEqual(r.status,0);assert.equal(jout(r).status,'BASELINE_APPROVE_ARGUMENTS_REQUIRED')});
test('baseline id is validated',()=>{const p=init(),x=makeReceipt(p);const a=approve(p,x.receipt,'../oops');assert.notEqual(a.r.status,0);assert.equal(a.o.status,'BASELINE_ID_INVALID')});
test('unknown tolerance profile is blocked',()=>{const p=init(),x=makeReceipt(p);const a=approve(p,x.receipt,'base-001','magic');assert.notEqual(a.r.status,0);assert.equal(a.o.status,'TOLERANCE_PROFILE_INVALID')});
test('baseline verify succeeds after approval',()=>{const p=init(),x=makeReceipt(p),a=approve(p,x.receipt);assert.equal(a.r.status,0);const r=run(regression,p,['baseline','verify','--project-root',p,'--baseline','base-001']);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_BASELINE_VALID')});
test('baseline manifest tampering is detected',()=>{const p=init(),x=makeReceipt(p),a=approve(p,x.receipt);const m=JSON.parse(fs.readFileSync(a.manifest));m.approval_ref='human:other';fs.writeFileSync(a.manifest,JSON.stringify(m));const r=run(regression,p,['baseline','verify','--project-root',p,'--baseline','base-001']);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('baseline_integrity_mismatch'))});
test('baseline image drift is detected',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);fs.appendFileSync(path.join(p,'.aledevos/visualqa/baselines/base-001/cases/home--default--narrow.png'),'x');const r=run(regression,p,['baseline','verify','--project-root',p,'--baseline','base-001']);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(e=>e.startsWith('baseline_file_drift:')))});
test('baseline ids are immutable and cannot be overwritten',()=>{const p=init(),x=makeReceipt(p);assert.equal(approve(p,x.receipt).r.status,0);const a=approve(p,x.receipt);assert.notEqual(a.r.status,0);assert.equal(a.o.status,'BASELINE_IMMUTABLE_EXISTS')});
test('invalid superseded baseline blocks promotion',()=>{const p=init(),x=makeReceipt(p);const a=approve(p,x.receipt,'base-002','strict','missing');assert.notEqual(a.r.status,0);assert.equal(a.o.status,'SUPERSEDED_BASELINE_INVALID')});
test('supersede requires the same visual case set',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{viewports:['narrow','wide']});const a=approve(p,y.receipt,'base-002','strict','base-001');assert.notEqual(a.r.status,0);assert.equal(a.o.status,'SUPERSEDE_CASE_SET_MISMATCH')});
test('supersede succeeds with the same visual case set',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'changed'});const a=approve(p,y.receipt,'base-002','strict','base-001');assert.equal(a.r.status,0,a.r.stdout);const m=JSON.parse(fs.readFileSync(a.manifest));assert.equal(m.supersedes.baseline_id,'base-001')});
test('baseline verification is self-contained after origin receipt disappears',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);fs.rmSync(x.receipt);const r=run(regression,p,['baseline','verify','--project-root',p,'--baseline','base-001']);assert.equal(r.status,0,r.stdout)});
test('identical screenshot passes strict visual regression',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p);const c=compare(p,y.receipt);assert.equal(c.r.status,0,c.r.stdout);assert.equal(c.o.status,'VISUAL_REGRESSION_PASS');assert.equal(c.o.report.summary.failed,0)});
test('visual-regression PASS does not claim visual quality or rendered accessibility',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p),c=compare(p,y.receipt);assert.equal(c.o.report.claims.visual_regression_verified,true);assert.equal(c.o.report.claims.visual_quality_verified,false);assert.equal(c.o.report.claims.rendered_layout_verified,false);assert.equal(c.o.report.claims.rendered_accessibility_verified,false)});
test('strict profile fails on a changed pixel',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'changed'}),c=compare(p,y.receipt);assert.equal(c.r.status,3,c.r.stdout);assert.equal(c.o.status,'VISUAL_REGRESSION_FAIL');assert.equal(c.o.report.cases[0].status,'FAIL');assert.equal(c.o.report.cases[0].metrics.diff_ratio,1)});
test('failed changed case emits a hashed PNG diff artifact',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'changed'}),c=compare(p,y.receipt);const ca=c.o.report.cases[0];assert.ok(ca.diff_path);const f=path.join(p,ca.diff_path);assert.ok(fs.existsSync(f));assert.equal(decodePng(f).width,1);assert.match(ca.diff_sha256,/^[a-f0-9]{64}$/)});
test('dimension mismatch is a visual regression failure',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'dimension'}),c=compare(p,y.receipt);assert.equal(c.r.status,3);assert.equal(c.o.report.cases[0].metrics.dimension_mismatch,true)});
test('browser_stable profile tolerates only its approved small channel noise',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt,'base-001','browser_stable');const y=makeReceipt(p,{mode:'minor'}),c=compare(p,y.receipt);assert.equal(c.r.status,0,c.r.stdout);assert.equal(c.o.status,'VISUAL_REGRESSION_PASS')});
test('strict profile does not tolerate the same minor channel change',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt,'base-001','strict');const y=makeReceipt(p,{mode:'minor'}),c=compare(p,y.receipt);assert.equal(c.r.status,3);assert.equal(c.o.status,'VISUAL_REGRESSION_FAIL')});
test('arbitrary numeric tolerance override is forbidden',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p);const c=compare(p,y.receipt,'base-001',null,['--channel-threshold','255']);assert.notEqual(c.r.status,0);assert.equal(c.o.status,'ARBITRARY_TOLERANCE_FORBIDDEN')});
test('route contract drift blocks instead of being misclassified as pixel regression',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{route:'/changed'}),c=compare(p,y.receipt);assert.equal(c.r.status,4,c.r.stdout);assert.equal(c.o.status,'VISUAL_REGRESSION_BLOCKED');assert.ok(c.o.report.blockers.some(x=>x.startsWith('case_contract_drift:')))});
test('case-set drift blocks instead of silently reducing coverage',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{viewports:['narrow','wide']}),c=compare(p,y.receipt);assert.equal(c.r.status,4);assert.ok(c.o.report.blockers.includes('case_set_mismatch'))});
test('comparison report verifies after PASS',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p),c=compare(p,y.receipt);const r=run(regression,p,['compare','verify','--project-root',p,'--report',c.out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_REGRESSION_REPORT_VALID')});
test('comparison report verifies after a real FAIL',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'changed'}),c=compare(p,y.receipt);assert.equal(c.r.status,3);const r=run(regression,p,['compare','verify','--project-root',p,'--report',c.out]);assert.equal(r.status,0,r.stdout)});
test('report tampering is detected',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p),c=compare(p,y.receipt);const o=JSON.parse(fs.readFileSync(c.out));o.status='VISUAL_REGRESSION_FAIL';fs.writeFileSync(c.out,JSON.stringify(o));const r=run(regression,p,['compare','verify','--project-root',p,'--report',c.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('report_integrity_mismatch'))});
test('current screenshot drift blocks comparison through Phase 2 verification',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p);fs.appendFileSync(path.join(p,y.output.receipt.captures[0].screenshot_path),'x');const c=compare(p,y.receipt);assert.notEqual(c.r.status,0);assert.equal(c.o.status,'PHASE2_RECEIPT_INVALID')});
test('baseline drift blocks comparison',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p);fs.appendFileSync(path.join(p,'.aledevos/visualqa/baselines/base-001/cases/home--default--narrow.png'),'x');const c=compare(p,y.receipt);assert.notEqual(c.r.status,0);assert.equal(c.o.status,'VISUAL_BASELINE_INVALID')});
test('diff artifact drift invalidates a previously sealed FAIL report',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p,{mode:'changed'}),c=compare(p,y.receipt);const dp=path.join(p,c.o.report.cases[0].diff_path);fs.appendFileSync(dp,'x');const r=run(regression,p,['compare','verify','--project-root',p,'--report',c.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(e=>e.startsWith('diff_artifact_drift:')))});
test('Phase 2 receipt drift invalidates the sealed regression report',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const y=makeReceipt(p),c=compare(p,y.receipt);fs.appendFileSync(y.receipt,' ');const r=run(regression,p,['compare','verify','--project-root',p,'--report',c.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('phase2_receipt_drift'))});
test('failed comparison never auto-promotes a new baseline',()=>{const p=init(),x=makeReceipt(p);approve(p,x.receipt);const before=fs.readdirSync(path.join(p,'.aledevos/visualqa/baselines')).sort();const y=makeReceipt(p,{mode:'changed'});compare(p,y.receipt);const after=fs.readdirSync(path.join(p,'.aledevos/visualqa/baselines')).sort();assert.deepEqual(after,before)});
test('baseline manifest stores references and hashes, not screenshot bytes',()=>{const p=init(),x=makeReceipt(p),a=approve(p,x.receipt);const raw=fs.readFileSync(a.manifest,'utf8');assert.ok(!raw.includes('iVBORw0KGgo'));assert.ok(raw.includes('baseline_path'));assert.ok(raw.includes('sha256'))});
test('Phase 3 policy pins named profiles and forbids arbitrary override and auto-promotion',()=>{const p=JSON.parse(fs.readFileSync(path.resolve('visualqa/policies/visualqa-policy.json'),'utf8')).phase3;assert.equal(p.default_tolerance_profile,'strict');assert.equal(p.arbitrary_tolerance_override_forbidden,true);assert.equal(p.baseline_auto_promotion_forbidden,true);assert.ok(p.tolerance_profiles.strict);assert.ok(p.tolerance_profiles.browser_stable)});
test('installer deploys Phase 3 runtime and persistent baseline plus transient report roots',()=>{const s=fs.readFileSync(path.resolve('scripts/05-install-into-project.ps1'),'utf8');assert.match(s,/regression\.mjs/);assert.match(s,/png-codec\.mjs/);assert.match(s,/visualqa\\baselines/);assert.match(s,/phase3\\reports/);assert.match(s,/phase3\\diffs/)});
test('dedicated visual regression agent cannot edit product files and has only narrow regression commands',()=>{const s=fs.readFileSync(path.resolve('adapters/opencode/.opencode/agents/visual-regression-runner.md'),'utf8');assert.match(s,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(s,/regression\.mjs compare run/);assert.match(s,/regression\.mjs compare verify/);assert.match(s,/regression\.mjs baseline approve/);assert.match(s,/action: webfetch[\s\S]*effect: deny/)});
test('read-only judges can verify Phase 3 evidence but cannot approve baselines',()=>{for(const n of ['design-system-guardian','judge-uxui','judge-quality','judge-regression','verifier']){const s=fs.readFileSync(path.resolve(`adapters/opencode/.opencode/agents/${n}.md`),'utf8');assert.match(s,/regression\.mjs compare verify/);assert.match(s,/regression\.mjs baseline verify/);assert.ok(!s.includes('regression.mjs baseline approve'),n)}});
test('Phase 3 Core contract preserves Visual Judge and rendered-check boundaries',()=>{const s=fs.readFileSync(path.resolve('core/design/contracts/VISUAL_QA_REGRESSION.md'),'utf8');assert.match(s,/does not prove aesthetic quality/i);assert.match(s,/baseline promotion requires explicit approval/i);assert.match(s,/rendered layout and accessibility remain deferred/i)});
