import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'),quality=path.resolve('uxui/engine/ui-quality.mjs'),vqa=path.resolve('visualqa/engine/visualqa.mjs'),runner=path.resolve('visualqa/engine/browser-runner.mjs'),regression=path.resolve('visualqa/engine/regression.mjs'),audit=path.resolve('visualqa/engine/runtime-audit.mjs');
const captureFixture=path.resolve('tests/fixtures/vqa-test-provider.mjs'),auditFixture=path.resolve('tests/fixtures/vqa-runtime-test-provider.mjs'),serverScript=path.resolve('tests/fixtures/vqa-server.mjs');let server,baseUrl;
const jout=r=>JSON.parse(r.stdout||'{}'),tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-vqa-p4-')),w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function run(runtime,cwd,args=[],env={}){return spawnSync(process.execPath,[runtime,...args],{cwd,encoding:'utf8',env:{...process.env,...env}})}
async function startServer(){server=spawn(process.execPath,[serverScript],{stdio:['ignore','pipe','pipe']});let b='';server.stdout.setEncoding('utf8');server.stdout.on('data',d=>b+=d);for(let i=0;i<100&&!b.includes('\n');i++)await new Promise(r=>setTimeout(r,20));assert.ok(b.includes('\n'));baseUrl=`http://127.0.0.1:${Number(b.trim())}`}
before(startServer);after(()=>{if(server&&!server.killed)server.kill('SIGTERM')});
function init({a11y=true,standard='WCAG_2_2_AA'}={}){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,['context','init','--project-root',p]).status,0);assert.equal(run(quality,p,['standards','init','--project-root',p]).status,0);const rf=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow.'},{id:'wide',width:1440,height:900,expectation:'Wide.'}],container_policy:'canonical',overflow_policy:'none',source_ref:'UI-ADR-1001'}));assert.equal(run(quality,p,['responsive','approve','--project-root',p,'--input',rf,'--approval-ref','human:approved']).status,0);if(a11y){const af=w(p,'a11y.json',JSON.stringify({standard,requirements:{semantics:'Semantic roles match behavior.',keyboard:'Controls work by keyboard.',focus:'Visible usable focus.',labels:'Controls have names.',contrast:'Rendered contrast meets target.',reduced_motion:'Reduced motion respected.'},source_ref:'UI-ADR-1000'}));assert.equal(run(quality,p,['accessibility','approve','--project-root',p,'--input',af,'--approval-ref','human:approved']).status,0)}w(p,'src/pages/Home.tsx','export const Home=()=> <main>Home</main>');const dir=path.join(p,'.aledevos/state/visualqa/test-providers');fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(captureFixture,path.join(dir,'capture.mjs'));fs.copyFileSync(auditFixture,path.join(dir,'audit.mjs'));return p}
function receipt(p,{task='task-ui-p4',route='/',viewports=['narrow']}={}){const req=w(p,`request-${task}.json`,JSON.stringify({task_id:task,base_url:baseUrl,changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route,viewport_ids:viewports,states:['DEFAULT'],state_contract_path:null}]})),plan=path.join(p,`.aledevos/state/visualqa/phase1/plans/${task}.json`);let r=run(vqa,p,['plan','create','--project-root',p,'--input',req,'--out',plan]);assert.equal(r.status,0,r.stdout);const spec=w(p,`spec-${task}.json`,JSON.stringify({task_id:task,provider:'playwright',browser:'chromium',stable_ms:0,case_bindings:[]})),out=path.join(p,`.aledevos/state/visualqa/phase2/receipts/${task}.json`),provider=path.join(p,'.aledevos/state/visualqa/test-providers/capture.mjs');r=run(runner,p,['run','execute','--project-root',p,'--plan',plan,'--spec',spec,'--out',out,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1'});assert.equal(r.status,0,r.stdout);return {path:out,obj:jout(r).receipt}}
function p3(p,rec,id='base-p4'){let r=run(regression,p,['baseline','approve','--project-root',p,'--receipt',rec,'--baseline-id',id,'--approval-ref','human:approved']);assert.equal(r.status,0,r.stdout);const out=path.join(p,`.aledevos/state/visualqa/phase3/reports/${id}.json`);r=run(regression,p,['compare','run','--project-root',p,'--receipt',rec,'--baseline',id,'--out',out]);assert.equal(r.status,0,r.stdout);return out}
function auditRun(p,rec,{mode='',p3report=null,extra=[]}={}){const out=path.join(p,'.aledevos/state/visualqa/phase4/reports/report.json'),provider=path.join(p,'.aledevos/state/visualqa/test-providers/audit.mjs'),a=['audit','run','--project-root',p,'--receipt',rec,'--out',out,'--provider-module',provider,...extra];if(p3report)a.push('--phase3-report',p3report);const r=run(audit,p,a,{ALEDEVOS_TEST_MODE:'1',VQA_RUNTIME_MODE:mode});return {r,o:jout(r),out}}

test('P4 PASS on clean deterministic runtime evidence',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path);assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.o.status,'VISUAL_RUNTIME_AUDIT_PASS');assert.equal(a.o.report.summary.passed,1)});
test('P4 PASS claims supported layout/accessibility but not aesthetics or full WCAG',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path);const c=a.o.report.claims;assert.equal(c.rendered_layout_verified,true);assert.equal(c.rendered_accessibility_verified,true);assert.equal(c.visual_quality_verified,false);assert.equal(c.full_wcag_conformance_verified,false);assert.equal(c.motion_quality_verified,false)});
test('controlled Phase 4 providers are explicitly marked as test provenance',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path);assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.o.report.provider.provenance,'CONTROLLED_TEST_PROVIDER')});
test('horizontal overflow is a deterministic FAIL',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'overflow'});assert.equal(a.r.status,3);assert.equal(a.o.status,'VISUAL_RUNTIME_AUDIT_FAIL');assert.equal(a.o.report.cases[0].failures[0].rule_id,'LAYOUT_HORIZONTAL_OVERFLOW')});
test('focusable viewport escape fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'escape'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='LAYOUT_FOCUSABLE_VIEWPORT_ESCAPE'))});
test('clipped focusable fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'clipped'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='LAYOUT_FOCUSABLE_CLIPPED'))});
test('missing accessible name fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'unnamed'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_ACCESSIBLE_NAME_MISSING'))});
test('missing image alt fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'alt'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_IMAGE_ALT_MISSING'))});
test('undersized target without exception fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'target'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_TARGET_SIZE_MINIMUM'))});
test('low rendered text contrast fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'contrast'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_TEXT_CONTRAST'))});
test('unmeasurable text contrast blocks instead of false PASS',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'unmeasurable'});assert.equal(a.r.status,4);assert.equal(a.o.status,'VISUAL_RUNTIME_AUDIT_BLOCKED');assert.ok(a.o.report.cases[0].blockers.some(x=>x.startsWith('A11Y_TEXT_CONTRAST_UNMEASURABLE')))});
test('missing keyboard focus indicator fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'focus'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_FOCUS_INDICATOR_MISSING'))});
test('obscured focused control fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'obscured'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_FOCUS_OBSCURED'))});
test('keyboard-unreachable focusable fails',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'unreachable'});assert.equal(a.r.status,3);assert.ok(a.o.report.cases[0].failures.some(x=>x.rule_id==='A11Y_KEYBOARD_UNREACHABLE'))});
test('focus scan truncation blocks',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'focus-truncated'});assert.equal(a.r.status,4);assert.ok(a.o.report.cases[0].blockers.includes('AUDIT_FOCUS_SCAN_TRUNCATED'))});
test('DOM scan truncation blocks',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'dom-truncated'});assert.equal(a.r.status,4);assert.ok(a.o.report.cases[0].blockers.includes('AUDIT_DOM_SCAN_TRUNCATED'))});
test('canonical accessibility policy must be ACTIVE',()=>{const p=init({a11y:false}),x=receipt(p),a=auditRun(p,x.path);assert.notEqual(a.r.status,0);assert.equal(a.o.status,'ACCESSIBILITY_POLICY_UNSET')});
test('unsupported accessibility standard blocks rather than inventing thresholds',()=>{const p=init({standard:'CUSTOM_A11Y'}),x=receipt(p),a=auditRun(p,x.path);assert.notEqual(a.r.status,0);assert.equal(a.o.status,'ACCESSIBILITY_STANDARD_UNSUPPORTED')});
test('arbitrary runtime threshold flags are forbidden',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{extra:['--target-size','1']});assert.notEqual(a.r.status,0);assert.equal(a.o.status,'ARBITRARY_RUNTIME_THRESHOLD_FORBIDDEN')});
test('valid Phase 3 report may be linked and is verified',()=>{const p=init(),x=receipt(p),r3=p3(p,x.path),a=auditRun(p,x.path,{p3report:r3});assert.equal(a.r.status,0,a.r.stdout);assert.equal(a.o.report.phase3_status,'VISUAL_REGRESSION_PASS');assert.ok(a.o.report.phase3_report_file_sha256)});
test('Phase 3 report tied to a different receipt is rejected',()=>{const p=init(),x=receipt(p,{task:'p4-a'}),y=receipt(p,{task:'p4-b'}),r3=p3(p,y.path,'other-base'),a=auditRun(p,x.path,{p3report:r3});assert.notEqual(a.r.status,0);assert.equal(a.o.status,'PHASE3_RECEIPT_MISMATCH')});
test('invalid Phase 2 evidence blocks P4',()=>{const p=init(),x=receipt(p),o=JSON.parse(fs.readFileSync(x.path));o.task_id='tampered';fs.writeFileSync(x.path,JSON.stringify(o));const a=auditRun(p,x.path);assert.notEqual(a.r.status,0);assert.equal(a.o.status,'PHASE2_RECEIPT_INVALID')});
test('runtime redirect origin drift blocks',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'redirect-origin'});assert.notEqual(a.r.status,0);assert.equal(a.o.status,'VISUAL_RUNTIME_AUDIT_BLOCKED');assert.equal(a.o.failure.status,'AUDIT_REDIRECT_ORIGIN_CHANGED')});
test('runtime redirect path drift blocks',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'redirect-path'});assert.notEqual(a.r.status,0);assert.equal(a.o.failure.status,'AUDIT_REDIRECT_PATH_CHANGED')});
test('provider audit failure blocks',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'fail'});assert.notEqual(a.r.status,0);assert.equal(a.o.failure.status,'FIXTURE_AUDIT_FAIL')});
test('sealed P4 report verifies after PASS',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path),r=run(audit,p,['audit','verify','--project-root',p,'--report',a.out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_RUNTIME_AUDIT_REPORT_VALID')});
test('sealed P4 report verifies after measured FAIL',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path,{mode:'contrast'}),r=run(audit,p,['audit','verify','--project-root',p,'--report',a.out]);assert.equal(r.status,0,r.stdout)});
test('report tampering is detected',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path),o=JSON.parse(fs.readFileSync(a.out));o.status='VISUAL_RUNTIME_AUDIT_FAIL';fs.writeFileSync(a.out,JSON.stringify(o));const r=run(audit,p,['audit','verify','--project-root',p,'--report',a.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('report_integrity_mismatch'))});
test('evidence tampering invalidates report',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path),ep=path.join(p,a.o.report.cases[0].evidence_path);fs.appendFileSync(ep,' ');const r=run(audit,p,['audit','verify','--project-root',p,'--report',a.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.some(x=>x.startsWith('evidence_file_drift:')))});
test('accessibility policy drift invalidates report',()=>{const p=init(),x=receipt(p),a=auditRun(p,x.path),ap=path.join(p,'.aledevos/design/accessibility-policy.json');fs.appendFileSync(ap,' ');const r=run(audit,p,['audit','verify','--project-root',p,'--report',a.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('accessibility_policy_drift'))});
test('Phase 4 policy pins WCAG 2.2 AA thresholds and forbids overrides',()=>{const p=JSON.parse(fs.readFileSync('visualqa/policies/visualqa-policy.json')).phase4,q=p.supported_accessibility_standards.WCAG_2_2_AA;assert.equal(q.normal_text_contrast_min,4.5);assert.equal(q.large_text_contrast_min,3);assert.equal(q.target_size_min_px,24);assert.equal(p.arbitrary_threshold_override_forbidden,true);assert.equal(p.full_wcag_conformance_claim_forbidden,true)});
test('Playwright adapter exposes audit in addition to capture',()=>{const s=fs.readFileSync('adapters/opencode/visualqa/playwright-driver.mjs','utf8');assert.match(s,/async audit\(c\)/);assert.match(s,/horizontal_overflow_px/);assert.match(s,/keyboard_focus/);assert.match(s,/text_contrast/)});
test('installer deploys P4 runtime and creates evidence/report roots',()=>{const s=fs.readFileSync('scripts/05-install-into-project.ps1','utf8');assert.match(s,/runtime-audit\.mjs/);assert.match(s,/phase4\\evidence/);assert.match(s,/phase4\\reports/);assert.match(s,/runtime-audit\.mjs/)});
test('dedicated runtime audit agent is narrow and cannot edit or approve baselines',()=>{const s=fs.readFileSync('adapters/opencode/.opencode/agents/visual-runtime-audit-runner.md','utf8');assert.match(s,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(s,/runtime-audit\.mjs audit run/);assert.match(s,/runtime-audit\.mjs audit verify/);assert.ok(!s.includes('baseline approve'));assert.match(s,/action: webfetch[\s\S]*effect: deny/)});
test('read-only visual consumers verify P4 but cannot execute it',()=>{for(const n of ['design-system-guardian','judge-uxui','judge-quality','judge-regression','verifier']){const s=fs.readFileSync(`adapters/opencode/.opencode/agents/${n}.md`,'utf8');assert.match(s,/runtime-audit\.mjs audit verify/);assert.ok(!s.includes('runtime-audit.mjs audit run'),n)}});
test('orchestrator can delegate capture regression and runtime audit narrow agents',()=>{const s=fs.readFileSync('adapters/opencode/.opencode/agents/orchestrator.md','utf8');for(const n of ['visual-capture-runner','visual-regression-runner','visual-runtime-audit-runner'])assert.ok(s.includes(`resource: "${n}"`),n)});
test('P4 Core contract preserves full WCAG and aesthetic boundaries',()=>{const s=fs.readFileSync('core/design/contracts/VISUAL_QA_RUNTIME.md','utf8');assert.match(s,/does \*\*not\*\* prove full WCAG conformance/i);assert.match(s,/aesthetic quality/i);assert.match(s,/Phase 5/i);assert.match(s,/Per-run numeric overrides are forbidden/i)});
test('P4 schemas and adapter capability are registered',()=>{for(const f of ['visualqa/schemas/runtime-audit-evidence.schema.json','visualqa/schemas/runtime-audit-report.schema.json'])assert.doesNotThrow(()=>JSON.parse(fs.readFileSync(f,'utf8')));const c=JSON.parse(fs.readFileSync('adapters/opencode/adapter-capabilities.json','utf8'));assert.equal(c.capabilities.visual_qa_runtime_checks.status,'implemented')});
test('release metadata keeps P4 frozen in current or later releases',()=>{const version=fs.readFileSync('VERSION.txt','utf8').trim();assert.match(version,/^1\.(?:2[5-9]|[3-9]\d|\d{3,})\./);const c=fs.readFileSync('CHANGELOG.md','utf8');assert.match(c,/v1\.25\.0[^\n]*Visual QA Phase 4/i);assert.match(c,/Preserved the frozen Visual QA P1-P5 engines|Preserved Visual QA P1-P5 frozen behavior/i)});
