import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';
const ux=path.resolve('uxui/engine/uxui.mjs'),quality=path.resolve('uxui/engine/ui-quality.mjs'),vqa=path.resolve('visualqa/engine/visualqa.mjs'),runner=path.resolve('visualqa/engine/browser-runner.mjs'),regression=path.resolve('visualqa/engine/regression.mjs'),audit=path.resolve('visualqa/engine/runtime-audit.mjs'),judge=path.resolve('visualqa/engine/visual-judge.mjs'),core=path.resolve('core/engine/aledevos.mjs');
const captureFixture=path.resolve('tests/fixtures/vqa-test-provider.mjs'),auditFixture=path.resolve('tests/fixtures/vqa-runtime-test-provider.mjs'),serverScript=path.resolve('tests/fixtures/vqa-server.mjs');let server,baseUrl;
const jout=r=>JSON.parse(r.stdout||'{}'),tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-vqa-p5-')),w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function run(runtime,cwd,args=[],env={}){return spawnSync(process.execPath,[runtime,...args],{cwd,encoding:'utf8',env:{...process.env,...env}})}
async function startServer(){server=spawn(process.execPath,[serverScript],{stdio:['ignore','pipe','pipe']});let b='';server.stdout.setEncoding('utf8');server.stdout.on('data',d=>b+=d);for(let i=0;i<100&&!b.includes('\n');i++)await new Promise(r=>setTimeout(r,20));assert.ok(b.includes('\n'));baseUrl=`http://127.0.0.1:${Number(b.trim())}`}
before(startServer);after(()=>{if(server&&!server.killed)server.kill('SIGTERM')});
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,['context','init','--project-root',p]).status,0);assert.equal(run(quality,p,['standards','init','--project-root',p]).status,0);const rf=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow.'},{id:'wide',width:1440,height:900,expectation:'Wide.'}],container_policy:'canonical',overflow_policy:'none',source_ref:'UI-ADR-1001'}));assert.equal(run(quality,p,['responsive','approve','--project-root',p,'--input',rf,'--approval-ref','human:approved']).status,0);const af=w(p,'a11y.json',JSON.stringify({standard:'WCAG_2_2_AA',requirements:{semantics:'Semantic roles match behavior.',keyboard:'Controls work by keyboard.',focus:'Visible usable focus.',labels:'Controls have names.',contrast:'Rendered contrast meets target.',reduced_motion:'Reduced motion respected.'},source_ref:'UI-ADR-1000'}));assert.equal(run(quality,p,['accessibility','approve','--project-root',p,'--input',af,'--approval-ref','human:approved']).status,0);w(p,'src/pages/Home.tsx','export const Home=()=> <main>Home</main>');const dir=path.join(p,'.aledevos/state/visualqa/test-providers');fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(captureFixture,path.join(dir,'capture.mjs'));fs.copyFileSync(auditFixture,path.join(dir,'audit.mjs'));assert.equal(run(core,p,['state','init','--task-id','task-ui-p5','--scope','src/**']).status,0);return p}
function receipt(p,{task='task-ui-p5',revision='initial',mode=''}={}){const req=w(p,`request-${task}-${revision}.json`,JSON.stringify({task_id:task,evidence_id:revision,base_url:baseUrl,changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['DEFAULT'],state_contract_path:null}]})),plan=path.join(p,`.aledevos/state/visualqa/phase1/plans/${task}--${revision}.json`);let r=run(vqa,p,['plan','create','--project-root',p,'--input',req,'--out',plan]);assert.equal(r.status,0,r.stdout);const spec=w(p,`spec-${task}-${revision}.json`,JSON.stringify({task_id:task,provider:'playwright',browser:'chromium',stable_ms:0,case_bindings:[]})),out=path.join(p,`.aledevos/state/visualqa/phase2/receipts/${task}--${revision}.json`),provider=path.join(p,'.aledevos/state/visualqa/test-providers/capture.mjs');r=run(runner,p,['run','execute','--project-root',p,'--plan',plan,'--spec',spec,'--out',out,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1',VQA_FIXTURE_MODE:mode});assert.equal(r.status,0,r.stdout);return {path:out,obj:jout(r).receipt,plan}}
function baseline(p,rec,id='base-p5'){const r=run(regression,p,['baseline','approve','--project-root',p,'--receipt',rec,'--baseline-id',id,'--approval-ref','human:approved']);assert.equal(r.status,0,r.stdout);return id}
function p3(p,rec,id='base-p5',revision='initial'){const out=path.join(p,`.aledevos/state/visualqa/phase3/reports/task-ui-p5--${revision}.json`),r=run(regression,p,['compare','run','--project-root',p,'--receipt',rec,'--baseline',id,'--out',out]);return {r,o:jout(r),out}}
function p4(p,rec,p3out,revision='initial',mode=''){const out=path.join(p,`.aledevos/state/visualqa/phase4/reports/task-ui-p5--${revision}.json`),provider=path.join(p,'.aledevos/state/visualqa/test-providers/audit.mjs'),r=run(audit,p,['audit','run','--project-root',p,'--receipt',rec,'--phase3-report',p3out,'--out',out,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1',VQA_RUNTIME_MODE:mode});return {r,o:jout(r),out}}
function upstream(p,{revision='initial',captureMode='',auditMode='',baselineId='base-p5',approve=false}={}){const x=receipt(p,{revision,mode:captureMode});if(approve)baseline(p,x.path,baselineId);const r3=p3(p,x.path,baselineId,revision);assert.equal(r3.r.status,0,r3.r.stdout);const r4=p4(p,x.path,r3.out,revision,auditMode);assert.equal(r4.r.status,0,r4.r.stdout);return {receipt:x.path,p3:r3.out,p4:r4.out,rec:x.obj}}
function packet(p,u,revision='initial'){const out=path.join(p,`.aledevos/state/visualqa/phase5/packets/task-ui-p5--${revision}.json`),r=run(judge,p,['packet','prepare','--project-root',p,'--receipt',u.receipt,'--phase3-report',u.p3,'--phase4-report',u.p4,'--out',out]);return {r,o:jout(r),out}}
function submissionObject(packetObj,{kind='pass',score=95,model='test-vision-1'}={}){const dims=packetObj.rubric.required_dimensions.map((id,i)=>({id,status:'PASS',score,note:`${id} is visually coherent in the observed screenshot.`}));const findings=[];if(kind==='fail'){dims[0]={id:dims[0].id,status:'FAIL',score:60,note:'Primary action is visually weaker than surrounding secondary content.'};findings.push({id:'F-1',category:dims[0].id,severity:'HIGH',blocking:false,summary:'Primary hierarchy is too weak for the intended action.',evidence:'The main action has similar emphasis to neighboring secondary controls.',repair_hint:'Increase hierarchy using canonical size, spacing or emphasis tokens without changing behavior.'})}if(kind==='blocked')dims[0]={id:dims[0].id,status:'UNVERIFIED',score:null,note:'The image evidence could not be observed reliably in this runtime.'};if(kind==='overall-low'){for(const d of dims){d.score=89;d.note=`${d.id} is acceptable but lacks final-pass polish.`}findings.push({id:'F-LOW',category:'polish_consistency',severity:'MEDIUM',blocking:false,summary:'Overall polish remains below final visual acceptance.',evidence:'Several small consistency issues combine to keep the holistic score below threshold.',repair_hint:'Normalize spacing, typography and emphasis using canonical design-system tokens.'})}return {schema_version:'1.0',phase:'VISUAL_QA_P5_SUBMISSION',task_id:packetObj.task_id,packet_sha256:packetObj.packet_sha256,judge:{agent_id:'visual-judge',model_ref:model,observation_mode:'NATIVE_IMAGE'},cases:packetObj.cases.map(c=>({case_id:c.case_id,observed_screenshot_sha256:c.screenshot_sha256,dimensions:structuredClone(dims),findings:structuredClone(findings)}))}}
function seal(p,pk,{kind='pass',revision='initial',mutate=null}={}){let s=submissionObject(pk.o.packet,{kind});if(mutate)s=mutate(s)||s;const inp=w(p,`.aledevos/state/visualqa/phase5/submissions/task-ui-p5--${revision}.json`,JSON.stringify(s)),out=path.join(p,`.aledevos/state/visualqa/phase5/judgments/task-ui-p5--${revision}.json`),r=run(judge,p,['judgment','seal','--project-root',p,'--packet',pk.out,'--input',inp,'--out',out]);return {r,o:jout(r),out,input:inp}}
function freshPassAfterRepair(p,baseId='base-p5',attempt=1){w(p,'src/pages/Home.tsx',`export const Home=()=> <main data-repair="${attempt}">Home</main>`);const rev=`repair-${attempt}`,u=upstream(p,{revision:rev,baselineId:baseId}),pk=packet(p,u,rev);assert.equal(pk.r.status,0,pk.r.stdout);const j=seal(p,pk,{kind:'pass',revision:rev});assert.equal(j.r.status,0,j.r.stdout);return {u,pk,j}}

test('P1/P2 evidence revisions preserve revision-specific artifact paths',()=>{const p=init(),x=receipt(p,{revision:'initial'}),y=receipt(p,{revision:'repair-1'});assert.equal(x.obj.evidence_id,'initial');assert.equal(y.obj.evidence_id,'repair-1');assert.notEqual(x.obj.captures[0].screenshot_path,y.obj.captures[0].screenshot_path);assert.ok(x.obj.captures[0].screenshot_path.includes('/initial/'));assert.ok(y.obj.captures[0].screenshot_path.includes('/repair-1/'))});
test('evidence revision ID rejects path-like unsafe values',()=>{const p=init(),req=w(p,'bad.json',JSON.stringify({task_id:'task-ui-p5',evidence_id:'../repair',base_url:baseUrl,changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['DEFAULT']}]})),r=run(vqa,p,['plan','create','--project-root',p,'--input',req]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('evidence_id_invalid'))});
test('P5 packet prepares only from P2 + PASS P3 + PASS P4',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u);assert.equal(pk.r.status,0,pk.r.stdout);assert.equal(pk.o.packet.status,'VISUAL_JUDGE_PACKET_READY');assert.equal(pk.o.packet.evidence_revision,'initial');assert.equal(pk.o.packet.cases.length,1)});
test('P5 packet verifies and is sealed',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),r=run(judge,p,['packet','verify','--project-root',p,'--packet',pk.out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_JUDGE_PACKET_VALID')});
test('packet tampering is detected',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),o=JSON.parse(fs.readFileSync(pk.out));o.observation_mode='TEXT_ONLY';fs.writeFileSync(pk.out,JSON.stringify(o));const r=run(judge,p,['packet','verify','--project-root',p,'--packet',pk.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('packet_integrity_mismatch'))});
test('packet blocks a genuine Phase 3 regression FAIL',()=>{const p=init(),a=receipt(p,{revision:'base'});baseline(p,a.path);const b=receipt(p,{revision:'changed',mode:'changed'}),r3=p3(p,b.path,'base-p5','changed');assert.equal(r3.r.status,3);const r4=p4(p,b.path,r3.out,'changed');assert.equal(r4.r.status,0,r4.r.stdout);const r=run(judge,p,['packet','prepare','--project-root',p,'--receipt',b.path,'--phase3-report',r3.out,'--phase4-report',r4.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'PHASE3_PASS_REQUIRED')});
test('packet blocks a genuine Phase 4 deterministic FAIL',()=>{const p=init(),x=receipt(p);baseline(p,x.path);const r3=p3(p,x.path);assert.equal(r3.r.status,0);const r4=p4(p,x.path,r3.out,'initial','contrast');assert.equal(r4.r.status,3);const r=run(judge,p,['packet','prepare','--project-root',p,'--receipt',x.path,'--phase3-report',r3.out,'--phase4-report',r4.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'PHASE4_PASS_REQUIRED')});
test('PASS judgment computes final score instead of trusting a claimed overall',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'pass'});assert.equal(j.r.status,0,j.r.stdout);assert.equal(j.o.status,'VISUAL_JUDGMENT_PASS');assert.equal(j.o.judgment.summary.overall_score,95);assert.equal(j.o.judgment.claims.visual_quality_verified,true)});
test('FAIL judgment is sealed and returns nonzero without becoming BLOCKED',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(j.r.status,3,j.r.stdout);assert.equal(j.o.status,'VISUAL_JUDGMENT_FAIL');assert.equal(j.o.judgment.claims.visual_quality_verified,false);assert.equal(j.o.judgment.cases[0].verdict,'FAIL')});
test('UNVERIFIED visual dimension produces BLOCKED rather than guessed FAIL/PASS',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'blocked'});assert.equal(j.r.status,4,j.r.stdout);assert.equal(j.o.status,'VISUAL_JUDGMENT_BLOCKED')});
test('native image observation is mandatory',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.judge.observation_mode='TEXT_ONLY';return s}});assert.notEqual(j.r.status,0);assert.equal(j.o.status,'VISUAL_JUDGMENT_SUBMISSION_INVALID');assert.ok(j.o.errors.includes('native_visual_observation_required'))});
test('judge identity is pinned to dedicated visual-judge role',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.judge.agent_id='repairer';return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.includes('judge_agent_invalid'))});
test('model reference is mandatory for semantic judgment provenance',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.judge.model_ref='';return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.includes('model_ref_required'))});
test('observed screenshot hash must match the packet evidence',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.cases[0].observed_screenshot_sha256='0'.repeat(64);return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.some(x=>x.startsWith('screenshot_observation_mismatch:')))});
test('all rubric dimensions are mandatory exactly once',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.cases[0].dimensions.pop();return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.some(x=>x.startsWith('dimension_set_mismatch:')))});
test('dimension score/status inconsistency is rejected',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.cases[0].dimensions[0].status='PASS';s.cases[0].dimensions[0].score=20;return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.some(x=>x.startsWith('dimension_status_score_mismatch:')))});
test('failed dimension requires a concrete finding',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{mutate:s=>{s.cases[0].dimensions[0].status='FAIL';s.cases[0].dimensions[0].score=60;s.cases[0].findings=[];return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.some(x=>x.startsWith('failed_dimension_finding_missing:')))});
test('critical visual finding must be blocking',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail',mutate:s=>{s.cases[0].findings[0].severity='CRITICAL';s.cases[0].findings[0].blocking=false;return s}});assert.notEqual(j.r.status,0);assert.ok(j.o.errors.some(x=>x.startsWith('critical_finding_must_block:')))});
test('overall score below 90 fails even if every dimension individually passes',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),s=submissionObject(pk.o.packet,{kind:'overall-low'}),inp=w(p,'.aledevos/state/visualqa/phase5/submissions/low.json',JSON.stringify(s)),out=path.join(p,'.aledevos/state/visualqa/phase5/judgments/low.json'),r=run(judge,p,['judgment','seal','--project-root',p,'--packet',pk.out,'--input',inp,'--out',out]);assert.equal(r.status,3,r.stdout);assert.equal(jout(r).judgment.summary.overall_score,89)});
test('judgment verification succeeds for semantic FAIL reports',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'}),r=run(judge,p,['judgment','verify','--project-root',p,'--judgment',j.out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_JUDGMENT_REPORT_VALID')});
test('judgment tampering is detected',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk),o=JSON.parse(fs.readFileSync(j.out));o.status='VISUAL_JUDGMENT_FAIL';fs.writeFileSync(j.out,JSON.stringify(o));const r=run(judge,p,['judgment','verify','--project-root',p,'--judgment',j.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('judgment_integrity_mismatch'))});
test('submission drift invalidates a sealed judgment',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk);fs.appendFileSync(j.input,' ');const r=run(judge,p,['judgment','verify','--project-root',p,'--judgment',j.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('submission_file_drift'))});
test('repair authorization requires global repair-start first',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'}),r=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'GLOBAL_REPAIR_NOT_STARTED')});
test('BLOCKED visual judgment is not eligible for automatic repair',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'blocked'});assert.equal(run(core,p,['state','repair-start']).status,0);const r=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'BLOCKED_JUDGMENT_NOT_AUTO_REPAIRABLE')});
test('PASS judgment cannot open a repair plan',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk);assert.equal(run(core,p,['state','repair-start']).status,0);const r=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'FAILED_JUDGMENT_REQUIRED')});
test('repair plan binds attempt, approved scope, findings, and no-baseline-promotion rules',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const r=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.equal(r.status,0,r.stdout);const q=jout(r).repair_plan;assert.equal(q.attempt,1);assert.deepEqual(q.authorized_scope,['src/**']);assert.ok(q.findings.length);assert.equal(q.requirements.baseline_promotion_forbidden,true);assert.equal(q.requirements.fresh_phase2_required,true)});
test('repair plans are immutable per repair attempt',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const a=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.equal(a.status,0);const b=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]);assert.notEqual(b.status,0);assert.equal(jout(b).status,'REPAIR_PLAN_IMMUTABLE')});
test('repair plan detects global scope-version drift',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const a=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(a).path);assert.equal(run(core,p,['state','scope-approve','--add','styles/**']).status,0);const r=run(judge,p,['repair','verify','--project-root',p,'--plan',plan]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('global_scope_version_drift'))});
test('repair cycle refuses stale P2/P3/P4 evidence',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const a=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(a).path),after=seal(p,pk,{kind:'pass',revision:'same-evidence'});assert.equal(after.r.status,0);const r=run(judge,p,['cycle','finalize','--project-root',p,'--before',j.out,'--plan',plan,'--after',after.out]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'STALE_POST_REPAIR_EVIDENCE')});
test('successful repair requires fresh P2 -> P3 -> P4 -> Visual Judge evidence',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(ar).path),fresh=freshPassAfterRepair(p);const out=path.join(p,'.aledevos/state/visualqa/phase5/cycles/cycle-1.json'),r=run(judge,p,['cycle','finalize','--project-root',p,'--before',j.out,'--plan',plan,'--after',fresh.j.out,'--out',out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_REPAIR_CYCLE_PASS');assert.deepEqual(jout(r).cycle.fresh_evidence,{phase2:true,phase3:true,phase4:true,judgment:true})});
test('historical failed judgment remains usable after source changes because repair authorization sealed it first',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(ar).path);w(p,'src/pages/Home.tsx','export const Home=()=> <main>Changed</main>');const r=run(judge,p,['repair','verify','--project-root',p,'--plan',plan]);assert.equal(r.status,0,r.stdout)});
test('failed repair 1 allows one more bounded retry',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(ar).path);w(p,'src/pages/Home.tsx','export const Home=()=> <main data-repair="1">Home</main>');const u2=upstream(p,{revision:'repair-1'}),pk2=packet(p,u2,'repair-1'),j2=seal(p,pk2,{kind:'fail',revision:'repair-1'});const r=run(judge,p,['cycle','finalize','--project-root',p,'--before',j.out,'--plan',plan,'--after',j2.out]);assert.equal(r.status,3,r.stdout);assert.equal(jout(r).status,'VISUAL_REPAIR_RETRY_ALLOWED')});
test('repair 2 failure exhausts the visual repair loop; there is no third visual repair',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);let ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan1=path.join(p,jout(ar).path);w(p,'src/pages/Home.tsx','export const Home=()=> <main data-repair="1">Home</main>');let u2=upstream(p,{revision:'repair-1'}),pk2=packet(p,u2,'repair-1'),j2=seal(p,pk2,{kind:'fail',revision:'repair-1'});let c1=run(judge,p,['cycle','finalize','--project-root',p,'--before',j.out,'--plan',plan1,'--after',j2.out]);assert.equal(c1.status,3);assert.equal(run(core,p,['state','repair-start']).status,0);ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j2.out]);const plan2=path.join(p,jout(ar).path);w(p,'src/pages/Home.tsx','export const Home=()=> <main data-repair="2">Home</main>');const u3=upstream(p,{revision:'repair-2'}),pk3=packet(p,u3,'repair-2'),j3=seal(p,pk3,{kind:'fail',revision:'repair-2'});const c2=run(judge,p,['cycle','finalize','--project-root',p,'--before',j2.out,'--plan',plan2,'--after',j3.out]);assert.equal(c2.status,7,c2.stdout);assert.equal(jout(c2).status,'VISUAL_REPAIR_EXHAUSTED');const third=run(core,p,['state','repair-start']);assert.equal(third.status,4);assert.match(third.stdout,/MAX_REPAIRS_REACHED/)});
test('acceptance PASS works directly when no repair was needed',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk),out=path.join(p,'.aledevos/state/visualqa/phase5/acceptance/final.json'),r=run(judge,p,['acceptance','seal','--project-root',p,'--judgment',j.out,'--out',out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_QA_PASS');assert.equal(jout(r).acceptance.repair_count,0)});
test('acceptance after repair requires the latest successful repair cycle',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk,{kind:'fail'});assert.equal(run(core,p,['state','repair-start']).status,0);const ar=run(judge,p,['repair','authorize','--project-root',p,'--judgment',j.out]),plan=path.join(p,jout(ar).path),fresh=freshPassAfterRepair(p),cycle=path.join(p,'.aledevos/state/visualqa/phase5/cycles/cycle-1.json');assert.equal(run(judge,p,['cycle','finalize','--project-root',p,'--before',j.out,'--plan',plan,'--after',fresh.j.out,'--out',cycle]).status,0);const noCycle=run(judge,p,['acceptance','seal','--project-root',p,'--judgment',fresh.j.out]);assert.notEqual(noCycle.status,0);assert.equal(jout(noCycle).status,'LATEST_REPAIR_CYCLE_REQUIRED');const ok=run(judge,p,['acceptance','seal','--project-root',p,'--judgment',fresh.j.out,'--cycle',cycle]);assert.equal(ok.status,0,ok.stdout)});
test('sealed final acceptance verifies',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk),out=path.join(p,'.aledevos/state/visualqa/phase5/acceptance/final.json');assert.equal(run(judge,p,['acceptance','seal','--project-root',p,'--judgment',j.out,'--out',out]).status,0);const r=run(judge,p,['acceptance','verify','--project-root',p,'--acceptance',out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'VISUAL_QA_ACCEPTANCE_VALID')});
test('P5 final acceptance explicitly does not claim motion quality or full WCAG',()=>{const p=init(),u=upstream(p,{approve:true}),pk=packet(p,u),j=seal(p,pk),out=path.join(p,'.aledevos/state/visualqa/phase5/acceptance/final.json');const r=run(judge,p,['acceptance','seal','--project-root',p,'--judgment',j.out,'--out',out]),c=jout(r).acceptance.claims;assert.equal(c.visual_quality_verified,true);assert.equal(c.motion_quality_verified,false);assert.equal(c.full_wcag_conformance_verified,false)});
test('Phase 5 policy pins holistic thresholds and two-repair cap',()=>{const p=JSON.parse(fs.readFileSync('visualqa/policies/visualqa-policy.json')).phase5;assert.equal(p.dimension_pass_score,80);assert.equal(p.overall_pass_score,90);assert.equal(p.max_repairs,2);assert.equal(p.automatic_baseline_promotion_forbidden,true);assert.equal(p.observation_mode,'NATIVE_IMAGE')});
