import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {once} from 'node:events';

const ux=path.resolve('uxui/engine/uxui.mjs');
const quality=path.resolve('uxui/engine/ui-quality.mjs');
const vqa=path.resolve('visualqa/engine/visualqa.mjs');
const runner=path.resolve('visualqa/engine/browser-runner.mjs');
const fixture=path.resolve('tests/fixtures/vqa-test-provider.mjs');
const serverScript=path.resolve('tests/fixtures/vqa-server.mjs');
let server,baseUrl;
const jout=r=>JSON.parse(r.stdout||'{}');
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'aledevos-vqa-p2-'));
const w=(p,r,c='')=>{const f=path.join(p,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c,'utf8');return f};
function run(runtime,cwd,args=[],env={}){return spawnSync(process.execPath,[runtime,...args],{cwd,encoding:'utf8',env:{...process.env,...env}})}
async function startServer(){server=spawn(process.execPath,[serverScript],{stdio:['ignore','pipe','pipe']});let buf='';server.stdout.setEncoding('utf8');server.stdout.on('data',d=>buf+=d);for(let i=0;i<100&&!buf.includes('\n');i++)await new Promise(r=>setTimeout(r,20));assert.ok(buf.includes('\n'),'server did not start');baseUrl=`http://127.0.0.1:${Number(buf.trim())}`}
before(startServer);after(()=>{if(server&&!server.killed)server.kill('SIGTERM')});
function init(){const p=tmp();w(p,'package.json','{}');assert.equal(run(ux,p,['context','init','--project-root',p]).status,0);assert.equal(run(quality,p,['standards','init','--project-root',p]).status,0);const rf=w(p,'responsive.json',JSON.stringify({strategy:'FLUID',viewports:[{id:'narrow',width:390,height:844,expectation:'No horizontal overflow.'},{id:'wide',width:1440,height:900,expectation:'Wide.'}],container_policy:'canonical',overflow_policy:'none',source_ref:'UI-ADR-1001'}));assert.equal(run(quality,p,['responsive','approve','--project-root',p,'--input',rf,'--approval-ref','human:approved']).status,0);w(p,'src/pages/Home.tsx','export const Home=()=> <main>Home</main>');const tp=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');fs.mkdirSync(path.dirname(tp),{recursive:true});fs.copyFileSync(fixture,tp);return p}
function makePlan(p,{states=['DEFAULT'],viewports=['narrow'],task='task-ui-002'}={}){const req=w(p,'capture-request.json',JSON.stringify({task_id:task,base_url:baseUrl,changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route:'/',viewport_ids:viewports,states,state_contract_path:null}]}));const out=path.join(p,`.aledevos/state/visualqa/phase1/plans/${task}.json`);const r=run(vqa,p,['plan','create','--project-root',p,'--input',req,'--out',out]);assert.equal(r.status,0,r.stdout);return {out,plan:jout(r).plan}}
function makeSpec(p,plan,{bindings=[],overrides={}}={}){return w(p,'browser-spec.json',JSON.stringify({task_id:plan.task_id,provider:'playwright',browser:'chromium',stable_ms:0,case_bindings:bindings,...overrides}))}
function execute(p,pi,opts={}){const spec=opts.spec||makeSpec(p,pi.plan,opts);const out=path.join(p,`.aledevos/state/visualqa/phase2/receipts/${pi.plan.task_id}.json`);const provider=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');const args=['run','execute','--project-root',p,'--plan',pi.out,'--spec',spec,'--out',out,'--provider-module',provider];const r=run(runner,p,args,{ALEDEVOS_TEST_MODE:'1',...(opts.env||{})});return {r,o:jout(r),out,spec}}

test('doctor accepts controlled test provider only in test mode',()=>{const p=init(),provider=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');const r=run(runner,p,['doctor','--project-root',p,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1'});assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'BROWSER_RUNNER_READY')});
test('arbitrary provider module is forbidden outside test mode',()=>{const p=init(),provider=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');const r=run(runner,p,['doctor','--project-root',p,'--provider-module',provider]);assert.notEqual(r.status,0);assert.equal(jout(r).status,'TEST_PROVIDER_FORBIDDEN')});
test('test provider must stay inside controlled project subdir',()=>{const p=init();const r=run(runner,p,['doctor','--project-root',p,'--provider-module',fixture],{ALEDEVOS_TEST_MODE:'1'});assert.notEqual(r.status,0);assert.equal(jout(r).status,'TEST_PROVIDER_PATH_INVALID')});
test('default state executes exact plan viewport and seals receipt',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi);assert.equal(x.r.status,0,x.r.stdout);assert.equal(x.o.status,'BROWSER_CAPTURE_COMPLETE');assert.equal(x.o.receipt.captures[0].viewport.width,390);assert.equal(x.o.receipt.captures[0].state_attestation,'DEFAULT_ROUTE');assert.ok(fs.existsSync(path.join(p,pi.plan.cases[0].expected_screenshot_path)))});
test('phase2 successful receipt attests rendering but not visual quality',()=>{const p=init(),x=execute(p,makePlan(p));assert.equal(x.r.status,0);assert.deepEqual(x.o.receipt.claims,{screenshot_capture_executed:true,render_execution_attested:true,visual_quality_verified:false,visual_regression_verified:false})});
test('controlled Phase 2 providers are explicitly marked as test provenance',()=>{const p=init(),x=execute(p,makePlan(p));assert.equal(x.r.status,0);assert.equal(x.o.receipt.provider.provenance,'CONTROLLED_TEST_PROVIDER')});
test('phase2 automatically seals compatible phase1 evidence run',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi);assert.equal(x.r.status,0);const rp=path.join(p,x.o.receipt.phase1_run_path);assert.ok(fs.existsSync(rp));const r=run(vqa,p,['run','verify','--project-root',p,'--run',rp]);assert.equal(r.status,0,r.stdout)});
test('non-default state requires explicit ready selector',()=>{const p=init(),pi=makePlan(p,{states:['LOADING']}),x=execute(p,pi);assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes(`state_ready_selector_required:${pi.plan.cases[0].case_id}`))});
test('non-default state with ready selector is attested',()=>{const p=init(),pi=makePlan(p,{states:['LOADING']}),cid=pi.plan.cases[0].case_id,x=execute(p,pi,{bindings:[{case_id:cid,route_suffix:'?vqaState=loading',ready_selector:'[data-vqa-state="LOADING"]'}]});assert.equal(x.r.status,0,x.r.stdout);assert.equal(x.o.receipt.captures[0].state_attestation,'READY_SELECTOR_VISIBLE');assert.equal(x.o.receipt.captures[0].route_suffix,'?vqaState=loading')});
test('unknown case binding is blocked',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi,{bindings:[{case_id:'ghost',ready_selector:'#x'}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('binding_unknown_case:ghost'))});
test('duplicate case bindings are blocked',()=>{const p=init(),pi=makePlan(p),cid=pi.plan.cases[0].case_id,x=execute(p,pi,{bindings:[{case_id:cid},{case_id:cid}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes(`binding_duplicate:${cid}`))});
test('route suffix cannot change the planned path',()=>{const p=init(),pi=makePlan(p),cid=pi.plan.cases[0].case_id,x=execute(p,pi,{bindings:[{case_id:cid,route_suffix:'/other'}]});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes(`route_suffix_invalid:${cid}`))});
test('stable delay is bounded by policy',()=>{const p=init(),pi=makePlan(p),spec=makeSpec(p,pi.plan,{overrides:{stable_ms:9000}}),x=execute(p,pi,{spec});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('stable_ms_invalid'))});
test('unsupported provider is blocked',()=>{const p=init(),pi=makePlan(p),spec=makeSpec(p,pi.plan,{overrides:{provider:'other'}}),x=execute(p,pi,{spec});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('provider_not_allowed'))});
test('unsupported browser is blocked',()=>{const p=init(),pi=makePlan(p),spec=makeSpec(p,pi.plan,{overrides:{browser:'firefox'}}),x=execute(p,pi,{spec});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('browser_not_allowed'))});
test('execution spec task mismatch is blocked',()=>{const p=init(),pi=makePlan(p),spec=makeSpec(p,pi.plan,{overrides:{task_id:'wrong'}}),x=execute(p,pi,{spec});assert.notEqual(x.r.status,0);assert.ok(x.o.errors.includes('task_id_mismatch'))});
test('plan tampering blocks before browser execution',()=>{const p=init(),pi=makePlan(p),o=JSON.parse(fs.readFileSync(pi.out));o.base_url='http://127.0.0.1:1';fs.writeFileSync(pi.out,JSON.stringify(o));const x=execute(p,pi);assert.notEqual(x.r.status,0);assert.equal(x.o.status,'CAPTURE_PLAN_INVALID')});
test('source drift blocks before browser execution',()=>{const p=init(),pi=makePlan(p);w(p,'src/pages/Home.tsx','changed');const x=execute(p,pi);assert.notEqual(x.r.status,0);assert.equal(x.o.status,'CAPTURE_PLAN_INVALID')});
test('unreachable dev server blocks execution',()=>{const p=init(),pi=makePlan(p);const o=JSON.parse(fs.readFileSync(pi.out));o.base_url='http://127.0.0.1:1';o.plan_sha256='';fs.writeFileSync(pi.out,JSON.stringify(o));const rr=run(vqa,p,['plan','create','--project-root',p,'--input',w(p,'bad-server-request.json',JSON.stringify({task_id:'badserver',base_url:'http://127.0.0.1:1',changed_files:['src/pages/Home.tsx'],surfaces:[{id:'home',route:'/',viewport_ids:['narrow'],states:['DEFAULT'],state_contract_path:null}]})),'--out',path.join(p,'.aledevos/state/visualqa/phase1/plans/badserver.json')]);assert.equal(rr.status,0);const pi2={out:path.join(p,'.aledevos/state/visualqa/phase1/plans/badserver.json'),plan:jout(rr).plan};const x=execute(p,pi2);assert.notEqual(x.r.status,0);assert.equal(x.o.status,'DEV_SERVER_UNAVAILABLE')});
test('provider failure blocks without a success receipt',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi,{env:{VQA_FIXTURE_MODE:'fail'}});assert.notEqual(x.r.status,0);assert.equal(x.o.status,'BROWSER_CAPTURE_BLOCKED');assert.equal(x.o.captures_completed,0)});
test('non-PNG provider output is blocked',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi,{env:{VQA_FIXTURE_MODE:'nonpng'}});assert.notEqual(x.r.status,0);assert.equal(x.o.failure.status,'CAPTURE_NOT_PNG')});

test('execution spec outside the project is blocked',()=>{const p=init(),pi=makePlan(p),external=path.join(os.tmpdir(),`vqa-spec-${Date.now()}.json`);fs.writeFileSync(external,JSON.stringify({task_id:pi.plan.task_id,provider:'playwright',browser:'chromium',case_bindings:[]}));const provider=path.join(p,'.aledevos/state/visualqa/test-providers/provider.mjs');const r=run(runner,p,['run','execute','--project-root',p,'--plan',pi.out,'--spec',external,'--provider-module',provider],{ALEDEVOS_TEST_MODE:'1'});assert.notEqual(r.status,0);assert.equal(jout(r).status,'EXECUTION_SPEC_PATH_INVALID');fs.rmSync(external,{force:true})});
test('cross-origin browser redirect is blocked',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi,{env:{VQA_FIXTURE_MODE:'redirect-origin'}});assert.notEqual(x.r.status,0);assert.equal(x.o.failure.status,'CAPTURE_REDIRECT_ORIGIN_CHANGED')});
test('unexpected browser path redirect is blocked',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi,{env:{VQA_FIXTURE_MODE:'redirect-path'}});assert.notEqual(x.r.status,0);assert.equal(x.o.failure.status,'CAPTURE_REDIRECT_PATH_CHANGED')});
test('receipt verification succeeds immediately after capture',()=>{const p=init(),x=execute(p,makePlan(p));assert.equal(x.r.status,0);const r=run(runner,p,['run','verify','--project-root',p,'--receipt',x.out]);assert.equal(r.status,0,r.stdout);assert.equal(jout(r).status,'BROWSER_CAPTURE_RECEIPT_VALID')});
test('receipt tampering is detected',()=>{const p=init(),x=execute(p,makePlan(p));const o=JSON.parse(fs.readFileSync(x.out));o.determinism.locale='xx-XX';fs.writeFileSync(x.out,JSON.stringify(o));const r=run(runner,p,['run','verify','--project-root',p,'--receipt',x.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('receipt_integrity_mismatch'))});
test('execution spec drift invalidates receipt',()=>{const p=init(),x=execute(p,makePlan(p));fs.appendFileSync(x.spec,'\n ');const r=run(runner,p,['run','verify','--project-root',p,'--receipt',x.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('execution_spec_drift'))});
test('screenshot drift invalidates receipt',()=>{const p=init(),pi=makePlan(p),x=execute(p,pi);fs.appendFileSync(path.join(p,pi.plan.cases[0].expected_screenshot_path),'x');const r=run(runner,p,['run','verify','--project-root',p,'--receipt',x.out]);assert.notEqual(r.status,0);const errs=jout(r).errors;assert.ok(errs.includes(`capture_drift:${pi.plan.cases[0].case_id}`)||errs.includes('phase1_run_invalid'))});
test('phase1 evidence drift invalidates receipt',()=>{const p=init(),x=execute(p,makePlan(p));fs.appendFileSync(path.join(p,x.o.receipt.phase1_run_path),' ');const r=run(runner,p,['run','verify','--project-root',p,'--receipt',x.out]);assert.notEqual(r.status,0);assert.ok(jout(r).errors.includes('phase1_run_drift'))});
test('receipt stores references and hashes, not screenshot bytes',()=>{const p=init(),x=execute(p,makePlan(p));assert.equal(x.r.status,0);const raw=fs.readFileSync(x.out,'utf8');assert.ok(!raw.includes('iVBORw0KGgo'));assert.ok(raw.includes('screenshot_path'));assert.ok(raw.includes('sha256'))});

test('Phase 2 policy pins deterministic browser-capture defaults',()=>{const o=JSON.parse(fs.readFileSync(path.resolve('visualqa/policies/visualqa-policy.json'),'utf8')).phase2;assert.equal(o.provider,'playwright');assert.deepEqual(o.allowed_browsers,['chromium']);assert.equal(o.device_scale_factor,1);assert.equal(o.wait_for_fonts,true);assert.equal(o.freeze_animations,true);assert.equal(o.sequential_cases,true);assert.equal(o.visual_quality_claim_deferred,true)});
test('installer deploys Phase 2 runner adapter provider contracts and state roots',()=>{const s=fs.readFileSync(path.resolve('scripts/05-install-into-project.ps1'),'utf8');assert.match(s,/browser-runner\.mjs/);assert.match(s,/\$adapterRoot 'visualqa'/);assert.match(s,/VISUAL_QA_\*\.md/);assert.match(s,/phase2\\receipts/);assert.match(s,/phase2\\results/)});
test('dedicated OpenCode visual capture agent is narrow and cannot edit product files',()=>{const s=fs.readFileSync(path.resolve('adapters/opencode/.opencode/agents/visual-capture-runner.md'),'utf8');assert.match(s,/action: edit[\s\S]*resource: "\*"[\s\S]*effect: deny/);assert.match(s,/browser-runner\.mjs run execute/);assert.match(s,/browser-runner\.mjs run verify/);assert.match(s,/action: webfetch[\s\S]*effect: deny/)});
test('read-only visual judges can verify Phase 2 receipts but cannot execute capture',()=>{for(const n of ['design-system-guardian','judge-uxui','judge-quality','verifier']){const s=fs.readFileSync(path.resolve(`adapters/opencode/.opencode/agents/${n}.md`),'utf8');assert.match(s,/browser-runner\.mjs run verify/);assert.ok(!s.includes('browser-runner.mjs run execute'),n)}});
test('Phase 2 Core contract preserves later visual-quality boundary',()=>{const s=fs.readFileSync(path.resolve('core/design/contracts/VISUAL_QA_BROWSER_CAPTURE.md'),'utf8');assert.match(s,/does \*\*not\*\* prove visual correctness/i);assert.match(s,/non-default state requires an explicit `ready_selector`/i);assert.match(s,/does not execute arbitrary JavaScript/i)});
