#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath, pathToFileURL} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const distRoot=path.resolve(here,'..');
const args=process.argv.slice(2);
const [group,cmd]=args;
const HASH=/^[a-f0-9]{64}$/;
const PNG=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
function take(flag,f=null){const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:f}
function fail(status,code=1,extra={}){process.stdout.write(JSON.stringify({status,...extra},null,2)+'\n');process.exit(code)}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n','utf8')}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort()){if(!['plan_sha256','run_sha256','receipt_sha256','integrity_sha256','contract_sha256','review_sha256'].includes(k))o[k]=stable(v[k])}return o}return v}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(stable(v))).digest('hex')}
function fileSha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function norm(p){return String(p||'').replaceAll('\\','/').replace(/^\.\//,'')}
function rootOf(p){const r=path.resolve(p||process.cwd());if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())fail('PROJECT_ROOT_INVALID',90);return r}
function inside(root,p){const rr=path.resolve(root)+path.sep, aa=path.resolve(p);return aa===path.resolve(root)||aa.startsWith(rr)}
function safeRel(v){const n=norm(v);return !!n&&!path.isAbsolute(v)&&!n.split('/').includes('..')&&!n.startsWith('/')}
function relWithin(root,rel){if(!safeRel(rel))return null;const a=path.resolve(root,rel);return inside(root,a)?a:null}
function asRel(root,abs){return norm(path.relative(root,abs))}
function pngOk(p){if(!fs.existsSync(p)||!fs.statSync(p).isFile())return false;const b=fs.readFileSync(p);return b.length>=8&&b.subarray(0,8).equals(PNG)}
function policy(){return readJson(path.join(distRoot,'policies','visualqa-policy.json')).phase2}
function validSeal(o,field){return !!o&&typeof o[field]==='string'&&HASH.test(o[field])&&o[field]===sha(o)}
function phase1Cli(){return path.join(here,'visualqa.mjs')}
function callPhase1(root,argv){const r=spawnSync(process.execPath,[phase1Cli(),...argv,'--project-root',root],{encoding:'utf8'});let o=null;try{o=JSON.parse(r.stdout||'{}')}catch{}return {status:r.status,stdout:r.stdout,stderr:r.stderr,obj:o}}
function verifyPlan(root,plan){const r=callPhase1(root,['plan','verify','--plan',plan]);if(r.status!==0||!r.obj?.valid)fail('CAPTURE_PLAN_INVALID',120,{errors:r.obj?.errors||['phase1_verify_failed']});return r.obj.plan}
function verifyPhase1Run(root,run){const r=callPhase1(root,['run','verify','--run',run]);return r.status===0&&r.obj?.valid?{valid:true,obj:r.obj}:{valid:false,obj:r.obj}}
function validateSuffix(s,re){if(s==null||s==='')return true;return typeof s==='string'&&new RegExp(re).test(s)&&!s.includes('://')&&!s.startsWith('//')}
function selectorOk(v,max){return typeof v==='string'&&v.length>0&&v.length<=max&&!/[\r\n]/.test(v)}
function buildUrl(base,route,suffix=''){const b=new URL(base);const u=new URL(route+suffix,b);if(u.origin!==b.origin)throw Object.assign(new Error('URL_ORIGIN_CHANGED'),{code:'URL_ORIGIN_CHANGED'});if(u.pathname!==new URL(route,b).pathname)throw Object.assign(new Error('ROUTE_PATH_CHANGED'),{code:'ROUTE_PATH_CHANGED'});return u.toString()}
async function probe(url,p){for(let i=0;i<p.server_probe_retries;i++){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),p.server_probe_timeout_ms);const r=await fetch(url,{method:'GET',redirect:'manual',signal:c.signal});clearTimeout(t);if(r.status<500)return {ok:true,status:r.status,attempts:i+1}}catch{}if(i+1<p.server_probe_retries)await new Promise(res=>setTimeout(res,p.server_probe_delay_ms))}return {ok:false,status:null,attempts:p.server_probe_retries}}
function validateSpec(plan,q,p){const errors=[];if(q.task_id!==plan.task_id)errors.push('task_id_mismatch');if((q.provider||p.provider)!==p.provider)errors.push('provider_not_allowed');const browser=q.browser||p.allowed_browsers[0];if(!p.allowed_browsers.includes(browser))errors.push('browser_not_allowed');const stableMs=q.stable_ms??p.stable_ms;if(!Number.isInteger(stableMs)||stableMs<0||stableMs>p.max_stable_ms)errors.push('stable_ms_invalid');const bindings=Array.isArray(q.case_bindings)?q.case_bindings:[];const seen=new Set();const caseIds=new Set((plan.cases||[]).map(c=>c.case_id));for(const b of bindings){if(seen.has(b.case_id))errors.push(`binding_duplicate:${b.case_id}`);seen.add(b.case_id);if(!caseIds.has(b.case_id))errors.push(`binding_unknown_case:${b.case_id}`);if(!validateSuffix(b.route_suffix,p.route_suffix_pattern))errors.push(`route_suffix_invalid:${b.case_id}`);if(b.ready_selector!=null&&!selectorOk(b.ready_selector,p.ready_selector_max_length))errors.push(`ready_selector_invalid:${b.case_id}`)}const bm=new Map(bindings.map(b=>[b.case_id,b]));if(p.non_default_state_requires_ready_selector){for(const c of plan.cases||[]){if(String(c.state).toUpperCase()!=='DEFAULT'&&!selectorOk(bm.get(c.case_id)?.ready_selector,p.ready_selector_max_length))errors.push(`state_ready_selector_required:${c.case_id}`)}}return {errors,browser,stableMs,bindingMap:bm}}
async function loadProvider(root,p,providerModule){if(providerModule){if(process.env.ALEDEVOS_TEST_MODE!=='1')fail('TEST_PROVIDER_FORBIDDEN',130);const a=path.resolve(providerModule);const allowed=path.resolve(root,p.test_provider_subdir);if(!inside(allowed,a)||!fs.existsSync(a))fail('TEST_PROVIDER_PATH_INVALID',131);return import(pathToFileURL(a).href)}return import(pathToFileURL(path.join(distRoot,'providers','playwright-driver.mjs')).href)}
function publicDriverResult(r){return {navigation_status:r?.navigation_status??null,final_url:r?.final_url??null,page_error_count:Number(r?.page_error_count||0),console_error_count:Number(r?.console_error_count||0),state_attestation:r?.state_attestation||null,duration_ms:Number.isFinite(r?.duration_ms)?r.duration_ms:null}}
function runtimeConfig(p,q,browser,stableMs){return {browser,headless:true,device_scale_factor:p.device_scale_factor,locale:q.locale||p.locale,timezone_id:q.timezone_id||p.timezone_id,color_scheme:q.color_scheme||p.color_scheme,reduced_motion:p.reduced_motion,service_workers:p.service_workers,navigation_wait_until:p.navigation_wait_until,navigation_timeout_ms:p.navigation_timeout_ms,selector_timeout_ms:p.selector_timeout_ms,wait_for_fonts:p.wait_for_fonts,freeze_animations:p.freeze_animations,hide_caret:p.hide_caret,stable_ms:stableMs,fail_on_page_error:p.fail_on_page_error,fail_on_console_error:p.fail_on_console_error,full_page:p.full_page,screenshot_scale:p.screenshot_scale}}
async function doctor(root,providerModule){const p=policy();const mod=await loadProvider(root,p,providerModule);if(typeof mod.doctor!=='function')fail('PROVIDER_CONTRACT_INVALID',132);const r=await mod.doctor({browser:p.allowed_browsers[0]});return {status:r.ok?'BROWSER_RUNNER_READY':'BROWSER_RUNNER_NOT_READY',provider:r}}
async function execute(root,planPath,specPath,outPath,providerModule){const p=policy();if(!inside(root,path.resolve(specPath))||!fs.existsSync(path.resolve(specPath)))fail('EXECUTION_SPEC_PATH_INVALID',139);const plan=verifyPlan(root,planPath);const q=readJson(specPath);const v=validateSpec(plan,q,p);if(v.errors.length)fail('CAPTURE_EXECUTION_SPEC_INVALID',140,{errors:v.errors});const pr=await probe(plan.base_url,p);if(!pr.ok)fail('DEV_SERVER_UNAVAILABLE',141,{attempts:pr.attempts});const mod=await loadProvider(root,p,providerModule);if(typeof mod.createSession!=='function')fail('PROVIDER_CONTRACT_INVALID',142);const cfg=runtimeConfig(p,q,v.browser,v.stableMs);let session;try{session=await mod.createSession(cfg)}catch(e){fail(e?.code||'BROWSER_SESSION_FAILED',143)}const startedAt=new Date().toISOString();const started=Date.now();const captures=[];const results=[];let failure=null;try{for(const c of plan.cases){const b=v.bindingMap.get(c.case_id)||{};let url;try{url=buildUrl(plan.base_url,c.route,b.route_suffix||'')}catch(e){failure={status:e?.code||'CAPTURE_URL_INVALID',case_id:c.case_id};break}const out=relWithin(root,c.expected_screenshot_path);if(!out){failure={status:'CAPTURE_OUTPUT_PATH_INVALID',case_id:c.case_id};break}fs.mkdirSync(path.dirname(out),{recursive:true});try{const r=await session.capture({case_id:c.case_id,url,viewport:{width:c.viewport.width,height:c.viewport.height},ready_selector:b.ready_selector||null,output_path:out});if(!r?.ok){failure={status:r?.status||'CAPTURE_FAILED',case_id:c.case_id};break}try{const fu=new URL(r.final_url||url),eu=new URL(url);if(fu.origin!==eu.origin){failure={status:'CAPTURE_REDIRECT_ORIGIN_CHANGED',case_id:c.case_id};break}if(fu.pathname!==eu.pathname){failure={status:'CAPTURE_REDIRECT_PATH_CHANGED',case_id:c.case_id};break}}catch{failure={status:'CAPTURE_FINAL_URL_INVALID',case_id:c.case_id};break}if(!pngOk(out)){failure={status:'CAPTURE_NOT_PNG',case_id:c.case_id};break}const pub=publicDriverResult(r);captures.push({case_id:c.case_id,screenshot_path:c.expected_screenshot_path,sha256:fileSha(out),bytes:fs.statSync(out).size,viewport:{width:c.viewport.width,height:c.viewport.height},state:c.state,route:c.route,route_suffix:b.route_suffix||null,ready_selector:b.ready_selector||null,...pub});results.push({case_id:c.case_id,screenshot_path:c.expected_screenshot_path})}catch(e){failure={status:e?.code||'CAPTURE_FAILED',case_id:c.case_id};break}}}finally{try{await session?.close?.()}catch{}}
if(failure)fail('BROWSER_CAPTURE_BLOCKED',144,{failure,captures_completed:captures.length});const evidenceSuffix=plan.evidence_id?`--${plan.evidence_id}`:'';const resultPath=path.join(root,p.results_root,`${plan.task_id}${evidenceSuffix}.json`);writeJson(resultPath,{task_id:plan.task_id,evidence_id:plan.evidence_id||null,results});const phase1RunPath=path.join(root,'.aledevos/state/visualqa/phase1/runs',`${plan.task_id}${evidenceSuffix}.json`);const sr=callPhase1(root,['run','seal','--plan',path.resolve(planPath),'--input',resultPath,'--out',phase1RunPath]);if(sr.status!==0)fail('PHASE1_EVIDENCE_SEAL_FAILED',145,{errors:sr.obj?.errors||[sr.obj?.status||'unknown']});const endedAt=new Date().toISOString();const receipt={schema_version:'1.0',phase:'VISUAL_QA_P2',task_id:plan.task_id,evidence_id:plan.evidence_id||null,status:'BROWSER_CAPTURE_COMPLETE',claims:{screenshot_capture_executed:true,render_execution_attested:true,visual_quality_verified:false,visual_regression_verified:false},plan_path:asRel(root,path.resolve(planPath)),plan_sha256:plan.plan_sha256,execution_spec_path:asRel(root,path.resolve(specPath)),execution_spec_sha256:fileSha(path.resolve(specPath)),phase1_run_path:asRel(root,phase1RunPath),phase1_run_sha256:fileSha(phase1RunPath),provider:{id:p.provider,browser:v.browser,package_id:session?.metadata?.package_id||null,browser_version:session?.metadata?.browser_version||null,provenance:providerModule?'CONTROLLED_TEST_PROVIDER':'ADAPTER_PROVIDER'},determinism:{headless:true,device_scale_factor:cfg.device_scale_factor,locale:cfg.locale,timezone_id:cfg.timezone_id,color_scheme:cfg.color_scheme,reduced_motion:cfg.reduced_motion,service_workers:cfg.service_workers,wait_for_fonts:cfg.wait_for_fonts,freeze_animations:cfg.freeze_animations,stable_ms:cfg.stable_ms,sequential_cases:true},server_probe:{status:pr.status,attempts:pr.attempts},started_at:startedAt,ended_at:endedAt,duration_ms:Date.now()-started,captures,receipt_sha256:''};receipt.receipt_sha256=sha(receipt);const out=outPath||path.join(root,p.receipts_root,`${plan.task_id}${evidenceSuffix}.json`);if(!inside(root,out))fail('RECEIPT_OUTPUT_PATH_INVALID',146);writeJson(out,receipt);return {status:'BROWSER_CAPTURE_COMPLETE',path:asRel(root,out),receipt}}
function verify(root,receiptPath){const errors=[];const abs=path.resolve(receiptPath);if(!inside(root,abs)||!fs.existsSync(abs))return {status:'BROWSER_CAPTURE_RECEIPT_INVALID',valid:false,errors:['receipt_missing_or_external']};let o;try{o=readJson(abs)}catch{return {status:'BROWSER_CAPTURE_RECEIPT_INVALID',valid:false,errors:['receipt_unreadable']}}if(!validSeal(o,'receipt_sha256'))errors.push('receipt_integrity_mismatch');if(o.claims?.screenshot_capture_executed!==true||o.claims?.render_execution_attested!==true)errors.push('render_execution_attestation_missing');if(o.claims?.visual_quality_verified!==false)errors.push('visual_quality_claim_forbidden');if(o.claims?.visual_regression_verified!==false)errors.push('visual_regression_claim_forbidden');const plan=relWithin(root,o.plan_path);if(!plan)errors.push('plan_path_invalid');else{const r=callPhase1(root,['plan','verify','--plan',plan]);if(r.status!==0||!r.obj?.valid)errors.push('plan_invalid');else if(r.obj.plan.plan_sha256!==o.plan_sha256)errors.push('plan_hash_mismatch')}const spec=relWithin(root,o.execution_spec_path);if(!spec||!fs.existsSync(spec))errors.push('execution_spec_missing');else if(fileSha(spec)!==o.execution_spec_sha256)errors.push('execution_spec_drift');const p1=relWithin(root,o.phase1_run_path);let p1Run=null;if(!p1||!fs.existsSync(p1))errors.push('phase1_run_missing');else{if(fileSha(p1)!==o.phase1_run_sha256)errors.push('phase1_run_drift');const vr=verifyPhase1Run(root,p1);if(!vr.valid)errors.push('phase1_run_invalid');else p1Run=vr.obj.run}if(p1Run){const a=new Map((p1Run.captures||[]).map(x=>[x.case_id,x]));if(a.size!==(o.captures||[]).length)errors.push('receipt_capture_set_mismatch');for(const c of o.captures||[]){const x=a.get(c.case_id);if(!x||x.sha256!==c.sha256||norm(x.screenshot_path)!==norm(c.screenshot_path))errors.push(`receipt_capture_mismatch:${c.case_id}`)}}for(const c of o.captures||[]){const a=relWithin(root,c.screenshot_path);if(!a||!fs.existsSync(a))errors.push(`capture_missing:${c.case_id}`);else{if(!pngOk(a))errors.push(`capture_not_png:${c.case_id}`);if(fileSha(a)!==c.sha256)errors.push(`capture_drift:${c.case_id}`)}}return {status:errors.length?'BROWSER_CAPTURE_RECEIPT_INVALID':'BROWSER_CAPTURE_RECEIPT_VALID',valid:errors.length===0,errors,receipt:o,path:asRel(root,abs)}}
const root=rootOf(take('--project-root',process.cwd()));
try{
 if(group==='doctor'){const r=await doctor(root,take('--provider-module'));process.stdout.write(JSON.stringify(r,null,2)+'\n');process.exit(r.status==='BROWSER_RUNNER_READY'?0:4)}
 if(group==='run'&&cmd==='execute'){const plan=take('--plan'),spec=take('--spec'),out=take('--out');if(!plan||!spec)fail('PLAN_AND_SPEC_REQUIRED',2);const r=await execute(root,path.resolve(plan),path.resolve(spec),out?path.resolve(out):null,take('--provider-module'));process.stdout.write(JSON.stringify(r,null,2)+'\n');process.exit(0)}
 if(group==='run'&&cmd==='verify'){const receipt=take('--receipt');if(!receipt)fail('RECEIPT_REQUIRED',2);const r=verify(root,path.resolve(receipt));process.stdout.write(JSON.stringify(r,null,2)+'\n');process.exit(r.valid?0:3)}
 fail('BROWSER_RUNNER_COMMAND_UNKNOWN',2,{usage:['doctor','run execute --plan <plan> --spec <json> [--out <json>]','run verify --receipt <json>']});
}catch(e){fail(e?.code||'BROWSER_RUNNER_FAILED',199)}
