#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath,pathToFileURL} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const distRoot=path.resolve(here,'..');
const args=process.argv.slice(2);const [group,cmd]=args;
const HASH=/^[a-f0-9]{64}$/;
function take(flag,f=null){const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:f}
function die(status,code=1,extra={}){process.stdout.write(JSON.stringify({status,...extra},null,2)+'\n');process.exit(code)}
function out(v){process.stdout.write(JSON.stringify(v,null,2)+'\n')}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n','utf8')}
function norm(p){return String(p||'').replaceAll('\\','/').replace(/^\.\//,'')}
function rootOf(p){const r=path.resolve(p||process.cwd());if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())die('PROJECT_ROOT_INVALID',90);return r}
function inside(root,p){const rr=path.resolve(root)+path.sep,aa=path.resolve(p);return aa===path.resolve(root)||aa.startsWith(rr)}
function safeRel(v){const n=norm(v);return !!n&&!path.isAbsolute(v)&&!n.split('/').includes('..')&&!n.startsWith('/')}
function relWithin(root,rel){if(!safeRel(rel))return null;const a=path.resolve(root,rel);return inside(root,a)?a:null}
function asRel(root,abs){return norm(path.relative(root,abs))}
function fileSha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function stable(v,omit=[]){if(Array.isArray(v))return v.map(x=>stable(x,omit));if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort())if(!omit.includes(k))o[k]=stable(v[k],omit);return o}return v}
function shaObject(v,omit=[]){return crypto.createHash('sha256').update(JSON.stringify(stable(v,omit))).digest('hex')}
function validSeal(o,field){return !!o&&HASH.test(o[field]||'')&&o[field]===shaObject(o,[field])}
function policy(){return readJson(path.join(distRoot,'policies','visualqa-policy.json')).phase4}
function callSibling(file,argv,root){const r=spawnSync(process.execPath,[path.join(here,file),...argv,'--project-root',root],{encoding:'utf8'});let obj=null;try{obj=JSON.parse(r.stdout||'{}')}catch{}return {status:r.status,obj,stdout:r.stdout,stderr:r.stderr}}
function verifyP2(root,p){const r=callSibling('browser-runner.mjs',['run','verify','--receipt',path.resolve(p)],root);return {ok:r.status===0&&r.obj?.valid,obj:r.obj}}
function verifyP3(root,p){const r=callSibling('regression.mjs',['compare','verify','--report',path.resolve(p)],root);return {ok:r.status===0&&r.obj?.valid,obj:r.obj}}
function buildUrl(base,route,suffix=''){const b=new URL(base),u=new URL(String(route||'/')+String(suffix||''),b),r=new URL(String(route||'/'),b);if(u.origin!==b.origin)throw Object.assign(new Error('URL_ORIGIN_CHANGED'),{code:'URL_ORIGIN_CHANGED'});if(u.pathname!==r.pathname)throw Object.assign(new Error('ROUTE_PATH_CHANGED'),{code:'ROUTE_PATH_CHANGED'});return u.toString()}
async function probe(url,p){for(let i=0;i<p.server_probe_retries;i++){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),p.server_probe_timeout_ms);const r=await fetch(url,{method:'GET',redirect:'manual',signal:c.signal});clearTimeout(t);if(r.status<500)return {ok:true,status:r.status,attempts:i+1}}catch{}if(i+1<p.server_probe_retries)await new Promise(res=>setTimeout(res,p.server_probe_delay_ms))}return {ok:false,status:null,attempts:p.server_probe_retries}}
function canonicalPolicy(root,rel,kind){const a=relWithin(root,rel);if(!a||!fs.existsSync(a))return {valid:false,errors:[`${kind}_policy_missing`]};let o;try{o=readJson(a)}catch{return {valid:false,errors:[`${kind}_policy_unreadable`]}}const errors=[];if(!validSeal(o,'integrity_sha256'))errors.push(`${kind}_policy_integrity_mismatch`);return {valid:!errors.length,errors,obj:o,path:a,file_sha256:fileSha(a)}}
async function loadProvider(root,p,providerModule){if(providerModule){if(process.env.ALEDEVOS_TEST_MODE!=='1')die('TEST_PROVIDER_FORBIDDEN',130);const a=path.resolve(providerModule),allowed=path.resolve(root,p.test_provider_subdir);if(!inside(allowed,a)||!fs.existsSync(a))die('TEST_PROVIDER_PATH_INVALID',131);return import(pathToFileURL(a).href)}return import(pathToFileURL(path.join(distRoot,'providers','playwright-driver.mjs')).href)}
function providerConfig(p,receipt,profile){return {browser:receipt.provider?.browser||p.allowed_browsers[0],headless:true,device_scale_factor:receipt.determinism?.device_scale_factor??1,locale:receipt.determinism?.locale||'en-US',timezone_id:receipt.determinism?.timezone_id||'UTC',color_scheme:receipt.determinism?.color_scheme||'light',reduced_motion:receipt.determinism?.reduced_motion||'reduce',service_workers:receipt.determinism?.service_workers||'block',wait_for_fonts:receipt.determinism?.wait_for_fonts!==false,freeze_animations:receipt.determinism?.freeze_animations!==false,stable_ms:Number(receipt.determinism?.stable_ms||0),navigation_wait_until:'domcontentloaded',navigation_timeout_ms:20000,selector_timeout_ms:8000,fail_on_page_error:true,fail_on_console_error:false,audit_profile:profile}}
function limited(arr,n){return Array.isArray(arr)?arr.slice(0,n):[]}
function classifyCase(evidence,profile,p){const m=evidence.measurements||{},layout=m.layout||{},a11y=m.accessibility||{},failures=[],blockers=[];const samples=profile.max_samples_per_category;
  const addFail=(rule,count,items=[],detail={})=>{if(Number(count)>0)failures.push({rule_id:rule,count:Number(count),items:limited(items,samples),...detail})};
  const overflow=Number(m.document?.horizontal_overflow_px||0);if(overflow>profile.layout_overflow_tolerance_px)addFail('LAYOUT_HORIZONTAL_OVERFLOW',1,[],{measured_px:overflow,allowed_px:profile.layout_overflow_tolerance_px});
  addFail('LAYOUT_FOCUSABLE_VIEWPORT_ESCAPE',layout.viewport_escape_count,layout.viewport_escapes);
  addFail('LAYOUT_FOCUSABLE_CLIPPED',layout.clipped_focusable_count,layout.clipped_focusables);
  if(a11y.scan_truncated)blockers.push('AUDIT_DOM_SCAN_TRUNCATED');
  if(a11y.focus_scan_truncated)blockers.push('AUDIT_FOCUS_SCAN_TRUNCATED');
  addFail('A11Y_KEYBOARD_UNREACHABLE',a11y.keyboard_focus?.unreachable_count,a11y.keyboard_focus?.unreachable);
  addFail('A11Y_FOCUS_INDICATOR_MISSING',a11y.keyboard_focus?.missing_indicator_count,a11y.keyboard_focus?.missing_indicator);
  addFail('A11Y_FOCUS_OBSCURED',a11y.keyboard_focus?.obscured_count,a11y.keyboard_focus?.obscured);
  addFail('A11Y_ACCESSIBLE_NAME_MISSING',a11y.unnamed_control_count,a11y.unnamed_controls);
  addFail('A11Y_IMAGE_ALT_MISSING',a11y.image_alt_missing_count,a11y.images_missing_alt);
  const badTargets=(a11y.target_size_violations||[]);const badTargetCount=Number.isFinite(Number(a11y.target_size_violation_count))?Number(a11y.target_size_violation_count):badTargets.length;addFail('A11Y_TARGET_SIZE_MINIMUM',badTargetCount,badTargets,{minimum_px:profile.target_size_min_px});
  const low=(a11y.text_contrast_violations||[]);const lowCount=Number.isFinite(Number(a11y.text_contrast_violation_count))?Number(a11y.text_contrast_violation_count):low.length;addFail('A11Y_TEXT_CONTRAST',lowCount,low);
  let unmeasurable=Number.isFinite(Number(a11y.text_contrast_unmeasurable_count))?Number(a11y.text_contrast_unmeasurable_count):(a11y.text_contrast||[]).filter(x=>!x.measurable).length;
  if(unmeasurable>0&&p.unmeasurable_text_contrast==='BLOCKED')blockers.push(`A11Y_TEXT_CONTRAST_UNMEASURABLE:${unmeasurable}`);
  const status=blockers.length?'BLOCKED':failures.length?'FAIL':'PASS';return {status,failures,blockers,summary:{failure_rules:failures.length,failed_instances:failures.reduce((n,x)=>n+x.count,0),blockers:blockers.length}};
}
function summarize(cases){const s={total_cases:cases.length,passed:0,failed:0,blocked:0,failed_instances:0};for(const c of cases){if(c.status==='PASS')s.passed++;else if(c.status==='FAIL')s.failed++;else s.blocked++;s.failed_instances+=Number(c.summary?.failed_instances||0)}return s}
function ensureP3MatchesReceipt(root,p3,receiptAbs,receipt){if(!p3)return null;const a=path.resolve(p3);if(!inside(root,a)||!fs.existsSync(a))die('PHASE3_REPORT_PATH_INVALID',120);const v=verifyP3(root,a);if(!v.ok)die('PHASE3_REPORT_INVALID',121,{errors:v.obj?.errors||[]});const r=v.obj.report;if(r.task_id!==receipt.task_id||path.resolve(root,r.phase2_receipt_path)!==receiptAbs||r.phase2_receipt_file_sha256!==fileSha(receiptAbs))die('PHASE3_RECEIPT_MISMATCH',122);return {path:a,file_sha256:fileSha(a),status:r.status}}
async function doctor(root,providerModule){const p=policy(),mod=await loadProvider(root,p,providerModule);if(typeof mod.doctor!=='function'||typeof mod.createSession!=='function')return {status:'RUNTIME_AUDIT_NOT_READY',provider:{ok:false,status:'PROVIDER_CONTRACT_INVALID'}};const d=await mod.doctor({browser:p.allowed_browsers[0]});return {status:d.ok?'RUNTIME_AUDIT_READY':'RUNTIME_AUDIT_NOT_READY',provider:d}}
async function runAudit(root,receiptPath,p3Path,outPath,providerModule){const p=policy();const recAbs=path.resolve(receiptPath);if(!inside(root,recAbs)||!fs.existsSync(recAbs))die('PHASE2_RECEIPT_PATH_INVALID',123);const p2=verifyP2(root,recAbs);if(!p2.ok)die('PHASE2_RECEIPT_INVALID',124,{errors:p2.obj?.errors||[]});const receipt=p2.obj.receipt;
  const a11y=canonicalPolicy(root,p.accessibility_policy_path,'accessibility'),resp=canonicalPolicy(root,p.responsive_policy_path,'responsive');const policyErrors=[...a11y.errors,...resp.errors];if(policyErrors.length)die('RUNTIME_POLICY_INVALID',125,{errors:policyErrors});if(p.require_active_accessibility_policy&&a11y.obj.status!=='ACTIVE')die('ACCESSIBILITY_POLICY_UNSET',126);if(p.require_active_responsive_policy&&resp.obj.status!=='ACTIVE')die('RESPONSIVE_POLICY_UNSET',127);
  const profile=p.supported_accessibility_standards[a11y.obj.standard];if(!profile)die('ACCESSIBILITY_STANDARD_UNSUPPORTED',128,{standard:a11y.obj.standard,supported:Object.keys(p.supported_accessibility_standards)});const p3=ensureP3MatchesReceipt(root,p3Path,recAbs,receipt);
  const planAbs=relWithin(root,receipt.plan_path);if(!planAbs||!fs.existsSync(planAbs))die('CAPTURE_PLAN_MISSING',129);const plan=readJson(planAbs);const pr=await probe(plan.base_url,p);if(!pr.ok)die('DEV_SERVER_UNAVAILABLE',133,{attempts:pr.attempts});const mod=await loadProvider(root,p,providerModule);if(typeof mod.createSession!=='function')die('PROVIDER_CONTRACT_INVALID',134);const cfg=providerConfig(p,receipt,profile);let session;try{session=await mod.createSession(cfg)}catch(e){die(e?.code||'BROWSER_SESSION_FAILED',135)}if(typeof session?.audit!=='function'){try{await session?.close?.()}catch{}die('PROVIDER_AUDIT_CONTRACT_MISSING',136)}
  const cases=[];let failure=null;const startedAt=new Date().toISOString(),started=Date.now();try{for(const c of receipt.captures||[]){let url;try{url=buildUrl(plan.base_url,c.route,c.route_suffix||'')}catch(e){failure={status:e?.code||'AUDIT_URL_INVALID',case_id:c.case_id};break}let r;try{r=await session.audit({case_id:c.case_id,url,viewport:c.viewport,ready_selector:c.ready_selector||null,profile})}catch(e){failure={status:e?.code||'RUNTIME_AUDIT_CASE_FAILED',case_id:c.case_id};break}if(!r?.ok){failure={status:r?.status||'RUNTIME_AUDIT_CASE_FAILED',case_id:c.case_id};break}try{const fu=new URL(r.final_url||url),eu=new URL(url);if(fu.origin!==eu.origin){failure={status:'AUDIT_REDIRECT_ORIGIN_CHANGED',case_id:c.case_id};break}if(fu.pathname!==eu.pathname){failure={status:'AUDIT_REDIRECT_PATH_CHANGED',case_id:c.case_id};break}}catch{failure={status:'AUDIT_FINAL_URL_INVALID',case_id:c.case_id};break}
      const ev={schema_version:'1.0',phase:'VISUAL_QA_P4_EVIDENCE',task_id:receipt.task_id,case_id:c.case_id,contract:{route:c.route,state:c.state,viewport:c.viewport,route_suffix:c.route_suffix||null,ready_selector:c.ready_selector||null},provider:{id:p.provider,browser:receipt.provider?.browser||cfg.browser,package_id:session.metadata?.package_id||null,browser_version:session.metadata?.browser_version||null,provenance:providerModule?'CONTROLLED_TEST_PROVIDER':'ADAPTER_PROVIDER'},navigation:{status:r.navigation_status??null,final_url:r.final_url||url,page_error_count:Number(r.page_error_count||0),console_error_count:Number(r.console_error_count||0),state_attestation:r.state_attestation||null,duration_ms:Number.isFinite(r.duration_ms)?r.duration_ms:null},measurements:r.evidence||{},evidence_sha256:''};ev.evidence_sha256=shaObject(ev,['evidence_sha256']);const ep=path.join(root,p.evidence_root,receipt.task_id,`${c.case_id}.json`);writeJson(ep,ev);const cls=classifyCase(ev,profile,p);cases.push({case_id:c.case_id,route:c.route,state:c.state,viewport:c.viewport,status:cls.status,failures:cls.failures,blockers:cls.blockers,summary:cls.summary,evidence_path:asRel(root,ep),evidence_file_sha256:fileSha(ep),evidence_sha256:ev.evidence_sha256})}}
  finally{try{await session?.close?.()}catch{}}
  if(failure)die('VISUAL_RUNTIME_AUDIT_BLOCKED',137,{failure,cases_completed:cases.length});const summary=summarize(cases),status=summary.blocked?'VISUAL_RUNTIME_AUDIT_BLOCKED':summary.failed?'VISUAL_RUNTIME_AUDIT_FAIL':'VISUAL_RUNTIME_AUDIT_PASS';const report={schema_version:'1.0',phase:'VISUAL_QA_P4',task_id:receipt.task_id,status,claims:{runtime_checks_executed:true,rendered_layout_verified:status==='VISUAL_RUNTIME_AUDIT_PASS',rendered_accessibility_verified:status==='VISUAL_RUNTIME_AUDIT_PASS',full_wcag_conformance_verified:false,visual_quality_verified:false,motion_quality_verified:false},phase2_receipt_path:asRel(root,recAbs),phase2_receipt_file_sha256:fileSha(recAbs),phase3_report_path:p3?asRel(root,p3.path):null,phase3_report_file_sha256:p3?.file_sha256||null,phase3_status:p3?.status||null,accessibility_policy_path:asRel(root,a11y.path),accessibility_policy_file_sha256:a11y.file_sha256,responsive_policy_path:asRel(root,resp.path),responsive_policy_file_sha256:resp.file_sha256,accessibility_standard:a11y.obj.standard,runtime_profile:profile,provider:{id:p.provider,browser:receipt.provider?.browser||cfg.browser,package_id:session?.metadata?.package_id||null,browser_version:session?.metadata?.browser_version||null,provenance:providerModule?'CONTROLLED_TEST_PROVIDER':'ADAPTER_PROVIDER'},server_probe:pr,started_at:startedAt,ended_at:new Date().toISOString(),duration_ms:Date.now()-started,cases,summary,report_sha256:''};report.report_sha256=shaObject(report,['report_sha256']);const rp=outPath?path.resolve(outPath):path.join(root,p.reports_root,`${receipt.task_id}.json`);if(!inside(root,rp))die('REPORT_OUTPUT_PATH_INVALID',138);writeJson(rp,report);return {status,path:asRel(root,rp),report,exit:status==='VISUAL_RUNTIME_AUDIT_PASS'?0:status==='VISUAL_RUNTIME_AUDIT_FAIL'?3:4};
}
function verifyEvidence(root,ep,expectedCase,expectedTask,profile,p){const errors=[];const a=relWithin(root,ep);if(!a||!fs.existsSync(a))return {valid:false,errors:['evidence_missing_or_external']};let e;try{e=readJson(a)}catch{return {valid:false,errors:['evidence_unreadable']}}if(fileSha(a)!==expectedCase.evidence_file_sha256)errors.push('evidence_file_drift');if(e.evidence_sha256!==expectedCase.evidence_sha256||!validSeal(e,'evidence_sha256'))errors.push('evidence_integrity_mismatch');if(e.task_id!==expectedTask||e.case_id!==expectedCase.case_id)errors.push('evidence_identity_mismatch');const cls=classifyCase(e,profile,p);if(cls.status!==expectedCase.status||JSON.stringify(cls.failures)!==JSON.stringify(expectedCase.failures)||JSON.stringify(cls.blockers)!==JSON.stringify(expectedCase.blockers)||JSON.stringify(cls.summary)!==JSON.stringify(expectedCase.summary))errors.push('case_classification_mismatch');return {valid:!errors.length,errors,evidence:e,classification:cls}}
function verifyReport(root,reportPath){const p=policy(),errors=[];const a=path.resolve(reportPath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_RUNTIME_AUDIT_REPORT_INVALID',valid:false,errors:['report_missing_or_external']};let r;try{r=readJson(a)}catch{return {status:'VISUAL_RUNTIME_AUDIT_REPORT_INVALID',valid:false,errors:['report_unreadable']}}if(!validSeal(r,'report_sha256'))errors.push('report_integrity_mismatch');const rec=relWithin(root,r.phase2_receipt_path);let receipt=null;if(!rec||!fs.existsSync(rec))errors.push('phase2_receipt_missing');else{if(fileSha(rec)!==r.phase2_receipt_file_sha256)errors.push('phase2_receipt_drift');const v=verifyP2(root,rec);if(!v.ok)errors.push('phase2_receipt_invalid');else receipt=v.obj.receipt}
  if(r.phase3_report_path){const p3=relWithin(root,r.phase3_report_path);if(!p3||!fs.existsSync(p3))errors.push('phase3_report_missing');else{if(fileSha(p3)!==r.phase3_report_file_sha256)errors.push('phase3_report_drift');const v=verifyP3(root,p3);if(!v.ok)errors.push('phase3_report_invalid');else if(receipt&&(v.obj.report.task_id!==receipt.task_id||v.obj.report.phase2_receipt_file_sha256!==r.phase2_receipt_file_sha256))errors.push('phase3_receipt_mismatch')}}
  const ap=canonicalPolicy(root,p.accessibility_policy_path,'accessibility'),rp=canonicalPolicy(root,p.responsive_policy_path,'responsive');if(!ap.valid)errors.push(...ap.errors);if(!rp.valid)errors.push(...rp.errors);if(ap.valid&&ap.file_sha256!==r.accessibility_policy_file_sha256)errors.push('accessibility_policy_drift');if(rp.valid&&rp.file_sha256!==r.responsive_policy_file_sha256)errors.push('responsive_policy_drift');const profile=ap.valid?p.supported_accessibility_standards[ap.obj.standard]:null;if(!profile)errors.push('accessibility_standard_unsupported');else{if(r.accessibility_standard!==ap.obj.standard)errors.push('accessibility_standard_mismatch');if(JSON.stringify(r.runtime_profile)!==JSON.stringify(profile))errors.push('runtime_profile_mismatch')}
  if(receipt&&profile){const receiptMap=new Map((receipt.captures||[]).map(x=>[x.case_id,x]));if(receiptMap.size!==(r.cases||[]).length)errors.push('case_set_mismatch');for(const c of r.cases||[]){const rc=receiptMap.get(c.case_id);if(!rc)errors.push(`case_unknown:${c.case_id}`);else if(rc.route!==c.route||rc.state!==c.state||JSON.stringify(rc.viewport)!==JSON.stringify(c.viewport))errors.push(`case_contract_drift:${c.case_id}`);const ev=verifyEvidence(root,c.evidence_path,c,r.task_id,profile,p);for(const e of ev.errors)errors.push(`${e}:${c.case_id}`)}const sm=summarize(r.cases||[]);if(JSON.stringify(sm)!==JSON.stringify(r.summary))errors.push('summary_mismatch');const status=sm.blocked?'VISUAL_RUNTIME_AUDIT_BLOCKED':sm.failed?'VISUAL_RUNTIME_AUDIT_FAIL':'VISUAL_RUNTIME_AUDIT_PASS';if(status!==r.status)errors.push('report_status_mismatch');const pass=status==='VISUAL_RUNTIME_AUDIT_PASS';if(r.claims?.runtime_checks_executed!==true)errors.push('runtime_execution_claim_missing');if(r.claims?.rendered_layout_verified!==pass)errors.push('rendered_layout_claim_mismatch');if(r.claims?.rendered_accessibility_verified!==pass)errors.push('rendered_accessibility_claim_mismatch')}
  if(r.claims?.full_wcag_conformance_verified!==false)errors.push('full_wcag_claim_forbidden');if(r.claims?.visual_quality_verified!==false)errors.push('visual_quality_claim_forbidden');if(r.claims?.motion_quality_verified!==false)errors.push('motion_quality_claim_forbidden');return {status:errors.length?'VISUAL_RUNTIME_AUDIT_REPORT_INVALID':'VISUAL_RUNTIME_AUDIT_REPORT_VALID',valid:!errors.length,errors,report:r,path:asRel(root,a)};
}

const root=rootOf(take('--project-root',process.cwd()));
const forbidden=['--normal-text-contrast','--large-text-contrast','--target-size','--overflow-tolerance','--max-focus-steps'];if(forbidden.some(x=>args.includes(x)))die('ARBITRARY_RUNTIME_THRESHOLD_FORBIDDEN',2);
try{
  if(group==='doctor'){const r=await doctor(root,take('--provider-module'));out(r);process.exit(r.status==='RUNTIME_AUDIT_READY'?0:4)}
  if(group==='audit'&&cmd==='run'){const receipt=take('--receipt');if(!receipt)die('PHASE2_RECEIPT_REQUIRED',2);const r=await runAudit(root,receipt,take('--phase3-report'),take('--out'),take('--provider-module'));out({status:r.status,path:r.path,report:r.report});process.exit(r.exit)}
  if(group==='audit'&&cmd==='verify'){const report=take('--report');if(!report)die('RUNTIME_AUDIT_REPORT_REQUIRED',2);const r=verifyReport(root,report);out(r);process.exit(r.valid?0:3)}
  die('RUNTIME_AUDIT_COMMAND_UNKNOWN',2,{usage:['doctor','audit run --receipt <p2-receipt> [--phase3-report <p3-report>] [--out <json>]','audit verify --report <json>']});
}catch(e){die(e?.code||'RUNTIME_AUDIT_FAILED',199)}
