#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const distRoot=path.resolve(here,'..');
const args=process.argv.slice(2);const [group,cmd]=args;const HASH=/^[a-f0-9]{64}$/;
function take(f,d=null){const i=args.indexOf(f);return i>=0&&i+1<args.length?args[i+1]:d}
function out(v){process.stdout.write(JSON.stringify(v,null,2)+'\n')}
function die(status,code=2,extra={}){out({status,...extra});process.exit(code)}
function fault(status,code=2,extra={}){const e=new Error(status);e.code=status;e.exitCode=code;e.extra=extra;throw e}
function readJson(p){return JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''))}
function writeJson(p,v){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n','utf8')}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};for(const k of Object.keys(v).sort()){if(!['packet_sha256','judgment_sha256','repair_plan_sha256','cycle_sha256','acceptance_sha256','plan_sha256','run_sha256','receipt_sha256','report_sha256','integrity_sha256','contract_sha256','review_sha256'].includes(k))o[k]=stable(v[k])}return o}return v}
function shaObject(v){return crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex')}
function fileSha(p){return crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}
function inside(root,p){const r=path.resolve(root),a=path.resolve(p);return a===r||a.startsWith(r+path.sep)}
function rootOf(p){const r=path.resolve(p||process.cwd());if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())die('PROJECT_ROOT_INVALID',90);return r}
function norm(p){return String(p||'').replaceAll('\\','/').replace(/^\.\//,'')}
function rel(root,p){return norm(path.relative(root,path.resolve(p)))}
function relWithin(root,p){if(typeof p!=='string'||!p||path.isAbsolute(p)||norm(p).split('/').includes('..'))return null;const a=path.resolve(root,p);return inside(root,a)?a:null}
function sealValid(o,field){return !!o&&HASH.test(o[field]||'')&&o[field]===shaObject(o)}
function policy(){const o=readJson(path.join(distRoot,'policies','visualqa-policy.json'));if(!o.phase5)die('VISUAL_JUDGE_POLICY_MISSING',91);return o.phase5}
function call(runtime,root,argv){const r=spawnSync(process.execPath,[runtime,...argv,'--project-root',root],{encoding:'utf8'});let obj=null;try{obj=JSON.parse(r.stdout||'{}')}catch{}return {ok:r.status===0,obj,status:r.status,stdout:r.stdout,stderr:r.stderr}}
function p2Verify(root,p){const r=call(path.join(here,'browser-runner.mjs'),root,['run','verify','--receipt',p]);return r.ok&&r.obj?.valid?{ok:true,obj:r.obj}:{ok:false,errors:r.obj?.errors||['phase2_verify_failed']}}
function p3Verify(root,p){const r=call(path.join(here,'regression.mjs'),root,['compare','verify','--report',p]);return r.ok&&r.obj?.valid?{ok:true,obj:r.obj}:{ok:false,errors:r.obj?.errors||['phase3_verify_failed']}}
function p4Verify(root,p){const r=call(path.join(here,'runtime-audit.mjs'),root,['audit','verify','--report',p]);return r.ok&&r.obj?.valid?{ok:true,obj:r.obj}:{ok:false,errors:r.obj?.errors||['phase4_verify_failed']}}
function coreState(root,stateArg=null){const p=path.resolve(stateArg||path.join(root,policy().global_run_state_path));if(!inside(root,p)||!fs.existsSync(p))fault('GLOBAL_RUN_STATE_MISSING',150,{path:rel(root,p)});let s;try{s=readJson(p)}catch{fault('GLOBAL_RUN_STATE_UNREADABLE',151)}return {path:p,obj:s,file_sha256:fileSha(p)}}
function normalizeScore(x){return Math.round(Number(x)*100)/100}
function mean(xs){return normalizeScore(xs.reduce((a,b)=>a+b,0)/xs.length)}

function validateUpstream(root,receiptPath,p3Path,p4Path,{requirePass=true}={}){
  const p=policy();const ra=path.resolve(receiptPath),p3a=path.resolve(p3Path),p4a=path.resolve(p4Path);
  for(const [n,a] of [['phase2',ra],['phase3',p3a],['phase4',p4a]])if(!inside(root,a)||!fs.existsSync(a))fault(`${n.toUpperCase()}_PATH_INVALID`,100);
  const v2=p2Verify(root,ra);if(!v2.ok)fault('PHASE2_RECEIPT_INVALID',101,{errors:v2.errors});
  const v3=p3Verify(root,p3a);if(!v3.ok)fault('PHASE3_REPORT_INVALID',102,{errors:v3.errors});
  const v4=p4Verify(root,p4a);if(!v4.ok)fault('PHASE4_REPORT_INVALID',103,{errors:v4.errors});
  const r2=v2.obj.receipt,r3=v3.obj.report,r4=v4.obj.report;
  if(r2.task_id!==r3.task_id||r2.task_id!==r4.task_id)fault('UPSTREAM_TASK_MISMATCH',104);
  const r2sha=fileSha(ra);if(r3.phase2_receipt_file_sha256!==r2sha||r4.phase2_receipt_file_sha256!==r2sha)fault('UPSTREAM_RECEIPT_MISMATCH',105);
  if(r4.phase3_report_path&&r4.phase3_report_file_sha256!==fileSha(p3a))fault('UPSTREAM_PHASE3_MISMATCH',106);
  if(requirePass&&p.require_phase3_pass&&r3.status!=='VISUAL_REGRESSION_PASS')fault('PHASE3_PASS_REQUIRED',107,{upstream_status:r3.status});
  if(requirePass&&p.require_phase4_pass&&r4.status!=='VISUAL_RUNTIME_AUDIT_PASS')fault('PHASE4_PASS_REQUIRED',108,{upstream_status:r4.status});
  return {receipt_abs:ra,p3_abs:p3a,p4_abs:p4a,receipt:r2,p3:r3,p4:r4,receipt_file_sha256:r2sha,p3_file_sha256:fileSha(p3a),p4_file_sha256:fileSha(p4a)};
}

function expectedPacket(root,u){
  const p=policy(),p3m=new Map((u.p3.cases||[]).map(x=>[x.case_id,x])),p4m=new Map((u.p4.cases||[]).map(x=>[x.case_id,x]));
  const cases=[];for(const c of u.receipt.captures||[]){const r3=p3m.get(c.case_id),r4=p4m.get(c.case_id);if(!r3||!r4)fault('UPSTREAM_CASE_SET_MISMATCH',109,{case_id:c.case_id});cases.push({case_id:c.case_id,route:c.route,state:c.state,viewport:c.viewport,screenshot_path:c.screenshot_path,screenshot_sha256:c.sha256,baseline_path:r3.baseline_path,baseline_sha256:r3.baseline_sha256,phase3_status:r3.status,phase3_metrics:r3.metrics,phase4_status:r4.status,phase4_summary:r4.summary})}
  return {schema_version:'1.0',phase:'VISUAL_QA_P5_PACKET',task_id:u.receipt.task_id,status:'VISUAL_JUDGE_PACKET_READY',claims:{phase2_verified:true,phase3_verified:true,phase4_verified:true,phase3_passed:u.p3.status==='VISUAL_REGRESSION_PASS',phase4_passed:u.p4.status==='VISUAL_RUNTIME_AUDIT_PASS',native_visual_observation_required:true,visual_quality_verified:false,motion_quality_verified:false},phase2_receipt_path:rel(root,u.receipt_abs),phase2_receipt_file_sha256:u.receipt_file_sha256,phase3_report_path:rel(root,u.p3_abs),phase3_report_file_sha256:u.p3_file_sha256,phase4_report_path:rel(root,u.p4_abs),phase4_report_file_sha256:u.p4_file_sha256,evidence_revision:u.receipt.evidence_id||'legacy',observation_mode:p.observation_mode,rubric:{required_dimensions:[...p.required_dimensions],dimension_pass_score:p.dimension_pass_score,case_pass_score:p.case_pass_score,overall_pass_score:p.overall_pass_score},cases,prepared_at:null,packet_sha256:''};
}
function preparePacket(root,receipt,p3,p4,outPath){const u=validateUpstream(root,receipt,p3,p4);const packet=expectedPacket(root,u);packet.prepared_at=new Date().toISOString();packet.packet_sha256=shaObject(packet);const fp=outPath?path.resolve(outPath):path.join(root,policy().packets_root,`${packet.task_id}.json`);if(!inside(root,fp))die('PACKET_OUTPUT_PATH_INVALID',110);writeJson(fp,packet);return {status:'VISUAL_JUDGE_PACKET_READY',path:rel(root,fp),packet}}
function verifyPacket(root,packetPath){const errors=[];const a=path.resolve(packetPath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_JUDGE_PACKET_INVALID',valid:false,errors:['packet_missing_or_external']};let q;try{q=readJson(a)}catch{return {status:'VISUAL_JUDGE_PACKET_INVALID',valid:false,errors:['packet_unreadable']}}if(!sealValid(q,'packet_sha256'))errors.push('packet_integrity_mismatch');let u=null;try{u=validateUpstream(root,path.resolve(root,q.phase2_receipt_path||''),path.resolve(root,q.phase3_report_path||''),path.resolve(root,q.phase4_report_path||''))}catch(e){errors.push('upstream_invalid')}if(u){if(fileSha(u.receipt_abs)!==q.phase2_receipt_file_sha256)errors.push('phase2_receipt_drift');if(fileSha(u.p3_abs)!==q.phase3_report_file_sha256)errors.push('phase3_report_drift');if(fileSha(u.p4_abs)!==q.phase4_report_file_sha256)errors.push('phase4_report_drift');if(q.task_id!==u.receipt.task_id)errors.push('task_mismatch');const e=expectedPacket(root,u);for(const k of ['schema_version','phase','task_id','status','claims','phase2_receipt_path','phase2_receipt_file_sha256','phase3_report_path','phase3_report_file_sha256','phase4_report_path','phase4_report_file_sha256','evidence_revision','observation_mode','rubric','cases'])if(JSON.stringify(q[k])!==JSON.stringify(e[k]))errors.push(`packet_field_mismatch:${k}`)}return {status:errors.length?'VISUAL_JUDGE_PACKET_INVALID':'VISUAL_JUDGE_PACKET_VALID',valid:!errors.length,errors,packet:q,path:rel(root,a)}}

function validateSubmission(packet,s){const p=policy(),errors=[];if(s?.schema_version!=='1.0')errors.push('schema_version_invalid');if(s?.phase!=='VISUAL_QA_P5_SUBMISSION')errors.push('phase_invalid');if(s?.task_id!==packet.task_id)errors.push('task_id_mismatch');if(s?.packet_sha256!==packet.packet_sha256)errors.push('packet_sha256_mismatch');if(s?.judge?.agent_id!==p.judge_agent_id)errors.push('judge_agent_invalid');if(s?.judge?.observation_mode!==p.observation_mode)errors.push('native_visual_observation_required');if(typeof s?.judge?.model_ref!=='string'||s.judge.model_ref.trim().length<2)errors.push('model_ref_required');const inputCases=Array.isArray(s?.cases)?s.cases:[];const cm=new Map(inputCases.map(x=>[x.case_id,x]));if(cm.size!==packet.cases.length||inputCases.length!==packet.cases.length)errors.push('case_set_mismatch');const normalized=[];let anyActionable=false;
  for(const pc of packet.cases){const c=cm.get(pc.case_id);if(!c){errors.push(`case_missing:${pc.case_id}`);continue}if(c.observed_screenshot_sha256!==pc.screenshot_sha256)errors.push(`screenshot_observation_mismatch:${pc.case_id}`);const dims=Array.isArray(c.dimensions)?c.dimensions:[],dm=new Map(dims.map(x=>[x.id,x]));if(dm.size!==p.required_dimensions.length||dims.length!==p.required_dimensions.length)errors.push(`dimension_set_mismatch:${pc.case_id}`);const nd=[];for(const id of p.required_dimensions){const d=dm.get(id);if(!d){errors.push(`dimension_missing:${pc.case_id}:${id}`);continue}if(!['PASS','FAIL','UNVERIFIED'].includes(d.status))errors.push(`dimension_status_invalid:${pc.case_id}:${id}`);let score=null;if(d.status==='UNVERIFIED'){if(d.score!==null&&d.score!==undefined)errors.push(`unverified_score_forbidden:${pc.case_id}:${id}`)}else{score=Number(d.score);if(!Number.isInteger(score)||score<0||score>100)errors.push(`dimension_score_invalid:${pc.case_id}:${id}`);else{const expected=score>=p.dimension_pass_score?'PASS':'FAIL';if(d.status!==expected)errors.push(`dimension_status_score_mismatch:${pc.case_id}:${id}`)}}if(typeof d.note!=='string'||d.note.trim().length<8||d.note.length>1200)errors.push(`dimension_note_invalid:${pc.case_id}:${id}`);nd.push({id,status:d.status,score:d.status==='UNVERIFIED'?null:score,note:String(d.note||'').trim()})}
    const findings=Array.isArray(c.findings)?c.findings:[],ids=new Set(),nf=[];for(const f of findings){if(typeof f.id!=='string'||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/.test(f.id)||ids.has(f.id)){errors.push(`finding_id_invalid:${pc.case_id}`);continue}ids.add(f.id);if(!p.required_dimensions.includes(f.category))errors.push(`finding_category_invalid:${pc.case_id}:${f.id}`);if(!p.finding_severities.includes(f.severity))errors.push(`finding_severity_invalid:${pc.case_id}:${f.id}`);if(typeof f.summary!=='string'||f.summary.trim().length<8||f.summary.length>800)errors.push(`finding_summary_invalid:${pc.case_id}:${f.id}`);if(typeof f.evidence!=='string'||f.evidence.trim().length<8||f.evidence.length>1200)errors.push(`finding_evidence_invalid:${pc.case_id}:${f.id}`);if(typeof f.repair_hint!=='string'||f.repair_hint.trim().length<8||f.repair_hint.length>1200)errors.push(`finding_repair_hint_invalid:${pc.case_id}:${f.id}`);const blocking=!!f.blocking;if(p.critical_findings_blocking&&f.severity==='CRITICAL'&&!blocking)errors.push(`critical_finding_must_block:${pc.case_id}:${f.id}`);nf.push({id:f.id,category:f.category,severity:f.severity,blocking,summary:String(f.summary||'').trim(),evidence:String(f.evidence||'').trim(),repair_hint:String(f.repair_hint||'').trim()});anyActionable=true}
    for(const d of nd.filter(x=>x.status==='FAIL'))if(p.require_finding_for_failed_dimension&&!nf.some(f=>f.category===d.id))errors.push(`failed_dimension_finding_missing:${pc.case_id}:${d.id}`);
    const unverified=nd.some(x=>x.status==='UNVERIFIED'),scores=nd.filter(x=>x.score!==null).map(x=>x.score),caseScore=scores.length?mean(scores):null,hasFail=nd.some(x=>x.status==='FAIL'),hasBlocking=nf.some(x=>x.blocking),verdict=unverified?'BLOCKED':(hasFail||hasBlocking||(caseScore??0)<p.case_pass_score)?'FAIL':'PASS';normalized.push({case_id:pc.case_id,observed_screenshot_sha256:pc.screenshot_sha256,dimensions:nd,findings:nf,score:caseScore,verdict})}
  const blocked=normalized.some(x=>x.verdict==='BLOCKED'),scores=normalized.map(x=>x.score).filter(x=>x!==null),overallScore=scores.length?mean(scores):null;let status=blocked?'VISUAL_JUDGMENT_BLOCKED':(normalized.some(x=>x.verdict==='FAIL')||(overallScore??0)<p.overall_pass_score)?'VISUAL_JUDGMENT_FAIL':'VISUAL_JUDGMENT_PASS';if(status==='VISUAL_JUDGMENT_FAIL'&&p.require_actionable_finding_on_fail&&!anyActionable)errors.push('actionable_finding_required_on_fail');return {errors,cases:normalized,overall_score:overallScore,status};}
function sealJudgment(root,packetPath,inputPath,outPath){const pv=verifyPacket(root,packetPath);if(!pv.valid)die('VISUAL_JUDGE_PACKET_INVALID',120,{errors:pv.errors});const ia=path.resolve(inputPath);if(!inside(root,ia)||!fs.existsSync(ia))die('JUDGMENT_INPUT_PATH_INVALID',121);let s;try{s=readJson(ia)}catch{die('JUDGMENT_INPUT_UNREADABLE',122)}const v=validateSubmission(pv.packet,s);if(v.errors.length)die('VISUAL_JUDGMENT_SUBMISSION_INVALID',123,{errors:v.errors});const pass=v.status==='VISUAL_JUDGMENT_PASS';const report={schema_version:'1.0',phase:'VISUAL_QA_P5',task_id:pv.packet.task_id,status:v.status,claims:{native_visual_observation_attested:true,visual_quality_verified:pass,holistic_visual_judgment_verified:pass,visual_regression_verified:true,rendered_layout_accessibility_verified:true,motion_quality_verified:false,full_wcag_conformance_verified:false,baseline_promotion_performed:false},packet_path:rel(root,path.resolve(packetPath)),packet_file_sha256:fileSha(path.resolve(packetPath)),packet_sha256:pv.packet.packet_sha256,submission_path:rel(root,ia),submission_file_sha256:fileSha(ia),judge:{agent_id:s.judge.agent_id,model_ref:s.judge.model_ref,observation_mode:s.judge.observation_mode},rubric:pv.packet.rubric,cases:v.cases,summary:{total_cases:v.cases.length,passed:v.cases.filter(x=>x.verdict==='PASS').length,failed:v.cases.filter(x=>x.verdict==='FAIL').length,blocked:v.cases.filter(x=>x.verdict==='BLOCKED').length,overall_score:v.overall_score,pass_threshold:policy().overall_pass_score},created_at:new Date().toISOString(),judgment_sha256:''};report.judgment_sha256=shaObject(report);const fp=outPath?path.resolve(outPath):path.join(root,policy().judgments_root,`${report.task_id}.json`);if(!inside(root,fp))die('JUDGMENT_OUTPUT_PATH_INVALID',124);writeJson(fp,report);return {status:report.status,path:rel(root,fp),judgment:report,exit:pass?0:report.status==='VISUAL_JUDGMENT_FAIL'?3:4}}
function verifyJudgment(root,reportPath){const errors=[];const a=path.resolve(reportPath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_JUDGMENT_REPORT_INVALID',valid:false,errors:['judgment_missing_or_external']};let r;try{r=readJson(a)}catch{return {status:'VISUAL_JUDGMENT_REPORT_INVALID',valid:false,errors:['judgment_unreadable']}}if(!sealValid(r,'judgment_sha256'))errors.push('judgment_integrity_mismatch');const pp=relWithin(root,r.packet_path),sp=relWithin(root,r.submission_path);let pv=null,s=null;if(!pp||!fs.existsSync(pp))errors.push('packet_missing');else{if(fileSha(pp)!==r.packet_file_sha256)errors.push('packet_file_drift');pv=verifyPacket(root,pp);if(!pv.valid)errors.push('packet_invalid');else if(pv.packet.packet_sha256!==r.packet_sha256)errors.push('packet_hash_mismatch')}if(!sp||!fs.existsSync(sp))errors.push('submission_missing');else{if(fileSha(sp)!==r.submission_file_sha256)errors.push('submission_file_drift');try{s=readJson(sp)}catch{errors.push('submission_unreadable')}}if(pv?.valid&&s){const v=validateSubmission(pv.packet,s);if(v.errors.length)errors.push(...v.errors.map(x=>`submission:${x}`));const pass=v.status==='VISUAL_JUDGMENT_PASS';if(r.status!==v.status)errors.push('judgment_status_mismatch');if(JSON.stringify(r.cases)!==JSON.stringify(v.cases))errors.push('judgment_cases_mismatch');const expectedSummary={total_cases:v.cases.length,passed:v.cases.filter(x=>x.verdict==='PASS').length,failed:v.cases.filter(x=>x.verdict==='FAIL').length,blocked:v.cases.filter(x=>x.verdict==='BLOCKED').length,overall_score:v.overall_score,pass_threshold:policy().overall_pass_score};if(JSON.stringify(r.summary)!==JSON.stringify(expectedSummary))errors.push('judgment_summary_mismatch');if(r.claims?.native_visual_observation_attested!==true)errors.push('visual_observation_claim_missing');if(r.claims?.visual_quality_verified!==pass||r.claims?.holistic_visual_judgment_verified!==pass)errors.push('visual_quality_claim_mismatch');if(r.claims?.visual_regression_verified!==true||r.claims?.rendered_layout_accessibility_verified!==true)errors.push('upstream_claim_mismatch')}if(r.claims?.motion_quality_verified!==false)errors.push('motion_quality_claim_forbidden');if(r.claims?.full_wcag_conformance_verified!==false)errors.push('full_wcag_claim_forbidden');if(r.claims?.baseline_promotion_performed!==false)errors.push('baseline_promotion_claim_forbidden');return {status:errors.length?'VISUAL_JUDGMENT_REPORT_INVALID':'VISUAL_JUDGMENT_REPORT_VALID',valid:!errors.length,errors,judgment:r,path:rel(root,a)}}

function historicalJudgment(root,reportPath){const errors=[];const a=path.resolve(reportPath);if(!inside(root,a)||!fs.existsSync(a))return {valid:false,errors:['judgment_missing_or_external']};let r;try{r=readJson(a)}catch{return {valid:false,errors:['judgment_unreadable']}}if(!sealValid(r,'judgment_sha256'))errors.push('judgment_integrity_mismatch');const pp=relWithin(root,r.packet_path),sp=relWithin(root,r.submission_path);if(!pp||!fs.existsSync(pp))errors.push('packet_missing');else{if(fileSha(pp)!==r.packet_file_sha256)errors.push('packet_file_drift');let q;try{q=readJson(pp)}catch{errors.push('packet_unreadable')}if(q&&!sealValid(q,'packet_sha256'))errors.push('packet_integrity_mismatch');if(q&&q.packet_sha256!==r.packet_sha256)errors.push('packet_hash_mismatch')}if(!sp||!fs.existsSync(sp))errors.push('submission_missing');else if(fileSha(sp)!==r.submission_file_sha256)errors.push('submission_file_drift');return {valid:!errors.length,errors,judgment:r,path:rel(root,a)}}
function scopeSnapshot(s){return {task_id:s.task_id,scope_version:s.scope_version,approved_scope:Array.isArray(s.approved_scope)?[...s.approved_scope]:[],repair_count:s.repair_count,max_repairs:s.max_repairs,final_state:s.final_state??null}}
function authorizeRepair(root,judgmentPath,outPath,stateArg){const jv=verifyJudgment(root,judgmentPath);if(!jv.valid)die('VISUAL_JUDGMENT_REPORT_INVALID',130,{errors:jv.errors});if(jv.judgment.status==='VISUAL_JUDGMENT_BLOCKED')die('BLOCKED_JUDGMENT_NOT_AUTO_REPAIRABLE',131);if(jv.judgment.status!=='VISUAL_JUDGMENT_FAIL')die('FAILED_JUDGMENT_REQUIRED',132);const st=coreState(root,stateArg),s=st.obj,p=policy();if(s.task_id!==jv.judgment.task_id)die('GLOBAL_TASK_MISMATCH',133);if(s.final_state)die('GLOBAL_RUN_ALREADY_FINAL',134,{final_state:s.final_state});if(!Number.isInteger(s.repair_count)||s.repair_count<1)die('GLOBAL_REPAIR_NOT_STARTED',135);const cap=Math.min(Number.isInteger(s.max_repairs)?s.max_repairs:p.max_repairs,p.max_repairs);if(s.repair_count>cap)die('VISUAL_REPAIR_CAP_EXCEEDED',136);if(!Array.isArray(s.approved_scope)||!s.approved_scope.length)die('APPROVED_SCOPE_REQUIRED',137);const attempt=s.repair_count,fp=outPath?path.resolve(outPath):path.join(root,p.repairs_root,`${jv.judgment.task_id}--repair-${attempt}.json`);if(!inside(root,fp))die('REPAIR_PLAN_OUTPUT_PATH_INVALID',138);if(fs.existsSync(fp))die('REPAIR_PLAN_IMMUTABLE',139);const pp=relWithin(root,jv.judgment.packet_path),packet=readJson(pp);const findings=jv.judgment.cases.flatMap(c=>c.findings.filter(f=>c.verdict==='FAIL'||f.blocking).map(f=>({case_id:c.case_id,...f})));const plan={schema_version:'1.0',phase:'VISUAL_QA_P5_REPAIR',task_id:jv.judgment.task_id,status:'VISUAL_REPAIR_AUTHORIZED',attempt,max_repairs:cap,source_judgment_path:rel(root,path.resolve(judgmentPath)),source_judgment_file_sha256:fileSha(path.resolve(judgmentPath)),source_judgment_sha256:jv.judgment.judgment_sha256,pre_repair_packet_sha256:jv.judgment.packet_sha256,pre_repair_upstream:{phase2_receipt_file_sha256:packet.phase2_receipt_file_sha256,phase3_report_file_sha256:packet.phase3_report_file_sha256,phase4_report_file_sha256:packet.phase4_report_file_sha256},global_state:scopeSnapshot(s),authorized_scope:[...s.approved_scope],findings,requirements:{repair_only_listed_visual_failures:true,scope_expansion_forbidden:true,canonical_policy_edits_forbidden:true,baseline_promotion_forbidden:true,fresh_phase2_required:true,fresh_phase3_required:true,fresh_phase4_required:true,fresh_visual_judgment_required:true},created_at:new Date().toISOString(),repair_plan_sha256:''};plan.repair_plan_sha256=shaObject(plan);writeJson(fp,plan);return {status:'VISUAL_REPAIR_AUTHORIZED',path:rel(root,fp),repair_plan:plan}}
function verifyRepair(root,planPath,stateArg){const errors=[];const a=path.resolve(planPath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_REPAIR_PLAN_INVALID',valid:false,errors:['repair_plan_missing_or_external']};let r;try{r=readJson(a)}catch{return {status:'VISUAL_REPAIR_PLAN_INVALID',valid:false,errors:['repair_plan_unreadable']}}if(!sealValid(r,'repair_plan_sha256'))errors.push('repair_plan_integrity_mismatch');const jp=relWithin(root,r.source_judgment_path);let jv=null;if(!jp||!fs.existsSync(jp))errors.push('source_judgment_missing');else{if(fileSha(jp)!==r.source_judgment_file_sha256)errors.push('source_judgment_drift');jv=historicalJudgment(root,jp);if(!jv.valid)errors.push('source_judgment_invalid');else{if(jv.judgment.judgment_sha256!==r.source_judgment_sha256)errors.push('source_judgment_hash_mismatch');if(jv.judgment.status!=='VISUAL_JUDGMENT_FAIL')errors.push('source_judgment_not_fail')}}let st=null;try{st=coreState(root,stateArg)}catch{errors.push('global_state_invalid')}if(st){const s=st.obj;if(s.task_id!==r.task_id)errors.push('global_task_mismatch');if(s.repair_count!==r.attempt)errors.push('global_repair_count_drift');if(s.scope_version!==r.global_state?.scope_version)errors.push('global_scope_version_drift');if(JSON.stringify(s.approved_scope||[])!==JSON.stringify(r.authorized_scope||[]))errors.push('authorized_scope_drift');if(r.attempt<1||r.attempt>Math.min(policy().max_repairs,s.max_repairs??policy().max_repairs))errors.push('repair_attempt_out_of_bounds')}for(const k of ['scope_expansion_forbidden','canonical_policy_edits_forbidden','baseline_promotion_forbidden','fresh_phase2_required','fresh_phase3_required','fresh_phase4_required','fresh_visual_judgment_required'])if(r.requirements?.[k]!==true)errors.push(`repair_requirement_missing:${k}`);return {status:errors.length?'VISUAL_REPAIR_PLAN_INVALID':'VISUAL_REPAIR_PLAN_VALID',valid:!errors.length,errors,repair_plan:r,path:rel(root,a)}}

function finalizeCycle(root,beforePath,planPath,afterPath,outPath,stateArg){const b=historicalJudgment(root,beforePath),rp=verifyRepair(root,planPath,stateArg),a=verifyJudgment(root,afterPath);if(!b.valid)die('BEFORE_JUDGMENT_INVALID',160,{errors:b.errors});if(!rp.valid)die('REPAIR_PLAN_INVALID',161,{errors:rp.errors});if(!a.valid)die('AFTER_JUDGMENT_INVALID',162,{errors:a.errors});if(b.judgment.status!=='VISUAL_JUDGMENT_FAIL')die('BEFORE_JUDGMENT_NOT_FAIL',163);if(b.judgment.task_id!==a.judgment.task_id||b.judgment.task_id!==rp.repair_plan.task_id)die('REPAIR_CYCLE_TASK_MISMATCH',164);if(fileSha(path.resolve(beforePath))!==rp.repair_plan.source_judgment_file_sha256)die('REPAIR_PLAN_SOURCE_MISMATCH',165);const bp=readJson(relWithin(root,b.judgment.packet_path)),ap=readJson(relWithin(root,a.judgment.packet_path)),fresh=[];for(const k of ['phase2_receipt_file_sha256','phase3_report_file_sha256','phase4_report_file_sha256'])if(bp[k]===ap[k])fresh.push(k);if(bp.evidence_revision===ap.evidence_revision)fresh.push('evidence_revision');if(policy().require_fresh_p2_p3_p4_after_repair&&fresh.length)die('STALE_POST_REPAIR_EVIDENCE',166,{unchanged:fresh});if(b.judgment.judgment_sha256===a.judgment.judgment_sha256)die('STALE_POST_REPAIR_JUDGMENT',167);let status;if(a.judgment.status==='VISUAL_JUDGMENT_PASS')status='VISUAL_REPAIR_CYCLE_PASS';else if(a.judgment.status==='VISUAL_JUDGMENT_BLOCKED')status='VISUAL_REPAIR_CYCLE_BLOCKED';else status=rp.repair_plan.attempt>=rp.repair_plan.max_repairs?'VISUAL_REPAIR_EXHAUSTED':'VISUAL_REPAIR_RETRY_ALLOWED';const cycle={schema_version:'1.0',phase:'VISUAL_QA_P5_REPAIR_CYCLE',task_id:b.judgment.task_id,status,attempt:rp.repair_plan.attempt,max_repairs:rp.repair_plan.max_repairs,before_judgment_path:rel(root,path.resolve(beforePath)),before_judgment_file_sha256:fileSha(path.resolve(beforePath)),before_judgment_sha256:b.judgment.judgment_sha256,repair_plan_path:rel(root,path.resolve(planPath)),repair_plan_file_sha256:fileSha(path.resolve(planPath)),repair_plan_sha256:rp.repair_plan.repair_plan_sha256,after_judgment_path:rel(root,path.resolve(afterPath)),after_judgment_file_sha256:fileSha(path.resolve(afterPath)),after_judgment_sha256:a.judgment.judgment_sha256,fresh_evidence:{phase2:true,phase3:true,phase4:true,judgment:true},created_at:new Date().toISOString(),cycle_sha256:''};cycle.cycle_sha256=shaObject(cycle);const fp=outPath?path.resolve(outPath):path.join(root,policy().cycles_root,`${cycle.task_id}--repair-${cycle.attempt}.json`);if(!inside(root,fp))die('CYCLE_OUTPUT_PATH_INVALID',168);if(fs.existsSync(fp))die('REPAIR_CYCLE_IMMUTABLE',169);writeJson(fp,cycle);return {status,path:rel(root,fp),cycle,exit:status==='VISUAL_REPAIR_CYCLE_PASS'?0:status==='VISUAL_REPAIR_RETRY_ALLOWED'?3:status==='VISUAL_REPAIR_EXHAUSTED'?7:4}}
function verifyCycle(root,cyclePath,stateArg){const errors=[];const a=path.resolve(cyclePath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_REPAIR_CYCLE_INVALID',valid:false,errors:['cycle_missing_or_external']};let c;try{c=readJson(a)}catch{return {status:'VISUAL_REPAIR_CYCLE_INVALID',valid:false,errors:['cycle_unreadable']}}if(!sealValid(c,'cycle_sha256'))errors.push('cycle_integrity_mismatch');const bp=relWithin(root,c.before_judgment_path),rp=relWithin(root,c.repair_plan_path),ap=relWithin(root,c.after_judgment_path);if(!bp||!fs.existsSync(bp))errors.push('before_judgment_missing');else if(fileSha(bp)!==c.before_judgment_file_sha256)errors.push('before_judgment_drift');if(!rp||!fs.existsSync(rp))errors.push('repair_plan_missing');else if(fileSha(rp)!==c.repair_plan_file_sha256)errors.push('repair_plan_drift');if(!ap||!fs.existsSync(ap))errors.push('after_judgment_missing');else if(fileSha(ap)!==c.after_judgment_file_sha256)errors.push('after_judgment_drift');if(bp&&rp&&ap&&fs.existsSync(bp)&&fs.existsSync(rp)&&fs.existsSync(ap)){const b=historicalJudgment(root,bp),r=verifyRepair(root,rp,stateArg),af=verifyJudgment(root,ap);if(!b.valid)errors.push('before_judgment_invalid');if(!r.valid)errors.push('repair_plan_invalid');if(!af.valid)errors.push('after_judgment_invalid');if(b.valid&&r.valid&&af.valid){if(b.judgment.status!=='VISUAL_JUDGMENT_FAIL')errors.push('before_judgment_not_fail');if(c.before_judgment_sha256!==b.judgment.judgment_sha256||c.repair_plan_sha256!==r.repair_plan.repair_plan_sha256||c.after_judgment_sha256!==af.judgment.judgment_sha256)errors.push('cycle_reference_hash_mismatch');const bpk=readJson(relWithin(root,b.judgment.packet_path)),apk=readJson(relWithin(root,af.judgment.packet_path));for(const k of ['phase2_receipt_file_sha256','phase3_report_file_sha256','phase4_report_file_sha256'])if(bpk[k]===apk[k])errors.push(`stale_post_repair:${k}`);if(bpk.evidence_revision===apk.evidence_revision)errors.push('stale_post_repair:evidence_revision');let expected;if(af.judgment.status==='VISUAL_JUDGMENT_PASS')expected='VISUAL_REPAIR_CYCLE_PASS';else if(af.judgment.status==='VISUAL_JUDGMENT_BLOCKED')expected='VISUAL_REPAIR_CYCLE_BLOCKED';else expected=r.repair_plan.attempt>=r.repair_plan.max_repairs?'VISUAL_REPAIR_EXHAUSTED':'VISUAL_REPAIR_RETRY_ALLOWED';if(c.status!==expected)errors.push('cycle_status_mismatch')}}return {status:errors.length?'VISUAL_REPAIR_CYCLE_INVALID':'VISUAL_REPAIR_CYCLE_VALID',valid:!errors.length,errors,cycle:c,path:rel(root,a)}}

function sealAcceptance(root,judgmentPath,cyclePath,outPath,stateArg){const j=verifyJudgment(root,judgmentPath);if(!j.valid)die('VISUAL_JUDGMENT_REPORT_INVALID',180,{errors:j.errors});if(j.judgment.status!=='VISUAL_JUDGMENT_PASS')die('PASS_JUDGMENT_REQUIRED',181);const st=coreState(root,stateArg),s=st.obj;if(s.task_id!==j.judgment.task_id)die('GLOBAL_TASK_MISMATCH',182);let cycle=null,cycleFile=null;if((s.repair_count||0)>0){if(!cyclePath)die('LATEST_REPAIR_CYCLE_REQUIRED',183);const cv=verifyCycle(root,cyclePath,stateArg);if(!cv.valid)die('REPAIR_CYCLE_INVALID',184,{errors:cv.errors});if(cv.cycle.status!=='VISUAL_REPAIR_CYCLE_PASS'||cv.cycle.attempt!==s.repair_count)die('LATEST_REPAIR_CYCLE_PASS_REQUIRED',185);if(cv.cycle.after_judgment_file_sha256!==fileSha(path.resolve(judgmentPath)))die('ACCEPTANCE_JUDGMENT_NOT_LATEST_REPAIR',186);cycle=cv.cycle;cycleFile=path.resolve(cyclePath)}const a={schema_version:'1.0',phase:'VISUAL_QA_P5_ACCEPTANCE',task_id:j.judgment.task_id,status:'VISUAL_QA_PASS',claims:{visual_quality_verified:true,visual_regression_verified:true,rendered_layout_accessibility_verified:true,native_visual_observation_attested:true,bounded_repair_loop_satisfied:true,motion_quality_verified:false,full_wcag_conformance_verified:false},judgment_path:rel(root,path.resolve(judgmentPath)),judgment_file_sha256:fileSha(path.resolve(judgmentPath)),judgment_sha256:j.judgment.judgment_sha256,repair_count:s.repair_count||0,max_repairs:Math.min(s.max_repairs??policy().max_repairs,policy().max_repairs),scope_version:s.scope_version,cycle_path:cycleFile?rel(root,cycleFile):null,cycle_file_sha256:cycleFile?fileSha(cycleFile):null,cycle_sha256:cycle?.cycle_sha256||null,created_at:new Date().toISOString(),acceptance_sha256:''};a.acceptance_sha256=shaObject(a);const fp=outPath?path.resolve(outPath):path.join(root,policy().acceptance_root,`${a.task_id}.json`);if(!inside(root,fp))die('ACCEPTANCE_OUTPUT_PATH_INVALID',187);writeJson(fp,a);return {status:'VISUAL_QA_PASS',path:rel(root,fp),acceptance:a}}
function verifyAcceptance(root,acceptancePath,stateArg){const errors=[];const a=path.resolve(acceptancePath);if(!inside(root,a)||!fs.existsSync(a))return {status:'VISUAL_QA_ACCEPTANCE_INVALID',valid:false,errors:['acceptance_missing_or_external']};let q;try{q=readJson(a)}catch{return {status:'VISUAL_QA_ACCEPTANCE_INVALID',valid:false,errors:['acceptance_unreadable']}}if(!sealValid(q,'acceptance_sha256'))errors.push('acceptance_integrity_mismatch');const jp=relWithin(root,q.judgment_path);let j=null;if(!jp||!fs.existsSync(jp))errors.push('judgment_missing');else{if(fileSha(jp)!==q.judgment_file_sha256)errors.push('judgment_drift');const v=verifyJudgment(root,jp);if(!v.valid)errors.push('judgment_invalid');else{j=v.judgment;if(j.status!=='VISUAL_JUDGMENT_PASS')errors.push('judgment_not_pass');if(j.judgment_sha256!==q.judgment_sha256)errors.push('judgment_hash_mismatch')}}let st=null;try{st=coreState(root,stateArg)}catch{errors.push('global_state_invalid')}if(st){const s=st.obj;if(s.task_id!==q.task_id)errors.push('global_task_mismatch');if((s.repair_count||0)!==q.repair_count)errors.push('repair_count_drift');if(s.scope_version!==q.scope_version)errors.push('scope_version_drift');if(q.repair_count>0){const cp=relWithin(root,q.cycle_path);if(!cp||!fs.existsSync(cp))errors.push('cycle_missing');else{if(fileSha(cp)!==q.cycle_file_sha256)errors.push('cycle_drift');const cv=verifyCycle(root,cp,stateArg);if(!cv.valid)errors.push('cycle_invalid');else{if(cv.cycle.status!=='VISUAL_REPAIR_CYCLE_PASS'||cv.cycle.attempt!==q.repair_count)errors.push('cycle_not_latest_pass');if(cv.cycle.cycle_sha256!==q.cycle_sha256)errors.push('cycle_hash_mismatch');if(j&&cv.cycle.after_judgment_file_sha256!==fileSha(jp))errors.push('judgment_not_cycle_after')}}}else if(q.cycle_path!==null||q.cycle_file_sha256!==null||q.cycle_sha256!==null)errors.push('unexpected_cycle_without_repair')}
  if(q.status!=='VISUAL_QA_PASS')errors.push('acceptance_status_invalid');for(const k of ['visual_quality_verified','visual_regression_verified','rendered_layout_accessibility_verified','native_visual_observation_attested','bounded_repair_loop_satisfied'])if(q.claims?.[k]!==true)errors.push(`acceptance_claim_missing:${k}`);if(q.claims?.motion_quality_verified!==false)errors.push('motion_quality_claim_forbidden');if(q.claims?.full_wcag_conformance_verified!==false)errors.push('full_wcag_claim_forbidden');return {status:errors.length?'VISUAL_QA_ACCEPTANCE_INVALID':'VISUAL_QA_ACCEPTANCE_VALID',valid:!errors.length,errors,acceptance:q,path:rel(root,a)}}

const root=rootOf(take('--project-root',process.cwd()));
try{
  if(group==='packet'&&cmd==='prepare'){const r=take('--receipt'),p3=take('--phase3-report'),p4=take('--phase4-report');if(!r||!p3||!p4)die('PACKET_ARGUMENTS_REQUIRED');const x=preparePacket(root,r,p3,p4,take('--out'));out(x);process.exit(0)}
  if(group==='packet'&&cmd==='verify'){const p=take('--packet');if(!p)die('PACKET_REQUIRED');const x=verifyPacket(root,p);out(x);process.exit(x.valid?0:3)}
  if(group==='judgment'&&cmd==='seal'){const p=take('--packet'),i=take('--input');if(!p||!i)die('JUDGMENT_ARGUMENTS_REQUIRED');const x=sealJudgment(root,p,i,take('--out'));out({status:x.status,path:x.path,judgment:x.judgment});process.exit(x.exit)}
  if(group==='judgment'&&cmd==='verify'){const p=take('--judgment');if(!p)die('JUDGMENT_REQUIRED');const x=verifyJudgment(root,p);out(x);process.exit(x.valid?0:3)}
  if(group==='repair'&&cmd==='authorize'){const j=take('--judgment');if(!j)die('JUDGMENT_REQUIRED');const x=authorizeRepair(root,j,take('--out'),take('--state'));out(x);process.exit(0)}
  if(group==='repair'&&cmd==='verify'){const p=take('--plan');if(!p)die('REPAIR_PLAN_REQUIRED');const x=verifyRepair(root,p,take('--state'));out(x);process.exit(x.valid?0:3)}
  if(group==='cycle'&&cmd==='finalize'){const b=take('--before'),p=take('--plan'),a=take('--after');if(!b||!p||!a)die('CYCLE_ARGUMENTS_REQUIRED');const x=finalizeCycle(root,b,p,a,take('--out'),take('--state'));out({status:x.status,path:x.path,cycle:x.cycle});process.exit(x.exit)}
  if(group==='cycle'&&cmd==='verify'){const p=take('--cycle');if(!p)die('CYCLE_REQUIRED');const x=verifyCycle(root,p,take('--state'));out(x);process.exit(x.valid?0:3)}
  if(group==='acceptance'&&cmd==='seal'){const j=take('--judgment');if(!j)die('JUDGMENT_REQUIRED');const x=sealAcceptance(root,j,take('--cycle'),take('--out'),take('--state'));out(x);process.exit(0)}
  if(group==='acceptance'&&cmd==='verify'){const p=take('--acceptance');if(!p)die('ACCEPTANCE_REQUIRED');const x=verifyAcceptance(root,p,take('--state'));out(x);process.exit(x.valid?0:3)}
  die('VISUAL_JUDGE_COMMAND_UNKNOWN',2,{usage:['packet prepare --receipt <p2> --phase3-report <p3> --phase4-report <p4>','packet verify --packet <json>','judgment seal --packet <packet> --input <submission>','judgment verify --judgment <json>','repair authorize --judgment <failed>','repair verify --plan <json>','cycle finalize --before <failed> --plan <repair> --after <judgment>','cycle verify --cycle <json>','acceptance seal --judgment <pass> [--cycle <pass-cycle>]','acceptance verify --acceptance <json>']});
}catch(e){die(e?.code||'VISUAL_JUDGE_FAILED',e?.exitCode||199,{...(e?.extra||{}),message:e?.message||String(e)})}
