#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const executionRoot=path.resolve(here,'..');
const sourcePackageRoot=path.basename(path.dirname(executionRoot))==='.aledevos'?null:path.resolve(executionRoot,'..');
const args=process.argv.slice(2),[group,cmd]=args;
const take=(flag,def=null)=>{const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:def};
const out=v=>process.stdout.write(JSON.stringify(v,null,2)+'\n');
const die=(status,code=2,extra={})=>{out({status,...extra});process.exit(code)};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')};
const shaBytes=b=>crypto.createHash('sha256').update(b).digest('hex');
const hashFile=p=>shaBytes(fs.readFileSync(p));
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!['receipt_sha256','evidence_sha256'].includes(k)).sort().map(k=>[k,stable(v[k])])):v;
const hashObj=v=>shaBytes(Buffer.from(JSON.stringify(stable(v))));
const policyPath=path.join(executionRoot,'policies/worktree-policy.json');
const policy=()=>read(policyPath);
const now=()=>new Date().toISOString();

function git(cwd,argv,{allowFailure=false}={}){
 const r=spawnSync('git',argv,{cwd,encoding:'utf8',windowsHide:true});
 if(r.error)return{ok:false,status:null,stdout:'',stderr:String(r.error.message||r.error)};
 const x={ok:r.status===0,status:r.status,stdout:(r.stdout||'').trim(),stderr:(r.stderr||'').trim()};
 if(!x.ok&&!allowFailure)throw new Error(`git ${argv.join(' ')} failed: ${x.stderr||x.stdout}`);
 return x;
}
function realExisting(p){return fs.realpathSync.native?fs.realpathSync.native(p):fs.realpathSync(p)}
function normalizePath(p){return path.resolve(p).replace(/[\\/]+$/,'')}
function pathEq(a,b){return process.platform==='win32'?normalizePath(a).toLowerCase()===normalizePath(b).toLowerCase():normalizePath(a)===normalizePath(b)}
function versionTuple(s){const m=String(s).match(/(\d+)\.(\d+)\.(\d+)/);return m?[+m[1],+m[2],+m[3]]:[0,0,0]}
function versionGte(a,b){const A=versionTuple(a),B=versionTuple(b);for(let i=0;i<3;i++){if(A[i]>B[i])return true;if(A[i]<B[i])return false}return true}
function validTaskId(id,p=policy()){if(typeof id!=='string'||id.length>p.max_task_id_length||!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(id)||id.includes('..')||id.endsWith('.')||/\.lock$/i.test(id))return false;return !/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(id)}
function validBaseRef(ref){return typeof ref==='string'&&ref.length>0&&ref.length<=200&&!ref.startsWith('-')&&!/[\0-\x1f\x7f]/.test(ref)}
function parseWorktreeList(text){
 const rows=[];let cur=null;for(const line of String(text||'').split(/\r?\n/)){if(line.startsWith('worktree ')){if(cur)rows.push(cur);cur={path:line.slice(9)}}else if(cur&&line.startsWith('HEAD '))cur.head=line.slice(5);else if(cur&&line.startsWith('branch '))cur.branch=line.slice(7);else if(cur&&line==='detached')cur.detached=true;else if(cur&&line==='bare')cur.bare=true}if(cur)rows.push(cur);return rows;
}
function repoIdentity(repo){const common=git(repo,['rev-parse','--git-common-dir']).stdout;const commonAbs=path.resolve(repo,common);return shaBytes(Buffer.from(`${normalizePath(repo)}\n${normalizePath(commonAbs)}`))}
function ongoingOperation(repo){for(const name of ['MERGE_HEAD','CHERRY_PICK_HEAD','REVERT_HEAD','BISECT_LOG']){const p=git(repo,['rev-parse','--git-path',name]).stdout;if(p&&fs.existsSync(path.resolve(repo,p)))return name}for(const name of ['rebase-merge','rebase-apply']){const p=git(repo,['rev-parse','--git-path',name]).stdout;if(p&&fs.existsSync(path.resolve(repo,p)))return name}return null}
function preflight(repoInput,{requireClean=true}={}){
 const errors=[],details={};if(!repoInput||!fs.existsSync(repoInput))return{status:'WORKTREE_PREFLIGHT_BLOCKED',valid:false,errors:['REPOSITORY_MISSING'],details};
 let repo;try{repo=realExisting(repoInput)}catch{return{status:'WORKTREE_PREFLIGHT_BLOCKED',valid:false,errors:['REPOSITORY_UNRESOLVABLE'],details}};
 const gv=git(repo,['--version'],{allowFailure:true});if(!gv.ok){errors.push('GIT_NOT_AVAILABLE');return{status:'WORKTREE_PREFLIGHT_BLOCKED',valid:false,errors,details:{repository_root:repo}}}
 const p=policy();details.git_version=gv.stdout.replace(/^git version\s+/,'');if(!versionGte(details.git_version,p.git_min_version))errors.push('GIT_VERSION_TOO_OLD');
 const bare=git(repo,['rev-parse','--is-bare-repository'],{allowFailure:true});if(!bare.ok||bare.stdout==='true')errors.push('BARE_REPOSITORY_UNSUPPORTED');
 const top=git(repo,['rev-parse','--show-toplevel'],{allowFailure:true});if(!top.ok)errors.push('NOT_A_GIT_WORKTREE');else{let actualTop=top.stdout;try{actualTop=realExisting(actualTop)}catch{}details.repository_root=actualTop;if(!pathEq(actualTop,repo))errors.push('REPOSITORY_ROOT_REQUIRED')}
 if(errors.includes('NOT_A_GIT_WORKTREE')||errors.includes('BARE_REPOSITORY_UNSUPPORTED'))return{status:'WORKTREE_PREFLIGHT_BLOCKED',valid:false,errors,details};
 const list=parseWorktreeList(git(repo,['worktree','list','--porcelain']).stdout);details.registered_worktrees=list.length;const primary=list[0];if(!primary||!pathEq(primary.path,repo))errors.push('PRIMARY_CHECKOUT_REQUIRED');
 const branch=git(repo,['symbolic-ref','--quiet','--short','HEAD'],{allowFailure:true});if(!branch.ok||!branch.stdout)errors.push('ATTACHED_PRIMARY_BRANCH_REQUIRED');else details.primary_branch=branch.stdout;
 const head=git(repo,['rev-parse','HEAD'],{allowFailure:true});if(!head.ok)errors.push('HEAD_UNRESOLVABLE');else details.primary_head=head.stdout;
 const status=git(repo,['status','--porcelain=v1','--untracked-files=all'],{allowFailure:true});details.primary_clean=status.ok&&status.stdout==='';if(requireClean&&!details.primary_clean)errors.push('PRIMARY_WORKTREE_DIRTY');
 const op=ongoingOperation(repo);details.ongoing_operation=op;if(op)errors.push(`GIT_OPERATION_IN_PROGRESS:${op}`);
 if(details.repository_root)details.repository_identity_sha256=repoIdentity(details.repository_root);
 return{status:errors.length?'WORKTREE_PREFLIGHT_BLOCKED':'WORKTREE_PREFLIGHT_PASS',valid:!errors.length,errors,details};
}
function resolveCommit(repo,ref){if(!validBaseRef(ref))return null;const r=git(repo,['rev-parse','--verify','--end-of-options',`${ref}^{commit}`],{allowFailure:true});return r.ok&&/^[0-9a-fA-F]{40,64}$/.test(r.stdout)?r.stdout.toLowerCase():null}
function branchName(taskId){return `${policy().branch_prefix}${taskId}`}
function repoBucket(repo){const base=path.basename(repo).replace(/[^A-Za-z0-9._-]/g,'_').slice(0,48)||'repo';return `${base}-${shaBytes(Buffer.from(normalizePath(repo))).slice(0,10)}`}
function allowedRoot(repo){const p=policy();return path.join(path.dirname(repo),p.worktree_container,repoBucket(repo))}
function targetPath(repo,taskId){return path.join(allowedRoot(repo),taskId)}
function pathEntryExists(p){try{fs.lstatSync(p);return true}catch(e){if(e?.code==='ENOENT')return false;throw e}}
function safeEnsureWorktreeRoot(repo){const p=policy(),container=path.join(path.dirname(repo),p.worktree_container),root=allowedRoot(repo),errors=[];for(const [label,dir] of [['CONTAINER',container],['ROOT',root]]){if(pathEntryExists(dir)){const st=fs.lstatSync(dir);if(st.isSymbolicLink())errors.push(`${label}_IS_SYMLINK`);else if(!st.isDirectory())errors.push(`${label}_NOT_DIRECTORY`)}}if(errors.length)return{valid:false,errors,root,container};if(!pathEntryExists(container))fs.mkdirSync(container);if(!pathEntryExists(root))fs.mkdirSync(root);try{if(!pathEq(realExisting(container),container))errors.push('CONTAINER_REALPATH_DRIFT');if(!pathEq(realExisting(root),root))errors.push('ROOT_REALPATH_DRIFT')}catch{errors.push('WORKTREE_ROOT_UNRESOLVABLE')}return{valid:errors.length===0,errors,root,container}}
function requestValidateShape(r){
 const errors=[];if(r?.schema_version!=='1.0'||r?.phase!=='ADVANCED_EXECUTION_P1_WORKTREES')errors.push('REQUEST_PHASE_OR_SCHEMA_INVALID');if(!r?.request_id)errors.push('REQUEST_ID_MISSING');if(!validTaskId(r?.task_id))errors.push('TASK_ID_INVALID');if(!validBaseRef(r?.base_ref))errors.push('BASE_REF_INVALID');if(!/^[0-9a-fA-F]{40,64}$/.test(r?.base_commit||''))errors.push('BASE_COMMIT_INVALID');if(!/^[0-9a-f]{64}$/.test(r?.repository_identity_sha256||''))errors.push('REPOSITORY_IDENTITY_INVALID');if(!/^[0-9a-fA-F]{40,64}$/.test(r?.primary_head_at_prepare||''))errors.push('PRIMARY_HEAD_INVALID');if(typeof r?.primary_branch_at_prepare!=='string'||!r.primary_branch_at_prepare)errors.push('PRIMARY_BRANCH_INVALID');if(typeof r?.prepared_at!=='string'||!r.prepared_at)errors.push('PREPARED_AT_INVALID');for(const k of ['branch_name','worktree_path','target_path','path'])if(Object.prototype.hasOwnProperty.call(r||{},k))errors.push(`USER_CONTROLLED_${k.toUpperCase()}_FORBIDDEN`);return errors;
}
function prepareRequest(repoInput,taskId,baseRef='HEAD',outFile=null){
 const pf=preflight(repoInput);if(!pf.valid)die(pf.status,5,{errors:pf.errors,details:pf.details});if(!validTaskId(taskId))die('WORKTREE_REQUEST_INVALID',3,{errors:['TASK_ID_INVALID']});if(git(pf.details.repository_root,['check-ref-format','--branch',branchName(taskId)],{allowFailure:true}).status!==0)die('WORKTREE_REQUEST_INVALID',3,{errors:['DERIVED_BRANCH_INVALID']});if(!validBaseRef(baseRef))die('WORKTREE_REQUEST_INVALID',3,{errors:['BASE_REF_INVALID']});const repo=pf.details.repository_root,commit=resolveCommit(repo,baseRef);if(!commit)die('WORKTREE_REQUEST_INVALID',3,{errors:['BASE_REF_UNRESOLVABLE']});const r={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P1_WORKTREES',request_id:`wt-${taskId}-${crypto.randomUUID()}`,task_id:taskId,base_ref:baseRef,base_commit:commit,repository_identity_sha256:pf.details.repository_identity_sha256,primary_head_at_prepare:pf.details.primary_head,primary_branch_at_prepare:pf.details.primary_branch,prepared_at:now()};if(outFile)write(path.resolve(outFile),r);return{status:'WORKTREE_REQUEST_PREPARED',request:r,request_sha256:hashObj(r),derived:{branch:branchName(taskId),worktree_root:allowedRoot(repo),worktree_path:targetPath(repo,taskId)}};
}
function verifyRequest(repoInput,file){
 const pf=preflight(repoInput),errors=[];if(!pf.valid)errors.push(...pf.errors);let r;if(!file||!fs.existsSync(file))errors.push('REQUEST_MISSING');else try{r=read(file)}catch{errors.push('REQUEST_UNREADABLE')};if(r)errors.push(...requestValidateShape(r));if(r&&pf.details.repository_root){if(r.repository_identity_sha256!==pf.details.repository_identity_sha256)errors.push('REPOSITORY_IDENTITY_DRIFT');if(r.primary_head_at_prepare.toLowerCase()!==String(pf.details.primary_head||'').toLowerCase())errors.push('PRIMARY_HEAD_DRIFT');if(r.primary_branch_at_prepare!==pf.details.primary_branch)errors.push('PRIMARY_BRANCH_DRIFT');const current=resolveCommit(pf.details.repository_root,r.base_ref);if(!current||current.toLowerCase()!==r.base_commit.toLowerCase())errors.push('BASE_REF_DRIFT');}
 return{status:errors.length?'WORKTREE_REQUEST_STALE_OR_INVALID':'WORKTREE_REQUEST_VALID',valid:!errors.length,errors,request:r||null,request_sha256:r?hashObj(r):null,derived:r&&pf.details.repository_root?{branch:branchName(r.task_id),worktree_root:allowedRoot(pf.details.repository_root),worktree_path:targetPath(pf.details.repository_root,r.task_id)}:null,preflight:pf};
}
function branchExists(repo,branch){return git(repo,['show-ref','--verify','--quiet',`refs/heads/${branch}`],{allowFailure:true}).status===0}
function registeredWorktree(repo,target){return parseWorktreeList(git(repo,['worktree','list','--porcelain']).stdout).find(x=>pathEq(x.path,target))||null}
function ensureWithin(child,parent){const rel=path.relative(parent,child);return rel&&!rel.startsWith('..')&&!path.isAbsolute(rel)}
function createWorktree(repoInput,requestFile,outFile=null){
 const rv=verifyRequest(repoInput,requestFile);if(!rv.valid)die('WORKTREE_CREATE_BLOCKED',5,{errors:rv.errors});const repo=rv.preflight.details.repository_root,r=rv.request,p=policy(),branch=branchName(r.task_id),root=allowedRoot(repo),target=targetPath(repo,r.task_id);const errors=[];
 if(!ensureWithin(target,root))errors.push('TARGET_PATH_ESCAPE');if(pathEntryExists(target))errors.push('TARGET_PATH_EXISTS');const safeRoot=safeEnsureWorktreeRoot(repo);if(!safeRoot.valid)errors.push(...safeRoot.errors);if(branchExists(repo,branch))errors.push('TASK_BRANCH_ALREADY_EXISTS');if(registeredWorktree(repo,target))errors.push('TARGET_ALREADY_REGISTERED');const taskWts=parseWorktreeList(git(repo,['worktree','list','--porcelain']).stdout).filter((x,i)=>i>0&&x.branch?.startsWith(`refs/heads/${p.branch_prefix}`));if(taskWts.length>=p.max_registered_task_worktrees)errors.push('MAX_REGISTERED_TASK_WORKTREES_REACHED');if(errors.length)die('WORKTREE_CREATE_BLOCKED',5,{errors,derived:{branch,target,root}});
 const beforeHead=git(repo,['rev-parse','HEAD']).stdout;const add=git(repo,['worktree','add','--no-track','-b',branch,target,r.base_commit],{allowFailure:true});if(!add.ok)die('WORKTREE_CREATE_FAILED',6,{errors:['GIT_WORKTREE_ADD_FAILED'],git:{stdout:add.stdout,stderr:add.stderr}});
 const after=preflight(repo);const wtTop=git(target,['rev-parse','--show-toplevel'],{allowFailure:true}),wtBranch=git(target,['symbolic-ref','--quiet','--short','HEAD'],{allowFailure:true}),wtHead=git(target,['rev-parse','HEAD'],{allowFailure:true});const verifyErrors=[];if(!after.valid)verifyErrors.push(...after.errors.map(x=>`POST_CREATE_${x}`));if(beforeHead!==after.details.primary_head)verifyErrors.push('PRIMARY_HEAD_MUTATED');if(!wtTop.ok||!pathEq(wtTop.stdout,target))verifyErrors.push('WORKTREE_TOPLEVEL_MISMATCH');if(!wtBranch.ok||wtBranch.stdout!==branch)verifyErrors.push('WORKTREE_BRANCH_MISMATCH');if(!wtHead.ok||wtHead.stdout.toLowerCase()!==r.base_commit.toLowerCase())verifyErrors.push('WORKTREE_HEAD_MISMATCH');if(verifyErrors.length){git(repo,['worktree','remove',target],{allowFailure:true});die('WORKTREE_CREATE_POSTCONDITION_FAILED',6,{errors:verifyErrors})}
 const receipt={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P1_WORKTREES',status:'WORKTREE_CREATED',task_id:r.task_id,request_id:r.request_id,request_sha256:hashFile(requestFile),repository:{root:repo,identity_sha256:after.details.repository_identity_sha256,primary_branch:after.details.primary_branch,primary_head_before:beforeHead,primary_head_after:after.details.primary_head,clean_after:true},worktree:{path:target,allowed_root:root,branch,branch_ref:`refs/heads/${branch}`,base_ref:r.base_ref,base_commit:r.base_commit,head_at_creation:wtHead.stdout},boundaries:{path_derived:true,branch_derived:true,branch_reused:false,target_preexisted:false,network_used:false,worker_started:false,concurrency_used:false,dispatcher_used:false,queue_used:false,multi_machine_used:false},git_version:after.details.git_version,created_at:now(),receipt_sha256:''};receipt.receipt_sha256=hashObj(receipt);if(outFile)write(path.resolve(outFile),receipt);return receipt;
}
function verifyReceipt(file,{repoInput=null,requestFile=null}={}){
 const errors=[];let r;if(!file||!fs.existsSync(file))return{status:'WORKTREE_RECEIPT_INVALID',valid:false,errors:['RECEIPT_MISSING']};try{r=read(file)}catch{return{status:'WORKTREE_RECEIPT_INVALID',valid:false,errors:['RECEIPT_UNREADABLE']}};if(r.schema_version!=='1.0'||r.phase!=='ADVANCED_EXECUTION_P1_WORKTREES'||r.status!=='WORKTREE_CREATED')errors.push('RECEIPT_PHASE_OR_STATUS_INVALID');if(r.receipt_sha256!==hashObj(r))errors.push('RECEIPT_INTEGRITY_MISMATCH');const b=r.boundaries||{};for(const k of ['path_derived','branch_derived'])if(b[k]!==true)errors.push(`BOUNDARY_${k.toUpperCase()}_INVALID`);for(const k of ['branch_reused','target_preexisted','network_used','worker_started','concurrency_used','dispatcher_used','queue_used','multi_machine_used'])if(b[k]!==false)errors.push(`BOUNDARY_${k.toUpperCase()}_INVALID`);
 if(requestFile){if(!fs.existsSync(requestFile))errors.push('REQUEST_SOURCE_MISSING');else if(r.request_sha256!==hashFile(requestFile))errors.push('REQUEST_HASH_DRIFT')}
 if(repoInput){const pf=preflight(repoInput);if(!pf.valid)errors.push(...pf.errors.map(x=>`PRIMARY_${x}`));else{const repo=pf.details.repository_root;if(!pathEq(repo,r.repository?.root||''))errors.push('REPOSITORY_ROOT_DRIFT');if(pf.details.repository_identity_sha256!==r.repository?.identity_sha256)errors.push('REPOSITORY_IDENTITY_DRIFT');if(pf.details.primary_head!==r.repository?.primary_head_after)errors.push('PRIMARY_HEAD_DRIFT');const expectedRoot=allowedRoot(repo),expectedTarget=targetPath(repo,r.task_id),expectedBranch=branchName(r.task_id);if(!pathEq(r.worktree?.allowed_root||'',expectedRoot))errors.push('ALLOWED_ROOT_DRIFT');const safeRoot=safeEnsureWorktreeRoot(repo);if(!safeRoot.valid)errors.push(...safeRoot.errors.map(x=>`WORKTREE_ROOT_${x}`));if(!pathEq(r.worktree?.path||'',expectedTarget))errors.push('WORKTREE_PATH_DRIFT');if(r.worktree?.branch!==expectedBranch)errors.push('WORKTREE_BRANCH_DRIFT');if(!ensureWithin(expectedTarget,expectedRoot))errors.push('WORKTREE_PATH_ESCAPE');const reg=registeredWorktree(repo,expectedTarget);if(!reg)errors.push('WORKTREE_NOT_REGISTERED');else if(reg.branch!==`refs/heads/${expectedBranch}`)errors.push('REGISTERED_BRANCH_DRIFT');if(!fs.existsSync(expectedTarget))errors.push('WORKTREE_PATH_MISSING');else{const top=git(expectedTarget,['rev-parse','--show-toplevel'],{allowFailure:true}),br=git(expectedTarget,['symbolic-ref','--quiet','--short','HEAD'],{allowFailure:true}),head=git(expectedTarget,['rev-parse','HEAD'],{allowFailure:true});if(!top.ok||!pathEq(top.stdout,expectedTarget))errors.push('WORKTREE_TOPLEVEL_INVALID');if(!br.ok||br.stdout!==expectedBranch)errors.push('WORKTREE_BRANCH_INVALID');if(!head.ok)errors.push('WORKTREE_HEAD_UNRESOLVABLE');else if(git(expectedTarget,['merge-base','--is-ancestor',r.worktree.base_commit,head.stdout],{allowFailure:true}).status!==0)errors.push('BASE_COMMIT_NOT_ANCESTOR')}}}
 return{status:errors.length?'WORKTREE_RECEIPT_INVALID':'WORKTREE_RECEIPT_VALID',valid:!errors.length,errors,receipt:r};
}
function inspectWorktree(receiptFile,repoInput){const vr=verifyReceipt(receiptFile,{repoInput});if(!vr.valid)return{status:'WORKTREE_INSPECTION_BLOCKED',valid:false,errors:vr.errors};const r=vr.receipt,target=r.worktree.path,status=git(target,['status','--porcelain=v1','--untracked-files=all']).stdout,head=git(target,['rev-parse','HEAD']).stdout;return{status:'WORKTREE_INSPECTION_PASS',valid:true,task_id:r.task_id,worktree_path:target,branch:r.worktree.branch,head,base_commit:r.worktree.base_commit,base_is_ancestor:git(target,['merge-base','--is-ancestor',r.worktree.base_commit,head],{allowFailure:true}).status===0,clean:status==='',changes:status?status.split(/\r?\n/):[],primary_unchanged:true}}
function cleanupWorktree(receiptFile,repoInput,outFile=null){const vr=verifyReceipt(receiptFile,{repoInput});if(!vr.valid)die('WORKTREE_CLEANUP_BLOCKED',5,{errors:vr.errors});const r=vr.receipt,target=r.worktree.path,repo=r.repository.root,status=git(target,['status','--porcelain=v1','--untracked-files=all']).stdout;if(status!=='')die('WORKTREE_CLEANUP_BLOCKED_DIRTY',5,{changes:status.split(/\r?\n/)});const rm=git(repo,['worktree','remove',target],{allowFailure:true});if(!rm.ok)die('WORKTREE_CLEANUP_FAILED',6,{git:{stdout:rm.stdout,stderr:rm.stderr}});const branchStill=branchExists(repo,r.worktree.branch),registered=registeredWorktree(repo,target)!==null;const pf=preflight(repo);const c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P1_WORKTREES',status:'WORKTREE_CLEANUP_COMPLETED',task_id:r.task_id,source_receipt_sha256:hashFile(receiptFile),repository:{root:repo,identity_sha256:r.repository.identity_sha256,primary_head:r.repository.primary_head_after,primary_unchanged:pf.valid&&pf.details.primary_head===r.repository.primary_head_after,clean:pf.valid&&pf.details.primary_clean===true},worktree:{path:target,registered_after_cleanup:registered,path_exists_after_cleanup:fs.existsSync(target),branch:r.worktree.branch,branch_preserved:branchStill},boundaries:{force_remove_used:false,branch_delete_used:false,network_used:false,worker_started:false,concurrency_used:false},cleaned_at:now(),receipt_sha256:''};c.receipt_sha256=hashObj(c);if(outFile)write(path.resolve(outFile),c);return c}
function verifyCleanup(file,{sourceReceiptFile=null,repoInput=null}={}){const errors=[];let c;if(!file||!fs.existsSync(file))return{status:'WORKTREE_CLEANUP_RECEIPT_INVALID',valid:false,errors:['CLEANUP_RECEIPT_MISSING']};try{c=read(file)}catch{return{status:'WORKTREE_CLEANUP_RECEIPT_INVALID',valid:false,errors:['CLEANUP_RECEIPT_UNREADABLE']}};if(c.schema_version!=='1.0'||c.phase!=='ADVANCED_EXECUTION_P1_WORKTREES'||c.status!=='WORKTREE_CLEANUP_COMPLETED')errors.push('CLEANUP_PHASE_OR_STATUS_INVALID');if(c.receipt_sha256!==hashObj(c))errors.push('CLEANUP_INTEGRITY_MISMATCH');if(c.boundaries?.force_remove_used!==false||c.boundaries?.branch_delete_used!==false||c.boundaries?.network_used!==false||c.boundaries?.worker_started!==false||c.boundaries?.concurrency_used!==false)errors.push('CLEANUP_BOUNDARY_INVALID');if(c.worktree?.registered_after_cleanup!==false||c.worktree?.path_exists_after_cleanup!==false||c.worktree?.branch_preserved!==true)errors.push('CLEANUP_POSTCONDITION_INVALID');if(sourceReceiptFile){if(!fs.existsSync(sourceReceiptFile))errors.push('SOURCE_RECEIPT_MISSING');else if(c.source_receipt_sha256!==hashFile(sourceReceiptFile))errors.push('SOURCE_RECEIPT_HASH_DRIFT')}if(repoInput){const pf=preflight(repoInput);if(!pf.valid)errors.push(...pf.errors.map(x=>`PRIMARY_${x}`));else{if(!pathEq(pf.details.repository_root,c.repository?.root||''))errors.push('REPOSITORY_ROOT_DRIFT');if(pf.details.repository_identity_sha256!==c.repository?.identity_sha256)errors.push('REPOSITORY_IDENTITY_DRIFT');if(pf.details.primary_head!==c.repository?.primary_head)errors.push('PRIMARY_HEAD_DRIFT');if(registeredWorktree(pf.details.repository_root,c.worktree.path))errors.push('WORKTREE_STILL_REGISTERED');if(fs.existsSync(c.worktree.path))errors.push('WORKTREE_PATH_STILL_EXISTS');if(!branchExists(pf.details.repository_root,c.worktree.branch))errors.push('TASK_BRANCH_NOT_PRESERVED')}}return{status:errors.length?'WORKTREE_CLEANUP_RECEIPT_INVALID':'WORKTREE_CLEANUP_RECEIPT_VALID',valid:!errors.length,errors,receipt:c}}
function policyVerify(){const p=policy(),errors=[];if(p.schema_version!=='1.0'||p.phase!=='ADVANCED_EXECUTION_P1_WORKTREES')errors.push('PHASE_OR_SCHEMA_INVALID');if(!versionGte('999.999.999',p.git_min_version))errors.push('GIT_MIN_VERSION_INVALID');if(!p.branch_prefix||!p.worktree_container)errors.push('DERIVATION_CONFIG_INVALID');if(!Number.isInteger(p.max_task_id_length)||p.max_task_id_length<8||p.max_task_id_length>128)errors.push('TASK_ID_BOUND_INVALID');if(!Number.isInteger(p.max_registered_task_worktrees)||p.max_registered_task_worktrees<1)errors.push('WORKTREE_BOUND_INVALID');const r=p.rules||{};for(const k of ['require_primary_checkout','require_attached_primary_branch','require_clean_primary','require_pinned_base_commit','require_base_ref_unchanged_at_create','require_primary_head_unchanged_at_create','derive_branch_name','derive_worktree_path','cleanup_requires_clean_worktree'])if(r[k]!==true)errors.push(`RULE_MISSING:${k}`);for(const k of ['allow_user_supplied_branch','allow_user_supplied_worktree_path','allow_existing_branch_reuse','allow_existing_target_path','allow_detached_task_worktree','allow_force_remove','cleanup_deletes_branch','network_used','worker_execution_enabled','concurrency_enabled','dispatcher_enabled','queue_enabled','multi_machine_enabled'])if(r[k]!==false)errors.push(`RULE_INVALID:${k}`);return{status:errors.length?'WORKTREE_POLICY_INVALID':'WORKTREE_POLICY_VALID',valid:!errors.length,errors,policy:p}}
function certificatePaths(){return['advanced-execution/worktrees/worktree-manager.mjs','advanced-execution/policies/worktree-policy.json','advanced-execution/schemas/worktree-request.schema.json','advanced-execution/schemas/worktree-receipt.schema.json','advanced-execution/templates/worktree-request.example.json','advanced-execution/contracts/WORKTREE_ISOLATION.md','scripts/05-install-into-project.ps1']}
function certifyRun(outFile){if(!sourcePackageRoot)die('WORKTREE_CERTIFICATION_SOURCE_LAYOUT_REQUIRED',4);const pv=policyVerify(),inputs=certificatePaths().map(rel=>({path:rel,sha256:hashFile(path.join(sourcePackageRoot,rel))}));const c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P1_WORKTREES',status:pv.valid?'ADVANCED_EXECUTION_P1_PACKAGE_CERTIFIED':'ADVANCED_EXECUTION_P1_PACKAGE_CERTIFICATION_FAILED',package_only:true,target_runtime_validation:'DEFERRED',claims:{git_worktree_isolation:true,pinned_base_commit:true,derived_paths_and_branches:true,primary_checkout_protected:true,non_destructive_cleanup:true,network_disabled:true,worker_execution_disabled:true,concurrency_disabled:true,dispatcher_queue_disabled:true,multi_machine_disabled:true},inputs,created_at:now(),evidence_sha256:''};c.evidence_sha256=hashObj(c);if(outFile)write(path.resolve(outFile),c);return c}
function certifyVerify(file){if(!sourcePackageRoot)return{status:'ADVANCED_EXECUTION_P1_CERTIFICATE_INVALID',valid:false,errors:['SOURCE_LAYOUT_REQUIRED']};if(!file||!fs.existsSync(file))return{status:'ADVANCED_EXECUTION_P1_CERTIFICATE_INVALID',valid:false,errors:['CERTIFICATE_MISSING']};let c;try{c=read(file)}catch{return{status:'ADVANCED_EXECUTION_P1_CERTIFICATE_INVALID',valid:false,errors:['CERTIFICATE_UNREADABLE']}};const errors=[];if(c.phase!=='ADVANCED_EXECUTION_P1_WORKTREES')errors.push('PHASE_INVALID');if(c.package_only!==true||c.target_runtime_validation!=='DEFERRED')errors.push('RUNTIME_BOUNDARY_INVALID');if(c.evidence_sha256!==hashObj(c))errors.push('CERTIFICATE_INTEGRITY_MISMATCH');const current=new Map(certificatePaths().map(rel=>[rel,hashFile(path.join(sourcePackageRoot,rel))]));for(const x of c.inputs||[])if(current.get(x.path)!==x.sha256)errors.push(`INPUT_DRIFT:${x.path}`);if((c.inputs||[]).length!==current.size)errors.push('INPUT_SET_DRIFT');return{status:errors.length?'ADVANCED_EXECUTION_P1_CERTIFICATE_STALE_OR_TAMPERED':'ADVANCED_EXECUTION_P1_CERTIFICATE_VALID',valid:!errors.length,errors,certificate:c}}

if(group==='policy'&&cmd==='verify'){const r=policyVerify();out(r);process.exit(r.valid?0:3)}
if(group==='preflight'&&cmd==='check'){const r=preflight(path.resolve(take('--repo','')));out(r);process.exit(r.valid?0:5)}
if(group==='request'&&cmd==='prepare'){const r=prepareRequest(path.resolve(take('--repo','')),take('--task-id',''),take('--base-ref','HEAD'),take('--out'));out(r);process.exit(0)}
if(group==='request'&&cmd==='verify'){const r=verifyRequest(path.resolve(take('--repo','')),path.resolve(take('--request','')));out(r);process.exit(r.valid?0:5)}
if(group==='worktree'&&cmd==='create'){const r=createWorktree(path.resolve(take('--repo','')),path.resolve(take('--request','')),take('--out'));out(r);process.exit(0)}
if(group==='worktree'&&cmd==='verify'){const r=verifyReceipt(path.resolve(take('--receipt','')),{repoInput:take('--repo')?path.resolve(take('--repo')):null,requestFile:take('--request')?path.resolve(take('--request')):null});out(r);process.exit(r.valid?0:5)}
if(group==='worktree'&&cmd==='inspect'){const r=inspectWorktree(path.resolve(take('--receipt','')),path.resolve(take('--repo','')));out(r);process.exit(r.valid?0:5)}
if(group==='worktree'&&cmd==='cleanup'){const r=cleanupWorktree(path.resolve(take('--receipt','')),path.resolve(take('--repo','')),take('--out'));out(r);process.exit(0)}
if(group==='cleanup'&&cmd==='verify'){const r=verifyCleanup(path.resolve(take('--cleanup','')),{sourceReceiptFile:take('--receipt')?path.resolve(take('--receipt')):null,repoInput:take('--repo')?path.resolve(take('--repo')):null});out(r);process.exit(r.valid?0:5)}
if(group==='certify'&&cmd==='run'){const c=certifyRun(take('--out'));out(c);process.exit(c.status.endsWith('CERTIFIED')?0:4)}
if(group==='certify'&&cmd==='verify'){const r=certifyVerify(path.resolve(take('--certificate','')));out(r);process.exit(r.valid?0:4)}
die('WORKTREE_COMMAND_UNKNOWN',2,{usage:['policy verify','preflight check --repo <root>','request prepare --repo <root> --task-id <id> [--base-ref HEAD] --out <json>','request verify --repo <root> --request <json>','worktree create --repo <root> --request <json> --out <json>','worktree verify --receipt <json> [--repo <root> --request <json>]','worktree inspect --receipt <json> --repo <root>','worktree cleanup --receipt <json> --repo <root> --out <json>','cleanup verify --cleanup <json> [--receipt <json> --repo <root>]','certify run --out <json>','certify verify --certificate <json>']});
