#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';

const here=path.dirname(fileURLToPath(import.meta.url));
const executionRoot=path.resolve(here,'..');
const sourcePackageRoot=path.basename(path.dirname(executionRoot))==='.aledevos'?null:path.resolve(executionRoot,'..');
const policyPath=path.join(executionRoot,'policies','multimachine-policy.json');
const p1=path.join(executionRoot,'worktrees','worktree-manager.mjs');
const p2=path.join(executionRoot,'workers','worker-manager.mjs');
const p3=path.join(executionRoot,'concurrency','concurrency-manager.mjs');
const p4=path.join(executionRoot,'dispatcher','dispatcher-manager.mjs');
const args=process.argv.slice(2),[domain,command]=args;
const take=(flag,def=null)=>{const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:def};
const takes=flag=>{const out=[];for(let i=0;i<args.length;i++)if(args[i]===flag&&i+1<args.length)out.push(args[i+1]);return out};
const out=v=>process.stdout.write(JSON.stringify(v,null,2)+'\n');
const die=(status,code=2,extra={})=>{out({status,...extra});process.exit(code)};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const atomicWrite=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.${process.pid}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,p)};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const hashFile=p=>sha(fs.readFileSync(p));
const stable=(v,omit=new Set())=>Array.isArray(v)?v.map(x=>stable(x,omit)):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!omit.has(k)).sort().map(k=>[k,stable(v[k],omit)])):v;
const hashObj=(v,...omit)=>sha(Buffer.from(JSON.stringify(stable(v,new Set(omit)))));
const canonical=v=>Buffer.from(JSON.stringify(stable(v,new Set(['signature','self_signature','envelope_sha256','identity_sha256','heartbeat_sha256','result_sha256','ack_sha256','registry_sha256','tasks_sha256']))));
const now=()=>new Date().toISOString();
const policy=()=>read(policyPath);
const slug=s=>/^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/.test(String(s||''));
function pidAlive(pid){if(!Number.isInteger(pid)||pid<=0)return false;try{process.kill(pid,0)}catch{return false}if(process.platform==='linux'){try{const s=fs.readFileSync(`/proc/${pid}/stat`,'utf8').trim().split(' ')[2];if(s==='Z'||s==='X')return false}catch{}}return true}
function runJson(script,argv,cwd){const r=spawnSync(process.execPath,[script,...argv],{cwd,encoding:'utf8',windowsHide:true});let data={};try{data=JSON.parse(r.stdout||'{}')}catch{}return{ok:r.status===0,status:r.status,data,stdout:r.stdout||'',stderr:r.stderr||''}}
function sign(privatePem,obj){return crypto.sign(null,canonical(obj),privatePem).toString('base64')}
function verify(publicPem,obj,sig){try{return crypto.verify(null,canonical(obj),publicPem,Buffer.from(sig,'base64'))}catch{return false}}
function chmod600(p){if(process.platform!=='win32')try{fs.chmodSync(p,0o600)}catch{}}
function phaseRoot(repo){return path.join(repo,'.aledevos','state','execution','phase5')}
function coordDir(repo){return path.join(phaseRoot(repo),'coordinator')}
function coordIdentity(repo){return path.join(coordDir(repo),'identity.json')}
function coordKey(repo){return path.join(coordDir(repo),'private-key.pem')}
function registryPath(repo){return path.join(phaseRoot(repo),'registry.json')}
function tasksPath(repo){return path.join(phaseRoot(repo),'tasks.json')}
function lockPath(repo){return path.join(phaseRoot(repo),'control.lock')}
function taskDir(repo,id){return path.join(phaseRoot(repo),'tasks',id)}
function payloadPath(repo,id){return path.join(taskDir(repo,id),'payload.bin')}
function nodeIdentity(nodeDir){return path.join(nodeDir,'identity','identity.json')}
function nodeKey(nodeDir){return path.join(nodeDir,'identity','private-key.pem')}
function nodeTrust(nodeDir){return path.join(nodeDir,'trust','coordinators.json')}
function nodeState(nodeDir){return path.join(nodeDir,'state','node.json')}
function inboxDir(nodeDir,id){return path.join(nodeDir,'inbox',id)}
function inboxAssignment(nodeDir,id){return path.join(inboxDir(nodeDir,id),'assignment.json')}
function inboxPayload(nodeDir,id){return path.join(inboxDir(nodeDir,id),'payload.bin')}
function coordinatorIdFromPublic(publicKey){return 'coord-'+sha(Buffer.from(publicKey)).slice(0,24)}
function emptyRegistry(repo){return{schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_MULTI_MACHINE',repository_root:path.resolve(repo),nodes:{},registry_sha256:''}}
function emptyTasks(repo){return{schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_MULTI_MACHINE',repository_root:path.resolve(repo),tasks:{},tasks_sha256:''}}
function sealRegistry(r){r.registry_sha256=hashObj(r,'registry_sha256');return r}
function sealTasks(r){r.tasks_sha256=hashObj(r,'tasks_sha256');return r}
function loadRegistry(repo){const f=registryPath(repo);if(!fs.existsSync(f))die('MULTIMACHINE_COORDINATOR_NOT_INITIALIZED',5);const r=read(f),e=[];if(r.phase!=='ADVANCED_EXECUTION_P5_MULTI_MACHINE')e.push('REGISTRY_PHASE_INVALID');if(path.resolve(r.repository_root)!==path.resolve(repo))e.push('REGISTRY_REPOSITORY_DRIFT');if(r.registry_sha256!==hashObj(r,'registry_sha256'))e.push('REGISTRY_INTEGRITY_MISMATCH');if(e.length)die('MULTIMACHINE_REGISTRY_INVALID',7,{errors:e});return r}
function loadTasks(repo){const f=tasksPath(repo);if(!fs.existsSync(f))die('MULTIMACHINE_COORDINATOR_NOT_INITIALIZED',5);const r=read(f),e=[];if(r.phase!=='ADVANCED_EXECUTION_P5_MULTI_MACHINE')e.push('TASKS_PHASE_INVALID');if(path.resolve(r.repository_root)!==path.resolve(repo))e.push('TASKS_REPOSITORY_DRIFT');if(r.tasks_sha256!==hashObj(r,'tasks_sha256'))e.push('TASKS_INTEGRITY_MISMATCH');for(const [id,t] of Object.entries(r.tasks||{})){if(t.task_id!==id)e.push(`TASK_ID_DRIFT:${id}`);if(t.task_sha256!==hashObj(t,'task_sha256'))e.push(`TASK_INTEGRITY_MISMATCH:${id}`)}if(e.length)die('MULTIMACHINE_TASKS_INVALID',7,{errors:e});return r}
function saveRegistry(repo,r){sealRegistry(r);atomicWrite(registryPath(repo),r)}
function saveTasks(repo,r){sealTasks(r);atomicWrite(tasksPath(repo),r)}
function acquire(repo){const f=lockPath(repo),p=policy();fs.mkdirSync(path.dirname(f),{recursive:true});for(let i=0;i<2;i++){try{const fd=fs.openSync(f,'wx');fs.writeFileSync(fd,JSON.stringify({pid:process.pid,created_at:now()})+'\n');return{fd,file:f}}catch(e){if(e?.code!=='EEXIST')throw e;let stale=false;try{const x=read(f),age=Date.now()-Date.parse(x.created_at||0);stale=(!pidAlive(Number(x.pid))&&age>=0)||age>p.locking.stale_lock_after_ms}catch{stale=true}if(stale&&p.locking.stale_lock_recovery){try{fs.rmSync(f,{force:true})}catch{};continue}die('MULTIMACHINE_CONTROL_BUSY',7)}}die('MULTIMACHINE_CONTROL_BUSY',7)}
function release(l){try{fs.closeSync(l.fd)}catch{};try{fs.rmSync(l.file,{force:true})}catch{}}
function locked(repo,fn){const l=acquire(repo);try{return fn()}finally{release(l)}}
function refreshNodeState(entry){if(['REVOKED','PENDING'].includes(entry.state))return entry;const stale=Date.now()-Date.parse(entry.last_heartbeat_at||0)>policy().registry.heartbeat_stale_after_ms;if(stale)entry.state='STALE';return entry}
function verifyIdentityObject(id){const e=[];if(id.phase!=='ADVANCED_EXECUTION_P5_MULTI_MACHINE_NODE_IDENTITY')e.push('IDENTITY_PHASE_INVALID');if(!slug(id.machine_id))e.push('MACHINE_ID_INVALID');if(id.algorithm!=='ed25519')e.push('IDENTITY_ALGORITHM_INVALID');if(!id.public_key_pem)e.push('PUBLIC_KEY_MISSING');if(id.identity_sha256!==hashObj(id,'identity_sha256','self_signature'))e.push('IDENTITY_HASH_INVALID');if(!verify(id.public_key_pem,id,id.self_signature))e.push('IDENTITY_SELF_SIGNATURE_INVALID');return e}
function identityCreate(nodeDir,machineId,capFile){if(!slug(machineId))die('MACHINE_ID_INVALID',4);if(fs.existsSync(nodeIdentity(nodeDir))||fs.existsSync(nodeKey(nodeDir)))die('MACHINE_IDENTITY_EXISTS',5);const caps=capFile?read(path.resolve(capFile)):{adapters:[],modalities:['text'],features:[],max_workers:1};const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const pub=publicKey.export({type:'spki',format:'pem'}).toString(),priv=privateKey.export({type:'pkcs8',format:'pem'}).toString();const id={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_MULTI_MACHINE_NODE_IDENTITY',machine_id:machineId,algorithm:'ed25519',platform:{os:process.platform,arch:process.arch},capabilities:{adapters:[...new Set(caps.adapters||[])].sort(),modalities:[...new Set(caps.modalities||[])].sort(),features:[...new Set(caps.features||[])].sort(),max_workers:Number.isInteger(caps.max_workers)&&caps.max_workers>0?caps.max_workers:1},public_key_pem:pub,created_at:now(),identity_sha256:'',self_signature:''};id.identity_sha256=hashObj(id,'identity_sha256','self_signature');id.self_signature=sign(priv,id);fs.mkdirSync(path.dirname(nodeKey(nodeDir)),{recursive:true});fs.writeFileSync(nodeKey(nodeDir),priv);chmod600(nodeKey(nodeDir));atomicWrite(nodeIdentity(nodeDir),id);atomicWrite(nodeState(nodeDir),{machine_id:machineId,heartbeat_sequence:0,last_fence_by_task:{},accepted_tasks:{}});return{status:'MACHINE_IDENTITY_CREATED',identity_path:nodeIdentity(nodeDir),machine_id:machineId,identity:id}}
function coordinatorInit(repo){return locked(repo,()=>{if(fs.existsSync(coordIdentity(repo)))die('MULTIMACHINE_COORDINATOR_EXISTS',5);const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519'),pub=publicKey.export({type:'spki',format:'pem'}).toString(),priv=privateKey.export({type:'pkcs8',format:'pem'}).toString(),cid=coordinatorIdFromPublic(pub);const id={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_COORDINATOR_IDENTITY',coordinator_id:cid,algorithm:'ed25519',public_key_pem:pub,created_at:now(),identity_sha256:''};id.identity_sha256=hashObj(id,'identity_sha256');fs.mkdirSync(coordDir(repo),{recursive:true});fs.writeFileSync(coordKey(repo),priv);chmod600(coordKey(repo));atomicWrite(coordIdentity(repo),id);atomicWrite(registryPath(repo),sealRegistry(emptyRegistry(repo)));atomicWrite(tasksPath(repo),sealTasks(emptyTasks(repo)));return{status:'MULTIMACHINE_COORDINATOR_READY',identity_path:coordIdentity(repo),coordinator:id}})}
function coordinatorExport(repo,file){if(!fs.existsSync(coordIdentity(repo)))die('MULTIMACHINE_COORDINATOR_NOT_INITIALIZED',5);fs.copyFileSync(coordIdentity(repo),path.resolve(file));return{status:'COORDINATOR_IDENTITY_EXPORTED',out:path.resolve(file)}}
function nodeTrustAdd(nodeDir,idFile){const c=read(path.resolve(idFile));if(c.phase!=='ADVANCED_EXECUTION_P5_COORDINATOR_IDENTITY'||c.identity_sha256!==hashObj(c,'identity_sha256')||coordinatorIdFromPublic(c.public_key_pem)!==c.coordinator_id)die('COORDINATOR_IDENTITY_INVALID',5);let t={schema_version:'1.0',coordinators:{}};if(fs.existsSync(nodeTrust(nodeDir)))t=read(nodeTrust(nodeDir));t.coordinators[c.coordinator_id]={public_key_pem:c.public_key_pem,identity_sha256:c.identity_sha256,added_at:now()};atomicWrite(nodeTrust(nodeDir),t);return{status:'COORDINATOR_TRUST_ADDED',coordinator_id:c.coordinator_id}}
function enroll(repo,idFile){return locked(repo,()=>{const id=read(path.resolve(idFile)),e=verifyIdentityObject(id);if(e.length)die('MACHINE_ENROLLMENT_BLOCKED',5,{errors:e});const r=loadRegistry(repo),p=policy();if(!r.nodes[id.machine_id]&&Object.keys(r.nodes).length>=p.registry.max_nodes)die('MACHINE_ENROLLMENT_BLOCKED',5,{errors:['NODE_LIMIT_EXCEEDED']});const existing=r.nodes[id.machine_id];if(existing&&existing.identity_sha256!==id.identity_sha256)die('MACHINE_IDENTITY_CONFLICT',6);r.nodes[id.machine_id]={machine_id:id.machine_id,state:existing?.state==='ACTIVE'?'ACTIVE':'PENDING',identity_sha256:id.identity_sha256,public_key_pem:id.public_key_pem,platform:id.platform,capabilities:id.capabilities,enrolled_at:existing?.enrolled_at||now(),approved_at:existing?.approved_at||null,last_heartbeat_at:existing?.last_heartbeat_at||null,last_heartbeat_sequence:existing?.last_heartbeat_sequence||0,revoked_at:existing?.revoked_at||null};saveRegistry(repo,r);return{status:'MACHINE_ENROLLED_PENDING_APPROVAL',machine_id:id.machine_id,node:r.nodes[id.machine_id]}})}
function nodeApprove(repo,machineId){return locked(repo,()=>{const r=loadRegistry(repo),n=r.nodes[machineId];if(!n)die('MACHINE_NOT_FOUND',4);if(n.state==='REVOKED')die('MACHINE_APPROVAL_BLOCKED',5,{errors:['NODE_REVOKED']});n.state='ACTIVE';n.approved_at=now();saveRegistry(repo,r);return{status:'MACHINE_APPROVED',machine_id:machineId,node:n}})}
function nodeRevoke(repo,machineId){return locked(repo,()=>{const r=loadRegistry(repo),n=r.nodes[machineId];if(!n)die('MACHINE_NOT_FOUND',4);n.state='REVOKED';n.revoked_at=now();saveRegistry(repo,r);return{status:'MACHINE_REVOKED',machine_id:machineId,node:n}})}
function heartbeatCreate(nodeDir,file){const id=read(nodeIdentity(nodeDir)),st=read(nodeState(nodeDir)),priv=fs.readFileSync(nodeKey(nodeDir),'utf8');st.heartbeat_sequence=(st.heartbeat_sequence||0)+1;atomicWrite(nodeState(nodeDir),st);const h={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_HEARTBEAT',machine_id:id.machine_id,identity_sha256:id.identity_sha256,sequence:st.heartbeat_sequence,capabilities_sha256:hashObj(id.capabilities),created_at:now(),heartbeat_sha256:'',signature:''};h.heartbeat_sha256=hashObj(h,'heartbeat_sha256','signature');h.signature=sign(priv,h);atomicWrite(path.resolve(file),h);return{status:'MACHINE_HEARTBEAT_CREATED',heartbeat:h,out:path.resolve(file)}}
function heartbeatAccept(repo,file){return locked(repo,()=>{const h=read(path.resolve(file)),r=loadRegistry(repo),n=r.nodes[h.machine_id];if(!n)die('HEARTBEAT_REJECTED',5,{errors:['NODE_NOT_ENROLLED']});if(n.state==='PENDING')die('HEARTBEAT_REJECTED',5,{errors:['NODE_NOT_APPROVED']});if(n.state==='REVOKED')die('HEARTBEAT_REJECTED',5,{errors:['NODE_REVOKED']});const e=[];if(h.phase!=='ADVANCED_EXECUTION_P5_HEARTBEAT')e.push('HEARTBEAT_PHASE_INVALID');if(h.identity_sha256!==n.identity_sha256)e.push('IDENTITY_DRIFT');if(h.capabilities_sha256!==hashObj(n.capabilities))e.push('CAPABILITY_DRIFT');if(h.heartbeat_sha256!==hashObj(h,'heartbeat_sha256','signature'))e.push('HEARTBEAT_HASH_INVALID');if(!verify(n.public_key_pem,h,h.signature))e.push('HEARTBEAT_SIGNATURE_INVALID');if(!Number.isInteger(h.sequence)||h.sequence<=n.last_heartbeat_sequence)e.push('HEARTBEAT_REPLAY');if(e.length)die('HEARTBEAT_REJECTED',6,{errors:e});n.last_heartbeat_sequence=h.sequence;n.last_heartbeat_at=h.created_at;n.state='ACTIVE';saveRegistry(repo,r);return{status:'MACHINE_HEARTBEAT_ACCEPTED',machine_id:n.machine_id,node:n}})}
function registryStatus(repo){const r=loadRegistry(repo);for(const n of Object.values(r.nodes))refreshNodeState(n);saveRegistry(repo,r);return{status:'MACHINE_REGISTRY_STATUS',nodes:r.nodes,registry_sha256:r.registry_sha256}}
function capMatch(n,req){const miss=[];for(const a of req.adapters||[])if(!(n.capabilities.adapters||[]).includes(a))miss.push(`adapter:${a}`);for(const a of req.modalities||[])if(!(n.capabilities.modalities||[]).includes(a))miss.push(`modality:${a}`);for(const a of req.features||[])if(!(n.capabilities.features||[]).includes(a))miss.push(`feature:${a}`);if((n.capabilities.max_workers||0)<(req.min_workers||1))miss.push('max_workers');return miss}
function taskSubmit(repo,id,payload,req){if(!slug(id))die('REMOTE_TASK_ID_INVALID',4);const f=path.resolve(payload);if(!fs.existsSync(f)||!fs.statSync(f).isFile())die('REMOTE_TASK_SUBMIT_BLOCKED',5,{errors:['PAYLOAD_MISSING']});const p=policy(),buf=fs.readFileSync(f);if(buf.length>p.tasks.max_payload_bytes)die('REMOTE_TASK_SUBMIT_BLOCKED',5,{errors:['PAYLOAD_TOO_LARGE']});return locked(repo,()=>{const t=loadTasks(repo);if(t.tasks[id])die('REMOTE_TASK_EXISTS',5);fs.mkdirSync(taskDir(repo,id),{recursive:true});fs.writeFileSync(payloadPath(repo,id),buf);const task={task_id:id,state:'READY',payload_sha256:sha(buf),payload_size:buf.length,requirements:req,current_lease:null,fence_counter:0,reassignments:0,authoritative_result:null,created_at:now(),updated_at:now(),task_sha256:''};task.task_sha256=hashObj(task,'task_sha256');t.tasks[id]=task;saveTasks(repo,t);return{status:'REMOTE_TASK_READY',task}})}
function coordinatorSign(repo,obj){return sign(fs.readFileSync(coordKey(repo),'utf8'),obj)}
function assign(repo,id,machineId,leaseMs,outFile,{reassign=false}={}){return locked(repo,()=>{const p=policy(),r=loadRegistry(repo),t=loadTasks(repo),task=t.tasks[id];if(!task)die('REMOTE_TASK_NOT_FOUND',4);const n=r.nodes[machineId];if(!n)die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:['NODE_NOT_ENROLLED']});refreshNodeState(n);if(n.state!=='ACTIVE')die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:[`NODE_NOT_ACTIVE:${n.state}`]});const miss=capMatch(n,task.requirements||{});if(miss.length)die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:miss.map(x=>`CAPABILITY_MISSING:${x}`)});leaseMs=Number(leaseMs||p.leases.default_lease_ms);if(!Number.isInteger(leaseMs)||leaseMs<p.leases.min_lease_ms||leaseMs>p.leases.max_lease_ms)die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:['LEASE_DURATION_INVALID']});if(task.authoritative_result)die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:['TASK_ALREADY_COMPLETED']});if(task.current_lease){const expired=Date.now()>Date.parse(task.current_lease.expires_at);if(!reassign)die('REMOTE_ASSIGNMENT_BLOCKED',5,{errors:['ACTIVE_LEASE_EXISTS']});const old=r.nodes[task.current_lease.machine_id];if(!expired)die('REMOTE_REASSIGNMENT_BLOCKED',5,{errors:['LEASE_NOT_EXPIRED']});if(old){refreshNodeState(old);if(!['STALE','REVOKED'].includes(old.state))die('REMOTE_REASSIGNMENT_BLOCKED',5,{errors:['PREVIOUS_OWNER_NOT_STALE_OR_REVOKED']})}if(task.reassignments>=p.tasks.max_reassignments)die('REMOTE_REASSIGNMENT_BLOCKED',5,{errors:['REASSIGNMENT_LIMIT_REACHED']});task.reassignments++}
 task.fence_counter++;const coord=read(coordIdentity(repo)),issued=now(),expires=new Date(Date.now()+leaseMs).toISOString();const lease={lease_id:'lease-'+sha(Buffer.from(`${id}:${machineId}:${task.fence_counter}:${issued}`)).slice(0,24),machine_id:machineId,fence_token:task.fence_counter,issued_at:issued,expires_at:expires,acked:false};task.current_lease=lease;task.state='LEASED';task.updated_at=now();task.task_sha256=hashObj(task,'task_sha256');saveRegistry(repo,r);saveTasks(repo,t);const payload=fs.readFileSync(payloadPath(repo,id));const env={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_REMOTE_ASSIGNMENT',coordinator_id:coord.coordinator_id,target_machine_id:machineId,task_id:id,task_sha256:task.task_sha256,payload_sha256:task.payload_sha256,payload_size:payload.length,payload_base64:payload.toString('base64'),requirements:task.requirements,lease,created_at:now(),envelope_sha256:'',signature:''};env.envelope_sha256=hashObj(env,'envelope_sha256','signature');env.signature=coordinatorSign(repo,env);if(outFile)atomicWrite(path.resolve(outFile),env);return{status:reassign?'REMOTE_TASK_REASSIGNED':'REMOTE_TASK_ASSIGNED',task,assignment:env,out:outFile?path.resolve(outFile):null}})}
function bundleImport(nodeDir,file){const env=read(path.resolve(file)),id=read(nodeIdentity(nodeDir)),trust=fs.existsSync(nodeTrust(nodeDir))?read(nodeTrust(nodeDir)):{coordinators:{}};const tr=trust.coordinators?.[env.coordinator_id],e=[];if(env.phase!=='ADVANCED_EXECUTION_P5_REMOTE_ASSIGNMENT')e.push('ASSIGNMENT_PHASE_INVALID');if(env.target_machine_id!==id.machine_id)e.push('WRONG_TARGET_MACHINE');if(!tr)e.push('COORDINATOR_NOT_TRUSTED');if(env.envelope_sha256!==hashObj(env,'envelope_sha256','signature'))e.push('ASSIGNMENT_HASH_INVALID');if(tr&&!verify(tr.public_key_pem,env,env.signature))e.push('ASSIGNMENT_SIGNATURE_INVALID');const payload=Buffer.from(env.payload_base64||'','base64');if(sha(payload)!==env.payload_sha256||payload.length!==env.payload_size)e.push('PAYLOAD_INTEGRITY_INVALID');if(Date.now()>Date.parse(env.lease?.expires_at||0))e.push('LEASE_EXPIRED');const st=read(nodeState(nodeDir)),prev=st.last_fence_by_task?.[env.task_id]||0;if(!Number.isInteger(env.lease?.fence_token)||env.lease.fence_token<=prev)e.push('STALE_FENCE_TOKEN');if(e.length)die('REMOTE_BUNDLE_REJECTED',6,{errors:e});fs.mkdirSync(inboxDir(nodeDir,env.task_id),{recursive:true});fs.writeFileSync(inboxPayload(nodeDir,env.task_id),payload);atomicWrite(inboxAssignment(nodeDir,env.task_id),env);st.last_fence_by_task[env.task_id]=env.lease.fence_token;st.accepted_tasks[env.task_id]={coordinator_id:env.coordinator_id,lease_id:env.lease.lease_id,fence_token:env.lease.fence_token,expires_at:env.lease.expires_at,payload_sha256:env.payload_sha256,imported_at:now()};atomicWrite(nodeState(nodeDir),st);return{status:'REMOTE_BUNDLE_ACCEPTED',task_id:env.task_id,fence_token:env.lease.fence_token,payload_path:inboxPayload(nodeDir,env.task_id)}}
function ackCreate(nodeDir,id,file){const st=read(nodeState(nodeDir)),a=st.accepted_tasks?.[id];if(!a)die('REMOTE_ACK_BLOCKED',5,{errors:['TASK_NOT_IMPORTED']});const ident=read(nodeIdentity(nodeDir)),priv=fs.readFileSync(nodeKey(nodeDir),'utf8');const ack={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_REMOTE_ACK',machine_id:ident.machine_id,identity_sha256:ident.identity_sha256,coordinator_id:a.coordinator_id,task_id:id,lease_id:a.lease_id,fence_token:a.fence_token,created_at:now(),ack_sha256:'',signature:''};ack.ack_sha256=hashObj(ack,'ack_sha256','signature');ack.signature=sign(priv,ack);atomicWrite(path.resolve(file),ack);return{status:'REMOTE_ACK_CREATED',ack,out:path.resolve(file)}}
function ackAccept(repo,file){return locked(repo,()=>{const a=read(path.resolve(file)),r=loadRegistry(repo),t=loadTasks(repo),task=t.tasks[a.task_id],n=r.nodes[a.machine_id],e=[];if(!task)e.push('TASK_NOT_FOUND');if(!n)e.push('NODE_NOT_FOUND');if(a.phase!=='ADVANCED_EXECUTION_P5_REMOTE_ACK')e.push('ACK_PHASE_INVALID');if(n&&a.identity_sha256!==n.identity_sha256)e.push('IDENTITY_DRIFT');if(a.ack_sha256!==hashObj(a,'ack_sha256','signature'))e.push('ACK_HASH_INVALID');if(n&&!verify(n.public_key_pem,a,a.signature))e.push('ACK_SIGNATURE_INVALID');if(task){if(!task.current_lease)e.push('LEASE_MISSING');else{if(a.machine_id!==task.current_lease.machine_id)e.push('LEASE_OWNER_MISMATCH');if(a.lease_id!==task.current_lease.lease_id)e.push('LEASE_ID_MISMATCH');if(a.fence_token!==task.current_lease.fence_token)e.push('STALE_FENCE_TOKEN');if(Date.now()>Date.parse(task.current_lease.expires_at))e.push('LEASE_EXPIRED')}}if(e.length)die('REMOTE_ACK_REJECTED',6,{errors:e});task.current_lease.acked=true;task.state='ACKED';task.updated_at=now();task.task_sha256=hashObj(task,'task_sha256');saveTasks(repo,t);return{status:'REMOTE_ACK_ACCEPTED',task}})}
function resultCreate(nodeDir,id,resultFile,outFile){const st=read(nodeState(nodeDir)),a=st.accepted_tasks?.[id];if(!a)die('REMOTE_RESULT_BLOCKED',5,{errors:['TASK_NOT_IMPORTED']});if(Date.now()>Date.parse(a.expires_at))die('REMOTE_RESULT_BLOCKED',5,{errors:['LEASE_EXPIRED']});const f=path.resolve(resultFile);if(!fs.existsSync(f))die('REMOTE_RESULT_BLOCKED',5,{errors:['RESULT_FILE_MISSING']});const buf=fs.readFileSync(f),ident=read(nodeIdentity(nodeDir)),priv=fs.readFileSync(nodeKey(nodeDir),'utf8');const res={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_REMOTE_RESULT',machine_id:ident.machine_id,identity_sha256:ident.identity_sha256,coordinator_id:a.coordinator_id,task_id:id,lease_id:a.lease_id,fence_token:a.fence_token,result_payload_sha256:sha(buf),result_payload_size:buf.length,result_payload_base64:buf.toString('base64'),created_at:now(),result_sha256:'',signature:''};res.result_sha256=hashObj(res,'result_sha256','signature');res.signature=sign(priv,res);atomicWrite(path.resolve(outFile),res);return{status:'REMOTE_RESULT_CREATED',result:res,out:path.resolve(outFile)}}
function resultAccept(repo,file){return locked(repo,()=>{const x=read(path.resolve(file)),r=loadRegistry(repo),t=loadTasks(repo),task=t.tasks[x.task_id],n=r.nodes[x.machine_id],e=[];if(!task)e.push('TASK_NOT_FOUND');if(!n)e.push('NODE_NOT_FOUND');if(x.phase!=='ADVANCED_EXECUTION_P5_REMOTE_RESULT')e.push('RESULT_PHASE_INVALID');if(n&&x.identity_sha256!==n.identity_sha256)e.push('IDENTITY_DRIFT');if(x.result_sha256!==hashObj(x,'result_sha256','signature'))e.push('RESULT_HASH_INVALID');if(n&&!verify(n.public_key_pem,x,x.signature))e.push('RESULT_SIGNATURE_INVALID');const buf=Buffer.from(x.result_payload_base64||'','base64');if(sha(buf)!==x.result_payload_sha256||buf.length!==x.result_payload_size)e.push('RESULT_PAYLOAD_INTEGRITY_INVALID');if(task){if(task.authoritative_result){if(task.authoritative_result.result_sha256===x.result_sha256)return{status:'REMOTE_RESULT_ALREADY_ACCEPTED',task};e.push('AUTHORITATIVE_RESULT_ALREADY_EXISTS')}if(!task.current_lease)e.push('LEASE_MISSING');else{if(x.machine_id!==task.current_lease.machine_id)e.push('LEASE_OWNER_MISMATCH');if(x.lease_id!==task.current_lease.lease_id)e.push('LEASE_ID_MISMATCH');if(x.fence_token!==task.current_lease.fence_token)e.push('STALE_FENCE_TOKEN');if(Date.now()>Date.parse(task.current_lease.expires_at))e.push('LEASE_EXPIRED');if(!task.current_lease.acked)e.push('LEASE_NOT_ACKED')}}if(e.length)die('REMOTE_RESULT_REJECTED',6,{errors:e});const d=taskDir(repo,x.task_id);fs.mkdirSync(d,{recursive:true});const resultOut=path.join(d,`result-fence-${x.fence_token}.bin`);fs.writeFileSync(resultOut,buf);task.authoritative_result={machine_id:x.machine_id,fence_token:x.fence_token,result_sha256:x.result_sha256,result_payload_sha256:x.result_payload_sha256,result_path:resultOut,accepted_at:now()};task.state='COMPLETED';task.updated_at=now();task.task_sha256=hashObj(task,'task_sha256');saveTasks(repo,t);return{status:'REMOTE_RESULT_ACCEPTED',task,result_path:resultOut}})}
function taskStatus(repo,id){const t=loadTasks(repo),task=t.tasks[id];if(!task)die('REMOTE_TASK_NOT_FOUND',4);return{status:'REMOTE_TASK_STATUS',task}}
function policyVerify(){const p=policy(),e=[];if(p.phase!=='ADVANCED_EXECUTION_P5_MULTI_MACHINE')e.push('PHASE_INVALID');if(p.identity.algorithm!=='ed25519')e.push('IDENTITY_ALGORITHM_INVALID');if(!p.identity.explicit_node_approval_required||!p.identity.coordinator_trust_anchor_required)e.push('TRUST_POLICY_WEAK');if(!p.leases.fencing_tokens_required||!p.leases.reassignment_requires_expired_lease||!p.leases.reassignment_requires_stale_or_revoked_owner)e.push('LEASE_POLICY_WEAK');if(p.tasks.max_reassignments!==2)e.push('REASSIGNMENT_CAP_INVALID');if(p.transport.network_transport_implemented!==false||p.transport.network_used_in_package_validation!==false)e.push('NETWORK_BOUNDARY_INVALID');if(p.boundaries.multi_machine_used!==true||p.boundaries.local_p1_p2_p3_p4_authority_preserved!==true)e.push('BOUNDARY_INVALID');if(p.boundaries.physical_duplicate_compute_under_partition_claimed_prevented!==false)e.push('DUPLICATE_COMPUTE_CLAIM_INVALID');if(p.boundaries.authoritative_duplicate_acceptance_prevented!==true)e.push('FENCING_CLAIM_INVALID');return{status:e.length?'MULTIMACHINE_POLICY_INVALID':'MULTIMACHINE_POLICY_VALID',valid:!e.length,errors:e,policy:p}}
function certificatePaths(){return['advanced-execution/multimachine/multimachine-manager.mjs','advanced-execution/policies/multimachine-policy.json','advanced-execution/contracts/MULTI_MACHINE_SUPPORT.md','advanced-execution/schemas/machine-identity.schema.json','advanced-execution/schemas/machine-registry.schema.json','advanced-execution/schemas/remote-task.schema.json','advanced-execution/schemas/remote-assignment.schema.json','advanced-execution/schemas/remote-result.schema.json','advanced-execution/templates/machine-capabilities.example.json','advanced-execution/templates/remote-task.example.json','release/certifications/advanced-execution-p1.json','release/certifications/advanced-execution-p2.json','release/certifications/advanced-execution-p3.json','release/certifications/advanced-execution-p4.json','scripts/05-install-into-project.ps1']}
function certVerifyDependency(script,cert){return runJson(script,['certify','verify','--certificate',cert],sourcePackageRoot)}
function certifyRun(outFile){if(!sourcePackageRoot)die('ADVANCED_EXECUTION_P5_CERTIFICATION_SOURCE_LAYOUT_REQUIRED',4);const pv=policyVerify(),certs=[certVerifyDependency(p1,path.join(sourcePackageRoot,'release/certifications/advanced-execution-p1.json')),certVerifyDependency(p2,path.join(sourcePackageRoot,'release/certifications/advanced-execution-p2.json')),certVerifyDependency(p3,path.join(sourcePackageRoot,'release/certifications/advanced-execution-p3.json')),certVerifyDependency(p4,path.join(sourcePackageRoot,'release/certifications/advanced-execution-p4.json'))];const inputs=certificatePaths().map(rel=>({path:rel,sha256:hashFile(path.join(sourcePackageRoot,rel))}));const ok=pv.valid&&certs.every(x=>x.ok);const c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P5_MULTI_MACHINE',status:ok?'ADVANCED_EXECUTION_P5_PACKAGE_CERTIFIED':'ADVANCED_EXECUTION_P5_PACKAGE_CERTIFICATION_FAILED',package_only:true,target_runtime_validation:'DEFERRED',claims:{ed25519_node_identity:true,explicit_node_approval:true,signed_heartbeats_anti_replay:true,signed_task_bundles:true,lease_fencing:true,stale_owner_reassignment:true,authoritative_duplicate_acceptance_prevented:true,physical_duplicate_compute_under_partition_claimed_prevented:false,network_transport_implemented:false,p1_p2_p3_p4_local_authority_preserved:true},dependencies:{p1_certificate_valid:certs[0].ok,p2_certificate_valid:certs[1].ok,p3_certificate_valid:certs[2].ok,p4_certificate_valid:certs[3].ok},inputs,created_at:now(),evidence_sha256:''};c.evidence_sha256=hashObj(c,'evidence_sha256');if(outFile)atomicWrite(path.resolve(outFile),c);return c}
function certifyVerify(file){if(!sourcePackageRoot)return{status:'ADVANCED_EXECUTION_P5_CERTIFICATE_INVALID',valid:false,errors:['SOURCE_LAYOUT_REQUIRED']};if(!file||!fs.existsSync(file))return{status:'ADVANCED_EXECUTION_P5_CERTIFICATE_INVALID',valid:false,errors:['CERTIFICATE_MISSING']};const c=read(file),e=[];if(c.phase!=='ADVANCED_EXECUTION_P5_MULTI_MACHINE')e.push('PHASE_INVALID');if(c.evidence_sha256!==hashObj(c,'evidence_sha256'))e.push('CERTIFICATE_INTEGRITY_MISMATCH');for(const rel of certificatePaths()){const x=(c.inputs||[]).find(i=>i.path===rel);if(!x||x.sha256!==hashFile(path.join(sourcePackageRoot,rel)))e.push(`INPUT_DRIFT:${rel}`)}return{status:e.length?'ADVANCED_EXECUTION_P5_CERTIFICATE_STALE_OR_TAMPERED':'ADVANCED_EXECUTION_P5_CERTIFICATE_VALID',valid:!e.length,errors:e,certificate:c}}

if(domain==='policy'&&command==='verify'){const r=policyVerify();out(r);process.exit(r.valid?0:3)}
if(domain==='identity'&&command==='create'){out(identityCreate(path.resolve(take('--node-dir','')),take('--machine-id',''),take('--capabilities')));process.exit(0)}
if(domain==='identity'&&command==='verify'){const id=read(path.resolve(take('--identity',''))),e=verifyIdentityObject(id);out({status:e.length?'MACHINE_IDENTITY_INVALID':'MACHINE_IDENTITY_VALID',valid:!e.length,errors:e,identity:id});process.exit(e.length?4:0)}
if(domain==='coordinator'&&command==='init'){out(coordinatorInit(path.resolve(take('--repo',''))));process.exit(0)}
if(domain==='coordinator'&&command==='export-identity'){out(coordinatorExport(path.resolve(take('--repo','')),take('--out')));process.exit(0)}
if(domain==='trust'&&command==='add'){out(nodeTrustAdd(path.resolve(take('--node-dir','')),take('--coordinator-identity')));process.exit(0)}
if(domain==='node'&&command==='enroll'){out(enroll(path.resolve(take('--repo','')),take('--identity')));process.exit(0)}
if(domain==='node'&&command==='approve'){out(nodeApprove(path.resolve(take('--repo','')),take('--machine-id','')));process.exit(0)}
if(domain==='node'&&command==='revoke'){out(nodeRevoke(path.resolve(take('--repo','')),take('--machine-id','')));process.exit(0)}
if(domain==='node'&&command==='status'){out(registryStatus(path.resolve(take('--repo',''))));process.exit(0)}
if(domain==='heartbeat'&&command==='create'){out(heartbeatCreate(path.resolve(take('--node-dir','')),take('--out')));process.exit(0)}
if(domain==='heartbeat'&&command==='accept'){out(heartbeatAccept(path.resolve(take('--repo','')),take('--heartbeat')));process.exit(0)}
if(domain==='task'&&command==='submit'){const req={adapters:takes('--adapter'),modalities:takes('--modality'),features:takes('--feature'),min_workers:Number(take('--min-workers','1'))};out(taskSubmit(path.resolve(take('--repo','')),take('--task-id',''),take('--payload'),req));process.exit(0)}
if(domain==='task'&&command==='assign'){out(assign(path.resolve(take('--repo','')),take('--task-id',''),take('--machine-id',''),take('--lease-ms'),take('--out'),{reassign:false}));process.exit(0)}
if(domain==='task'&&command==='reassign'){out(assign(path.resolve(take('--repo','')),take('--task-id',''),take('--machine-id',''),take('--lease-ms'),take('--out'),{reassign:true}));process.exit(0)}
if(domain==='task'&&command==='status'){out(taskStatus(path.resolve(take('--repo','')),take('--task-id','')));process.exit(0)}
if(domain==='bundle'&&command==='import'){out(bundleImport(path.resolve(take('--node-dir','')),take('--bundle')));process.exit(0)}
if(domain==='ack'&&command==='create'){out(ackCreate(path.resolve(take('--node-dir','')),take('--task-id',''),take('--out')));process.exit(0)}
if(domain==='ack'&&command==='accept'){out(ackAccept(path.resolve(take('--repo','')),take('--ack')));process.exit(0)}
if(domain==='result'&&command==='create'){out(resultCreate(path.resolve(take('--node-dir','')),take('--task-id',''),take('--result'),take('--out')));process.exit(0)}
if(domain==='result'&&command==='accept'){out(resultAccept(path.resolve(take('--repo','')),take('--result')));process.exit(0)}
if(domain==='certify'&&command==='run'){const c=certifyRun(take('--out'));out(c);process.exit(c.status.endsWith('CERTIFIED')?0:4)}
if(domain==='certify'&&command==='verify'){const r=certifyVerify(path.resolve(take('--certificate','')));out(r);process.exit(r.valid?0:4)}
die('MULTIMACHINE_COMMAND_UNKNOWN',2,{usage:['policy verify','identity create|verify','coordinator init|export-identity','trust add','node enroll|approve|revoke|status','heartbeat create|accept','task submit|assign|reassign|status','bundle import','ack create|accept','result create|accept','certify run|verify']});
