#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const executionRoot=path.resolve(here,'..');
const sourcePackageRoot=path.basename(path.dirname(executionRoot))==='.aledevos'?null:path.resolve(executionRoot,'..');
const p3=path.join(executionRoot,'concurrency','concurrency-manager.mjs');
const policyPath=path.join(executionRoot,'policies','dispatcher-policy.json');
const args=process.argv.slice(2),[domain,command]=args;
const take=(flag,def=null)=>{const i=args.indexOf(flag);return i>=0&&i+1<args.length?args[i+1]:def};
const out=v=>process.stdout.write(JSON.stringify(v,null,2)+'\n');
const die=(status,code=2,extra={})=>{out({status,...extra});process.exit(code)};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const atomicWrite=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});const t=`${p}.${process.pid}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2)+'\n');fs.renameSync(t,p)};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const hashFile=p=>sha(fs.readFileSync(p));
const stable=(v,omit)=>Array.isArray(v)?v.map(x=>stable(x,omit)):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!omit.has(k)).sort().map(k=>[k,stable(v[k],omit)])):v;
const hashObj=(v,...omit)=>sha(Buffer.from(JSON.stringify(stable(v,new Set(omit)))));
const now=()=>new Date().toISOString();
const policy=()=>read(policyPath);
const pathEq=(a,b)=>{const A=path.resolve(a).replace(/[\\/]+$/,''),B=path.resolve(b).replace(/[\\/]+$/,'');return process.platform==='win32'?A.toLowerCase()===B.toLowerCase():A===B};
function runJson(script,argv,cwd){const r=spawnSync(process.execPath,[script,...argv],{cwd,encoding:'utf8',windowsHide:true});let data={};try{data=JSON.parse(r.stdout||'{}')}catch{}return{ok:r.status===0,status:r.status,data,stdout:r.stdout||'',stderr:r.stderr||''}}
function pidAlive(pid){if(!Number.isInteger(pid)||pid<=0)return false;try{process.kill(pid,0)}catch{return false}if(process.platform==='linux'){try{const s=fs.readFileSync(`/proc/${pid}/stat`,'utf8').trim().split(' ')[2];if(s==='Z'||s==='X')return false}catch{}}return true}

function stateRoot(repo){return path.join(repo,'.aledevos','state','execution','phase4')}
function queueFile(repo){return path.join(stateRoot(repo),'queue.json')}
function lockFile(repo){return path.join(stateRoot(repo),'control.lock')}
function itemDir(repo,id){return path.join(stateRoot(repo),'items',id)}
function planSnapshot(repo,id){return path.join(itemDir(repo,id),'plan.json')}
function receiptDir(repo,id){return path.join(itemDir(repo,id),'receipts')}
function emptyQueue(repo){return{schema_version:'1.0',phase:'ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE',repository_root:path.resolve(repo),mode:'ACTIVE',dispatch_epoch:0,next_sequence:1,items:{},created_at:now(),updated_at:now(),queue_sha256:''}}
function sealItem(x){x.item_sha256=hashObj(x,'item_sha256');return x}
function sealQueue(q){for(const x of Object.values(q.items||{}))sealItem(x);q.updated_at=now();q.queue_sha256=hashObj(q,'queue_sha256');return q}
function writeQueue(repo,q){sealQueue(q);atomicWrite(queueFile(repo),q)}
function validateQueueShape(repo,q){const e=[];if(q.schema_version!=='1.0'||q.phase!=='ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE')e.push('QUEUE_PHASE_INVALID');if(!pathEq(q.repository_root,repo))e.push('QUEUE_REPOSITORY_DRIFT');if(!['ACTIVE','PAUSED','DRAINING','DRAINED'].includes(q.mode))e.push('QUEUE_MODE_INVALID');if(q.queue_sha256!==hashObj(q,'queue_sha256'))e.push('QUEUE_INTEGRITY_MISMATCH');for(const [id,x] of Object.entries(q.items||{})){if(x.dispatch_id!==id)e.push(`ITEM_ID_DRIFT:${id}`);if(x.item_sha256!==hashObj(x,'item_sha256'))e.push(`ITEM_INTEGRITY_MISMATCH:${id}`);if(!fs.existsSync(x.plan_snapshot_path))e.push(`PLAN_SNAPSHOT_MISSING:${id}`);else if(hashFile(x.plan_snapshot_path)!==x.plan_file_sha256)e.push(`PLAN_SNAPSHOT_DRIFT:${id}`)}return e}
function loadQueue(repo,{create=true}={}){const f=queueFile(repo);if(!fs.existsSync(f)){if(!create)return null;const q=sealQueue(emptyQueue(repo));atomicWrite(f,q);return q}const q=read(f),e=validateQueueShape(repo,q);if(e.length)die('DISPATCH_QUEUE_INVALID',7,{errors:e});return q}
function acquire(repo){const f=lockFile(repo),p=policy();fs.mkdirSync(path.dirname(f),{recursive:true});for(let n=0;n<2;n++){try{const fd=fs.openSync(f,'wx');fs.writeFileSync(fd,JSON.stringify({pid:process.pid,created_at:now()})+'\n');return{fd,file:f}}catch(e){if(e?.code!=='EEXIST')throw e;let stale=false;try{const l=read(f),age=Date.now()-Date.parse(l.created_at||0);stale=(!pidAlive(l.pid)&&age>=0)||age>p.locking.stale_lock_after_ms}catch{stale=true}if(stale&&p.locking.stale_lock_recovery){try{fs.rmSync(f,{force:true})}catch{};continue}die('DISPATCH_CONTROL_BUSY',7)}}die('DISPATCH_CONTROL_BUSY',7)}
function release(l){try{fs.closeSync(l.fd)}catch{};try{fs.rmSync(l.file,{force:true})}catch{}}
function locked(repo,fn){const l=acquire(repo);try{return fn()}finally{release(l)}}
function p3PlanVerify(repo,file){return runJson(p3,['plan','verify','--repo',repo,'--plan',file],repo)}
function effectivePriority(x,epoch){const p=policy(),wait=Math.max(0,epoch-(x.enqueued_epoch||0)),boost=Math.floor(wait/p.fairness.aging_every_epochs)*p.fairness.aging_priority_boost;return Math.min(p.fairness.max_effective_priority,x.priority+boost)}
function itemReceipt(repo,q,x,event,extra={}){const r={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE',dispatch_id:x.dispatch_id,event,queue_epoch:q.dispatch_epoch,state:x.state,plan_sha256:x.plan_sha256,created_at:now(),...extra,receipt_sha256:''};r.receipt_sha256=hashObj(r,'receipt_sha256');const d=receiptDir(repo,x.dispatch_id);fs.mkdirSync(d,{recursive:true});const f=path.join(d,`${String(q.dispatch_epoch).padStart(8,'0')}-${event.toLowerCase().replace(/[^a-z0-9-]+/g,'-')}.json`);atomicWrite(f,r);return{path:f,receipt:r}}
function syncRunning(repo,q){for(const x of Object.values(q.items)){if(x.state!=='RUNNING'||!x.group_file)continue;const r=runJson(p3,['group','status','--repo',repo,'--group',x.group_file],repo);x.runtime_health=r.ok?'HEALTHY':'DEGRADED';x.runtime_errors=r.data.errors||[];x.last_synced_at=now()}if(q.mode==='DRAINING'&&!Object.values(q.items).some(x=>x.state==='RUNNING'))q.mode='DRAINED';return q}
function policyVerify(){const p=policy(),e=[];if(p.schema_version!=='1.0'||p.phase!=='ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE')e.push('PHASE_INVALID');for(const k of ['max_items','default_priority','max_priority','max_dispatch_starts_per_tick','max_dispatch_attempts'])if(!Number.isInteger(p.queue?.[k]))e.push(`QUEUE_NUMERIC_INVALID:${k}`);if(p.queue.min_priority!==0||p.queue.default_priority<p.queue.min_priority||p.queue.default_priority>p.queue.max_priority)e.push('PRIORITY_POLICY_INVALID');if(p.fairness?.policy!=='PRIORITY_FIFO_WITH_EPOCH_AGING')e.push('FAIRNESS_POLICY_INVALID');if(!p.dispatch?.never_bypass_p3||!p.dispatch?.never_spawn_worker_directly)e.push('P3_AUTHORITY_NOT_ENFORCED');if(p.boundaries?.dispatcher_used!==true||p.boundaries?.queue_used!==true)e.push('P4_BOUNDARY_NOT_ENABLED');for(const k of ['multi_machine_used','network_used'])if(p.boundaries?.[k]!==false)e.push(`BOUNDARY_INVALID:${k}`);if(p.boundaries?.safe_concurrency_authority!=='ADVANCED_EXECUTION_P3')e.push('P3_AUTHORITY_INVALID');if(p.boundaries?.target_agent_runtime_binding!=='DEFERRED_MASTER_VALIDATION')e.push('TARGET_RUNTIME_BOUNDARY_INVALID');return{status:e.length?'DISPATCH_POLICY_INVALID':'DISPATCH_POLICY_VALID',valid:!e.length,errors:e,policy:p}}
function queueVerify(repo){const q=loadQueue(repo,{create:false});if(!q)return{status:'DISPATCH_QUEUE_MISSING',valid:false,errors:['QUEUE_MISSING']};const e=validateQueueShape(repo,q);for(const x of Object.values(q.items||{})){if(fs.existsSync(x.plan_snapshot_path)){const pv=p3PlanVerify(repo,x.plan_snapshot_path);if(!pv.ok)e.push(`P3_PLAN_INVALID:${x.dispatch_id}`);else if(pv.data.plan?.plan_sha256!==x.plan_sha256)e.push(`P3_PLAN_SHA_DRIFT:${x.dispatch_id}`)}}return{status:e.length?'DISPATCH_QUEUE_INVALID':'DISPATCH_QUEUE_VALID',valid:!e.length,errors:e,queue:q}}
function submit(repo,planFile,priority,label){const p=policy();priority=priority==null?p.queue.default_priority:Number(priority);if(!Number.isInteger(priority)||priority<p.queue.min_priority||priority>p.queue.max_priority)die('DISPATCH_SUBMIT_BLOCKED',5,{errors:['PRIORITY_INVALID']});const pv=p3PlanVerify(repo,planFile);if(!pv.ok)die('DISPATCH_SUBMIT_BLOCKED',5,{errors:['P3_PLAN_INVALID'],detail:pv.data});const plan=pv.data.plan,planSha=plan.plan_sha256,id='dispatch-'+sha(Buffer.from(planSha)).slice(0,24);return locked(repo,()=>{const q=loadQueue(repo),active=Object.values(q.items).filter(x=>!['COMPLETED','CANCELLED','FAILED'].includes(x.state));if(active.length>=p.queue.max_items)die('DISPATCH_SUBMIT_BLOCKED',5,{errors:['QUEUE_CAPACITY_EXCEEDED']});if(p.queue.deduplicate_active_plan&&active.some(x=>x.plan_sha256===planSha))die('DISPATCH_DUPLICATE_ACTIVE_PLAN',5,{dispatch_id:id});const snap=planSnapshot(repo,id);fs.mkdirSync(path.dirname(snap),{recursive:true});fs.copyFileSync(path.resolve(planFile),snap);const x=sealItem({dispatch_id:id,state:'QUEUED',label:label||null,priority,enqueue_sequence:q.next_sequence++,enqueued_epoch:q.dispatch_epoch,enqueued_at:now(),plan_sha256:planSha,plan_snapshot_path:snap,plan_file_sha256:hashFile(snap),group_id:plan.group_id,worker_count:(plan.workers||[]).length,dispatch_attempts:0,admission_checks:0,last_error:null,last_block_reasons:[],group_file:null,runtime_health:null,runtime_errors:[],started_at:null,finished_at:null,item_sha256:''});q.items[id]=x;writeQueue(repo,q);const rec=itemReceipt(repo,q,x,'SUBMITTED',{priority,enqueue_sequence:x.enqueue_sequence});return{status:'DISPATCH_ITEM_QUEUED',dispatch_id:id,item:x,queue_file:queueFile(repo),receipt:rec}})}
function sortCandidates(q){return Object.values(q.items).filter(x=>['QUEUED','BLOCKED'].includes(x.state)).map(x=>({x,ep:effectivePriority(x,q.dispatch_epoch)})).sort((a,b)=>b.ep-a.ep||a.x.enqueue_sequence-b.x.enqueue_sequence||a.x.dispatch_id.localeCompare(b.x.dispatch_id))}
function parseP3Block(r){const errs=r.data?.errors||[];return errs}
function tick(repo,maxStarts){const p=policy();maxStarts=maxStarts==null?p.queue.max_dispatch_starts_per_tick:Number(maxStarts);if(!Number.isInteger(maxStarts)||maxStarts<1||maxStarts>p.queue.max_dispatch_starts_per_tick)die('DISPATCH_TICK_BLOCKED',5,{errors:['MAX_STARTS_INVALID']});return locked(repo,()=>{const q=syncRunning(repo,loadQueue(repo));q.dispatch_epoch++;const events=[];if(q.mode!=='ACTIVE'){writeQueue(repo,q);return{status:q.mode==='DRAINING'||q.mode==='DRAINED'?'DISPATCH_DRAINING':'DISPATCH_PAUSED',started:0,events,queue:q}}let started=0;for(const {x,ep} of sortCandidates(q)){if(started>=maxStarts)break;if(x.state==='PAUSED')continue;const pv=p3PlanVerify(repo,x.plan_snapshot_path);x.admission_checks++;if(!pv.ok){x.state='FAILED';x.last_error='P3_PLAN_INVALID';x.finished_at=now();events.push({dispatch_id:x.dispatch_id,event:'FAILED',reason:x.last_error});continue}const r=runJson(p3,['group','start','--repo',repo,'--plan',x.plan_snapshot_path],repo);if(r.ok){x.state='RUNNING';x.group_file=r.data.group_file;x.runtime_health='HEALTHY';x.runtime_errors=[];x.started_at=now();x.last_error=null;x.last_block_reasons=[];started++;events.push({dispatch_id:x.dispatch_id,event:'STARTED',effective_priority:ep,group_file:x.group_file});itemReceipt(repo,q,x,'STARTED',{effective_priority:ep,group_file:x.group_file});continue}const errs=parseP3Block(r),temporary=errs.some(e=>p.dispatch.temporary_block_reasons.includes(e));if(temporary){x.state='BLOCKED';x.last_block_reasons=errs;x.last_error='P3_ADMISSION_BLOCKED';events.push({dispatch_id:x.dispatch_id,event:'BLOCKED',reasons:errs,effective_priority:ep});continue}x.dispatch_attempts++;x.last_error=r.data?.status||'P3_START_FAILED';x.last_block_reasons=errs;if(x.dispatch_attempts>=p.queue.max_dispatch_attempts){x.state='FAILED';x.finished_at=now();events.push({dispatch_id:x.dispatch_id,event:'FAILED',reason:x.last_error})}else{x.state='QUEUED';events.push({dispatch_id:x.dispatch_id,event:'RETRY_QUEUED',attempt:x.dispatch_attempts,reason:x.last_error})}}writeQueue(repo,q);return{status:'DISPATCH_TICK_COMPLETED',started,events,queue:q}})}
function queueMode(repo,mode){return locked(repo,()=>{const q=syncRunning(repo,loadQueue(repo));if(mode==='PAUSED'){q.mode='PAUSED'}else if(mode==='ACTIVE'){q.mode='ACTIVE'}else if(mode==='DRAINING'){q.mode='DRAINING';if(!Object.values(q.items).some(x=>x.state==='RUNNING'))q.mode='DRAINED'}else die('DISPATCH_QUEUE_MODE_INVALID',4);writeQueue(repo,q);return{status:`DISPATCH_QUEUE_${q.mode}`,queue:q}})}
function itemAction(repo,id,action){return locked(repo,()=>{const q=syncRunning(repo,loadQueue(repo)),x=q.items[id];if(!x)die('DISPATCH_ITEM_NOT_FOUND',4,{dispatch_id:id});if(action==='pause'){if(!['QUEUED','BLOCKED'].includes(x.state))die('DISPATCH_ITEM_ACTION_BLOCKED',5,{state:x.state});x.state='PAUSED'}else if(action==='resume'){if(x.state!=='PAUSED')die('DISPATCH_ITEM_ACTION_BLOCKED',5,{state:x.state});x.state='QUEUED';x.last_error=null;x.last_block_reasons=[]}else if(action==='cancel'){if(['COMPLETED','CANCELLED','FAILED'].includes(x.state))die('DISPATCH_ITEM_ACTION_BLOCKED',5,{state:x.state});if(x.state==='RUNNING'&&x.group_file){const r=runJson(p3,['group','stop','--repo',repo,'--group',x.group_file],repo);if(!r.ok)die('DISPATCH_CANCEL_BLOCKED',6,{detail:r.data})}x.state='CANCELLED';x.finished_at=now();x.runtime_health='STOPPED'}else if(action==='complete'){if(x.state!=='RUNNING')die('DISPATCH_ITEM_ACTION_BLOCKED',5,{state:x.state});if(x.state==='RUNNING'&&x.group_file){const r=runJson(p3,['group','stop','--repo',repo,'--group',x.group_file],repo);if(!r.ok)die('DISPATCH_COMPLETE_BLOCKED',6,{detail:r.data})}x.state='COMPLETED';x.finished_at=now();x.runtime_health='STOPPED'}else die('DISPATCH_ITEM_ACTION_UNKNOWN',4);sealItem(x);if(q.mode==='DRAINING'&&!Object.values(q.items).some(y=>y.state==='RUNNING'))q.mode='DRAINED';writeQueue(repo,q);const rec=itemReceipt(repo,q,x,action.toUpperCase());const sm={pause:'PAUSED',resume:'RESUMED',cancel:'CANCELLED',complete:'COMPLETED'};return{status:`DISPATCH_ITEM_${sm[action]}`,item:x,receipt:rec,queue:q}})}
function status(repo){const q=syncRunning(repo,loadQueue(repo));writeQueue(repo,q);const counts={};for(const x of Object.values(q.items))counts[x.state]=(counts[x.state]||0)+1;return{status:'DISPATCH_QUEUE_STATUS',mode:q.mode,dispatch_epoch:q.dispatch_epoch,counts,items:Object.values(q.items).sort((a,b)=>a.enqueue_sequence-b.enqueue_sequence),queue_sha256:q.queue_sha256}}
function certificatePaths(){return['advanced-execution/dispatcher/dispatcher-manager.mjs','advanced-execution/policies/dispatcher-policy.json','advanced-execution/contracts/DISPATCHER_QUEUE.md','advanced-execution/schemas/dispatcher-queue.schema.json','advanced-execution/schemas/dispatch-item.schema.json','advanced-execution/schemas/dispatch-receipt.schema.json','advanced-execution/templates/dispatch-submit.example.json','advanced-execution/concurrency/concurrency-manager.mjs','advanced-execution/policies/concurrency-policy.json','release/certifications/advanced-execution-p1.json','release/certifications/advanced-execution-p2.json','release/certifications/advanced-execution-p3.json','scripts/05-install-into-project.ps1']}
function certifyRun(outFile){if(!sourcePackageRoot)die('ADVANCED_EXECUTION_P4_CERTIFICATION_SOURCE_LAYOUT_REQUIRED',4);const pv=policyVerify();const certs=['p1','p2','p3'].map((n,i)=>runJson(i===0?path.join(executionRoot,'worktrees','worktree-manager.mjs'):i===1?path.join(executionRoot,'workers','worker-manager.mjs'):p3,['certify','verify','--certificate',path.join(sourcePackageRoot,'release/certifications',`advanced-execution-${n}.json`)],sourcePackageRoot));const inputs=certificatePaths().map(rel=>({path:rel,sha256:hashFile(path.join(sourcePackageRoot,rel))}));const ok=pv.valid&&certs.every(x=>x.ok);const c={schema_version:'1.0',phase:'ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE',status:ok?'ADVANCED_EXECUTION_P4_PACKAGE_CERTIFIED':'ADVANCED_EXECUTION_P4_PACKAGE_CERTIFICATION_FAILED',package_only:true,target_runtime_validation:'DEFERRED',claims:{durable_local_queue:true,deterministic_priority_fifo_aging:true,p3_authoritative_dispatch:true,bounded_dispatch_retry:true,pause_resume_cancel_drain:true,stale_lock_recovery:true,work_conserving_dispatch:true,p1_p2_p3_frozen_dependencies:true,multi_machine_disabled:true,network_disabled:true,target_agent_runtime_binding:false},dependencies:{p1_certificate_valid:certs[0].ok,p2_certificate_valid:certs[1].ok,p3_certificate_valid:certs[2].ok},inputs,created_at:now(),evidence_sha256:''};c.evidence_sha256=hashObj(c,'evidence_sha256');if(outFile)atomicWrite(path.resolve(outFile),c);return c}
function certifyVerify(file){if(!sourcePackageRoot)return{status:'ADVANCED_EXECUTION_P4_CERTIFICATE_INVALID',valid:false,errors:['SOURCE_LAYOUT_REQUIRED']};if(!file||!fs.existsSync(file))return{status:'ADVANCED_EXECUTION_P4_CERTIFICATE_INVALID',valid:false,errors:['CERTIFICATE_MISSING']};const c=read(file),e=[];if(c.phase!=='ADVANCED_EXECUTION_P4_DISPATCHER_QUEUE')e.push('PHASE_INVALID');if(c.evidence_sha256!==hashObj(c,'evidence_sha256'))e.push('CERTIFICATE_INTEGRITY_MISMATCH');const expected=certificatePaths();if((c.inputs||[]).length!==expected.length)e.push('INPUT_SET_DRIFT');for(const rel of expected){const x=(c.inputs||[]).find(i=>i.path===rel);if(!x||x.sha256!==hashFile(path.join(sourcePackageRoot,rel)))e.push(`INPUT_DRIFT:${rel}`)}return{status:e.length?'ADVANCED_EXECUTION_P4_CERTIFICATE_STALE_OR_TAMPERED':'ADVANCED_EXECUTION_P4_CERTIFICATE_VALID',valid:!e.length,errors:e,certificate:c}}

if(domain==='policy'&&command==='verify'){const r=policyVerify();out(r);process.exit(r.valid?0:3)}
if(domain==='queue'&&command==='init'){const repo=path.resolve(take('--repo',''));const r=locked(repo,()=>{const q=loadQueue(repo);writeQueue(repo,q);return{status:'DISPATCH_QUEUE_READY',queue_file:queueFile(repo),queue:q}});out(r);process.exit(0)}
if(domain==='queue'&&command==='verify'){const r=queueVerify(path.resolve(take('--repo','')));out(r);process.exit(r.valid?0:5)}
if(domain==='queue'&&command==='status'){out(status(path.resolve(take('--repo',''))));process.exit(0)}
if(domain==='queue'&&command==='submit'){const r=submit(path.resolve(take('--repo','')),path.resolve(take('--plan','')),take('--priority'),take('--label'));out(r);process.exit(0)}
if(domain==='queue'&&command==='pause'){out(queueMode(path.resolve(take('--repo','')),'PAUSED'));process.exit(0)}
if(domain==='queue'&&command==='resume'){out(queueMode(path.resolve(take('--repo','')),'ACTIVE'));process.exit(0)}
if(domain==='queue'&&command==='drain'){out(queueMode(path.resolve(take('--repo','')),'DRAINING'));process.exit(0)}
if(domain==='dispatch'&&command==='tick'){out(tick(path.resolve(take('--repo','')),take('--max-starts')));process.exit(0)}
if(domain==='item'&&['pause','resume','cancel','complete'].includes(command)){out(itemAction(path.resolve(take('--repo','')),take('--dispatch-id',''),command));process.exit(0)}
if(domain==='certify'&&command==='run'){const c=certifyRun(take('--out'));out(c);process.exit(c.status.endsWith('CERTIFIED')?0:4)}
if(domain==='certify'&&command==='verify'){const r=certifyVerify(path.resolve(take('--certificate','')));out(r);process.exit(r.valid?0:4)}
die('DISPATCH_COMMAND_UNKNOWN',2,{usage:['policy verify','queue init|verify|status --repo <repo>','queue submit --repo <repo> --plan <p3-plan.json> [--priority 0..9] [--label text]','queue pause|resume|drain --repo <repo>','dispatch tick --repo <repo> [--max-starts N]','item pause|resume|cancel|complete --repo <repo> --dispatch-id <id>','certify run|verify']});
