param(
  [string]$Profile,
  [switch]$InventoryOnly
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$validator=Join-Path $root 'release\templates\master-validator-multimodel.mjs'
$release=Join-Path $root 'release\engine\v1-release.mjs'
$state=Join-Path $root '.aledevos\state\release\master\inputs\multimodel\p3'
$inputs=Join-Path $root '.aledevos\state\release\master\inputs'
New-Item -ItemType Directory -Path $state,$inputs -Force | Out-Null

$inventory=Join-Path $state 'inventory.json'
if($InventoryOnly -or [string]::IsNullOrWhiteSpace($Profile)){
  & node $validator inventory --root $root --out $inventory
  exit $LASTEXITCODE
}

$profileAbs=(Resolve-Path $Profile).Path
$profileLocal=Join-Path $state 'target-profile.json'
Copy-Item $profileAbs $profileLocal -Force
$receipt=Join-Path $state 'target-receipt.json'
& node $validator run --root $root --profile $profileLocal --out $receipt
$probeCode=$LASTEXITCODE
if(-not (Test-Path $receipt)){throw 'MASTER_VALIDATION_P3_RECEIPT_MISSING'}
$q=Get-Content $receipt -Raw | ConvertFrom-Json
$receiptRel=Get-AleDevRelativePath $root $receipt

function Art([string]$role,[string]$indexKey){
  $v=$q.artifact_index.$indexKey
  if([string]::IsNullOrWhiteSpace([string]$v)){return $null}
  return [ordered]@{role=$role;path=[string]$v}
}
function Seal-Check([string]$id,[string]$status,[object[]]$arts,[hashtable]$claims){
  $clean=@($arts | Where-Object { $_ -ne $null })
  $inputPath=Join-Path $inputs "$id.input.json"
  [ordered]@{
    schema_version='1.0';check_id=$id;status=$status;
    target=[ordered]@{phase='MASTER_VALIDATION_P3';target_fingerprint_sha256=$q.target.target_fingerprint_sha256;target_runtime=$q.target.target_runtime};
    artifacts=$clean;claims=$claims;notes=@('Generated by scripts/55-master-validation-p3-target-multimodel.ps1')
  } | ConvertTo-Json -Depth 20 | Set-Content -Encoding utf8 $inputPath
  & node $release master-evidence seal --input $inputPath --project-root $root
  if($LASTEXITCODE -ne 0){throw "MASTER_VALIDATION_P3_EVIDENCE_SEAL_FAILED:$id"}
}

$base=@([ordered]@{role='multimodel_target_receipt';path=$receiptRel})
Seal-Check 'primary_secondary_models_real' $q.checks.primary_secondary_models_real @(
  $base + (Art 'model_binding' 'model_binding')
) @{probe_exit_code=$probeCode;active_primary=$q.models.primary.runtime_ready;active_secondary=$q.models.secondary.runtime_ready}

Seal-Check 'model_router_real' $q.checks.model_router_real @(
  $base + (Art 'model_binding' 'model_binding') + (Art 'route_request' 'route_request') + (Art 'route_decision' 'route_decision')
) @{probe_exit_code=$probeCode;router_real=$true}

Seal-Check 'judge_diversity_real' $q.checks.judge_diversity_real @(
  $base + (Art 'model_binding' 'model_binding') + (Art 'primary_judge_evidence' 'primary_judge_evidence') + (Art 'secondary_judge_evidence' 'secondary_judge_evidence') + (Art 'judge_comparison' 'judge_comparison') + (Art 'diversity_decision' 'diversity_decision')
) @{probe_exit_code=$probeCode;semantic_independence_claimed=$false}

Seal-Check 'model_fallback_real' $q.checks.model_fallback_real @(
  $base + (Art 'fallback_weak_binding' 'fallback_weak_binding') + (Art 'fallback_route_request' 'fallback_route_request') + (Art 'fallback_blocked_diversity' 'fallback_blocked_diversity') + (Art 'fallback_plan' 'fallback_plan') + (Art 'fallback_trigger' 'fallback_trigger') + (Art 'fallback_decision' 'fallback_decision') + (Art 'fallback_replacement_binding' 'fallback_replacement_binding') + (Art 'fallback_fresh_route' 'fallback_fresh_route') + (Art 'fallback_fresh_diversity' 'fallback_fresh_diversity')
) @{probe_exit_code=$probeCode;fallback_mode='DIVERSITY_BLOCKED_CONTROLLED_REAL_MODELS';model_shopping=$false}

& node $release master-gate evaluate --project-root $root
exit $LASTEXITCODE
