param(
  [string]$Profile,
  [switch]$InventoryOnly
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$validator=Join-Path $root 'release\templates\master-validator-visual-runtime.mjs'
$release=Join-Path $root 'release\engine\v1-release.mjs'
$state=Join-Path $root '.aledevos\state\release\master\inputs\visual-runtime\p4'
$inputs=Join-Path $root '.aledevos\state\release\master\inputs'
New-Item -ItemType Directory -Path $state,$inputs -Force | Out-Null

if($InventoryOnly -or [string]::IsNullOrWhiteSpace($Profile)){
  $browser=Join-Path $root 'visualqa\engine\browser-runner.mjs'
  $audit=Join-Path $root 'visualqa\engine\runtime-audit.mjs'
  Write-Host '===== ALEDEVOS MASTER VALIDATION P4 INVENTORY =====' -ForegroundColor Cyan
  & node $browser doctor --project-root $root
  $browserCode=$LASTEXITCODE
  & node $audit doctor --project-root $root
  $auditCode=$LASTEXITCODE
  Write-Host "Browser doctor exit: $browserCode"
  Write-Host "Runtime audit doctor exit: $auditCode"
  Write-Host 'Inventory mode never declares a Master PASS.' -ForegroundColor Yellow
  exit 0
}

$profileAbs=(Resolve-Path $Profile).Path
$profileLocal=Join-Path $state 'target-profile.json'
Copy-Item $profileAbs $profileLocal -Force
$receipt=Join-Path $state 'target-receipt.json'
& node $validator compile --root $root --profile $profileLocal --out $receipt
if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P4_RECEIPT_COMPILE_FAILED'}
$q=Get-Content $receipt -Raw | ConvertFrom-Json
$receiptRel=Get-AleDevRelativePath $root $receipt

function Art([string]$role){
  $a=@($q.artifacts | Where-Object { $_.role -eq $role })
  if($a.Count -eq 0){return $null}
  return [ordered]@{role=$role;path=[string]$a[0].path}
}
function Seal-Check([string]$id,[string]$status,[string[]]$roles,[hashtable]$claims){
  $arts=@([ordered]@{role='visual_target_receipt';path=$receiptRel})
  foreach($r in $roles){$x=Art $r;if($null -ne $x){$arts += $x}}
  $inputPath=Join-Path $inputs "$id.input.json"
  [ordered]@{
    schema_version='1.0';check_id=$id;status=$status;
    target=[ordered]@{phase='MASTER_VALIDATION_P4';target_fingerprint_sha256=$q.target.target_fingerprint_sha256;target_runtime=$q.target.target_runtime};
    artifacts=$arts;claims=$claims;notes=@('Generated by scripts/57-master-validation-p4-target-visual.ps1')
  } | ConvertTo-Json -Depth 20 | Set-Content -Encoding utf8 $inputPath
  & node $release master-evidence seal --input $inputPath --project-root $root
  if($LASTEXITCODE -ne 0){throw "MASTER_VALIDATION_P4_EVIDENCE_SEAL_FAILED:$id"}
}

# PASS is attempted only when the profile contains all artifacts for that check.
function Has-All([string[]]$roles){foreach($r in $roles){if($null -eq (Art $r)){return $false}};return $true}
$r1=@('phase2_receipt')
$r2=@('phase2_receipt','phase4_report')
$r3=@('phase2_receipt','phase4_report','visual_judgment','native_image_invocation')
$r4=@('phase2_receipt','phase4_report','repair_success_cycle','repair_success_before_invocation','repair_success_after_invocation')
$r5=@('phase2_receipt','phase4_report','repair_exhaustion_cycle1','repair_exhaustion_cycle2','repair_exhaustion_initial_invocation','repair_exhaustion_after1_invocation','repair_exhaustion_after2_invocation','third_repair_probe')
Seal-Check 'playwright_chromium_real' ($(if(Has-All $r1){'PASS'}else{'BLOCKED'})) $r1 @{real_adapter_provider=$true;browser='chromium'}
Seal-Check 'runtime_layout_a11y_real' ($(if(Has-All $r2){'PASS'}else{'BLOCKED'})) $r2 @{rendered_runtime_audit=$true;full_wcag_claimed=$false}
Seal-Check 'native_image_visual_judge_real' ($(if(Has-All $r3){'PASS'}else{'BLOCKED'})) $r3 @{native_image_observation=$true;text_only_substitute=$false}
Seal-Check 'visual_repair_success_real' ($(if(Has-All $r4){'PASS'}else{'BLOCKED'})) $r4 @{fresh_p2_p3_p4_p5_required=$true;repair_attempt=1}
Seal-Check 'visual_repair_exhaustion_real' ($(if(Has-All $r5){'PASS'}else{'BLOCKED'})) $r5 @{max_repairs=2;third_repair_forbidden=$true}
& node $release master-gate evaluate --project-root $root
exit $LASTEXITCODE
