param(
  [string]$Profile,
  [switch]$InventoryOnly,
  [string]$TransportProbeProfile,
  [string]$CrashGroup,
  [string]$CrashWorkerId
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$validator=Join-Path $root 'release\templates\master-validator-advanced-execution.mjs'
$release=Join-Path $root 'release\engine\v1-release.mjs'
$state=Join-Path $root '.aledevos\state\release\master\inputs\advanced-execution\p5'
$inputs=Join-Path $root '.aledevos\state\release\master\inputs'
New-Item -ItemType Directory -Path $state,$inputs -Force | Out-Null

if($InventoryOnly -or [string]::IsNullOrWhiteSpace($Profile)){
  Write-Host '===== ALEDEVOS MASTER VALIDATION P5 INVENTORY =====' -ForegroundColor Cyan
  & node $validator inventory --root $root --out (Join-Path $state 'inventory.json')
  Write-Host 'Inventory mode never declares a Master PASS.' -ForegroundColor Yellow
  exit 0
}

if(-not [string]::IsNullOrWhiteSpace($TransportProbeProfile)){
  $tp=(Resolve-Path $TransportProbeProfile).Path
  & node $validator transport-probe --root $root --profile $tp --out (Join-Path $state 'transport-probe.json')
  if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P5_TRANSPORT_PROBE_FAILED'}
}
if(-not [string]::IsNullOrWhiteSpace($CrashGroup)){
  $cg=(Resolve-Path $CrashGroup).Path
  $args=@('crash-probe','--root',$root,'--group',$cg,'--out',(Join-Path $state 'crash-recovery-probe.json'))
  if(-not [string]::IsNullOrWhiteSpace($CrashWorkerId)){$args += @('--worker-id',$CrashWorkerId)}
  & node $validator @args
  if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P5_CRASH_PROBE_FAILED'}
}

$profileAbs=(Resolve-Path $Profile).Path
$profileLocal=Join-Path $state 'target-profile.json'
Copy-Item $profileAbs $profileLocal -Force
$receipt=Join-Path $state 'target-receipt.json'
& node $validator compile --root $root --profile $profileLocal --out $receipt
if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P5_RECEIPT_COMPILE_FAILED'}
$q=Get-Content $receipt -Raw | ConvertFrom-Json
$receiptRel=Get-AleDevRelativePath $root $receipt

function Art([string]$role){
  $a=@($q.artifacts | Where-Object { $_.role -eq $role })
  if($a.Count -eq 0){return $null}
  return [ordered]@{role=$role;path=[string]$a[0].path}
}
function Has-All([string[]]$roles){foreach($r in $roles){if($null -eq (Art $r)){return $false}};return $true}
function Seal-Check([string]$id,[string]$status,[string[]]$roles,[hashtable]$claims){
  $arts=@([ordered]@{role='advanced_execution_target_receipt';path=$receiptRel})
  foreach($r in $roles){$x=Art $r;if($null -ne $x){$arts += $x}}
  $inputPath=Join-Path $inputs "$id.input.json"
  [ordered]@{
    schema_version='1.0';check_id=$id;status=$status;
    target=[ordered]@{phase='MASTER_VALIDATION_P5';target_fingerprint_sha256=$q.target.target_fingerprint_sha256;target_runtime=$q.target.target_runtime};
    artifacts=$arts;claims=$claims;notes=@('Generated by scripts/59-master-validation-p5-target-advanced-execution.ps1')
  } | ConvertTo-Json -Depth 24 | Set-Content -Encoding utf8 $inputPath
  & node $release master-evidence seal --input $inputPath --project-root $root
  if($LASTEXITCODE -ne 0){throw "MASTER_VALIDATION_P5_EVIDENCE_SEAL_FAILED:$id"}
}

$r1=@('worktree_receipt','worker_assignment','worker_session')
$r2=@('concurrency_plan','concurrency_group','concurrency_conflict_plan')
$r3=@('dispatcher_queue','dispatcher_started_receipt')
$r4=@('transport_probe','remote_result_envelope')
$r5=@('crash_recovery_probe','stale_result_envelope','current_result_envelope')
Seal-Check 'worktree_worker_real' ($(if(Has-All $r1){'PASS'}else{'BLOCKED'})) $r1 @{live_worktree=$true;real_worker_supervisor=$true}
Seal-Check 'safe_concurrency_real' ($(if(Has-All $r2){'PASS'}else{'BLOCKED'})) $r2 @{minimum_live_workers=2;active_scope_conflict_must_block=$true}
Seal-Check 'dispatcher_queue_real' ($(if(Has-All $r3){'PASS'}else{'BLOCKED'})) $r3 @{durable_queue=$true;dispatcher_delegates_to_p3=$true}
Seal-Check 'multi_machine_transport_real' ($(if(Has-All $r4){'PASS'}else{'BLOCKED'})) $r4 @{real_network_roundtrip=$true;distinct_machine=$true;controlled_provider_forbidden=$true}
Seal-Check 'crash_recovery_real' ($(if(Has-All $r5){'PASS'}else{'BLOCKED'})) $r5 @{worker_process_loss_injected=$true;healthy_peer_survives=$true;fencing_reassignment_required=$true}
& node $release master-gate evaluate --project-root $root
exit $LASTEXITCODE
