param(
  [string]$Profile,
  [switch]$InventoryOnly,
  [string]$ProjectPath,
  [string]$TraceDraft,
  [string]$TraceOut
)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$validator=Join-Path $root 'release\templates\master-validator-end-to-end.mjs'
$release=Join-Path $root 'release\engine\v1-release.mjs'
$state=Join-Path $root '.aledevos\state\release\master\inputs\end-to-end\p6'
$inputs=Join-Path $root '.aledevos\state\release\master\inputs'
New-Item -ItemType Directory -Path $state,$inputs -Force | Out-Null

if(-not [string]::IsNullOrWhiteSpace($TraceDraft)){
  if([string]::IsNullOrWhiteSpace($TraceOut)){$TraceOut=Join-Path $state 'orchestration-trace.json'}
  & node $validator trace-seal --root $root --input (Resolve-Path $TraceDraft).Path --out $TraceOut
  if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P6_TRACE_SEAL_FAILED'}
}

if($InventoryOnly -or [string]::IsNullOrWhiteSpace($Profile)){
  Write-Host '===== ALEDEVOS MASTER VALIDATION P6 INVENTORY =====' -ForegroundColor Cyan
  $args=@('inventory','--root',$root,'--out',(Join-Path $state 'inventory.json'))
  if(-not [string]::IsNullOrWhiteSpace($ProjectPath)){
    $projectAbs=(Resolve-Path $ProjectPath).Path
    $projectRel=Get-AleDevRelativePath $root $projectAbs
    $args += @('--project',$projectRel)
  }
  & node $validator @args
  Write-Host 'Inventory mode never declares a Master PASS.' -ForegroundColor Yellow
  exit 0
}

$profileAbs=(Resolve-Path $Profile).Path
$profileLocal=Join-Path $state 'target-profile.json'
Copy-Item $profileAbs $profileLocal -Force
$receipt=Join-Path $state 'target-receipt.json'
& node $validator compile --root $root --profile $profileLocal --out $receipt
if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P6_RECEIPT_COMPILE_FAILED'}
$q=Get-Content $receipt -Raw | ConvertFrom-Json
$receiptRel=Get-AleDevRelativePath $root $receipt
$required=@('user_request','task_contract','context_handoff','orchestration_trace','skill_route','skill_composition','skill_load','skill_execution_handoff','skill_governance','skill_execution_receipt','model_binding','model_route','worktree_receipt','worker_assignment','worker_session','worker_handoff','dispatcher_queue','dispatcher_started_receipt','phase2_receipt','phase4_report','visual_acceptance','primary_judge_evidence','secondary_judge_evidence','judge_comparison','diversity_decision','global_state','telemetry_summary')
$present=@{}
foreach($a in $q.artifacts){$present[[string]$a.role]=$true}
$all=$true
foreach($r in $required){if(-not $present.ContainsKey($r)){$all=$false}}
$inputPath=Join-Path $inputs 'full_stack_real_project.input.json'
[ordered]@{
  schema_version='1.0';check_id='full_stack_real_project';status=if($all){'PASS'}else{'BLOCKED'};
  target=[ordered]@{phase='MASTER_VALIDATION_P6';target_fingerprint_sha256=$q.target.target_fingerprint_sha256;target_runtime=$q.target.target_runtime;project_path=$q.project.path;task_id=$q.project.task_id};
  artifacts=@([ordered]@{role='end_to_end_target_receipt';path=$receiptRel});
  claims=[ordered]@{complete_pipeline_required=$true;all_required_artifacts_present=$all;p7_efficiency_claimed=$false;p8_security_reliability_claimed=$false};
  notes=@('Generated by scripts/61-master-validation-p6-target-full-stack.ps1')
} | ConvertTo-Json -Depth 24 | Set-Content -Encoding utf8 $inputPath
& node $release master-evidence seal --input $inputPath --project-root $root
if($LASTEXITCODE -ne 0){throw 'MASTER_VALIDATION_P6_EVIDENCE_SEAL_FAILED'}
& node $release master-gate evaluate --project-root $root
exit $LASTEXITCODE
