param(
  [string]$ProjectRoot = ".",
  [string]$TaskContract,
  [string]$Signals,
  [string]$BenchmarkProfile,
  [switch]$InventoryOnly,
  [switch]$PlanOnly
)
$ErrorActionPreference='Stop'
$root=(Resolve-Path $ProjectRoot).Path
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$srcRoot=Split-Path -Parent $PSScriptRoot
$installedEff=Join-Path $root '.aledevos\efficiency\runtime\efficiency-governor.mjs'
$installedRelease=Join-Path $root '.aledevos\release\runtime\v1-release.mjs'
$eff=if(Test-Path $installedEff){$installedEff}else{Join-Path $srcRoot 'efficiency\engine\efficiency-governor.mjs'}
$release=if(Test-Path $installedRelease){$installedRelease}else{Join-Path $srcRoot 'release\engine\v1-release.mjs'}
if(-not(Test-Path $eff)){throw 'P7 efficiency runtime not found.'}
if(-not(Test-Path $release)){throw 'Master release runtime not found.'}

if($InventoryOnly){
  & node $eff inventory --root $root
  if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
  Write-Host 'P7 inventory only. NO MASTER PASS is declared.' -ForegroundColor Yellow
  exit 0
}
if(-not $TaskContract){throw '-TaskContract is required.'}
if(-not $Signals){throw '-Signals is required.'}
$task=(Resolve-Path (Join-Path $root $TaskContract)).Path
$signals=(Resolve-Path (Join-Path $root $Signals)).Path
$taskObj=Get-Content $task -Raw | ConvertFrom-Json
$taskId=[string]$taskObj.task_id
if(-not $taskId){throw 'Task Contract has no task_id.'}
$planDir=Join-Path $root '.aledevos\state\efficiency\plans';New-Item -ItemType Directory -Path $planDir -Force|Out-Null
$plan=Join-Path $planDir "$taskId.plan.json"
& node $eff plan create --root $root --task $task --signals $signals --out $plan
if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
& node $eff plan verify --root $root --plan $plan --task $task --signals $signals
if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
if($PlanOnly){Write-Host "P7 plan created and verified: $plan" -ForegroundColor Green;exit 0}
if(-not $BenchmarkProfile){throw '-BenchmarkProfile is required unless -PlanOnly or -InventoryOnly is used.'}
$bench=(Resolve-Path (Join-Path $root $BenchmarkProfile)).Path
$benchDir=Join-Path $root '.aledevos\state\efficiency\benchmarks';New-Item -ItemType Directory -Path $benchDir -Force|Out-Null
$receipt=Join-Path $benchDir "$taskId.efficiency-receipt.json"
& node $eff benchmark assess --root $root --profile $bench --out $receipt
$assessmentExit=$LASTEXITCODE
& node $eff benchmark verify --root $root --receipt $receipt --profile $bench
$verifyExit=$LASTEXITCODE
if($verifyExit -ne 0){throw 'P7 benchmark receipt verification failed.'}
$receiptObj=Get-Content $receipt -Raw | ConvertFrom-Json
$benchStatus=[string]$receiptObj.status
$masterStatus=if($benchStatus -eq 'EFFICIENCY_PASS'){'PASS'}elseif($benchStatus -eq 'EFFICIENCY_FAIL'){'FAIL'}else{'BLOCKED'}
$inputs=Join-Path $root '.aledevos\state\release\master\inputs';New-Item -ItemType Directory -Path $inputs -Force|Out-Null
$evidence=Join-Path $root '.aledevos\state\release\master\evidence';New-Item -ItemType Directory -Path $evidence -Force|Out-Null
function Rel([string]$p){return Get-AleDevRelativePath $root $p}
function Seal([string]$id,[string]$status,[array]$arts){
  $input=Join-Path $inputs "$id.input.json"
  $obj=[ordered]@{schema_version='1.0';check_id=$id;status=$status;target=[ordered]@{runtime='GLOBAL_EFFICIENCY_P7';project_root_sha256=([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($root))).ToLowerInvariant())};artifacts=$arts;claims=[ordered]@{measured_not_estimated=$true;quality_before_savings=$true;user_is_goal_owner_not_project_manager=$true};notes=@('Generated by scripts/63-master-validation-p7-target-efficiency.ps1')}
  $obj|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $input
  & node $release master-evidence seal --project-root $root --input $input --out (Join-Path $evidence "$id.json")
  if($LASTEXITCODE -ne 0){throw "Master evidence seal failed: $id"}
}
$commonPlan=@(
  [ordered]@{role='task_contract';path=(Rel $task)},
  [ordered]@{role='efficiency_signals';path=(Rel $signals)},
  [ordered]@{role='efficiency_plan';path=(Rel $plan)}
)
Seal 'adaptive_execution_governor_real' 'PASS' $commonPlan
$benchArts=@(
  [ordered]@{role='efficiency_benchmark_profile';path=(Rel $bench)},
  [ordered]@{role='efficiency_benchmark_receipt';path=(Rel $receipt)}
)
Seal 'context_token_efficiency_real' $masterStatus $benchArts
Seal 'quality_preservation_real' $masterStatus $benchArts
Seal 'user_project_manager_independence_real' $masterStatus $benchArts
Write-Host "P7 target evidence sealed. Benchmark status: $benchStatus" -ForegroundColor $(if($masterStatus -eq 'PASS'){'Green'}elseif($masterStatus -eq 'FAIL'){'Red'}else{'Yellow'})
exit $assessmentExit
