param(
  [string]$ProjectRoot = ".",
  [string]$Profile,
  [switch]$InventoryOnly
)
$ErrorActionPreference='Stop'
$root=(Resolve-Path $ProjectRoot).Path
function Get-AleDevRelativePath([string]$BasePath,[string]$TargetPath){
  # Windows PowerShell 5.1 runs on .NET Framework, which does not provide
  # System.IO.Path.GetRelativePath(). All Final Campaign scripts use this
  # descendant-only implementation so the same package works in PS 5.1/7+.
  $baseFull=[IO.Path]::GetFullPath($BasePath)
  $targetFull=[IO.Path]::GetFullPath($TargetPath)
  $sep=[IO.Path]::DirectorySeparatorChar
  if(-not $baseFull.EndsWith([string]$sep)){$baseFull += $sep}
  $cmp=if($env:OS -eq 'Windows_NT'){[System.StringComparison]::OrdinalIgnoreCase}else{[System.StringComparison]::Ordinal}
  if(-not $targetFull.StartsWith($baseFull,$cmp)){throw "ALEDEVOS_PATH_OUTSIDE_ROOT:$TargetPath"}
  return $targetFull.Substring($baseFull.Length).Replace('\','/')
}
$srcRoot=Split-Path -Parent $PSScriptRoot
$secInstalled=Join-Path $root '.aledevos\security-reliability\runtime\security-assurance.mjs'
$sec=if(Test-Path $secInstalled){$secInstalled}else{Join-Path $srcRoot 'security-reliability\engine\security-assurance.mjs'}
$regInstalled=Join-Path $root '.aledevos\security-reliability\runtime\reliability-registry.mjs'
$reg=if(Test-Path $regInstalled){$regInstalled}else{Join-Path $srcRoot 'security-reliability\engine\reliability-registry.mjs'}
$releaseInstalled=Join-Path $root '.aledevos\release\runtime\v1-release.mjs'
$release=if(Test-Path $releaseInstalled){$releaseInstalled}else{Join-Path $srcRoot 'release\engine\v1-release.mjs'}
$validatorInstalled=Join-Path $root '.aledevos\release\templates\master-validator-security-reliability.mjs'
$validator=if(Test-Path $validatorInstalled){$validatorInstalled}else{Join-Path $srcRoot 'release\templates\master-validator-security-reliability.mjs'}
if($InventoryOnly -or [string]::IsNullOrWhiteSpace($Profile)){
  & node $validator inventory --root $root
  if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
  & node $sec inventory --root $root
  Write-Host 'P8 inventory only. NO MASTER PASS is declared.' -ForegroundColor Yellow
  exit $LASTEXITCODE
}
$profileAbs=(Resolve-Path (Join-Path $root $Profile)).Path
$p=Get-Content $profileAbs -Raw | ConvertFrom-Json
if([string]$p.phase -ne 'MASTER_VALIDATION_P8_TARGET_PROFILE'){throw 'P8 target profile phase invalid.'}
$state=Join-Path $root '.aledevos\state\security-reliability';New-Item -ItemType Directory -Path $state -Force|Out-Null
$native=Join-Path $state 'native-scan.json'; & node $sec scan run --root $root --out $native; if($LASTEXITCODE -ne 0){throw 'Native scan execution failed.'}
$probe=Join-Path $state 'security-reviewer-probe.json'; & node $validator probe --root $root --profile $profileAbs --out $probe; $probeExit=$LASTEXITCODE
$submission=(Resolve-Path (Join-Path $root ([string]$p.security_review_submission))).Path
$review=Join-Path $state 'security-review.json'; & node $sec review seal --root $root --scan $native --submission $submission --out $review; $reviewExit=$LASTEXITCODE
$extProfile=(Resolve-Path (Join-Path $root ([string]$p.external_security_profile))).Path
$external=Join-Path $state 'external-scan.json'; & node $sec external run --root $root --profile $extProfile --out $external; $externalExit=$LASTEXITCODE
$testInput=(Resolve-Path (Join-Path $root ([string]$p.test_health_input))).Path
$testHealth=Join-Path $state 'test-health.json'; & node $sec test-health seal --root $root --input $testInput --out $testHealth; $testExit=$LASTEXITCODE
function Rel([string]$x){return Get-AleDevRelativePath $root $x}
$records=@();foreach($r in $p.registry_records){$records += (Resolve-Path (Join-Path $root ([string]$r))).Path}
$assuranceProfile=Join-Path $state 'assurance-profile.json'
[ordered]@{schema_version='1.0';phase='SECURITY_RELIABILITY_P8_ASSURANCE_PROFILE';native_scan=(Rel $native);security_review=(Rel $review);external_scan=(Rel $external);external_profile=(Rel $extProfile);test_health=(Rel $testHealth);registry_records=@($records|ForEach-Object{Rel $_})}|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $assuranceProfile
$assurance=Join-Path $state 'assurance-receipt.json'; & node $sec gate assess --root $root --profile $assuranceProfile --out $assurance; $gateExit=$LASTEXITCODE
$inputs=Join-Path $root '.aledevos\state\release\master\inputs';New-Item -ItemType Directory -Path $inputs -Force|Out-Null
$evidence=Join-Path $root '.aledevos\state\release\master\evidence';New-Item -ItemType Directory -Path $evidence -Force|Out-Null
function Seal([string]$id,[string]$status,[array]$arts){$inp=Join-Path $inputs "$id.input.json";[ordered]@{schema_version='1.0';check_id=$id;status=$status;target=[ordered]@{phase='SECURITY_RELIABILITY_P8'};artifacts=$arts;claims=[ordered]@{perfect_security_claimed=$false;deterministic_blockers_authoritative=$true};notes=@('Generated by P8 target runner')}|ConvertTo-Json -Depth 20|Set-Content -Encoding utf8 $inp;& node $release master-evidence seal --project-root $root --input $inp --out (Join-Path $evidence "$id.json");if($LASTEXITCODE -ne 0){throw "P8 master evidence seal failed: $id"}}
$nativeStatus='PASS';$reviewStatus=if($reviewExit -eq 0 -and $probeExit -eq 0){'PASS'}else{'BLOCKED'};$depStatus=if($externalExit -eq 0){'PASS'}else{'BLOCKED'};$testStatus=if($testExit -eq 0){'PASS'}else{'BLOCKED'}
$bug=@($records|Where-Object{(Get-Content $_ -Raw|ConvertFrom-Json).record_type -eq 'BUG'}|Select-Object -First 1)
$vuln=@($records|Where-Object{(Get-Content $_ -Raw|ConvertFrom-Json).record_type -eq 'VULNERABILITY'}|Select-Object -First 1)
$inc=@($records|Where-Object{(Get-Content $_ -Raw|ConvertFrom-Json).record_type -eq 'INCIDENT'}|Select-Object -First 1)
Seal 'security_native_scan_real' $nativeStatus @([ordered]@{role='security_native_scan';path=(Rel $native)})
Seal 'security_reviewer_real' $reviewStatus @([ordered]@{role='security_review_receipt';path=(Rel $review)},[ordered]@{role='security_reviewer_probe';path=(Rel $probe)})
Seal 'dependency_security_scan_real' $depStatus @([ordered]@{role='external_security_scan';path=(Rel $external)},[ordered]@{role='external_security_profile';path=(Rel $extProfile)})
if($bug.Count -gt 0){Seal 'bug_regression_registry_real' 'PASS' @([ordered]@{role='bug_record';path=(Rel $bug[0])})}else{Seal 'bug_regression_registry_real' 'BLOCKED' @()}
if($vuln.Count -gt 0 -and $inc.Count -gt 0){Seal 'incident_vulnerability_registry_real' 'PASS' @([ordered]@{role='vulnerability_record';path=(Rel $vuln[0])},[ordered]@{role='incident_record';path=(Rel $inc[0])})}else{Seal 'incident_vulnerability_registry_real' 'BLOCKED' @()}
Seal 'test_health_real' $testStatus @([ordered]@{role='test_health_summary';path=(Rel $testHealth)})
$gateStatus=if($gateExit -eq 0){'PASS'}else{'BLOCKED'}
Seal 'security_reliability_assurance_real' $gateStatus @([ordered]@{role='security_assurance_profile';path=(Rel $assuranceProfile)},[ordered]@{role='security_assurance_receipt';path=(Rel $assurance)})
& node $release master-gate evaluate --project-root $root
exit $LASTEXITCODE
