import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { invalidateResearchByPaths } from './research-cache.mjs';

const VERSION='0.5.0';
const TEXT_EXTS=new Set(['.js','.jsx','.ts','.tsx','.mjs','.cjs','.py','.go','.rs','.java','.cs','.rb','.php','.swift','.kt','.kts','.vue','.svelte','.json','.jsonc','.yaml','.yml','.toml','.ini','.md','.mdx','.txt','.css','.scss','.sass','.less','.html','.htm','.sql','.graphql','.gql','.sh','.ps1','.bat','.cmd','.xml','.properties','.env.example']);
const SOURCE_EXTS=new Set(['.js','.jsx','.ts','.tsx','.mjs','.cjs','.py','.go','.rs','.java','.cs','.rb','.php','.swift','.kt','.kts','.vue','.svelte']);
const JS_EXTS=new Set(['.js','.jsx','.ts','.tsx','.mjs','.cjs']);
const PY_EXTS=new Set(['.py']);
const LANG_BY_EXT={'.js':'javascript','.jsx':'javascript-react','.ts':'typescript','.tsx':'typescript-react','.mjs':'javascript','.cjs':'javascript','.py':'python','.go':'go','.rs':'rust','.java':'java','.cs':'csharp','.rb':'ruby','.php':'php','.swift':'swift','.kt':'kotlin','.kts':'kotlin','.vue':'vue','.svelte':'svelte','.sql':'sql','.css':'css','.scss':'scss','.html':'html'};
const CONFIG_NAMES=new Set(['package.json','package-lock.json','pnpm-lock.yaml','yarn.lock','tsconfig.json','jsconfig.json','pyproject.toml','pytest.ini','requirements.txt','go.mod','cargo.toml','dockerfile','makefile']);

function canon(v){if(Array.isArray(v))return '['+v.map(canon).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}';return JSON.stringify(v)}
function shaText(s){return crypto.createHash('sha256').update(s).digest('hex')}
function payload(v){const x=structuredClone(v);delete x.integrity;delete x.generated_at;delete x.refreshed_at;return x}
function payloadHash(v){return shaText(canon(payload(v)))}
function hashFile(file){const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),buf=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n))}}finally{fs.closeSync(fd)}return h.digest('hex')}
function atomicWriteJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+`.tmp-${process.pid}-${Date.now()}`;fs.writeFileSync(tmp,JSON.stringify(value,null,2)+'\n','utf8');fs.renameSync(tmp,file)}
function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''))}
function rel(root,p){return path.relative(root,p).replaceAll('\\','/')}
function git(root,args){return spawnSync('git',args,{cwd:root,encoding:'utf8',windowsHide:true})}
function gitMeta(root){const inside=git(root,['rev-parse','--is-inside-work-tree']);if(inside.status!==0)return {is_git_repo:false,head:null,branch:null};const head=git(root,['rev-parse','HEAD']),branch=git(root,['branch','--show-current']);return {is_git_repo:true,head:head.status===0?head.stdout.trim():null,branch:branch.status===0?branch.stdout.trim()||null:null}}
function extOf(name){const low=name.toLowerCase();if(low==='.env.example')return '.env.example';return path.extname(low)}
function isTextCandidate(name){const ext=extOf(name),low=path.basename(name).toLowerCase();return TEXT_EXTS.has(ext)||CONFIG_NAMES.has(low)||low.startsWith('readme')||low.startsWith('license')||low==='agents.md'||low==='.gitignore'||low==='.gitattributes'}
function roleOf(p){const low=p.toLowerCase(),name=path.basename(low);if(/(^|\/)(test|tests|__tests__|spec|specs)(\/|$)/.test(low)||/\.(test|spec)\.[^.]+$/.test(name))return 'test';if(CONFIG_NAMES.has(name)||/(^|\/)(config|configs)(\/|$)/.test(low)||/(^|\/)(\.github|\.opencode)(\/|$)/.test(low))return 'config';if(/\.(md|mdx|txt)$/.test(name)||/(^|\/)(docs?|documentation)(\/|$)/.test(low))return 'docs';if(SOURCE_EXTS.has(extOf(name)))return 'source';return 'other'}
function shouldIgnore(relPath,policy){const parts=relPath.split('/').filter(Boolean),ignoreNames=new Set(policy.knowledge?.ignore_directory_names||['.git','node_modules','.aledevos','dist','build','coverage','.next','.cache','vendor']);return parts.some(x=>ignoreNames.has(x))}
function walkFiles(root,policy,{withHashes=true}={}){const max=Number(policy.knowledge?.max_files||25000),out=[];function walk(dir){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const abs=path.join(dir,ent.name),r=rel(root,abs);if(ent.isDirectory()){if(shouldIgnore(r,policy))continue;walk(abs)}else if(ent.isFile()&&isTextCandidate(ent.name)){const st=fs.statSync(abs);out.push({abs,path:r,bytes:st.size,ext:extOf(ent.name),role:roleOf(r),language:LANG_BY_EXT[extOf(ent.name)]||null,sha256:withHashes?hashFile(abs):null});if(out.length>max)throw new Error(`KNOWLEDGE_MAX_FILES_EXCEEDED:${out.length}>${max}`)}}}walk(root);return out.sort((a,b)=>a.path.localeCompare(b.path))}
function readForParse(file,policy){const max=Number(policy.knowledge?.max_parse_file_bytes||2097152);if(file.bytes>max)return null;try{return fs.readFileSync(file.abs,'utf8').replace(/^\uFEFF/,'')}catch{return null}}
function sourceSignature(files){const h=crypto.createHash('sha256');for(const f of files){h.update(f.path);h.update('\0');h.update(f.sha256||hashFile(f.abs));h.update('\n')}return h.digest('hex')}
function projectName(root){try{const p=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));if(p.name)return p.name}catch{}return path.basename(root)}
function resolveLocal(root,from,spec,candidates){if(!spec.startsWith('.'))return null;const base=path.resolve(root,path.dirname(from),spec),tries=[base,...['.ts','.tsx','.js','.jsx','.mjs','.cjs','.py'].map(x=>base+x),...['index.ts','index.tsx','index.js','index.jsx','index.mjs','index.cjs','__init__.py'].map(x=>path.join(base,x))];for(const t of tries){const r=rel(root,t);if(candidates.has(r))return r}return null}
function externalRoot(spec){if(spec.startsWith('@'))return spec.split('/').slice(0,2).join('/');return spec.split('/')[0]}
function parseDependencySpecs(file,text){const deps=[];if(JS_EXTS.has(file.ext)){const re=/(?:\bimport\s+(?:[^'";]+?\s+from\s+)?|\bexport\s+[^'";]+?\s+from\s+|\brequire\s*\(|\bimport\s*\()\s*['"]([^'"]+)['"]/g;let m;while((m=re.exec(text))){const spec=m[1];deps.push({specifier:spec,type:spec.startsWith('.')?'local':'external',external:spec.startsWith('.')?null:externalRoot(spec)})}}else if(PY_EXTS.has(file.ext)){for(const line of text.split(/\r?\n/)){let m=line.match(/^\s*from\s+([^\s]+)\s+import\s+/);if(m){const spec=m[1];deps.push({specifier:spec,type:spec.startsWith('.')?'local':'external',external:spec.startsWith('.')?null:spec.split('.')[0]});continue}m=line.match(/^\s*import\s+([^#]+)/);if(m){for(const raw of m[1].split(',')){const spec=raw.trim().split(/\s+as\s+/)[0];if(spec)deps.push({specifier:spec,type:'external',external:spec.split('.')[0]})}}}}const key=x=>`${x.specifier}|${x.type}|${x.external||''}`;return [...new Map(deps.map(x=>[key(x),x])).values()].sort((a,b)=>key(a).localeCompare(key(b)))}
function parseSymbols(file,text){const out=[],seen=new Set(),lines=text.split(/\r?\n/);function add(name,kind,exported,line){const k=`${name}|${kind}|${line}`;if(!name||seen.has(k))return;seen.add(k);out.push({name,kind,exported:Boolean(exported),line})}if(JS_EXTS.has(file.ext)){for(let i=0;i<lines.length;i++){const s=lines[i];let m=s.match(/^\s*(export\s+default\s+|export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)/);if(m){add(m[2],'function',Boolean(m[1]),i+1);continue}m=s.match(/^\s*(export\s+default\s+|export\s+)?class\s+([A-Za-z_$][\w$]*)/);if(m){add(m[2],'class',Boolean(m[1]),i+1);continue}m=s.match(/^\s*(export\s+)?(?:declare\s+)?(interface|type|enum)\s+([A-Za-z_$][\w$]*)/);if(m){add(m[3],m[2],Boolean(m[1]),i+1);continue}m=s.match(/^\s*(export\s+)?(const|let|var)\s+([A-Za-z_$][\w$]*)/);if(m)add(m[3],m[2],Boolean(m[1]),i+1)}}else if(PY_EXTS.has(file.ext)){for(let i=0;i<lines.length;i++){const s=lines[i];let m=s.match(/^(?:async\s+)?def\s+([A-Za-z_]\w*)\s*\(/);if(m){add(m[1],'function',!m[1].startsWith('_'),i+1);continue}m=s.match(/^class\s+([A-Za-z_]\w*)\b/);if(m)add(m[1],'class',!m[1].startsWith('_'),i+1)}}return out}
function globOne(pattern,p){const a=pattern.split('/'),b=p.split('/');if(a.length!==b.length)return false;for(let i=0;i<a.length;i++)if(a[i]!=='*'&&a[i]!==b[i])return false;return true}
function domainRoot(filePath,policy){const parts=filePath.split('/');for(const pattern of policy.knowledge?.domain_root_patterns||[]){const n=pattern.split('/').length;if(parts.length>=n){const prefix=parts.slice(0,n).join('/');if(globOne(pattern,prefix))return prefix}}return '__root__'}
function domainId(root){if(root==='__root__')return 'root';const base=root.replace(/[^A-Za-z0-9._-]+/g,'--').replace(/^-+|-+$/g,'').toLowerCase()||'domain';return `${base}-${shaText(root).slice(0,8)}`}
function seal(map){map.integrity={algorithm:'sha256',payload_sha256:payloadHash(map)};return map}
function mapEntry(file,map){return {path:file,payload_sha256:map.integrity.payload_sha256}}
function copyDirIfExists(src,dst){if(!fs.existsSync(src))return;fs.cpSync(src,dst,{recursive:true,force:true})}
function loadOldInventory(outRoot){const p=path.join(outRoot,'inventory.json');if(!fs.existsSync(p))return null;try{return readJson(p)}catch{return null}}
function diffInventory(previous,current){const a=new Map((previous?.files||[]).map(x=>[x.path,x])),b=new Map(current.map(x=>[x.path,x]));const added=[],changed=[],deleted=[],unchanged=[];for(const [p,x] of b){if(!a.has(p))added.push(p);else if(a.get(p).sha256!==x.sha256)changed.push(p);else unchanged.push(p)}for(const p of a.keys())if(!b.has(p))deleted.push(p);return {added:added.sort(),changed:changed.sort(),deleted:deleted.sort(),unchanged:unchanged.sort()}}
function loadParseCache(outRoot){const p=path.join(outRoot,'.internal','file-cache.json');if(!fs.existsSync(p))return {version:VERSION,files:{}};try{const c=readJson(p);if(c.version!==VERSION||c.integrity?.payload_sha256!==payloadHash(c))return {version:VERSION,files:{}};return c}catch{return {version:VERSION,files:{}}}}
function parseEntry(f,policy){const text=readForParse(f,policy);if(text===null)return {path:f.path,source_sha256:f.sha256,ext:f.ext,role:f.role,language:f.language,parse_status:'SKIPPED_LARGE',dependency_specs:[],symbols:[]};const supported=JS_EXTS.has(f.ext)||PY_EXTS.has(f.ext);return {path:f.path,source_sha256:f.sha256,ext:f.ext,role:f.role,language:f.language,parse_status:supported?'PARSED':'UNSUPPORTED',dependency_specs:supported?parseDependencySpecs(f,text):[],symbols:supported?parseSymbols(f,text):[]}}
function verifyOne(file,expected){if(!fs.existsSync(file))return {valid:false,error:'missing'};let v;try{v=readJson(file)}catch{return {valid:false,error:'invalid_json'}}const actual=payloadHash(v),internal=v.integrity?.payload_sha256||null;return {valid:actual===expected&&internal===expected,actual,expected,internal}}

export function knowledgeFreshness({cwd,policy}){const outRoot=path.join(cwd,policy.knowledge?.output_dir||'.aledevos/state/knowledge'),manifestPath=path.join(outRoot,'manifest.json'),inventoryPath=path.join(outRoot,'inventory.json');if(!fs.existsSync(manifestPath)||!fs.existsSync(inventoryPath))return {status:'UNKNOWN',fresh:false,reason:'KNOWLEDGE_NOT_BUILT',added:[],changed:[],deleted:[]};let manifest,inventory;try{manifest=readJson(manifestPath);inventory=readJson(inventoryPath)}catch{return {status:'UNKNOWN',fresh:false,reason:'KNOWLEDGE_INVALID_JSON',added:[],changed:[],deleted:[]}};if(manifest.version!==VERSION||inventory.version!==VERSION)return {status:'UNKNOWN',fresh:false,reason:'KNOWLEDGE_VERSION_MISMATCH',added:[],changed:[],deleted:[]};const files=walkFiles(cwd,policy),delta=diffInventory(inventory,files),fresh=delta.added.length===0&&delta.changed.length===0&&delta.deleted.length===0;return {status:fresh?'FRESH':'STALE',fresh,reason:fresh?'SOURCE_MATCH':'SOURCE_DRIFT',source_fingerprint_sha256:sourceSignature(files),manifest_source_fingerprint_sha256:manifest.source?.source_fingerprint_sha256||null,...delta,current_files:files.length}}

function generateKnowledge({cwd,policy,incremental=false}){
 const cfg=policy.knowledge||{};if(cfg.enabled!==true)throw new Error('KNOWLEDGE_DISABLED');const outRoot=path.join(cwd,cfg.output_dir||'.aledevos/state/knowledge'),oldInventory=loadOldInventory(outRoot),files=walkFiles(cwd,policy),delta=diffInventory(oldInventory,files);
 if(incremental&&oldInventory&&delta.added.length===0&&delta.changed.length===0&&delta.deleted.length===0){return {status:'KNOWLEDGE_FRESH_NOOP',version:VERSION,output_dir:rel(cwd,outRoot),files:files.length,incremental:{reparsed_files:0,reused_parse_entries:files.filter(x=>x.role==='source'||x.role==='test').length,added:0,changed:0,deleted:0},freshness:'FRESH'}}
 const stageRoot=outRoot+`.tmp-${process.pid}-${Date.now()}`,domainDir=path.join(stageRoot,'domains'),internalDir=path.join(stageRoot,'.internal'),candidateSet=new Set(files.map(x=>x.path)),git=gitMeta(cwd),sig=sourceSignature(files),generated=new Date().toISOString(),oldCache=incremental?loadParseCache(outRoot):{files:{}};fs.mkdirSync(domainDir,{recursive:true});fs.mkdirSync(internalDir,{recursive:true});copyDirIfExists(path.join(outRoot,'research'),path.join(stageRoot,'research'));
 const langs={};for(const f of files)if(f.language)langs[f.language]=(langs[f.language]||0)+1;
 const repo=seal({version:VERSION,generated_at:generated,root:'.',project:{name:projectName(cwd)},source:{git,source_fingerprint_sha256:sig},stats:{files:files.length,source_files:files.filter(x=>x.role==='source').length,test_files:files.filter(x=>x.role==='test').length,config_files:files.filter(x=>x.role==='config').length,docs_files:files.filter(x=>x.role==='docs').length,languages:langs},files:files.map(({path,bytes,ext,role,language,sha256})=>({path,bytes,ext,role,language,sha256}))});
 const inventory=seal({version:VERSION,generated_at:generated,source_fingerprint_sha256:sig,files:files.map(({path,bytes,sha256,role})=>({path,bytes,sha256,role}))});
 const parseFiles=files.filter(x=>x.role==='source'||x.role==='test'),cacheEntries={},stats={reparsed_files:0,reused_parse_entries:0,added:delta.added.length,changed:delta.changed.length,deleted:delta.deleted.length};
 for(const f of parseFiles){const prior=oldCache.files?.[f.path];if(incremental&&prior&&prior.source_sha256===f.sha256){cacheEntries[f.path]=prior;stats.reused_parse_entries++}else{cacheEntries[f.path]=parseEntry(f,policy);stats.reparsed_files++}}
 const coverage={parsed_js_ts:0,parsed_python:0,unsupported_source:0,skipped_large:0};for(const e of Object.values(cacheEntries)){if(e.parse_status==='SKIPPED_LARGE')coverage.skipped_large++;else if(e.parse_status==='UNSUPPORTED')coverage.unsupported_source++;else if(JS_EXTS.has(e.ext))coverage.parsed_js_ts++;else if(PY_EXTS.has(e.ext))coverage.parsed_python++}
 const depFiles=[],symFiles=[];for(const f of parseFiles){const e=cacheEntries[f.path];depFiles.push({path:f.path,dependency_specs:e.dependency_specs||[],parse_status:e.parse_status});symFiles.push({path:f.path,symbols:e.symbols||[],parse_status:e.parse_status})}
 const edges=[],externals=new Map(),unresolved=[];for(const x of depFiles)for(const d of x.dependency_specs){if(d.type==='local'){const resolved=resolveLocal(cwd,x.path,d.specifier,candidateSet);if(resolved)edges.push({from:x.path,to:resolved,type:'local',specifier:d.specifier});else unresolved.push({from:x.path,specifier:d.specifier,type:'local'})}else{const arr=externals.get(d.external)||[];arr.push(x.path);externals.set(d.external,arr);edges.push({from:x.path,to:d.external,type:'external',specifier:d.specifier})}}
 const dep=seal({version:VERSION,generated_at:generated,source:{git,source_fingerprint_sha256:sig},parser_coverage:coverage,nodes:depFiles.map(x=>({path:x.path,parse_status:x.parse_status})),edges:edges.sort((a,b)=>`${a.from}|${a.to}`.localeCompare(`${b.from}|${b.to}`)),external_packages:[...externals].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,users])=>({name,used_by:[...new Set(users)].sort()})),unresolved});
 const symbols=seal({version:VERSION,generated_at:generated,source:{git,source_fingerprint_sha256:sig},parser_coverage:coverage,files:symFiles,total_symbols:symFiles.reduce((n,x)=>n+x.symbols.length,0)});
 const roots=new Map();for(const f of files){if(f.role==='source'){const r=domainRoot(f.path,policy);if(!roots.has(r))roots.set(r,[]);roots.get(r).push(f.path)}}const rootIds=new Map([...roots.keys()].map(r=>[r,domainId(r)]));
 const tests=files.filter(x=>x.role==='test').map(x=>x.path),testByDomain=new Map([...roots.keys()].map(r=>[r,[]]));for(const t of tests){let matched=null;for(const r of roots.keys()){if(r==='__root__')continue;const term=r.split('/').pop().toLowerCase();if(t.toLowerCase().split('/').some(x=>x.includes(term))){matched=r;break}}if(!matched)matched=roots.has('__root__')?'__root__':[...roots.keys()][0]||'__root__';if(!testByDomain.has(matched))testByDomain.set(matched,[]);testByDomain.get(matched).push(t)}
 const fileToDomain=new Map();for(const [r,arr] of roots)for(const f of arr)fileToDomain.set(f,r);const cross=new Map();for(const e of edges.filter(x=>x.type==='local')){const a=fileToDomain.get(e.from),b=fileToDomain.get(e.to);if(a&&b&&a!==b){const k=`${a}|${b}`;cross.set(k,(cross.get(k)||0)+1)}}
 const domainMaps=[];for(const [r,sourceFiles] of [...roots.entries()].sort((a,b)=>a[0].localeCompare(b[0]))){const id=rootIds.get(r),all=[...sourceFiles,...(testByDomain.get(r)||[])].sort(),symbolCount=symFiles.filter(x=>sourceFiles.includes(x.path)).reduce((n,x)=>n+x.symbols.length,0),ext=new Set(),depsOut=new Map(),depsIn=new Map();for(const e of edges)if(sourceFiles.includes(e.from)&&e.type==='external')ext.add(e.to);for(const [k,n] of cross){const [a,b]=k.split('|');if(a===r)depsOut.set(rootIds.get(b),n);if(b===r)depsIn.set(rootIds.get(a),n)}const dm=seal({version:VERSION,generated_at:generated,id,root:r,source:{git,source_fingerprint_sha256:sig},files:all,source_files:sourceFiles.sort(),test_files:(testByDomain.get(r)||[]).sort(),symbol_count:symbolCount,external_dependencies:[...ext].sort(),depends_on_domains:[...depsOut].sort((a,b)=>a[0].localeCompare(b[0])).map(([domain,edge_count])=>({domain,edge_count})),depended_by_domains:[...depsIn].sort((a,b)=>a[0].localeCompare(b[0])).map(([domain,edge_count])=>({domain,edge_count}))});domainMaps.push(dm);atomicWriteJson(path.join(domainDir,`${id}.json`),dm)}
 const domainIndex=seal({version:VERSION,generated_at:generated,source:{git,source_fingerprint_sha256:sig},domains:domainMaps.map(d=>({id:d.id,root:d.root,files:d.files.length,source_files:d.source_files.length,test_files:d.test_files.length,symbol_count:d.symbol_count,payload_sha256:d.integrity.payload_sha256}))});
 const parseCache=seal({version:VERSION,generated_at:generated,files:cacheEntries});
 atomicWriteJson(path.join(stageRoot,'inventory.json'),inventory);atomicWriteJson(path.join(stageRoot,'repo-map.json'),repo);atomicWriteJson(path.join(stageRoot,'dependency-map.json'),dep);atomicWriteJson(path.join(stageRoot,'symbol-map.json'),symbols);atomicWriteJson(path.join(stageRoot,'domains.index.json'),domainIndex);atomicWriteJson(path.join(internalDir,'file-cache.json'),parseCache);
 const manifest=seal({version:VERSION,generated_at:generated,source:{git,source_fingerprint_sha256:sig,inventory_files:files.length},maps:{inventory:mapEntry('inventory.json',inventory),repo:mapEntry('repo-map.json',repo),dependency:mapEntry('dependency-map.json',dep),symbols:mapEntry('symbol-map.json',symbols),domains_index:mapEntry('domains.index.json',domainIndex),domains:domainMaps.map(d=>mapEntry(`domains/${d.id}.json`,d))},internal:{parse_cache:mapEntry('.internal/file-cache.json',parseCache)},coverage,incremental:stats});atomicWriteJson(path.join(stageRoot,'manifest.json'),manifest);
 const backup=outRoot+`.bak-${process.pid}-${Date.now()}`;let movedOld=false;try{if(fs.existsSync(outRoot)){fs.renameSync(outRoot,backup);movedOld=true}fs.renameSync(stageRoot,outRoot);if(movedOld)fs.rmSync(backup,{recursive:true,force:true})}catch(e){try{if(fs.existsSync(stageRoot))fs.rmSync(stageRoot,{recursive:true,force:true});if(movedOld&&fs.existsSync(backup)&&!fs.existsSync(outRoot))fs.renameSync(backup,outRoot)}catch{}throw e}
 const invalidated=delta.added.length+delta.changed.length+delta.deleted.length?invalidateResearchByPaths({cwd,policy,paths:[...delta.changed,...delta.deleted],reason:'SOURCE_CHANGED'}):{invalidated:0};
 return {status:incremental?'KNOWLEDGE_REFRESHED':'KNOWLEDGE_BUILT',version:VERSION,output_dir:rel(cwd,outRoot),source_fingerprint_sha256:sig,files:files.length,domains:domainMaps.length,symbols:symbols.total_symbols,dependency_edges:dep.edges.length,coverage,incremental:stats,research_invalidated:invalidated.invalidated||0,manifest_sha256:manifest.integrity.payload_sha256};
}

export function buildKnowledgeMaps({cwd,policy}){return generateKnowledge({cwd,policy,incremental:false})}
export function refreshKnowledgeMaps({cwd,policy}){return generateKnowledge({cwd,policy,incremental:true})}
export function verifyKnowledgeMaps({cwd,policy}){const outRoot=path.join(cwd,policy.knowledge?.output_dir||'.aledevos/state/knowledge'),mp=path.join(outRoot,'manifest.json');if(!fs.existsSync(mp))return {valid:false,errors:['manifest:missing']};let m;try{m=readJson(mp)}catch{return {valid:false,errors:['manifest:invalid_json']}}const errors=[];if(m.version!==VERSION)errors.push('manifest:version');const manifestActual=payloadHash(m);if(m.integrity?.payload_sha256!==manifestActual)errors.push('manifest:integrity');const entries=[m.maps?.inventory,m.maps?.repo,m.maps?.dependency,m.maps?.symbols,m.maps?.domains_index,...(m.maps?.domains||[]),m.internal?.parse_cache].filter(Boolean);const checks=[];for(const e of entries){const c=verifyOne(path.join(outRoot,e.path),e.payload_sha256);checks.push({path:e.path,...c});if(!c.valid)errors.push(`map:${e.path}:${c.error||'integrity'}`)}return {valid:errors.length===0,version:m.version,source:m.source,incremental:m.incremental,checks,errors,manifest_payload_sha256:manifestActual}}
export function summarizeKnowledge({cwd,policy}){const outRoot=path.join(cwd,policy.knowledge?.output_dir||'.aledevos/state/knowledge');const read=n=>readJson(path.join(outRoot,n)),repo=read('repo-map.json'),dep=read('dependency-map.json'),sym=read('symbol-map.json'),domains=read('domains.index.json'),manifest=read('manifest.json'),freshness=knowledgeFreshness({cwd,policy});return {version:VERSION,project:repo.project,source:manifest.source,freshness:{status:freshness.status,added:freshness.added.length,changed:freshness.changed.length,deleted:freshness.deleted.length},stats:repo.stats,domains:domains.domains,dependency_edges:dep.edges.length,external_packages:dep.external_packages.length,unresolved_dependencies:dep.unresolved.length,total_symbols:sym.total_symbols,parser_coverage:manifest.coverage,incremental:manifest.incremental}}
