import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const VERSION='0.5.0';
function canon(v){if(Array.isArray(v))return '['+v.map(canon).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}';return JSON.stringify(v)}
function shaText(s){return crypto.createHash('sha256').update(s).digest('hex')}
function payload(v){const x=structuredClone(v);delete x.integrity;return x}
function payloadHash(v){return shaText(canon(payload(v)))}
function hashFile(file){const h=crypto.createHash('sha256'),fd=fs.openSync(file,'r'),buf=Buffer.allocUnsafe(1024*1024);try{for(;;){const n=fs.readSync(fd,buf,0,buf.length,null);if(!n)break;h.update(buf.subarray(0,n))}}finally{fs.closeSync(fd)}return h.digest('hex')}
function atomicWriteJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+`.tmp-${process.pid}-${Date.now()}`;fs.writeFileSync(tmp,JSON.stringify(value,null,2)+'\n','utf8');fs.renameSync(tmp,file)}
function readJson(file){return JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''))}
function rootDir(cwd,policy){return path.join(cwd,policy.knowledge?.output_dir||'.aledevos/state/knowledge','research')}
function normalizeQuery(q){return String(q||'').trim().replace(/\s+/g,' ').toLowerCase()}
function cacheId(query,namespace='repo'){return shaText(`${namespace}\0${normalizeQuery(query)}`).slice(0,40)}
function safeRel(cwd,p){const abs=path.resolve(cwd,p),r=path.relative(cwd,abs).replaceAll('\\','/');if(!r||r.startsWith('../')||path.isAbsolute(r))throw new Error(`RESEARCH_SOURCE_OUTSIDE_WORKSPACE:${p}`);return r}
function seal(v){v.integrity={algorithm:'sha256',payload_sha256:payloadHash(v)};return v}
function validateEntry(e){const errors=[];if(e?.version!==VERSION)errors.push('version');if(!e?.cache_id)errors.push('cache_id');if(!e?.query)errors.push('query');if(!Array.isArray(e?.sources)||!e.sources.length)errors.push('sources');if(typeof e?.result_summary!=='string'||!e.result_summary.trim())errors.push('result_summary');if(e?.transcript!==undefined||e?.messages!==undefined||e?.raw_conversation!==undefined)errors.push('transcript_forbidden');if(e?.integrity?.payload_sha256!==payloadHash(e))errors.push('integrity');return {valid:errors.length===0,errors}}
export function putResearchCache({cwd,policy,input,now=new Date()}){const cfg=policy.research_cache||{};if(cfg.enabled!==true)throw new Error('RESEARCH_CACHE_DISABLED');if(input?.transcript!==undefined||input?.messages!==undefined||input?.raw_conversation!==undefined)throw new Error('RESEARCH_TRANSCRIPT_FORBIDDEN');const query=String(input.query||'').trim();if(!query)throw new Error('RESEARCH_QUERY_REQUIRED');const namespace=String(input.namespace||'repo'),paths=[...new Set((input.source_paths||[]).map(String))];if(!paths.length)throw new Error('RESEARCH_SOURCES_REQUIRED');if(String(input.result_summary||'').length>Number(cfg.max_summary_chars||6000))throw new Error('RESEARCH_SUMMARY_TOO_LARGE');const sources=paths.map(p=>{const r=safeRel(cwd,p),abs=path.join(cwd,r);if(!fs.existsSync(abs)||!fs.statSync(abs).isFile())throw new Error(`RESEARCH_SOURCE_MISSING:${r}`);return {path:r,sha256:hashFile(abs)}}).sort((a,b)=>a.path.localeCompare(b.path));const sourceSet=new Set(sources.map(x=>x.path)),evidence=(input.evidence||[]).map(x=>({claim:String(x.claim||''),source_path:safeRel(cwd,x.source_path)}));for(const e of evidence)if(!sourceSet.has(e.source_path))throw new Error(`RESEARCH_EVIDENCE_SOURCE_NOT_DECLARED:${e.source_path}`);const maxAge=Math.min(Number(input.max_age_seconds??cfg.default_max_age_seconds??604800),Number(cfg.max_max_age_seconds||2592000));if(!Number.isFinite(maxAge)||maxAge<0)throw new Error('RESEARCH_MAX_AGE_INVALID');const id=cacheId(query,namespace),entry=seal({version:VERSION,cache_id:id,namespace,query,query_fingerprint_sha256:shaText(normalizeQuery(query)),created_at:now.toISOString(),max_age_seconds:maxAge,source_fingerprint_sha256:shaText(canon(sources)),sources,result_summary:String(input.result_summary),evidence,tags:[...new Set((input.tags||[]).map(String))].sort(),invalidated_at:null,invalidation_reason:null,invalidated_paths:[],integrity:{}}),v=validateEntry(entry);if(!v.valid)throw new Error(`RESEARCH_ENTRY_INVALID:${v.errors.join(',')}`);const p=path.join(rootDir(cwd,policy),`${id}.json`);atomicWriteJson(p,entry);return {status:'RESEARCH_CACHE_STORED',cache_id:id,path:path.relative(cwd,p).replaceAll('\\','/'),sources:sources.length,max_age_seconds:maxAge,payload_sha256:entry.integrity.payload_sha256}}
function inspectEntry({cwd,policy,entry,now=new Date()}){const v=validateEntry(entry);if(!v.valid)return {status:'INVALID',fresh:false,usable:false,reasons:v.errors};const reasons=[];if(entry.invalidated_at)reasons.push(`INVALIDATED:${entry.invalidation_reason||'UNKNOWN'}`);const age=Math.max(0,Math.floor((now.getTime()-Date.parse(entry.created_at))/1000));if(age>Number(entry.max_age_seconds))reasons.push('TTL_EXPIRED');for(const s of entry.sources){const abs=path.join(cwd,s.path);if(!fs.existsSync(abs)){reasons.push(`SOURCE_MISSING:${s.path}`);continue}if(hashFile(abs)!==s.sha256)reasons.push(`SOURCE_CHANGED:${s.path}`)}return {status:reasons.length?'STALE':'FRESH',fresh:reasons.length===0,usable:reasons.length===0,reasons,age_seconds:age}}
export function getResearchCache({cwd,policy,query,namespace='repo',now=new Date()}){const id=cacheId(query,namespace),p=path.join(rootDir(cwd,policy),`${id}.json`);if(!fs.existsSync(p))return {status:'MISS',fresh:false,usable:false,cache_id:id};let entry;try{entry=readJson(p)}catch{return {status:'INVALID',fresh:false,usable:false,cache_id:id,reasons:['INVALID_JSON']}}const state=inspectEntry({cwd,policy,entry,now});if(!state.usable)return {...state,cache_id:id,namespace:entry.namespace,query:entry.query,created_at:entry.created_at,sources:entry.sources.map(x=>x.path)};return {...state,cache_id:id,entry}}
export function verifyResearchCache({cwd,policy,now=new Date()}){const dir=rootDir(cwd,policy);if(!fs.existsSync(dir))return {valid:true,total:0,fresh:0,stale:0,invalid:0,entries:[]};const entries=[];for(const name of fs.readdirSync(dir).filter(x=>x.endsWith('.json')).sort()){let e;try{e=readJson(path.join(dir,name))}catch{entries.push({file:name,status:'INVALID',reasons:['INVALID_JSON']});continue}const s=inspectEntry({cwd,policy,entry:e,now});entries.push({file:name,cache_id:e.cache_id,status:s.status,reasons:s.reasons})}const invalid=entries.filter(x=>x.status==='INVALID').length,stale=entries.filter(x=>x.status==='STALE').length,fresh=entries.filter(x=>x.status==='FRESH').length;return {valid:invalid===0,total:entries.length,fresh,stale,invalid,entries}}
export function invalidateResearchByPaths({cwd,policy,paths,reason='SOURCE_CHANGED',now=new Date()}){const dir=rootDir(cwd,policy);if(!fs.existsSync(dir))return {invalidated:0,cache_ids:[]};const targets=new Set((paths||[]).map(String)),ids=[];for(const name of fs.readdirSync(dir).filter(x=>x.endsWith('.json'))){const p=path.join(dir,name);let e;try{e=readJson(p)}catch{continue}if(!validateEntry(e).valid)continue;const hits=e.sources.map(x=>x.path).filter(x=>targets.has(x));if(!hits.length)continue;e.invalidated_at=now.toISOString();e.invalidation_reason=reason;e.invalidated_paths=[...new Set([...(e.invalidated_paths||[]),...hits])].sort();e.integrity={algorithm:'sha256',payload_sha256:''};e.integrity.payload_sha256=payloadHash(e);atomicWriteJson(p,e);ids.push(e.cache_id)}return {invalidated:ids.length,cache_ids:ids.sort()}}
export function explicitInvalidateResearch({cwd,policy,query,namespace='repo',reason='MANUAL',now=new Date()}){const id=cacheId(query,namespace),p=path.join(rootDir(cwd,policy),`${id}.json`);if(!fs.existsSync(p))return {status:'MISS',cache_id:id};const e=readJson(p);if(!validateEntry(e).valid)throw new Error('RESEARCH_ENTRY_INVALID');e.invalidated_at=now.toISOString();e.invalidation_reason=reason;e.invalidated_paths=[];e.integrity={algorithm:'sha256',payload_sha256:''};e.integrity.payload_sha256=payloadHash(e);atomicWriteJson(p,e);return {status:'RESEARCH_CACHE_INVALIDATED',cache_id:id,reason}}
export { cacheId };
