#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const mmRoot=path.resolve(here,'..');
const args=process.argv.slice(2),[group,cmd]=args;
const take=(f,d=null)=>{const i=args.indexOf(f);return i>=0&&i+1<args.length?args[i+1]:d};
const out=v=>process.stdout.write(JSON.stringify(v,null,2)+'\n');
const die=(status,code=2,extra={})=>{out({status,...extra});process.exit(code)};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const norm=p=>String(p||'').replaceAll('\\','/');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).filter(k=>!['evidence_sha256','comparison_sha256'].includes(k)).sort().map(k=>[k,stable(v[k])])):v;
const hashObj=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const hashFile=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')};
const policy=()=>read(path.join(mmRoot,'policies/judge-pair-policy.json'));
const registry=()=>read(path.join(mmRoot,'registry/model-registry.json'));
function bindingVerify(file,{requireReady=false}={}){
 const r=registry(),errors=[]; if(!file||!fs.existsSync(file))return{status:'MODEL_BINDING_MISSING',valid:false,errors:['binding_missing']}; let b;try{b=read(file)}catch{return{status:'MODEL_BINDING_INVALID',valid:false,errors:['binding_unreadable']}};
 if(b.schema_version!=='1.0')errors.push('schema_version_invalid');if(!b.binding_id)errors.push('binding_id_missing');if(!b.target_runtime)errors.push('target_runtime_missing');
 for(const s of ['primary','secondary']){const x=b.slots?.[s];if(!x){errors.push(`${s}_slot_missing`);continue}for(const k of ['provider_id','model_id','provider_family','modalities','context_window_tokens','cost_class','runtime_ready'])if(x[k]===undefined||x[k]===null)errors.push(`${s}_${k}_missing`);if(!Array.isArray(x.modalities)||!x.modalities.includes('text'))errors.push(`${s}_text_capability_missing`);if(!Number.isInteger(x.context_window_tokens)||x.context_window_tokens<0)errors.push(`${s}_context_invalid`);if(requireReady&&x.runtime_ready!==true)errors.push(`${s}_runtime_not_ready`)}
 const a=b.slots?.primary,c=b.slots?.secondary;if(a&&c&&a.provider_id===c.provider_id&&a.model_id===c.model_id)errors.push('model_identity_not_distinct');
 return{status:errors.length?'MODEL_BINDING_INVALID':'MODEL_BINDING_VALID',valid:!errors.length,errors,binding:b,registry_id:r.registry_id,package_support:true,target_runtime_ready:!errors.length&&a?.runtime_ready===true&&c?.runtime_ready===true};
}
function registryVerify(){const r=registry(),errors=[];if(r.schema_version!=='1.0')errors.push('schema_version');if(r.adapter_independent!==true)errors.push('adapter_independent');if(r.judge_slots?.length!==2)errors.push('slot_count');const ids=(r.judge_slots||[]).map(x=>x.slot);if(ids.join(',')!=='primary,secondary')errors.push('slot_identity');if(r.rules?.missing_model_never_implies_consensus!==true)errors.push('missing_model_rule');if(r.rules?.final_decision_authority!=='ALEDEVOS_DETERMINISTIC_GATE')errors.push('decision_authority');if(r.rules?.provider_diversity_required!==false)errors.push('diversity_premature');return{status:errors.length?'MODEL_REGISTRY_INVALID':'MODEL_REGISTRY_VALID',valid:!errors.length,errors,registry:r}}
function sealEvidence(bindingFile,slot,inputFile,rubricFile,submissionFile,outFile){
 const bv=bindingVerify(bindingFile);if(!bv.valid)die('MODEL_BINDING_INVALID',3,{errors:bv.errors});if(!['primary','secondary'].includes(slot))die('JUDGE_SLOT_INVALID',3);for(const p of [inputFile,rubricFile,submissionFile])if(!p||!fs.existsSync(p))die('JUDGE_EVIDENCE_INPUT_MISSING',3,{path:p});const s=read(submissionFile),p=policy();if(!p.allowed_roles.includes(s.judge_role))die('JUDGE_ROLE_INVALID',3);if(!p.allowed_outcomes.includes(s.outcome))die('JUDGE_OUTCOME_INVALID',3);if(!Number.isFinite(s.score)||s.score<0||s.score>100)die('JUDGE_SCORE_INVALID',3);if(!s.task_id)die('TASK_ID_REQUIRED',3);const m=bv.binding.slots[slot];if(s.judge_role==='visual'&&!m.modalities.includes('image'))die('VISUAL_JUDGE_MODEL_IMAGE_CAPABILITY_REQUIRED',3,{slot});
 const ev={schema_version:'1.0',phase:'MULTIMODEL_P1_JUDGE_EVIDENCE',task_id:s.task_id,judge_role:s.judge_role,slot,model:{provider_id:m.provider_id,provider_family:m.provider_family,model_id:m.model_id,modalities:m.modalities,context_window_tokens:m.context_window_tokens,cost_class:m.cost_class},input:{path:norm(path.relative(process.cwd(),path.resolve(inputFile))),sha256:hashFile(inputFile)},rubric:{path:norm(path.relative(process.cwd(),path.resolve(rubricFile))),sha256:hashFile(rubricFile)},result:{outcome:s.outcome,score:Math.round(s.score*100)/100,blockers:Number.isInteger(s.blockers)?s.blockers:0,unverified:Number.isInteger(s.unverified)?s.unverified:0,summary:s.summary||null},runtime:{target_runtime:bv.binding.target_runtime,runtime_ready:m.runtime_ready===true,runtime_evidence:m.runtime_evidence||null,package_support:true},created_at:new Date().toISOString(),evidence_sha256:''};ev.evidence_sha256=hashObj(ev);if(outFile)write(path.resolve(outFile),ev);return ev;
}
function verifyEvidence(file){if(!file||!fs.existsSync(file))return{status:'JUDGE_MODEL_EVIDENCE_INVALID',valid:false,errors:['evidence_missing']};let e;try{e=read(file)}catch{return{status:'JUDGE_MODEL_EVIDENCE_INVALID',valid:false,errors:['evidence_unreadable']}};const errors=[];if(e.phase!=='MULTIMODEL_P1_JUDGE_EVIDENCE')errors.push('phase_invalid');if(!['primary','secondary'].includes(e.slot))errors.push('slot_invalid');if(!policy().allowed_roles.includes(e.judge_role))errors.push('role_invalid');if(!policy().allowed_outcomes.includes(e.result?.outcome))errors.push('outcome_invalid');if(e.evidence_sha256!==hashObj(e))errors.push('integrity_mismatch');for(const h of [e.input?.sha256,e.rubric?.sha256])if(!/^[a-f0-9]{64}$/.test(h||''))errors.push('hash_invalid');if(!e.model?.provider_id||!e.model?.model_id)errors.push('model_identity_missing');return{status:errors.length?'JUDGE_MODEL_EVIDENCE_INVALID':'JUDGE_MODEL_EVIDENCE_VALID',valid:!errors.length,errors,evidence:e}}
function compare(primaryFile,secondaryFile,outFile){
 const a=verifyEvidence(primaryFile),b=verifyEvidence(secondaryFile);if(!a.valid||!b.valid)die('JUDGE_PAIR_EVIDENCE_INVALID',4,{primary_errors:a.errors,secondary_errors:b.errors});const x=a.evidence,y=b.evidence;if(x.slot!=='primary'||y.slot!=='secondary')die('JUDGE_PAIR_SLOT_MISMATCH',4);if(x.task_id!==y.task_id||x.judge_role!==y.judge_role)die('JUDGE_PAIR_TASK_ROLE_MISMATCH',4);const distinct=!(x.model.provider_id===y.model.provider_id&&x.model.model_id===y.model.model_id);if(!distinct)die('JUDGE_PAIR_MODEL_IDENTITY_NOT_DISTINCT',4);const sameInput=x.input.sha256===y.input.sha256,sameRubric=x.rubric.sha256===y.rubric.sha256;if(!sameInput)die('JUDGE_PAIR_INPUT_MISMATCH',4);if(!sameRubric)die('JUDGE_PAIR_RUBRIC_MISMATCH',4);const ready=x.runtime.runtime_ready===true&&y.runtime.runtime_ready===true;const sameOutcome=x.result.outcome===y.result.outcome;const state=!ready?'INCOMPLETE':sameOutcome?'AGREE':'DISAGREE';
 const c={schema_version:'1.0',phase:'MULTIMODEL_P1_JUDGE_COMPARISON',task_id:x.task_id,judge_role:x.judge_role,state,primary:{evidence_sha256:x.evidence_sha256,provider_id:x.model.provider_id,model_id:x.model.model_id,outcome:x.result.outcome,score:x.result.score,runtime_ready:x.runtime.runtime_ready},secondary:{evidence_sha256:y.evidence_sha256,provider_id:y.model.provider_id,model_id:y.model.model_id,outcome:y.result.outcome,score:y.result.score,runtime_ready:y.runtime.runtime_ready},same_input:sameInput,same_rubric:sameRubric,same_outcome:sameOutcome,score_delta:Math.round(Math.abs(x.result.score-y.result.score)*100)/100,blocker_delta:Math.abs(x.result.blockers-y.result.blockers),provider_diverse:x.model.provider_family!==y.model.provider_family,consensus_claimed:false,final_decision:null,final_decision_authority:'ALEDEVOS_DETERMINISTIC_GATE',router_used:false,fallback_used:false,created_at:new Date().toISOString(),comparison_sha256:''};c.comparison_sha256=hashObj(c);if(outFile)write(path.resolve(outFile),c);return c;
}
function verifyComparison(file){if(!file||!fs.existsSync(file))return{status:'JUDGE_PAIR_COMPARISON_INVALID',valid:false,errors:['comparison_missing']};let c;try{c=read(file)}catch{return{status:'JUDGE_PAIR_COMPARISON_INVALID',valid:false,errors:['comparison_unreadable']}};const errors=[];if(c.phase!=='MULTIMODEL_P1_JUDGE_COMPARISON')errors.push('phase_invalid');if(!policy().comparison_states.includes(c.state))errors.push('state_invalid');if(c.consensus_claimed!==false)errors.push('consensus_forbidden');if(c.final_decision!==null)errors.push('final_decision_forbidden');if(c.final_decision_authority!=='ALEDEVOS_DETERMINISTIC_GATE')errors.push('authority_invalid');if(c.router_used!==false||c.fallback_used!==false)errors.push('future_phase_feature_forbidden');if(c.comparison_sha256!==hashObj(c))errors.push('integrity_mismatch');return{status:errors.length?'JUDGE_PAIR_COMPARISON_INVALID':'JUDGE_PAIR_COMPARISON_VALID',valid:!errors.length,errors,comparison:c}}

function certificateInputs(){const files=['engine/multimodel.mjs','registry/model-registry.json','policies/judge-pair-policy.json','schemas/model-binding.schema.json','schemas/judge-model-evidence.schema.json','schemas/judge-pair-comparison.schema.json','templates/target-model-bindings.example.json'];return files.map(rel=>({path:rel,sha256:hashFile(path.join(mmRoot,rel))}))}
function certifyRun(outFile){const rv=registryVerify(),inputs=certificateInputs();const c={schema_version:'1.0',phase:'MULTIMODEL_P1',status:rv.valid?'MULTIMODEL_P1_PACKAGE_CERTIFIED':'MULTIMODEL_P1_PACKAGE_CERTIFICATION_FAILED',package_only:true,target_runtime_validation:'DEFERRED',claims:{two_judge_slots:true,adapter_independent:true,explicit_model_provenance:true,immutable_input_and_rubric:true,missing_secondary_never_consensus:true,router_not_implemented:true,diversity_not_enforced:true,fallback_not_implemented:true},registry_status:rv.status,inputs,created_at:new Date().toISOString(),evidence_sha256:''};c.evidence_sha256=hashObj(c);if(outFile)write(path.resolve(outFile),c);return c}
function certifyVerify(file){if(!file||!fs.existsSync(file))return{status:'MULTIMODEL_P1_CERTIFICATE_INVALID',valid:false,errors:['certificate_missing']};let c;try{c=read(file)}catch{return{status:'MULTIMODEL_P1_CERTIFICATE_INVALID',valid:false,errors:['certificate_unreadable']}};const errors=[];if(c.phase!=='MULTIMODEL_P1')errors.push('phase_invalid');if(c.package_only!==true||c.target_runtime_validation!=='DEFERRED')errors.push('runtime_boundary_invalid');if(c.evidence_sha256!==hashObj(c))errors.push('certificate_integrity_mismatch');const current=new Map(certificateInputs().map(x=>[x.path,x.sha256]));for(const x of c.inputs||[])if(current.get(x.path)!==x.sha256)errors.push(`input_drift:${x.path}`);if((c.inputs||[]).length!==current.size)errors.push('input_set_drift');return{status:errors.length?'MULTIMODEL_P1_CERTIFICATE_STALE_OR_TAMPERED':'MULTIMODEL_P1_CERTIFICATE_VALID',valid:!errors.length,errors,certificate:c}}

if(group==='registry'&&cmd==='verify'){const r=registryVerify();out(r);process.exit(r.valid?0:3)}
if(group==='binding'&&cmd==='verify'){const r=bindingVerify(path.resolve(take('--binding','')),{requireReady:take('--require-ready','false')==='true'});out(r);process.exit(r.valid?0:3)}
if(group==='readiness'&&cmd==='check'){const r=bindingVerify(path.resolve(take('--binding','')));if(!r.valid){out(r);process.exit(3)}const p=r.binding.slots.primary,s=r.binding.slots.secondary;let status='MULTIMODEL_TARGET_READY';if(!p.runtime_ready)status='PRIMARY_JUDGE_MODEL_NOT_READY';else if(!s.model_id||/REQUIRED|UNBOUND|SECOND_MODEL_ID/.test(s.model_id))status='SECONDARY_JUDGE_MODEL_UNBOUND';else if(!s.runtime_ready)status='SECONDARY_JUDGE_MODEL_NOT_READY';out({status,package_support:true,target_runtime_ready:status==='MULTIMODEL_TARGET_READY',primary:{provider_id:p.provider_id,model_id:p.model_id,runtime_ready:p.runtime_ready},secondary:{provider_id:s.provider_id,model_id:s.model_id,runtime_ready:s.runtime_ready}});process.exit(status==='MULTIMODEL_TARGET_READY'?0:5)}
if(group==='evidence'&&cmd==='seal'){out(sealEvidence(path.resolve(take('--binding','')),take('--slot'),path.resolve(take('--input','')),path.resolve(take('--rubric','')),path.resolve(take('--submission','')),take('--out')));process.exit(0)}
if(group==='evidence'&&cmd==='verify'){const r=verifyEvidence(path.resolve(take('--evidence','')));out(r);process.exit(r.valid?0:3)}
if(group==='pair'&&cmd==='compare'){out(compare(path.resolve(take('--primary','')),path.resolve(take('--secondary','')),take('--out')));process.exit(0)}
if(group==='pair'&&cmd==='verify'){const r=verifyComparison(path.resolve(take('--comparison','')));out(r);process.exit(r.valid?0:3)}
if(group==='certify'&&cmd==='run'){const c=certifyRun(take('--out'));out(c);process.exit(c.status.endsWith('CERTIFIED')?0:4)}
if(group==='certify'&&cmd==='verify'){const r=certifyVerify(path.resolve(take('--certificate','')));out(r);process.exit(r.valid?0:4)}
die('MULTIMODEL_COMMAND_UNKNOWN',2,{usage:['registry verify','binding verify --binding <json>','readiness check --binding <json>','evidence seal --binding <json> --slot <primary|secondary> --input <file> --rubric <file> --submission <json>','evidence verify --evidence <json>','pair compare --primary <json> --secondary <json>','pair verify --comparison <json>']});
